### ISSUE TITLE
Settings Menu Overriding Window Controls

### ISSUE THREAD

**Issue by jacksonwelsh** [ciderapp/Cider-2#10]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win11 Edu 22H2 (22621.1265)

### Describe the Bug

(downloaded cider from alpha discord channel)

When mousing near the top-right of the settings popover, the window control icons are also highlighted.

![image](https://user-images.githubusercontent.com/20214768/223301673-6306ecd7-c333-453f-a10e-5d0b2c860b05.png)

### Steps to Reproduce

1. Open Cider, and make the window relatively small (1/4 of my 32" display)
1. Open settings
1. Hover mouse near top-right of settings page

### Anything else?

This is a very minor issue, but because the close button for the settings page is in this region, it is very likely for users to notice this (or potentially miss and accidentally close the application).

**Comment by coredev-uk** [comment]
We're looking at redesigning the whole settings menu, so this may not be an issue in future.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
