### ISSUE TITLE
[Bug]: manually uploaded songs problems

### ISSUE THREAD

**Issue by zaebokkunwow** [ciderapp/Cider-2#115]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1088637577243934812

### Operating System Version

Windows 11 22621.1485

### Describe the Bug

1) Artworks of albums which you upload manually in iTunes from your PC to your apple music library redownloading every time you open "Albums" tab in Cider 2. 
2) In "Songs" tab some of this songs artworks not shown and some have default windows image icon
![image](https://user-images.githubusercontent.com/12572522/228646831-1271700a-a382-4839-8914-51c54aaa6e9c.png)

### Steps to Reproduce

1. Upload some songs to music library with iTunes
2. Wait until synchronization is done
3. Open "Albums" and "Songs" tabs in Cider 2

**Comment by coredev-uk** [comment]
Further support for uploaded items is planned for later in development.

**Comment by coredev-uk** [comment]
Going back to this, do all uploads appear as intended on Apple Music web?

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
