### ISSUE TITLE
[Bug]:  Lyrics run off the lyrics windows and are unreadable.  

### ISSUE THREAD

**Issue by nrodriguez2477** [ciderapp/Cider-2#131]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

4/11/2023

### Operating System Version

Windows 11 22H2

### Describe the Bug

When opening the lyrics for a song that is playing, some of the lyrics run off the screen when it's a long line. The song I experices this was Peaches by Jack Black. While attempting to recreate the error I closed the application and reopened it and noticed that the text now wrapped to a new line.

### Steps to Reproduce

1. Open app
2. Play song
3. click lyrics button

### Anything else?

None

**Comment by coredev-uk** [comment]
I think this may have just been a bug with how the song was stored in AM's API. Upon testing it just now, all lyrics display correctly, as this is a recently added song to AM it may have just been a mess up on porting the lyrics. If you find the issue persisting feel free to reopen the issue, and could you provide a screenshot of the lyrics. Thanks.
