### ISSUE TITLE
[Bug]: Windows Precision Touchpad Issue

### ISSUE THREAD

**Issue by HackZy01** [ciderapp/Cider-2#136]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

13.04.2023 MS Store build

### Operating System Version

Windows 10 [22H2] (19045.2788)

### Describe the Bug

Windows Precision Trackpad browser gestures interfere with trying to browse things

https://user-images.githubusercontent.com/77678316/231855273-417a6c6c-2f57-47a6-8902-d048ae7fc55b.mp4

### Steps to Reproduce

1. Use a Windows Precision Trackpad
![image](https://user-images.githubusercontent.com/77678316/231855679-fb437d42-019e-464b-863d-bb9f502fb7f3.png)
2. Try to scroll left or right
3. If doesn't replicate, try harder

**Comment by booploops** [comment]
On track for fix in 2.0.3

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
