### ISSUE TITLE
[Bug]: Immersive mode fullscreen issues

### ISSUE THREAD

**Issue by gamersi** [ciderapp/Cider-2#155]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

newest release from discord donator rewards

### Operating System Version

Windows 11 22H2

### Describe the Bug

When I start fullscreen, the taskbar looks strange. I like this app very much so I am commit to report issues I encounter so that the app will get better for everyone. Thank you for developing this masterpiece.

### Steps to Reproduce

1. start immersive mode
2. click on the fullscreen icon

### Anything else?

![grafik](https://user-images.githubusercontent.com/46320904/234081275-836137c5-497e-41d5-bbe3-1b72bfcdcdfc.png)

### Connect Device ID

zXk7fyUdUStccgFPDGmh

### Build timestamp

1682359771779

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
