### ISSUE TITLE
[Bug]: Unable to Play Explicit Songs After 2 Updates Ago

### ISSUE THREAD

**Issue by appletimemac** [ciderapp/Cider-2#157]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2.0.1

### Operating System Version

Windows 11 2H22 (22621)

### Describe the Bug

I am unable to listen to anything marked as Explicit. I've also gone into my Apple Music preferences and set up parental controls and set music, video, and TV Showes to 'Explicit', "TV-MA'. I can play it just fine on the website, but not Cider.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/180153/234374696-d2e9f51b-cd61-4c8b-882a-b8a590984a9d.png">

I will click a song and Cider will skip it and play the following song if the selected song was Explicit. (Note: this also occurs if playing a 'clean' song and going forward in the playlist, with that next song being Explicit, Cider will skip it and play the next clean song).

### Steps to Reproduce

Pre-Requisites:
- Set up Parental Controls to have highest level of acceptance (Explicit)
- Install Cider 2.0.1

1. Launch Cider
2. Click on a playlist containing an explicit song
3. Double-click on the explicit song

Expected Behavior:
Cider will play the Explicit song as all permissions are set to be able to do this.

Actual Behavior:
The Explicit song is not played, it is skipped, and Cider will play the next 'Clean' song.

Notes:
<img width="1925" alt="image" src="https://user-images.githubusercontent.com/180153/234375401-1d822009-7af1-44f2-96bb-f85ef403db30.png">

### Anything else?

<img width="1925" alt="image" src="https://user-images.githubusercontent.com/180153/234375517-7b3fc939-67d3-4e21-b912-a336c047d319.png">

**Comment by fidelmarques** [comment]
Adding to the thread:

1) The app won't play any Clean song before an Explicit song more than 1~2 sec. The playback breaks, and if we try to skip the music via controls, nothing happens.

2) If any Clean music is playing and it ends (or manually skipped), it will try to play the next song, as expected. If the next music is Clean, but the next to this is Explicit (Actual music -> Clean -> Explicit order), the player will skip every music until it finds 2 Clean songs in a row (Clean -> Clean).

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
