### ISSUE TITLE
[Bug]: Saki AI can be spammed without entering text, and also does not work.

### ISSUE THREAD

**Issue by Beamy68** [ciderapp/Cider-2#158]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider 2.x (Beta 30)

### Operating System Version

Windows 11 Home Insider Preview 22H2 Build 25330.1000 

### Describe the Bug

When typing to the AI, it says "Sorry, I can't have a conversation right now. Please try again later." and suggests the search feature. Not entering anything into the message box and pressing enter, or clicking the send icon, will still send the message.

### Steps to Reproduce

Enabled the Saki AI, went into its menu, and then typed to it. Without typing and pressing enter, it counted the message as being sent.

### Anything else?

![image](https://user-images.githubusercontent.com/31512954/234463753-a5ab4de7-30fa-46af-9ab7-ef0d2327b5ac.png)

### Connect Device ID

UqGTlivrXMRLLiDefanC

### Build timestamp

1682479996799

**Comment by coredev-uk** [comment]
Saki has been removed.
