### ISSUE TITLE
[Bug]: Playlist Propeties won't load

### ISSUE THREAD

**Issue by joebro1907** [ciderapp/Cider-2#175]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider v2.0.2 - Sabiiro (Microsoft Store)

### Operating System Version

Window 11 Home 22H2 (OS Build 22621.1635)

### Describe the Bug

When clicking the "Properties" option on the "More" menu for playlists the Propeties Panel opens, but nothing loads. This happens on any playlist in the library.

### Steps to Reproduce

1. Go to any playlist in your Library
2. Click the "More" button
3. Click the "Properties" option
4. Wait...

### Anything else?

![image](https://user-images.githubusercontent.com/94337292/235827246-40cf194a-a4c3-487e-8057-22bf7f29861c.png)

### Build timestamp

5/1/2023

**Comment by MickeyOern** [comment]
Can confirm the same issue.

**Comment by joebro1907** [comment]
Part of the issue was fixed. The "Details" section now loads

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/94337292/b6245c9a-c2e9-43c9-a93d-276136561645)

But the "Artwork" section still doesn't

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/94337292/043d391b-1640-498e-b001-2b5bfb073ca8)

Here's the console output

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/94337292/35cca8cd-d021-44f0-9f94-d1d6e0ddef59)

**Comment by coredev-uk** [comment]
Once catalog calls are implemented correctly, this should be resolved.
