### ISSUE TITLE
[Bug]: Library Albums page won't load

### ISSUE THREAD

**Issue by joebro1907** [ciderapp/Cider-2#176]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider v2.0.2 - Sabiiro (Microsoft Store)

### Operating System Version

Windows 11 Home (OS Build 22621.1635)

### Describe the Bug

When clicking on "Albums" in the Library section, said page is shown, but nothing will load.

### Steps to Reproduce

1. Click on the "Albums" section under "Library" on the sidebar
2. Wait...

### Anything else?

![image](https://user-images.githubusercontent.com/94337292/235829078-a94ce5b0-6e0f-4988-9d4f-05cbde1d0168.png)

### Build timestamp

5/1/2023

**Comment by coredev-uk** [comment]
Firstly, I suggest updating to the latest build if you haven't already. 
Can you please open your console with Ctrl+Shift+I and take a screenshot of that

**Comment by joebro1907** [comment]
I updated the client and the Albums page loaded the first time, however, after selecting a sorting method it won't load again even after restarting the app.

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/94337292/0d3af3a7-6585-4fd0-8898-e4d8a686d4bc)

Here's the console output

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/94337292/0b881007-2a55-41fc-86e0-e679fd1793e7)

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
