### ISSUE TITLE
[Bug]: unable to share playlists

### ISSUE THREAD

**Issue by svalencia014** [ciderapp/Cider-2#180]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2.0.2

### Operating System Version

22H2

### Describe the Bug

Unable to share playlists
![image](https://user-images.githubusercontent.com/68522351/236072772-19e0c5ca-25fe-4d01-97aa-1e37cc6e5cbb.png)

### Steps to Reproduce

1. Make playlist
2. Try to share it

### Connect Device ID

bjd95FSJFbA3y3EXUUXD

### Build timestamp

1683156349297

**Comment by svalencia014** [comment]
On the same windows version on my laptop, the same error occurs 
![image](https://user-images.githubusercontent.com/68522351/236197942-d01b83a4-b3c0-4712-b252-b6eb44f62e7b.png)

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
