### ISSUE TITLE
[Bug]:"Currently Playing" Widget doesn't work properly

### ISSUE THREAD

**Issue by AgentePaura** [ciderapp/Cider-2#184]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

I don't remember when I downloaded Cider.

### Operating System Version

Windows 11

### Describe the Bug

It only appears for one second, saying "Not Playing Anything". The widget then disappears.

### Steps to Reproduce

1. Open Cider Connect Dashboard
2. Click "Currently Playing Widget"

### Connect Device ID

0k70y3OLknAQcC6niuPQ

### Build timestamp

1683220662690

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
