### ISSUE TITLE
[Bug]: Dark mode become different (light) after PC inactivity (lock or sleep) 

### ISSUE THREAD

**Issue by cquanu** [ciderapp/Cider-2#188]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

03/05/2023

### Operating System Version

Windows 11 Pro 22H2 25352.1

### Describe the Bug

Normal dark mode
![Cider_eU75lIK3ga](https://user-images.githubusercontent.com/16508884/236620995-2b0b6b06-2330-470b-b2e2-55b9bd2a1c21.png)

After waking up from lock or sleep mode
![Cider_uJnYE5Vg6m](https://user-images.githubusercontent.com/16508884/236621016-e17f0f41-3d30-43ba-b543-e270c4ec538c.png)

### Steps to Reproduce

Open Cider, Lock the Windows or put it to sleep. Then unlock or wake the PC up.
The theme changed and the text become illegible.

### Build timestamp

1683371494061

**Comment by Swammii** [comment]
I have the same issue, only for me it is when my wallpaper changes. I have windows set up to change my wallpaper every 10 minutes, and whenever it changes, Cider goes from the normal dark view to completely white so I cannot read any text or see any buttons. If I close Cider and relaunch it, everything is fine again until the next wallpaper change. This happens every time.

![2023-06-16_19h52_06](https://github.com/ciderapp/Cider-2/assets/136863892/4646248f-1311-4ea7-96b7-42b3b4e41f30)
![2023-06-16_19h53_17](https://github.com/ciderapp/Cider-2/assets/136863892/1c8be6aa-ca18-4bcc-8872-00b8da255b1d)

**Comment by New-Authentication** [comment]
IT has something to do with Settings -> Visual -> Window Vibrancy Type - when I set this to none, I don't experience the problem.

**Comment by New-Authentication** [comment]
My Windows 11 (beta channel) is running in Light mode, if that has anything to say.

**Comment by Henonnnn** [comment]
It's also happening when minimising the app while it's in fullscreen when I reopen it it's like that 
![image](https://github.com/ciderapp/Cider-2/assets/46067390/397649e3-ba30-4df1-9316-ea30c7c9e58c)

**Comment by StephenDini** [comment]
I think this is caused by the windows themes overwriting the fonts colors for the lite version. If you switch to any personalization settings that switch between light and dark modes this happens. Turn on Sweetener to overwrite this. 
![jwWaTFY9EB](https://github.com/ciderapp/Cider-2/assets/38794144/0e3a895f-f118-4628-a779-d8082abae749)

**Comment by StephenDini** [comment]
Both videos did not upload so I had to shorten one. 
![LNd5zJs8Ew](https://github.com/ciderapp/Cider-2/assets/38794144/3f57abd9-9432-4d1d-9575-e7735a548af4)

**Comment by cquanu** [comment]
Any solution?

**Comment by coredev-uk** [comment]
This appears to just be a bug with Mica/Tabbed usage. Just turn off vibrancy as stated above.
