### ISSUE TITLE
[Bug]: Cider Connect lagging out

### ISSUE THREAD

**Issue by svalencia014** [ciderapp/Cider-2#193]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Build 5/2/2023 | Quasar v2.11.10 | cd304ef210f9e99118f9c13f2

### Operating System Version

Windows 11 22H2

### Describe the Bug

Connect now playing and Cider are no longer in sync
![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/68522351/7e1c02a9-eb44-40eb-9c2d-07666a8cedd5)

### Steps to Reproduce

1. Play a song
2. Open cider connect now playing

### Connect Device ID

bjd95FSJFbA3y3EXUUXD

### Build timestamp

1683764992394

**Comment by cryptofyre** [comment]
Should be mitigated in 2.2.0
