### ISSUE TITLE
Artist Station Failing to Queue

### ISSUE THREAD

**Issue by gryffindor-coder** [ciderapp/Cider-2#196]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

7 May 2023

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

Incorrect track name for currently playing and a negative timestamp on the right in the player. Also no ability to click on the song name or the album art to bring up more options as usual.

### Steps to Reproduce

1. Went to an artist's page.
2. Clicked on their play icon which starts their radio station.
3. Waited and nothing happened, clicked again.
4. Received a message along the lines of "play() request interrupted..." and then a song's info and time was displayed while a different longer song played.

### Build timestamp

1683909945477

**Comment by gryffindor-coder** [comment]
> What artist are you attempting to play?

I think it was Taylor Swift

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
