### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by happytraveller-alone** [ciderapp/Cider-2#197]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2023.5.3 install from microsoft store

### Operating System Version

Windows11 Latest Version

### Describe the Bug

A white login screen pops up instead of jumping directly to the URL, and the interface shows blank, and when trying to close it, the page pops up again, unless the main cider interface is closed manually.

### Steps to Reproduce

Just Open the Cider and click the button of signing in  apple music in the corner.

### Build timestamp

1683960447709

**Comment by coredev-uk** [comment]
If you haven't already, update to the latest version. Please try logging into [Apple Music Web](https://beta.music.apple.com).

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
