### ISSUE TITLE
[Bug]: Recently played not updating

### ISSUE THREAD

**Issue by villesuh** [ciderapp/Cider-2#200]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

MS Store latest

### Operating System Version

Windows 10 22H2

### Describe the Bug

Listening to music using Cider does not seem to affect Apple Music stats at all

### Steps to Reproduce

1. Listen to music on Cider
2. Check the "Recently played" section on "Home" or "Listen Now" tab
3. No change

### Build timestamp

1684150807178

**Comment by aitbw** [comment]
I've been affected by this bug as well ever since I got Cider (Preview) on March 24th, Windows 11 Home (21H2)

Currently running Cider 2.0.3 (v1.1.7.0, acc. to the Microsoft Store)

**Comment by coredev-uk** [comment]
Check to make sure you haven't got private mode enabled. It will come up as 
![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/64542347/dcd6bf7c-9c98-4dc0-bc0f-92dd197b05d8)
in the playback controls area.

**Comment by villesuh** [comment]
> Check to make sure you haven't got private mode enabled. It will come up as ![image](https://user-images.githubusercontent.com/64542347/242661994-dcd6bf7c-9c98-4dc0-bc0f-92dd197b05d8.png) in the playback controls area.

No, private session is not enabled. Made sure by toggling between, no change.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
