### ISSUE TITLE
Minimize app on sleep

### ISSUE THREAD

**Issue by nikcorleone13** [ciderapp/Cider-2#211]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

17 May 2023

### Operating System Version

Windows 10

### Describe the Bug

App is not minimizing after the desktop is on sleep mode. After logging in the app misbehaves sometimes and displays as if pixelated. Happens sometimes when app is untouched for a while

### Steps to Reproduce

1.Log off from windows
2.Re login

### Anything else?

Love this app.Keep going

### Build timestamp

1684513106374

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
