### ISSUE TITLE
Playlist Cache Building Failing

### ISSUE THREAD

**Issue by thelazurus** [ciderapp/Cider-2#212]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

5/20/23, using Windows Store

### Operating System Version

Windows 11 Version 22H2

### Describe the Bug

The app is stuck with a notification of "building playlist cache"

### Steps to Reproduce

1. Install Cider
2. Sign In to Apple Music
3. Look in the top right for the spinner

### Anything else?

I have already tried a clean install with no change.

**Comment by thelazurus** [comment]
![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/9217220/be2ef91a-70eb-4a0b-bfe1-afd5419ede42)

**Comment by coredev-uk** [comment]
Check to make sure you're on the latest version, these errors appear to be very old issues.

**Comment by thelazurus** [comment]
I took that screenshot from a fresh install from MS Store on a new device

**Comment by coredev-uk** [comment]
Resolved in 2.3.0.
