### ISSUE TITLE
Issues Loading Elements

### ISSUE THREAD

**Issue by TheNewSkai** [ciderapp/Cider-2#215]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9:40 PM PST May 21 2023

### Operating System Version

Windows 10 22H2

### Describe the Bug

Elements often won't load after switching between tabs in the sidebar or at all.

### Steps to Reproduce

1. Start in either "recently added," "songs," ~~or "albums."~~
2. Switch to a different one of those three tabs.
3. Switch back to the tab you were in originally.
4. It won't load now.

### Anything else?

The "songs" tab also seems to not load at all. It originally loaded when I first launched the app but after choosing the option to sort by name it now just shows a blank screen. The search options button is gone so I can't switch it back.

I found that when the "albums" and "recently added" tabs were not loading, I could press CTRL + R to force it to refresh, making it load until I switched tabs again. This did not work for the songs tab.

I have a feeling that this might be due to me having many songs in my library. Last I checked, I had a couple thousand songs at least. 

### Connect Device ID

Version 2.0.3

### Build timestamp

Built on 5/16/2023, 10:25:48 PM | Quasar v2.11.10 | Sabiiro

**Comment by coredev-uk** [comment]
Please provide with more information. 
- A screenshot of your devtools console (Ctrl+Shift+I -> Console)
- Do you have ClientDB enabled in Settings?

**Comment by TheNewSkai** [comment]
Here's the screenshot of the console:
![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/112280549/1cf4021b-cbd2-4543-8d01-2ff1a86b7e80)

The issue happens regardless of if ClientDB is enabled or disabled.

**Comment by coredev-uk** [comment]
Old issue, closing.
