### ISSUE TITLE
Blank screen when opening albums

### ISSUE THREAD

**Issue by irisariuan** [ciderapp/Cider-2#218]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17/5/2023

### Operating System Version

Windows 11, 22H2

### Describe the Bug

Main content becomes blank after clicking into any of albums

### Steps to Reproduce

1. Click any albums
2. Content appears for tenth of a second
3. The screen becomes blank

### Anything else?

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/39485107/a14562b9-4231-4a22-a718-540b99f8c45f)

**Comment by coredev-uk** [comment]
Please provide with more information. 
- A screenshot of your devtools console (Ctrl+Shift+I -> Console)
- Do you have ClientDB enabled in Settings?
