### ISSUE TITLE
[Bug]: Media controls not prioritizing Cider over other applications

### ISSUE THREAD

**Issue by jlee0111** [ciderapp/Cider-2#219]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Installed 3 days ago, Cider 2 version 2.0.3

### Operating System Version

Windows 10 latest update

### Describe the Bug

When streaming audio/video from a tab on my browser, pressing the play/pause button on my keyboard's media controls always prioritizes the browser instance to first activate the play/pause action over Cider, even when Cider is the focused window and was the last thing I pressed play/pause on. I tested this on the Microsoft Edge and Brave web browsers. The result of this is that every time I want to play/pause my music on Cider while I have something simultaneously playing on my browser, it will always mess with my browser instance when I just want to control Cider only. It's worth noting the Cider Beta did not have this issue and my media controls would always prioritize play/pausing the last used application as it should. Thank you for making this program and reading this. <3

### Steps to Reproduce

1. Play video/audio from your browser.
2. While that is playing, play something on the Cider 2 application.
4. Try pressing play/pause on your media control keys on your keyboard.

### Build timestamp

1685307132315

**Comment by coredev-uk** [comment]
Cider does not control how Window prioritises audio. The only thing we can suggest is that you play Cider first, or run it as admin. 

@d3rpp if you can do anything with Tauri to change this that would be great.
