### ISSUE TITLE
[Bug]: Animated Artwork not working in Immersive Mode

### ISSUE THREAD

**Issue by jeleddddd** [ciderapp/Cider-2#237]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17/05/2023, 1:25:48 pm Quasar v2.11.10

### Operating System Version

Windows 11 Version 22H2

### Describe the Bug

Animated Artwork not working in Immersive Mode despite the toggle is on in the settings

### Steps to Reproduce

Play an album with animated artwork and turn on immersive mode

### Build timestamp

1686108754036

**Comment by coredev-uk** [comment]
It was a bit hit or miss around the time of this build. I did make a few changes that should resolve it. When the next build comes out give it a try, if its still happening feel free to reopen this issue.
