### ISSUE TITLE
[Bug] Cider insist on playing at the lowest quality (AAC 64kbits) on the Microsoft Store version

### ISSUE THREAD

**Issue by alexvojacek** [ciderapp/Cider-2#240]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3 Sabiiro

### Operating System Version

Windows 11

### Describe the Bug

Cider just bought from the Microsoft Store insist on playing almost all the tracks at the lowest quality possible and I can't seem to be able to change this.

Music plays at just 64kbits AAC while on the same Apple Music it shows 256kbits AAC Loseless.

At this point, the player is unusable if the sound quality is going to be this low.  I can spot the lower quality with almost every track on my BeyerDynamics DT-990

### Steps to Reproduce

Play any track.
Which for Quality Output.

### Anything else?

The first time I've opened the App it seemed to play at 256kbits and now I'm stuck forever at 64kbits.

**Comment by alexvojacek** [comment]
I found out why this is happening.  It's random but here it is:

- It's the Hi-Res images option enabled.

As soon as I enable that option, everything goes down to 64kbits AAC no matter what I do.  If I disable this option, everything goes up to 256kbits.

PS:  I have a 750Mbit fiber optics connections.. This should not be happening.

**Comment by alexvojacek** [comment]
Scratch that.  Worked 2 times.  Now it stopped working, even with Hi-Res images disabled. 
What is going on?

**Comment by alexvojacek** [comment]
There appears to be affecting some tracks and not others.  I would really like a reply on this issue.  I just purchased the App to help you guys on the development but I just can't use it like this.  It's playing more than half the tracks at 64kbits low AAC quality.

**Comment by alexvojacek** [comment]
Is there any dev checking the issues?.

**Comment by coredev-uk** [comment]
Please refer to this issue for full details, this will not be discussed further. 
https://github.com/ciderapp/Cider-2/issues/206
