### ISSUE TITLE
Cider showing as msedgewebview2

### ISSUE THREAD

**Issue by Sarojidipity** [ciderapp/Cider-2#242]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

built on 17/05/2023, Quasar v2.11.10

### Operating System Version

Windows 10 Pro version 22H2

### Describe the Bug

I use Eartrumpet (v. 2.2.2.0) to send sound from different programs to different outputs - for Cider I send it to my speakers. 

Cider shows up in Eartrumpet as a generic (program?) "msedgewebview2", so I have to reassign it to the correct device every time I open Cider. In version 1.x it showed up with the actual Cider icon and name, so Eartrumpet always remembered my preference.

All other program outputs are recognised and remembered by Eartrumpet, it appears to be due to the fact it is recognised as something generic, and thus a new process/program, rather than a distinct program.

### Steps to Reproduce

Start Cider, click play. Sound comes from default device.
Open the Eartrumpet quickmenu from the task bar - Cider shows as "msedgewebview2".
Assign to the correct output device in Eartrumpet.
Close Cider and re-open. Cider shows as msedgewebview2 and the sound output resets to default as if it was a new program, and needs to be re-assigned.

**Comment by alexvojacek** [comment]
I'm not a Dev but I can asume there is an issue somewhere and it is showing up the real program name.  This is because Cider was made basically on top of Microsoft Edge and it is using Edge for everything.  You're seeing a web program opened on a private windows of Microsoft Edge name as Cider, that's basically it.
