### ISSUE TITLE
Cider not filling snap sections correctly

### ISSUE THREAD

**Issue by Sarojidipity** [ciderapp/Cider-2#243]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

version 2.0.3, built on 17/05/2023, Quasar v2.11.10

### Operating System Version

Windows 10 Pro version 22H2

### Describe the Bug

I have a two monitors, with different resolutions - main monitor (3840 x 2160) and a second monitor (2560 x 1440).  When using windows snap to arrange windows on that lower resolution monitor, cider only fills a portion of the area when moving it to the lower right quadrant fairly consistently, and other sections sporadically.  I've tried to find a pattern for what causes it with the other sections, but can't.

Moving it to the top edge to make it go full screen works consistently, but when I remove it from that edge it can make the window incredibly huge (wider than both of my monitors), and if I attempt to resize it it can make the cider window disappear entirely (possibly automatically resizing to the size it should be, but beyond the bound of the viewable display area?), clicking on the icon does not make it reappear.  Dragging a different window to a snap section on that monitor will give the option of placing Cider an unfilled section, which will make the window reappear.

It appears to work correctly on the main monitor (4k).  All other programs will fill the areas correctly.

### Steps to Reproduce

Have two displays of different resolutions.

Have Snap enabled in Window Multi-tasking settings: 

"Automatically resize it to fill available space" selected.  
"When I snap a window, show what I can snap next to it" selected
"When I resize a snapped window, simultaneously resize any adjacent snapped window" selected
Virtual desktops set to "only the desktop I am using"

Open Cider. 
Drag the menu bar of Cider to the bottom right corner of the lower resolution display to highlight that quadrant and release.
Cider only fills a portion of the section.
Dragging to other corners/edges *may* show the same issue - sometimes does, sometimes doesn't.

Full screen works consistently, but removing it can cause the cider window to become incredibly large

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
