### ISSUE TITLE
Low Quality App Icon

### ISSUE THREAD

**Issue by CodingYolk** [ciderapp/Cider-2#244]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

5/17/2023

### Operating System Version

Windows 11 22H2

### Describe the Bug

![Screenshot 2023-06-09 13121645](https://github.com/ciderapp/Cider-2/assets/33628131/e4edbaba-8770-493f-9a9b-a592d4b151a2)

The logo appears to be low quality or miscolored in the taskbar.

### Steps to Reproduce

1. Launch Cider
2. Look at Taskbar

**Comment by coredev-uk** [comment]
Previously reported: https://github.com/ciderapp/Cider-2/issues/118
