### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Codshi** [ciderapp/Cider-2#245]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Fps droping on desk 

### Operating System Version

WIN 11

### Describe the Bug

How is it possible to pay 4 dlls for an app that is better than its free version?
more functions, (plugins, equalizer, performance, etc etc, they plan to improve it or better change the version of windows edition for the free one, the free one is a million times better, I am seriously thinking about a refund since it is useless, it ends losing functions the paid one LOL,

PAY TO LOSE

### Steps to Reproduce

nothing, always drop fps 

### Connect Device ID

Cider 2 

### Build timestamp

1686358100316

**Comment by coredev-uk** [comment]
It was your choice to buy it... If you want us to actually work on your issue you need to be more helpful instead of moaning about features in an app that has a completely overhauled codebase, UI and functionality set, and has only been in development for 6 months.
