### ISSUE TITLE
[Bug]: Low-res artwork on Editorial/Multiroom search pages

### ISSUE THREAD

**Issue by scarryaa** [ciderapp/Cider-2#247]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

v2.0.3 Sabiiro

### Operating System Version

Windows 11 Pro Version	22H2 build 22621.1702

### Describe the Bug

Artwork is blurry and low-res on editorial/us/multirooms/ search pages.

### Steps to Reproduce

1. Go to search page
2. Click on editorial/multiroom tile ("Hip Hop DNA", "Sing", etc)
3. Scroll down to media categories
4. Observe low res artwork

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/77030329/fd27fc8a-bc34-4c0e-8972-a23cc3de8b95)

### Build timestamp

1686421175085

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
