### ISSUE TITLE
Artist search bug

### ISSUE THREAD

**Issue by Paetrig** [ciderapp/Cider-2#248]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3 - Sabiiro

### Operating System Version

Version 21H2 (OS Build 22000.1936)

### Describe the Bug

When searching for artists in succession in the Artists tab of my Library, clicking the X to clear the search field does nothing. To continue searching, I must highlight the field's existing text and overwrite it.

In my testing, I have found this is specific and unique to the search field of the Artists tab and does not occur in other search fields (e.g. global search fields or search fields in other tabs and/or sections).

### Steps to Reproduce

1. In the Library section, click Artists.
2. In the Search field, enter an artist's name.
3. 
![image](https://github.com/ciderapp/Cider-2/assets/104074436/6e07d767-311e-4a9f-bfaa-d8bf81f61daf)
4. Click the X to clear the search field.
The contents of the Search field are not cleared.
To clear the contents of the Search field, highlight the text and replace.

**Comment by coredev-uk** [comment]
Clear button has been removed.
