### ISSUE TITLE
Line below screen when switching full screen

### ISSUE THREAD

**Issue by teddy0115** [ciderapp/Cider-2#251]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

quasar v2.11.10

### Operating System Version

windows 11 pro 22h2

### Describe the Bug

Line below screen when switching full screen! it is bad

### Steps to Reproduce

play music in full screen cider
press immersive button
press full screen button
![제목 없음](https://github.com/ciderapp/Cider-2/assets/136608993/72df53a4-b1ec-4cd1-88a5-417f8ff7245e)

**Comment by sethbrown321** [comment]
I had the same issue and was told that you can mitigate it by having the app not maximized when you enter immersive. Apparently something with the way Windows composites the app.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
