### ISSUE TITLE
[Bug]:playlist only showing 1000 songs when there's more than that

### ISSUE THREAD

**Issue by leelee901** [ciderapp/Cider-2#252]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

91d26a65a3dc310c7e68fef9d3d03144ce9de937

### Operating System Version

Windows 11

### Describe the Bug

I have 2 playlist that has more than 1000 song when i got to song 1000 it just goes back to the first song

### Steps to Reproduce

Simple just play the playlist to the 1,000th song or go to the bottom of the play list to see that the rest of the playlist is notloaded.

### Build timestamp

1686783428676

**Comment by Shotz5** [comment]
Same issue here except I'm limited to only 300 in a playlist.
![image](https://i.imgur.com/KyLdFMu.png)

Current build (Windows 11 22H2)
![image](https://i.imgur.com/teq5OHP.png)

**Comment by Shotz5** [comment]
300 song limit issue has randomly fixed itself for me and is now showing all 313 tracks. Definitely a bug here though as it was only showing 300 tracks for multiple days.

**Comment by marclallen** [comment]
Same issue here... in my case, it's 600.  It was 400, and I added a mess of songs... many of them don't show up.  According to my iPhone, I have well over 1000 (which means I had well over 600 originally, since I only added about 300 songs).

**Comment by Willij30** [comment]
Same issue, except ALL my playlists are capped at 400 songs.

**Comment by coredev-uk** [comment]
We're aware of issues with large playlists, we have an internal issue for handling this. Closing.
