### ISSUE TITLE
[Bug]:Cannot Login

### ISSUE THREAD

**Issue by blogdefotsec** [ciderapp/Cider-2#253]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Windows 11 Ver 22H2

### Describe the Bug

Nothing Happened while click on "Login to Apple Music" and "Apple Music"->"Sign in".

### Steps to Reproduce

1. Install in Microsoft Store
2. Open Cider 2
3. Click "Login to Apple Music"
4. Nothing happened while cilcked few times.
5. Click "Bypass"
6. Click "..." on the left ->Apple Music->Sign in
7. Nothing happened while clicked few times.

### Build timestamp

1686879243970

**Comment by blogdefotsec** [comment]
*While Cider Beta is able to open login window. But meets problem after 2-step-authorization.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
