### ISSUE TITLE
the listen along feature does not work properly

### ISSUE THREAD

**Issue by itsmateii** [ciderapp/Cider-2#254]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

i have purchased cider in january this year 

### Operating System Version

windows 11 pro 22h2

### Describe the Bug

the link option does not work for someone to connect, same as the settings button 

### Steps to Reproduce

1: i clicked on listen along button
2: i have created a party
3: i have sent the link to a friend
4: the friend saw that the link is not working to connect
5: i have opened settings aftere closing the party

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
