### ISSUE TITLE
Cider taskbar icon is too big

### ISSUE THREAD

**Issue by allpenguin** [ciderapp/Cider-2#255]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

build 2.0.3

### Operating System Version

Windows 11

### Describe the Bug

The Cider icon appears to be too large and does not show proper on the windows taskbar

### Steps to Reproduce

Specs
Windows 11
duo 1440p monitors
Cider version: 2.0.3

Steps
Once you start the Cider app you should notice the irregular size of the icon.

### Build timestamp

1686942225000

**Comment by cryptofyre** [comment]
Can't confirm this issue present in 2.2.0

**Comment by DottieDot** [comment]
This is still an issue for me 

![image](https://github.com/ciderapp/Cider-2/assets/22892293/3e9ba4c0-56ee-4078-ae0f-17bb8a768b79)

![image](https://github.com/ciderapp/Cider-2/assets/22892293/825973a7-96b8-44b6-a526-dc9d2da4d299)
