### ISSUE TITLE
Can't display Windows taskbar (auto-hide) if Cider window is focused and maximized

### ISSUE THREAD

**Issue by ZestMyu** [ciderapp/Cider-2#257]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

5/16/2023, 10:25:48 PM

### Operating System Version

Windows 10 version 22H2

### Describe the Bug

Windows taskbar (set to auto-hide) can't be displayed when Cider window is in focus and maximized.

### Steps to Reproduce

1. Set Windows taskbar to auto-hide while in desktop mode
2. Maximize Cider window
3. Have Cider window as the currently focused window

### Anything else?

What auto-hidden windows taskbar looks like:
![Windows_taskbar_auto-hide](https://github.com/ciderapp/Cider-2/assets/4792742/006f7798-34ca-4553-8720-5144e20fb4fd)

When Cider is both maximized and in focus:
![Cider_maximized](https://github.com/ciderapp/Cider-2/assets/4792742/2f148146-98f4-418e-9414-582c92ea2536)

**Comment by coredev-uk** [comment]
This appears to be an issue with how windows/webview handles the window. We cannot control things like this, out of our scope.
