### ISSUE TITLE
[Bug]: Show in Apple Music button when playing station restarts station

### ISSUE THREAD

**Issue by Xyl-AU** [ciderapp/Cider-2#260]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Windows 11 22H2

### Describe the Bug

I was playing my personal mix. I right clicked on the player and clicked "Show in Apple Music". Rather than the regular behaviour of going to the song in Apple Music, the station restarted.

### Steps to Reproduce

1. Play a station, such as your personal mix or by creating a station from a song.
2. Right-click on the player
3. Click "Show in Apple Music"

### Build timestamp

1687313677849

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
