### ISSUE TITLE
Music sound quality

### ISSUE THREAD

**Issue by sanarijang** [ciderapp/Cider-2#261]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Windows 11

### Describe the Bug

The music quality is only limit to 64kbps. I have tried to change every setting but it doesn't work.
![2023-06-21](https://github.com/ciderapp/Cider-2/assets/60514325/26be7366-40ad-4857-9e1f-c4e430a257db)

### Steps to Reproduce

When I play the music

**Comment by sethbrown321** [comment]
Okay, so the devs have said that they cannot do anything about this as this is an issue with MusicKit, so this is ultimately Apple's fault.
