### ISSUE TITLE
Failed to load because no supported source was found

### ISSUE THREAD

**Issue by mrcoprea** [ciderapp/Cider-2#262]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

21-06-23

### Operating System Version

Windows 10 Enterprise

### Describe the Bug

I'm unable to play any station, this message pops up "Failed to load because no supported source was found".

### Steps to Reproduce

1. Search: Romania
2. Scroll down and click on "Stations"
3. Play "Virgin Radio", "Kiss FM", etc.
3. Window message pops up.

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/122538186/2f1bd3d3-2a2d-45d0-905b-f2756d185cad)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
