### ISSUE TITLE
Songs are out of order if sorted by Date of Addition

### ISSUE THREAD

**Issue by JadenAnjara** [ciderapp/Cider-2#265]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Quasar v2.11.10

### Operating System Version

Windows 10 build 19045.3086

### Describe the Bug

Songs are out of order if sorted by Recently Added (they are not missing but are found later down the list, way later than where they should be)

![image](https://github.com/ciderapp/Cider-2/assets/30911537/6395cd95-922e-4495-8009-07a7e73c43e0)
![image](https://github.com/ciderapp/Cider-2/assets/30911537/7d8624b4-c961-4219-99b6-8a8e0dc5e6a2)
![image](https://github.com/ciderapp/Cider-2/assets/30911537/0b34feeb-adfe-433c-9cbc-9002f91e8bbe)

I expected here, taking Ed Sheeran and 21 Pilots as an example, to have either the songs sorted by actual Date of Addition (which would mean that some of the songs would be way later down the list, considering I added some songs to the 21P album as early as 2020), or clumped by albums but to the date when I added the first song of the album to my library or finally clumped by albums but at the position of the latest song addition to my library (more explanation in Steps to Reproduce)

### Steps to Reproduce

I'm gonna take two different albums in example here. **Vessels** by 21 Pilots and **- (Deluxe)** by Ed Sheeran. I added some songs from Vessels in 2020, some in 2021, some in 2022 and some in 2023 and some songs from the Ed Sheeran album on 20/05/2023 then another one on 19/06/2023

I guess to reproduce it you'd have to add different songs from a same album to the library, with other songs in between and compare how they get sorted in Songs tab of the library, sorted by Date of Addition

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
