### ISSUE TITLE
[Bug]: Clear Queue on Top Songs and Albums not working

### ISSUE THREAD

**Issue by Destroer47** [ciderapp/Cider-2#267]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Windows 10 Education Version 22H2

### Describe the Bug

I clicked on a song and played it from an artists top songs section, and saw that all the songs next in my queue were all their top songs. After I saw this I hit the clear queue button and then all the songs disappeared, but then when the song I was playing ended, it just played the next song like I had never cleared the queue, but in the mini player at the bottom of the screen, it was showing the previous songs info like it thought I was replaying the song I had just played, but what was actually playing was the next song on their top songs list. **UPDATE** Did more testing, clear queue is broken on albums too

### Steps to Reproduce

1. play an artist's top song / album
2. clear the queue 
3. let the song end
4. the next song will play still (when it shouldn't) and the song info will be wrong and messed up

### Build timestamp

1687662615266

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
