### ISSUE TITLE
Discord Linking Doesn't Work

### ISSUE THREAD

**Issue by Destroer47** [ciderapp/Cider-2#268]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Windows Store, 2.0.3 - Sabiiro

### Operating System Version

Windows 10 Education Version 22H2

### Describe the Bug

I signed up for Cider Connect, and then tried linking my Discord account by clicking the Discord link button and after I authorized it through Discord on my web browser, it would redirect to a cidercollective.dev link and get hung up on this website and never go through.

### Steps to Reproduce

1. I clicked on settings
2. I clicked on the Cider Connect button at the bottom of the settings sidebar (left of the screen)
3. I clicked on the Discord link button
4. A new tab on my web browser opened up, and I clicked authorize to authorize Cider access to Discord
5. It got hung up after it redirected me to the cidercollective.dev

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
