### ISSUE TITLE
[Bug]: Resize window to nothingness and unable to resize back to visibility

### ISSUE THREAD

**Issue by LenardValdez** [ciderapp/Cider-2#269]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Appimage package on version 2.0.3

### Operating System Version

Fedora workstation 38

### Describe the Bug

You can resize the windows to nothingness, no pixel visible for resizing back to visibility

### Steps to Reproduce

1. drag edge(left or right edge) the of window
2. resize the windows pass the opposite side 
[Screencast from 2023-06-25 20-22-16.webm](https://github.com/ciderapp/Cider-2/assets/23581438/8b55204a-e7c7-434f-91e7-1f26e9912af7)

### Build timestamp

1687695802345

**Comment by cryptofyre** [comment]
Fixed in 2.2.0..?

**Comment by LenardValdez** [comment]
> Fixed in 2.2.0..?

unfortunately no.
