### ISSUE TITLE
[Bug]:Dynamic Background Fails When Quitting Immersive Mode

### ISSUE THREAD

**Issue by potatoler** [ciderapp/Cider-2#270]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2023/5/17

### Operating System Version

Windows11 22H2 22621.1848

### Describe the Bug

After I quit immersive mode I found the dynamic background displays black rather than the colour of album cover.

### Steps to Reproduce

1. Play a song（and the background shows the colour of current album cover）
2. Go into immersive mode
3. Quit immersive mode（and the background turns black）

### Build timestamp

1687782903654

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
