### ISSUE TITLE
Adding songs to library often doesn't work

### ISSUE THREAD

**Issue by miketunes** [ciderapp/Cider-2#272]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3 - built 5/17/2023

### Operating System Version

Win11 22H2

### Describe the Bug

Clicking plus from search doesn't add song to library.
Clicking on plus on albums does not add album to libary.  

### Steps to Reproduce

Song Issue:
Search for song in search bar
right click song
click plus (does not add to library)

Album Issue:
Open Album
Click Add button (does not add to library)

Song Workaround:
open the album containing song
click plus, it spins for a second and does add it to library

Album Workaround:
Add from itunes instead

### Anything else?

.

**Comment by sontopo** [comment]
I'm having this issue as well

**Comment by emorris00** [comment]
From what I have seen it does actually add it to the library it just takes a while and there is no visual feedback.

**Comment by tyler-groves** [comment]
I believe the same may apply to albums, or at least the "add" button does not change to reflect the added state. After clicking the "refresh" button, the "add" button" changes to a checkmark reflecting the added state.

**Comment by cryptofyre** [comment]
Behavior for both of these has changed in 2.3.0 and it should be much more reliable now, closing this issue.

https://github.com/ciderapp/Cider-2/assets/33162551/f7cbf6af-9978-4146-b095-3863d3fc0777
