### ISSUE TITLE
Search does not focus on keyboard shortcut

### ISSUE THREAD

**Issue by eleanormally** [ciderapp/Cider-2#276]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Macos Ventura 13.4

### Describe the Bug

after pressing command+f, the app goes to the homepage instead of focusing the search bar. I have checked that meta+f is the shortcut for search and have manually set it as such. The searchbar should be highlighted, but also I don't think it should go to the home page, and should instead just focus search from the current page.

### Steps to Reproduce

press keyboard shortcut for search.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
