### ISSUE TITLE
[Bug]:The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by Ghost-D18** [ciderapp/Cider-2#281]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17-05-2023

### Operating System Version

Windows 11

### Describe the Bug

Often random crashes.

### Steps to Reproduce

While listen to music

### Build timestamp

1688479358392

**Comment by cryptofyre** [comment]
This behavior happens when you use PlayReady DRM, switch it back to Widevine or Default to avoid this behavior.
