### ISSUE TITLE
Music Videos not playing -> Playback Error

### ISSUE THREAD

**Issue by thedogmaniac** [ciderapp/Cider-2#282]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17.05.2023, Quasar v2.11.10

### Operating System Version

Windows 11 Pro N | Version 10.0.22621 Build 22621

### Describe the Bug

When I try to play Music Videos, I get a Playback Issue. The Song plays without any video, as soon as I click on the small picture of the music video, I get a reminder that there is a playback issue.

### Steps to Reproduce

1. Clicked on Music Videos Playlist
2. Clicked on Play or Shuffle
3. Takes a second to load
4. Music plays, video doesn't
5. after clicking on video icon the message with the error pops up

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
