### ISSUE TITLE
[Bug]: playlists fail to load

### ISSUE THREAD

**Issue by selly139** [ciderapp/Cider-2#286]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Had cider for a couple weeks.

### Operating System Version

Windows 10

### Describe the Bug

My playlists will not load in the library section

### Steps to Reproduce

Each time I launch cider (only the last several times) it says that the application is trying to make a playlist cache but it never completes

### Build timestamp

1688763086961

**Comment by jaydeelive01** [comment]
I have the same issue !

**Comment by cryptofyre** [comment]
Duplicate issue and also known, fixed in v2.1 closing.
