### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by bnbliss** [ciderapp/Cider-2#287]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

05/16/2023

### Operating System Version

Windows 11 insider 230608

### Describe the Bug

Playlists won't populate. Keeping getting a spinning "Building Playlist Cache"

### Steps to Reproduce

clicked on All Playlists

### Anything else?

click on the All Playlists button

### Build timestamp

1688842918143

**Comment by jaydeelive01** [comment]
I also have this issue !

**Comment by samrossclayton** [comment]
also experiencing this issue. signing into apple music again and reinstalling app from store did not fix.

**Comment by samrossclayton** [comment]
> also experiencing this issue. signing into apple music again and reinstalling app from store did not fix.

update: the issue seems to have resolved itself. unsure if ms pushed through an update but all's well
