### ISSUE TITLE
Notification Overload

### ISSUE THREAD

**Issue by Keloran** [ciderapp/Cider-2#289]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

52956d5

### Operating System Version

Linux framework 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux

### Describe the Bug

Cider 1 had an option of "playback notifications" this enabled/suppressed the notifications sent to notifyd this option appears to be missing from Cider2

because this is missing every song change sends a new notification

### Steps to Reproduce

Have notifyd, and something that can listen to it, e.g. Sway-Notification-Center

play song

**Comment by coredev-uk** [comment]
The option will be available in connectivity settings on the next release.
