### ISSUE TITLE
Immersive mode is broken on small resolutions

### ISSUE THREAD

**Issue by SkyRexHUN** [ciderapp/Cider-2#290]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Quasar v2.11.10 Built on 17/07/2023

### Operating System Version

Windows 11 Pro x64 22H2

### Describe the Bug

When using immersive mode and the Windows 11 snap layout feature (to 1/4th of a 1080p screen), the One (default) style is completely broken (see attachment 1).
![image](https://github.com/ciderapp/Cider-2/assets/92554890/685795eb-4eca-47b1-9eab-bdb4894ddbf1)
The Sonoma style is broken too (see attachment 2).
![image](https://github.com/ciderapp/Cider-2/assets/92554890/0dad45ba-dcb6-4c71-8f51-0e347b064a24)

Additionally, after a song has finished playing, or skipping, the upcoming tab becomes empty (see attachment 3).
![image](https://github.com/ciderapp/Cider-2/assets/92554890/c4084e63-f3da-4964-ad86-4f5f3c838054)
This also happens on bigger app sizes (see attachment 4).
![image](https://github.com/ciderapp/Cider-2/assets/92554890/244777cf-3ea3-4bd2-8e7a-b6ba413a51d8)

Hope you can fix this, I love using the immersive mode, it's very aesthetic.

### Steps to Reproduce

1. Snap Cider window to quarter of screen
2. Click on immersive mode (any of the themes)
3. For the up next section, just skip a song or wait for the next one, both clears the list.

### Anything else?

Snap layout
![image](https://github.com/ciderapp/Cider-2/assets/92554890/b76fd18c-f81f-4e74-9dfe-05e486432c1d)

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
