### ISSUE TITLE
[Bug]:U cant control play stop and next song putting ur cursor in the window

### ISSUE THREAD

**Issue by TakeshiFudo** [ciderapp/Cider-2#291]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Today

### Operating System Version

Windows 11

### Describe the Bug

U cant control the songs putting ur cursor in the windows

### Steps to Reproduce

1. Play a song
2. Put your cursor in the window cider
3. u cant pause play next song

### Anything else?

a

### Connect Device ID

a

### Build timestamp

1689643083706

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
