### ISSUE TITLE
Panel font display issue

### ISSUE THREAD

**Issue by thunderbuddy85** [ciderapp/Cider-2#292]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.0.0

### Operating System Version

Windows 11 v22H2 22621.1992

### Describe the Bug

Space limitations with the font that cuts off the bottoms of letters like 'p, y, g'.

Desktop res: 4k with scaling at 150%
Surface Pro - 2880x1920 with scaling to 150%

Changing either of these devices' res or scaling does not fix it

### Steps to Reproduce

Logging into the app. This seems to only appear on the left side panel as the main window does not display this behavior.

<img width="169" alt="image" src="https://github.com/ciderapp/Cider-2/assets/80337902/d5445780-e7e0-4015-819e-0c4b64bc176b">

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
