### ISSUE TITLE
Song playing adds to queue when clicking the last track button.

### ISSUE THREAD

**Issue by shayanz23** [ciderapp/Cider-2#293]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Thu 06 Jul 2023

### Operating System Version

Linux, Opensuse Tumbleweed

### Describe the Bug

Song playing adds to queue when clicking the last track button.
![Screenshot from 2023-07-19 22-23-58](https://github.com/ciderapp/Cider-2/assets/35084589/974b68ce-a6d5-40a7-808f-0f82584fa673)

### Steps to Reproduce

1. start playing a playlist
2. click previous track button 
3. look at the queue
4. profit?

### Anything else?

Im using the 07/07/2023 pre-release from booploops on discord.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
