### ISSUE TITLE
LastFM isn't scrobbling itunes local files and Discord Rich Presence isn't displaying itunes local files infos

### ISSUE THREAD

**Issue by Joviverde** [ciderapp/Cider-2#296]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

22/07/2023 5:28 AM

### Operating System Version

Windows 11

### Describe the Bug

the title is self explanatory, cider isnt scrobbling music that was added to itunes using mp3 files and the music info of those songs isnt showing on discord rich presence

### Steps to Reproduce

1. Play a song added to iTunes
2. Check last.fm page
3. Check discord rich presence

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
