### ISSUE TITLE
"Credits" Tab on songs properties slide the opposite way it was supposed to

### ISSUE THREAD

**Issue by variananora** [ciderapp/Cider-2#297]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7/17/2023 11:46:46AM

### Operating System Version

Windows 10 22H2

### Describe the Bug

When looking at songs properties clicking the tab credits will slide the thing the opposite direction, for example you are from "Credits" tab then to "Artists" tab, it should slide from right to left, but we got it from left to right. This also flipped from "Artists" to "Credits".

### Steps to Reproduce

1. Play any song
2. Open up properties
3. Click "Credits" tab
4. Click "Artists" tab
5. See the animation is flipped

### Anything else?

Video for clarification: https://youtu.be/yji5b2EVOQM

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
