### ISSUE TITLE
Extra song properties doesn't load if you open it from your library

### ISSUE THREAD

**Issue by variananora** [ciderapp/Cider-2#298]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7/17/2023 11:46:46AM

### Operating System Version

Windows 10 22H2

### Describe the Bug

Opening song properties so see extra details like "Credits" or "Audio Analysis" doesn't show up if you open your song properties from your songs library. It works fine if you open it from currently playing songs or the search/artist/album.

### Steps to Reproduce

1. Open your songs library
2. Open any song properties
3. See the extra details is missing

### Anything else?

Video for clarification: https://youtu.be/3YfiTa2EPj8

**Comment by cryptofyre** [comment]
Normal query behavior, not much we can do about it due to how Apple returns API data.
