### ISSUE TITLE
Weird now playing animation in song library

### ISSUE THREAD

**Issue by variananora** [ciderapp/Cider-2#299]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7/17/2023 11:46:46AM

### Operating System Version

Windows 10 22H2

### Describe the Bug

Playing songs from songs library then right clicking on currently playing songs will remove the "now playing" animation on the song. Also there is weird animation on now playing songs when right clicked for the first time. My words here are probably a little bit confusing, check the video below for clarification.

### Steps to Reproduce

1. Open your songs library
2. Play any song properties
3. Right click on currently playing songs (the player below)
4. See the now playing animation on library is gone and the player 'refresh'

### Anything else?

Video for clarification: https://youtu.be/K_EzCAF8cRo

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
