### ISSUE TITLE
Choose music & Rich Presence (Apple Music doesn't work)

### ISSUE THREAD

**Issue by enzoo27** [ciderapp/Cider-2#300]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

I bought it on 07/22/2023 on Microsoft Store

### Operating System Version

Windows 11

### Describe the Bug

When I click on a specific music in my playlist, it chooses another music for me.
Another thing too, when I click for the rich presence on "Apple Music" it stays on "Cider 2"

### Steps to Reproduce

When I click on a specific music in my playlist, it chooses another music for me.
Another thing too, when I click for the rich presence on "Apple Music" it stays on "Cider 2"

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
