### ISSUE TITLE
[Bug]: Discord RPC doesn't work on Silicon Mac

### ISSUE THREAD

**Issue by Moresteck** [ciderapp/Cider-2#301]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

2023-07-22

### Operating System Version

macOS Ventura 13.4.1 (M1)

### Describe the Bug

Discord RPC simply doesn't work. I've tried to change the application id to `AppleMusic` or `Cider` — no difference. I've made sure I started Discord before Cider. I've tried resetting my Cider data. Tried the Intel version too. In the end, tried to reboot the Mac. All to no avail. Every other DiscordRPC-application I use appears fine (so it can't be my Discord settings either).

PS. I've got no idea where Cider 2 stores logs.

### Steps to Reproduce

1. Download and run Cider
2. Go through the setup process
3. Go to settings, enable Discord RPC under Connectivity
4. Start playing a song
5. Notice that Discord RPC doesn't work

### Build timestamp

1690066328438

**Comment by Moresteck** [comment]
Confirmed on macOS Ventura 13.5

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
