### ISSUE TITLE
[Bug]: Apple Music Radio Player

### ISSUE THREAD

**Issue by bddylol** [ciderapp/Cider-2#302]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Installed Cider today, not sure what part of the build.

### Operating System Version

Windows 11 22H2

### Describe the Bug

With the Apple Music Radio, you can see the playback controls and when it starts and ends. That bugs out,

### Steps to Reproduce

1. Listen to Apple Music Radio
2. Look at the playback controls

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/55510116/b8c00acd-7f7c-49c2-91b6-9ddadd8de380)

### Build timestamp

1690163554743

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
