### ISSUE TITLE
[Bug]: Changing Apple ID behavior

### ISSUE THREAD

**Issue by loudmog** [ciderapp/Cider-2#304]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.0

### Operating System Version

Windows 11 22621.1992

### Describe the Bug

Changed Apple ID on another device yesterday,  today I was unable to access Cider without removing and reinstalling. This includes killing the app. Selecting sign in with Apple ID produces no behavior.

### Steps to Reproduce

Change Apple ID on another device
Open Cider
Attempt to sign in

### Build timestamp

1690305514193

**Comment by loudmog** [comment]
Would like to comment that removing Cider and reinstalling from Windows Store produced the desired behavior.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
