### ISSUE TITLE
[Bug]: No chromecast icon to connect to devices

### ISSUE THREAD

**Issue by jerbeck24** [ciderapp/Cider-2#305]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

07/26/23 from itch.io

### Operating System Version

Ventura 13.5

### Describe the Bug

I cannot find how to cast to devices using chromecast in version 2.1.0

### Steps to Reproduce

Open the app and there is not casting icon anywhere.

### Build timestamp

1690344163446

**Comment by cryptofyre** [comment]
Fixed in 2.2.0

**Comment by Shanayara** [comment]
Where is the Chromecast icon supposed to be? I can't find it and there is no mention in the docs about it. I can find the Airplay icon when enabling it in settings explicitly (but it straight up doesn't find my Airplay devices anyhow). Chromecast icon doesn't exist.
