### ISSUE TITLE
[Bug]:Playlist Profile Picture not loading

### ISSUE THREAD

**Issue by justusk18s** [ciderapp/Cider-2#306]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 17.7.2023, 06:46:46 | Quasar v2.11.10 | Sabiiro 9fe528a840fcde410ac059b600597cebb7d8155e

### Operating System Version

Windows 11 22H2

### Describe the Bug

When opening a Playlist, the Authors Profile Picture us not being shown instead there is just a loading animation.

### Steps to Reproduce

1. Open a Playlist
2. Done

### Anything else?

![Screenshot 2023-07-26 211117](https://github.com/ciderapp/Cider-2/assets/75168050/d9ae672f-4842-4e1f-9530-05574049c0da)

### Connect Device ID

Sabiiro 9fe528a840fcde410ac059b600597cebb7d8155e

### Build timestamp

1690397827022

**Comment by coredev-uk** [comment]
The author probably doesn't have a profile picture set.

**Comment by coredev-uk** [comment]
Could you please provide a link to this playlist?

**Comment by justusk18s** [comment]
https://music.apple.com/de/playlist/wdr-4-top-444/pl.u-jV899rptDXApda

You are right. The author only has the standard initials set.
