### ISSUE TITLE
[Bug]: Bug in playAtIndex causes offset when unavailable songs in playlist

### ISSUE THREAD

**Issue by beyonik** [ciderapp/Cider-2#307]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Build date: 7/17/2023 7:46:46 AM

### Operating System Version

Windows 11 22H2

### Describe the Bug

A logic bug in the ``playAtIndex`` function causes playlists to be offset by the number of unavailable songs preceding the song you're trying to play, only if the song is not in the first 5 in the playlist.

The check in question is: ``Math.abs(v - t) < 5``. I'm not sure why this check exists, even though I'm sure there is a very good reason, all I know is removing it fixes this bug in my case. This check used in the find algorithm causes the song to not be found and the index variable to not be overwritten, which leads to the original value being used (which includes the unavailable songs and leads to the wrong song being played).

### Steps to Reproduce

Create a playlist with at least 5 songs, include some unavailable songs and after the unavailable songs add a couple songs which can be played. When trying to play any of the songs after the unavailable ones, it will play a song located lower in the playlist.

### Anything else?

-

### Build timestamp

1690493176547

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
