### ISSUE TITLE
[Bug]: Cider Audio Labs CAP Strength option tooltip references non-existing suboption

### ISSUE THREAD

**Issue by Wyatt-Stanke** [ciderapp/Cider-2#309]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 7/22/2023, 4:06:02 PM

### Operating System Version

macOS Ventura 13.3.1 (a) (22E772610a)

### Describe the Bug

When configuring the Cider Audio Labs and changing the CAP Strength, if you hover over the dropdown it says "(Aggressive may yield undesirable results)", but there is no "Aggressive" option.
Screenshots:
![image](https://github.com/ciderapp/Cider-2/assets/47758296/667ac00e-6544-41b5-8b55-cb737b69607d)
![image](https://github.com/ciderapp/Cider-2/assets/47758296/286f66fc-8fab-49d4-a607-d2450b096da6)

### Steps to Reproduce

1. Click on the Cider Audio Labs button
2. Hover over CAP Strength

### Build timestamp

1690657117655

**Comment by maikirakiwi** [comment]
In the latest prerelease, all options are deprecated leaving a simple switch for on/off which uses "Maikiwi (Adaptive+)."
