### ISSUE TITLE
[Bug]: Discord RPC not working on Linux

### ISSUE THREAD

**Issue by Ratintosh** [ciderapp/Cider-2#310]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

7/22/2023

### Operating System Version

Kubuntu 22.04.2 LTS x86_64  

### Describe the Bug

Whenever I go to play music, Discord doesn't show Cider as my activity status.

### Steps to Reproduce

1. Play a song
2. Nothing shows in my Discord status

### Anything else?

I've tried everything I can to troubleshoot the issue. I noticed that in the console, it spits out this error:

[Module][com.ciderapp.discordrpc] Discord RPC Client Ready
(node:26231) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'link')

It might be related.

### Build timestamp

1690764386953

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
