### ISSUE TITLE
[Bug]: Visual glitch in the player (maverick)

### ISSUE THREAD

**Issue by Interstellar73** [ciderapp/Cider-2#311]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 7/16/2023, 9:46:46 PM | Quasar v2.11.10 | Sabiiro

### Operating System Version

Windows 11 Home version 22H2

### Describe the Bug

when opened not in fullscreen, then fullscreen. bar at the top is slightly offset. (maverick player position)
![image](https://github.com/ciderapp/Cider-2/assets/130942323/c03a6532-8567-4dbf-9d95-c84b71d6d133)

### Steps to Reproduce

open cider not in fullscreen, then fullscreen.

### Build timestamp

1690915957076

**Comment by Amaru8** [comment]
Hey there! The reported issue was resolved in [version 2.2.0](https://outline.cider.sh/s/2-2-0-changelog). Make sure to install the latest update available on your respective platform.

![image](https://github.com/ciderapp/Cider-2/assets/52407090/1cf305aa-d102-418d-9dbb-b1baea5bad23)
