### ISSUE TITLE
[Bug]: I am unable to search within my library

### ISSUE THREAD

**Issue by selly139** [ciderapp/Cider-2#312]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Like 2 months ago

### Operating System Version

Windows 10

### Describe the Bug

I am able to search all of apple music for music, but I am not able to search within my library. After I hit search nothing happens, this has been occurring for about 2 weeks probably, so I just search all of apple music or use other tabs. But, it'd be nice to have this feature available again.  

### Steps to Reproduce

I have tried to use the library search option several times, but it has failed to execute any change to the interface. 

### Build timestamp

1690945385339

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
