### ISSUE TITLE
[Bug]: Now Playing duration shows wrong duration

### ISSUE THREAD

**Issue by Kentakoong** [ciderapp/Cider-2#313]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

7/23/2023 2:58:11 AM | Quasar v2.12.0 | Electron

### Operating System Version

macOS Ventura 13.4.1(c)

### Describe the Bug

<img width="1710" alt="Screenshot 2023-08-02 at 19 55 10" src="https://github.com/ciderapp/Cider-2/assets/35761701/a5e97e59-79d0-4289-8b85-c95f14b47a51">
Wrong duration shown.

### Steps to Reproduce

Play any music on macOS, click on mac's media control(or any apps that are using the Now Playing API) and that's where it's shown

### Build timestamp

1690980977198

**Comment by cryptofyre** [comment]
macOS and Chromium have this bug with stream able content, not much we can do about this.
