### ISSUE TITLE
Explicit Mode

### ISSUE THREAD

**Issue by AngeloDg01** [ciderapp/Cider-2#315]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

now

### Operating System Version

Windows 10

### Describe the Bug

I can listen 5 songs on 15 of the new album of ICONA POP. I think is because the explicit mode is on but i dont know how to put off

### Steps to Reproduce

Search Icona pop, click the new album and try to listen all the songs

**Comment by Vinicius-Icaro** [comment]
Same problem here
Happens in all explicit songs : /

**Comment by xBiei** [comment]
Go to iTunes Store app and select an explicit song,
click the price button is if you're purchasing the song,
you'll see an alert, just click allow and you'll be allowed to listen to explicit stuff.

**Comment by xBiei** [comment]
https://github.com/ciderapp/Cider-2/discussions/398

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
