### ISSUE TITLE
[Bug]: Immersive view not showing animated album cover if the song is being played from library

### ISSUE THREAD

**Issue by Wyatt-Stanke** [ciderapp/Cider-2#316]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 7/22/2023, 4:06:02 PM

### Operating System Version

macOS Ventura 13.5 (22G74)

### Describe the Bug

If you start playing a song from your library and open immersive view, the animated album cover doesn't play, but if you start playing the song from search, it does.

### Steps to Reproduce

1. Start song from library
2. Open immersive view

### Anything else?

Video examples:

https://github.com/ciderapp/Cider-2/assets/47758296/023903c5-5d0e-46f8-94f4-e317ce0bef66

https://github.com/ciderapp/Cider-2/assets/47758296/d0dc555f-60a6-4302-84f7-f3b622e99574

### Build timestamp

1691173351742

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
