### ISSUE TITLE
[Bug]: Blank screen after clicking specific album

### ISSUE THREAD

**Issue by 1100a** [ciderapp/Cider-2#317]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2023. 7. 17. 오후 1:46:46 | Quasar v2.11.10 | Sabiiro

### Operating System Version

Windows 11 22H2

### Describe the Bug

I can't see content of "V EXTENSION IV (Original Soundtrack)" album.

### Steps to Reproduce

1. Open [V EXTENSION IV (Original Soundtrack)](https://music.apple.com/kr/album/v-extension-iv-original-soundtrack/1690336088) album.

### Build timestamp

1691222924878

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
