### ISSUE TITLE
[Bug]: Cider doesn't remember window size

### ISSUE THREAD

**Issue by trparky** [ciderapp/Cider-2#318]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 8/5/2023, 7: 16:36 AM I Quasar v2.12.3 1 Sabiiro 9ba65ac8c786a640589458a3faeeb34074c6@9d9

### Operating System Version

Windows 11 22H2

### Describe the Bug

Cider doesn't remember window size. You can resize the window, close the program and relaunch it yet it will not relaunch with the previous window size.

### Steps to Reproduce

1. Launch Cider.
2. Resize the program window to what you want the size of the window to be.
3. Close Cider.
4. Relaunch Cider.
5. Note how the program window isn't the size you had before you closed and relaunched Cider.

### Connect Device ID

svPaexmPIKPLGtGQZyaP

### Build timestamp

1691332846334

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
