### ISSUE TITLE
[Bug]: Queue disappears every time a new song starts

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#320]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.2 built on 8/6/2023

### Operating System Version

Windows 11 22H2

### Describe the Bug

Any time a new song starts playing, the queue disappears from view; the pane stays open, but all the songs within it go invisible and don't reappear without closing and re-opening the queue. Occurs in both standard and immersive view.

### Steps to Reproduce

1. Opened a playlist and pressed shuffle
2. The first song is played and the queue is filled
3. Once the song starts playing, the queue disappears

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/95056585/8deac286-686b-40f3-9600-59f40846dde4)

### Build timestamp

1691519415092

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
