### ISSUE TITLE
[Bug]: F5 refreshes the app and stops music playback

### ISSUE THREAD

**Issue by nikosalonen** [ciderapp/Cider-2#321]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7.46.46

### Operating System Version

Microsoft Windows 11 Pro Version	10.0.22631 Build 22631

### Describe the Bug

OS Name	Microsoft Windows 11 Pro

### Steps to Reproduce

1. Play music
2. Press `F5`
3. UI reloads, and music is stopped

### Build timestamp

1691645065712

**Comment by coredev-uk** [comment]
F5 is meant to reload the app, just don't press it. It's not a bug, but something baked into all renderer processes we use as its what browsers do.
