### ISSUE TITLE
[Bug]: Thai Lyrics Doesn't show correctly.

### ISSUE THREAD

**Issue by toonnongaeoy** [ciderapp/Cider-2#323]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Quasar v2,12,3 | Sabiiro | Built on 8/5/2023

### Operating System Version

Windows 10 version 22H2

### Describe the Bug

Some Thai song that have Apple Sing, Like ทราบแล้วเปลี่ยน (attention please) or อาวรณ์ (I Want You). Vowel like -้ -ู -ี doesn't show when like you need to sing this song (I don't know how to describe that) but other else, it display correctly.

Same guy as reported on Discord.
![image](https://github.com/ciderapp/Cider-2/assets/82090464/02a34af0-7e9e-465a-b1fa-1e4a64a98399)

### Steps to Reproduce

Just listen to any Thai Song that have Apple Sing on, Like ทราบแล้วเปลี่ยน (attention please) or อาวรณ์ (I Want You). 

### Build timestamp

1691680801466

**Comment by cryptofyre** [comment]
We've made some changes to how Sing lyrics are displayed, this might be fixed in 2.2.0.

**Comment by toonnongaeoy** [comment]
Still Happen on 2.2.0 Pre-Release 2
![Screenshot_20230921_233158](https://github.com/ciderapp/Cider-2/assets/82090464/a8f29454-07d9-489d-919d-30f37011972e)

**Comment by toonnongaeoy** [comment]
Maybe, I will try on Windows later.
