### ISSUE TITLE
unable to add playlist to library

### ISSUE THREAD

**Issue by LFbbyyy** [ciderapp/Cider-2#324]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

version 2.1.0 - sabiiro

### Operating System Version

windows 11

### Describe the Bug

the add button on playlists makes a little animation when clicking it but goes back too just add and the playlist isnt added to my library.

### Steps to Reproduce

try and add a playlist

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
