### ISSUE TITLE
Timestamp wrong place

### ISSUE THREAD

**Issue by orjawell** [ciderapp/Cider-2#325]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17/07/2023, MS-Store, V.2.1.0

### Operating System Version

Windows 10 21H2

### Describe the Bug

Wrong placement of the timebar.

![image](https://github.com/ciderapp/Cider-2/assets/69430732/9116b1b4-a7e1-4fdf-9d7d-2652e75face1)

Player position : Mavericks

### Steps to Reproduce

Sadly, idk, I just launched Cider 2 and this happened

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
