### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by WayneBTB** [ciderapp/Cider-2#327]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

22/07/2023

### Operating System Version

macOS 14 Sonoma beta 5

### Describe the Bug

Cider JavaScript error on reopening main window.

### Steps to Reproduce

1. Opened the Cider app
2. Closed the Cider window
3. Tried to reopen Cider again

### Anything else?

This is the exact error message.
![CleanShot 2023-08-11 at 13 52 40@2x](https://github.com/ciderapp/Cider-2/assets/61112327/52eceeef-8726-40af-8bf2-ede2bb22bf88)

### Build timestamp

1691754161246

**Comment by andrewbaker-uk** [comment]
Seeing the same issue with Ubuntu 23.04 when Minimise to Tray is enabled
