### ISSUE TITLE
Mini Player is always on top

### ISSUE THREAD

**Issue by jrbanach** [ciderapp/Cider-2#328]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7/17/2023 12:46am

### Operating System Version

Windows 11 Insider Preview

### Describe the Bug

When I change to the mini player, the app defaults to being always on top.  

I like the mini player, but i have a large screen and want to stick it in a corner but also don't want it always on top. 

### Steps to Reproduce

Click on Mini PLayer.
Tried to hide it behind other windows

**Comment by Vinicius-Icaro** [comment]
A while ago, I opened an issue requesting that the mini-player always stay on top.
As it was in Cider 1, however in that version of Cider there was the possibility to fix or not the mini-player window. I think this is the solution for everyone to be happy.

https://github.com/ciderapp/Cider-2/issues/154

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
