### ISSUE TITLE
[Bug]: Chosen locale's metadata being ignored after restart, shows in storefront's default locale instead

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Cider-2#329]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 8/9/2023, 12:31:02 PM

### Operating System Version

Windows 11 22H2 Build 22621.1992

### Describe the Bug

Upon selecting a new language in the settings panel, metadata served will change accordingly as expected. However, once Cider is restarted, it instead serves metadata in the storefront's default locale, ignoring the preferred locale.

For example, changing the locale to `ja` will serve metadata in Japanese as expected:

![1](https://github.com/ciderapp/Cider-2/assets/79871965/0c04eb67-bd0a-409d-a597-6fe12cee853e)

Upon restarting Cider, it will instead serve metadata in the storefront's default locale, in my case `en-US`, ignoring the currently selected locale:

![2](https://github.com/ciderapp/Cider-2/assets/79871965/6a72d30d-65ae-4812-bd9d-9f36c1217ae9)

### Steps to Reproduce

1. Select a different language through the settings panel
2. Restart Cider
3. Metadata will now be displayed in your storefront's default locale instead of your preferred one

### Build timestamp

1691865609107

**Comment by cryptofyre** [comment]
Should work as intended now in 2.2.0
