### ISSUE TITLE
[Bug]: Pressing Spacebar Doesn't Always Play/Pause Current Track

### ISSUE THREAD

**Issue by joshlewis** [ciderapp/Cider-2#330]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Version 2.1.1

### Operating System Version

macOS Ventura 13.4.1 ©

### Describe the Bug

When Cider is in the foreground, hitting the spacebar should _always_ pause the current playing song, or if it is paused, continue playing it. That doesn't happen.

### Steps to Reproduce

1. Brought Cider to the foreground. 
2. Began playing a song
3. Clicked in an empty spot on the application, just to make sure no particular UI element was highlighted or focused. 
4. Hit spacebar
5. Noticed the song did not pause

### Build timestamp

1691875413008

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
