### ISSUE TITLE
Lyrics are incorrect for song

### ISSUE THREAD

**Issue by anonmily** [ciderapp/Cider-2#331]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2023-08-12

### Operating System Version

Windows 11

### Describe the Bug

When playing Chinese songs, the lyrics seem to be completely incorrect... Seemed to be happening for all non-English songs.
![image](https://github.com/ciderapp/Cider-2/assets/8203544/7d16b87b-cecd-4c02-956f-42d3c339f702)

However, after I played an English song to check the lyrics, I went back and tried Japanese/Chinese songs again, and the lyrics were working after that. However, I was able to reproduce the issue after closing Cider and reopening it again. It seems that if you start Cider and try playing a non-English song right after opening, the lyrics are unable to be matched for some reason. You have to play an English song first before lyrics start to work again.

### Steps to Reproduce

1. Open Cider
2. Immediately try playing a Chinese song on Apple music (e.g. 燕无歇 by Snow Jiang)
3. The lyrics are incorrect

### Anything else?

Currently on Cider version 2.1.0
Built on 7/19/2023, 9:46:46PM Quasar v2.11.10 Sabiiro
Windows 11

**Comment by genericness** [comment]
Ask Apple Music or MusixMath, Cider doesn't do it

**Comment by anonmily** [comment]
? The problem is that Apple Music Lyrics is just fine. It is just Cider with the problem
