### ISSUE TITLE
Playlists Stop At 100

### ISSUE THREAD

**Issue by Ezyne23** [ciderapp/Cider-2#332]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.1.0 - Build 2023/7/16 (Quasar v2.11.10)

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

When going through my playlists, I noticed a few of them were stopping at 100 Songs when each one had 100+. The result is that all the music in the playlist after the 100th Song does not appear in the playlist, and I instead have to go searching through my library or forget what other songs I had in the playlist -- I have noticed it only seems to be playlists between 100 and 300 (possibly higher), for I have playlists under 100 that are just fine, and one in the 600s that is also the correct amount (There is one with 202 that also stops at 100 however).

### Steps to Reproduce

I was just simply listening to a playlist when I noticed it abruptly end earlier than it should have. When I looked, I noticed it only had 100 Songs, and in checking my other playlists I noticed they also stopped at 100. All of these playlists should have from 110 to 202 (each one is a different real amount but all stopped at 100)

### Anything else?

The following are two screenshots of the same playlist, 1st being in Cider 2 and 2nd being in Apple Music Preview.

![image](https://github.com/ciderapp/Cider-2/assets/134811348/c1c0ffe2-17b5-4f2b-a89f-f31d6c6f0dec)
![image](https://github.com/ciderapp/Cider-2/assets/134811348/2ac1b7c1-8cd1-47c8-903b-5085ea7650a9)

These are also one single playlist, with 1st being Cider 2 and 2nd being Apple Music Preview.

![image](https://github.com/ciderapp/Cider-2/assets/134811348/edb9483d-2228-4312-aa1e-c3e192df7cf4)
![image](https://github.com/ciderapp/Cider-2/assets/134811348/de547589-37a7-40f1-9fce-5d370aa82c10)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
