### ISSUE TITLE
Unable to shuffle play in Songs in Library

### ISSUE THREAD

**Issue by tomakura-aren** [ciderapp/Cider-2#333]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.1.0 - Build 2023/7/16 (Quasar v2.11.10)

### Operating System Version

Windows 11 Pro 22H2

### Describe the Bug

ライブラリのSongsにあるシャッフル再生ボタンを押しても機能しない。

### Steps to Reproduce

この画像の右上にあるシャッフルボタンを押しても何も動かない。
![image](https://github.com/ciderapp/Cider-2/assets/38022277/e6f574b9-a7cf-4c88-b6c7-5936de39b477)

**Comment by maikirakiwi** [comment]
Issueで問題の報告ありがとうございました。

**Comment by maikirakiwi** [comment]
Issueで問題の報告ありがとうございました。
今確認してみます。
もしDiscordを使ってるなら、是非Ciderの[サーバ](https://discord.gg/applemusic)に参加してみませんか？

**Comment by maikirakiwi** [comment]
Fixed in versions newer than or equal to 2023/8/16
