### ISSUE TITLE
Linux KDE Media Player widget volume control action doesn't work and can crash Cider Appimage

### ISSUE THREAD

**Issue by gabeklavans** [ciderapp/Cider-2#335]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

8/18/23

### Operating System Version

Nobara Linux 38 (KDE 5.27.6, X11, Kernel 6.4.10-202.fsync.fc38.x86_64)

### Describe the Bug

The built-in KDE Media Player widget is designed to be able to adjust the volume of the application that is playing media. The song info comes through just fine, and pause/play/skip works. But changing the volume does not affect the volume of the Appimage version of Cider-2 (changing the volume on the panel icon does work, however).

Rarely, trying to change the volume in the Media Player widget can crash the app with the following error:
![image](https://github.com/ciderapp/Cider-2/assets/32149200/4cd894f3-50e9-458d-826a-75aa5453d76e)

### Steps to Reproduce

1. Launch the app and play a song
2. Hover mouse over the KDE Media Player widget
3. Scroll mouse-wheel

### Connect Device ID

Cider Linux 6.4.10-202.fsync.fc38.x86_64

### Build timestamp

7/22/2023, 7:13:44 AM

**Comment by coredev-uk** [comment]
Dont think our MPRIS plugin (which integrates with KDE's media player) supports volume control, ill have a look to see if we can get it added

**Comment by thiccaxe** [comment]
Related: 
```
cider does respond to mpris "stop" command

cider GUI doesn't react to mpris volume change, shuffle change```

**Comment by coredev-uk** [comment]
added the stop command support, ill need to look further into the volume and shuffle issue

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
