### ISSUE TITLE
[Bug]: Cider only plays previews after restart (requires signoff/signin

### ISSUE THREAD

**Issue by ryryog25** [ciderapp/Cider-2#336]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 7/22/23, 6:13:44 AM | Quasar v2.12.2 | Electron 8c4ad0e62bacd9b9284a0e1341bf55222252a971

### Operating System Version

Pop!_OS 22.04 LTS | GNOME Version 42.9 | Wayland | 64-bit

### Describe the Bug

After closing cider 2 and reopening the application, while everything appears normal and I'm signed in and can play radios, playlists, search, what have you, when I go to actually play a song, in a radio or otherwise, only the 1:30 or so long preview from Apple Music plays, not the full song. This is fixed by signing out and signing back in.

### Steps to Reproduce

1. Open Cider2
2. Log In
3. Play a song (this works)
4. Close cider via the "X" at the top right corner
5. Re-open cider
6. Attempt to play song
7. Fail to profit (only preview plays)
8. Go to the left menu, Apple Music, Sign Out.
9. Repeat 

### Build timestamp

1692586997785

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
