### ISSUE TITLE
Empty playlists display as "NavBtn" in list

### ISSUE THREAD

**Issue by divrep222** [ciderapp/Cider-2#338]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.1, 7/22/2023

### Operating System Version

Windows 10

### Describe the Bug

Playlists originally created in Cider (many versions ago, likely in 1.0) and then emptied of tracks still display in the playlist list as "NavBtn", and I am unable to delete them.  Although they initially appear as if they're deleted, they re-appear after refreshing my playlists or restarting Cider.

These playlists do not show up when viewing my playlists in Apple Music.

### Steps to Reproduce

1. Created playlist in Cider with multiple tracks
2. Removed all tracks from playlist
3. Restarted Cider
4. Empty playlists display as "NavBtn" in playlist list

Note that I cannot reproduce this issue in Cider 2.1.1, although my empty "NavBtn" playlists created in 1.0 still remain when viewing in 2.1.1.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
