### ISSUE TITLE
Unable to play Soulection radio and view episodes

### ISSUE THREAD

**Issue by hardcodedvalue** [ciderapp/Cider-2#340]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7/22/2023

### Operating System Version

Win 11 Enterprise

### Describe the Bug

When I search for the radio station 'Soulection'. It doesn't navigate to the radio station page. Furthermore, I've played the radio on my phone, and if I pick show #605, it doesn't play.

### Steps to Reproduce

1. select search bar
2. type soulection
3. click on the radio station in the drop down list
4. observe results

**Comment by cryptofyre** [comment]
Those radio stations use Fairplay which is an encryption type not currently supported on Windows platforms.
