### ISSUE TITLE
X button to close cider, opened it again and "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by Kentakoong** [ciderapp/Cider-2#345]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

7/23/2023 2:58:11 AM | Quasar v2.12.0 | Electron

### Operating System Version

macOS Ventura 13.4.1 (c)

### Describe the Bug

Basically, if you open cider and use the red close button, it closes the app
<img width="239" alt="Screenshot 2023-08-26 at 21 50 47" src="https://github.com/ciderapp/Cider-2/assets/35761701/c3a7627d-1f8e-4eaf-87bd-abef9764f082">

 but once it opens, the bug occurs

<img width="632" alt="Screenshot 2023-08-26 at 21 51 52" src="https://github.com/ciderapp/Cider-2/assets/35761701/59071642-135a-4b65-88bc-a56735432401">

a vid explaining it: 

https://github.com/ciderapp/Cider-2/assets/35761701/568a83ed-a1fe-4ac2-bfac-bb086212e342

### Steps to Reproduce

1. Click the red X button on Cider's main page, with macOS
2. click to reveal cider again
3. walla! there is the bug!

**Comment by a-sahonchik** [comment]
Having the same issue with Cider 2.3 on Ubuntu 22.04 after minimizing app and maximizing it back.

![2024-02-06_21-11](https://github.com/ciderapp/Cider-2/assets/39532116/2bfac4b7-cf14-40d3-9ec0-b21bf5890d5e)
![2024-02-06_21-11_1](https://github.com/ciderapp/Cider-2/assets/39532116/f7af2162-febd-4fc3-9a49-d0348dcdce88)

**Comment by Kentakoong** [comment]
It's fixed in 2.3.0, so I'll close this issue for you guys, thanks for devving!

**Comment by Kentakoong** [comment]
OH, it's broken in Ubuntu right now, but macOS is fine, so I'll be reopening this;-;

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
