### ISSUE TITLE
Cider won't reopen as the previous settled screen size, potential bug? or not a feature?

### ISSUE THREAD

**Issue by Kentakoong** [ciderapp/Cider-2#346]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

7/23/2023 2:58:11 AM | Quasar v2.12.0 | Electron

### Operating System Version

macOS Ventura 13.4.1 (c)

### Describe the Bug

While opening Cider, it always remain the constant size when starting the app, so basically it doesn't resize to full screen, or the previous size setted.

https://github.com/ciderapp/Cider-2/assets/35761701/1fa35cca-0b8c-4cf9-941f-ed7a6d24fbe3

### Steps to Reproduce

1. Open Cider
2. Resize Cider's window
3. Close Cider
4. Open it again.

**Comment by Shotz5** [comment]
Encounter the same issue on Windows 11 22H2 and previous. Previous location on screen not saved,

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
