### ISSUE TITLE
Immersive background black with songs uploaded to iCloud Music Library

### ISSUE THREAD

**Issue by ErikDombi** [ciderapp/Cider-2#347]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2023-08-18 2:34:28 AM

### Operating System Version

Windows 11 Pro

### Describe the Bug

Songs that have been uploaded to your iCloud Music Library don't seem to have a background in the immersive view

![image](https://github.com/ciderapp/Cider-2/assets/23159219/7ec3bf0c-b354-4dc2-b757-b1782b1ce74f)

### Steps to Reproduce

1. Upload a song to Apple Music (I used the new Apple Music app for Windows, not iTunes)
2. Open Cider and play the newly uploaded song
3. Enter immersive view

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
