### ISSUE TITLE
[Bug]: Screen goes white

### ISSUE THREAD

**Issue by moiep** [ciderapp/Cider-2#349]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

29/08/2023

### Operating System Version

Windows 11 Pro

### Describe the Bug

Screen goes white and gray.

### Steps to Reproduce

Added a new album, tried to sort my albums by date added and screen reverted to this. 

### Anything else?

<img width="964" alt="image" src="https://github.com/ciderapp/Cider-2/assets/104405105/e187fcaf-2e2c-432d-8c7f-b7fa6147c10e">

### Build timestamp

1693268553481

**Comment by fiddler89** [comment]
Yeah, same issue for me when Cider is inactive for a while or upon resumption from sleep/standby mode.

**Comment by angelvilu** [comment]
Same bug here

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
