### ISSUE TITLE
[Bug]: Playback Bar — Incorrect localizations (certain languages/nitpick)

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider-2#35]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

The Now Playing bar currently displays data from `.nowPlayingItem` and not [somewhere else in previous Electron builds].

This results in some non-localized information being displayed. (e.g. displaying Simplified Chinese in a storefront that defaults to Traditional Chinese)
![image](https://user-images.githubusercontent.com/32032824/223418928-5f60bdab-69fb-4881-8f3a-11df92b79c34.png)
🚫 *Fujisan builds*

Electron builds before February 9th loads the correct metadata. (it also showed non-localized data, but correct data replaces it within a second)
![image](https://user-images.githubusercontent.com/32032824/223418842-0d69ccfc-8ffb-4fde-aa8e-9ebde7f84fd9.png)
✅ *Electron build, Feb 9th*

### Steps to Reproduce

1. Play a song (e.g. https://music.apple.com/tw/album/945738516?i=945738655)
2. See effect

### Anything else?

For those people who like to OSINT me, no, this is not where I live.

If the aforementioned storefront isn't showing the effect, please DM me on Discord: SoNothing#8224 (aka CDN)

**Comment by coredev-uk** [comment]
Old backend, no longer an issue.
