### ISSUE TITLE
Animated artwork only plays while cider window is focused

### ISSUE THREAD

**Issue by emorris00** [ciderapp/Cider-2#350]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9fe528a840fcde410ac059b600597cebb7d8155e

### Operating System Version

Windows 11

### Describe the Bug

Animated artwork only plays while the cider window is focused.

### Steps to Reproduce

1. Go to album with animated artwork or play album with animated artwork in immersive mode
2. Focus another window

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
