### ISSUE TITLE
Last.fm integration is buggy

### ISSUE THREAD

**Issue by n-1-c-k-y** [ciderapp/Cider-2#352]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

9/2/2023 Build

### Operating System Version

Not relevant

### Describe the Bug

When the album is by 'Various Artists,' it scrobbles with the artist as 'Various Artists' instead of the primary artist of the song. Most of the time, it doesn't remove the featured artists correctly, and some songs doesn't even scrobble, and it affects the Discord RPC when it shouldn't.

![Cider_hUXM9JMoHF](https://github.com/ciderapp/Cider-2/assets/55335959/5b75607a-a612-4487-b5a3-ad7edbb40ac9)
![nicememe rufBpDdTOZ6L8kudMKR](https://github.com/ciderapp/Cider-2/assets/55335959/450d8bfe-1eeb-4472-9aab-157f6d880a9b)
![nicememe IhINm22erDvdGQIJXOo](https://github.com/ciderapp/Cider-2/assets/55335959/a7a83456-8e9a-4842-a243-ad9974b89166)
![firefox_GQGbIJcV1K](https://github.com/ciderapp/Cider-2/assets/55335959/130b7d98-0aa5-4dd1-8de7-2b29654659b3)

### Steps to Reproduce

You can test it with these songs: https://music.apple.com/br/album/the-scotts/1509730426?i=1509730429, https://music.apple.com/br/song/1445949267, https://music.apple.com/br/album/better-days/1573415040?i=1573415045

**Comment by cryptofyre** [comment]
Fixed in 2.2.0

**Comment by n-1-c-k-y** [comment]
> Fixed in 2.2.0



> Fixed in 2.2.0



> Fixed in 2.2.0

has the build been released yet?, because 2.2.0 pr2 still had the same issues
