### ISSUE TITLE
[Bug]: Discord Rich Presence not displaying what I am listening to

### ISSUE THREAD

**Issue by Inactivels** [ciderapp/Cider-2#353]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Build 2.1.1

### Operating System Version

Windows 11

### Describe the Bug

Cider is not displaying to Discord what I am listening to anymore. It worked for about 15 minutes and stopped working.

### Steps to Reproduce

Just stopped working

### Build timestamp

1693720541617

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
