### ISSUE TITLE
[Bug]: Cannot use party on microsoft cider app

### ISSUE THREAD

**Issue by Twixer10** [ciderapp/Cider-2#355]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Last verison from microsoft store

### Operating System Version

Win 11

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/25131553/292952e0-ba6a-45d0-b51c-b5edc504fc42)

When i use party with my frinds the link bellow as undefind parameter.

### Steps to Reproduce

Create party on host, join with another user and open debug console

### Build timestamp

1693773383319

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
