### ISSUE TITLE
Music Reproducer Strange (See photo)

### ISSUE THREAD

**Issue by MuriloNovel** [ciderapp/Cider-2#358]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

The latest build on itchio

### Operating System Version

Windows 11

### Describe the Bug

Music Reproducer Strange (See photo)

### Steps to Reproduce

just opened the app
![image](https://github.com/ciderapp/Cider-2/assets/144291451/8f9e49a6-1ccf-445b-a65a-bc94f3977e67)

**Comment by Amaru8** [comment]
Hey there! The reported issue was resolved in [version 2.2.0](https://outline.cider.sh/s/2-2-0-changelog). Make sure to install the latest update available on our Itch.io page.

![image](https://github.com/ciderapp/Cider-2/assets/52407090/1cf305aa-d102-418d-9dbb-b1baea5bad23)
