### ISSUE TITLE
Tags like cider audio, or spacial thing, or kpbs arent appearing on maverick style

### ISSUE THREAD

**Issue by MuriloNovel** [ciderapp/Cider-2#359]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Latest Itchio Build

### Operating System Version

Windows 11

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/144291451/54e12ed6-584b-4dec-9423-befa695e6fe2)
Tags like cider audio, or spacial thing, or kpbs arent appearing on maverick style

### Steps to Reproduce

Well it is what it is

**Comment by Amaru8** [comment]
Hey there! The reported issue was resolved in [version 2.2.0](https://outline.cider.sh/s/2-2-0-changelog). Make sure to install the latest update available on our Itch.io page.

![image](https://github.com/ciderapp/Cider-2/assets/52407090/1cf305aa-d102-418d-9dbb-b1baea5bad23)
