### ISSUE TITLE
[Bug]: Custom Scaling Factor does not do anything

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider-2#36]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

I like using Cider with 1.2 scaling, since (even at 125% system scaling) text in Cider looks to small for me to read without needing to get way too close.

However, Custom Scaling Factor is not working in ~~Fujisan~~ (now Sabiiro) builds (Electron works fine). Changing the preference values does nothing, even after a relaunch.

### Steps to Reproduce

1. Open Settings → Visual → Advanced
2. Change Custom Scaling Factor
3. Nothing happens

### Anything else?

Some logs:
```
2023/03/07 22:04:10 Reading: C:\Users\[username]\AppData\Roaming\Cider-Fuji\spa-config.json
2023/03/07 22:04:10 Unable to cast json to struct: json: cannot unmarshal number 1.2 into Go struct field .visual.scalingFactor of type int
```

**Comment by SoNothingMC** [comment]
Problem still exists in Sabiiro btw, would love to increase element sizes without changing Windows scaling settings.

**Comment by coredev-uk** [comment]
@d3rpp theres a line https://github.com/ciderapp/project2/blob/0cb133931cbe9b87c5fb88f941f431e7e3297b56/src/components/settings/pages/VisualSettingsPage.vue#L33 referencing scaling, could you implement a function on the backend to update the scale factor

**Comment by d3rpp** [comment]
> @d3rpp theres a line https://github.com/ciderapp/project2/blob/0cb133931cbe9b87c5fb88f941f431e7e3297b56/src/components/settings/pages/VisualSettingsPage.vue#L33 referencing scaling, could you implement a function on the backend to update the scale factor

Core this is Fujisan

Not Sabiiro

This is an incredibly old version of Cider

**Comment by d3rpp** [comment]
If you saw my previous comment

Disregard, I'll take a look into this

**Comment by coredev-uk** [comment]
Any update on this @d3rpp?

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
