### ISSUE TITLE
app using 10% of my GPU

### ISSUE THREAD

**Issue by Ishikudeska** [ciderapp/Cider-2#360]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.0 Sabiiro

### Operating System Version

windows 10 LTE

### Describe the Bug

when I open task manager, Cider is using 10% of my GPU, everything is on default settings

### Steps to Reproduce

1. open cider
2. open task manager and look at gpu usage
3. discover cider is using 10% of overall GPU power

### Anything else?

my system runs on a 1050Ti, so any sort of GPU power given up is a huge loss in game performance, and stream performance

**Comment by cryptofyre** [comment]
Utilize the Game Mode on 2.2.0, and also stay away from immersive and sing lyrics when playing games as they are more intensive on GPU resources.
