### ISSUE TITLE
Visual tab bar glitch when closing immersive mode

### ISSUE THREAD

**Issue by stachie** [ciderapp/Cider-2#361]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17/07/2023

### Operating System Version

Windows 11 Pro version 21H2

### Describe the Bug

When closing out of preview mode that was used in full screen for some time, an old tab bar shows up either somewhere random or under the normal tab bar.
![Screenshot 2023-09-13 170621](https://github.com/ciderapp/Cider-2/assets/98183023/b95283de-3260-4daf-8e8f-2d8ca5ca4360)
![Screenshot 2023-09-13 170622](https://github.com/ciderapp/Cider-2/assets/98183023/5b771ca8-6d07-4721-9f38-1deea958e5e4)

### Steps to Reproduce

1. Go into immersive mode
2. Enable full screen
3. Disable full screen
4. Leave immersive mode

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
