### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by FiFo101SVK** [ciderapp/Cider-2#362]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9fe528a840fcde410ac059b600597cebb7d8155e

### Operating System Version

Windows 11 23H2 22631.2191

### Describe the Bug

Cannot play any playlist, only single songs

### Steps to Reproduce

1. click on any playlist and it won't start.
(also when opening the playlist and playing it/shuffle)

### Connect Device ID

B334A70A-F771-42F6-9B7A-AE2721C877C0

### Build timestamp

1694622931986

**Comment by cryptofyre** [comment]
Need to be more descriptive, utilize the template properly and provide logging if possible. 

Press `CTRL+SHIFT+I` then enter the `Console` tab to do so.
