### ISSUE TITLE
[Bug]:Change the window control position to the right is fail!

### ISSUE THREAD

**Issue by Owenfly** [ciderapp/Cider-2#363]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2023.4.10

### Operating System Version

Windows 11 22H2

### Describe the Bug

Change the window control position to the right, and then change it back to coincide with the closing of the settings menu, so there is no way to save the settings.

### Steps to Reproduce

![image](https://github.com/ciderapp/Cider-2/assets/55825205/1d47d9ba-d4eb-43f7-bb7a-d62208477886)

### Build timestamp

1694697952220

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
