### ISSUE TITLE
[Bug]: Home does not stop loading

### ISSUE THREAD

**Issue by Beret70** [ciderapp/Cider-2#364]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Today 14th September Build: 22/07/2023

### Operating System Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎10/‎08/‎2020 OS build	19045.3448 Experience	Windows Feature Experience Pack 1000.19044.1000.0

### Describe the Bug

Home does not stop loading

### Steps to Reproduce

Open Cider. 
Open Home.

### Build timestamp

1694728044457

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
