### ISSUE TITLE
[Bug]: Lyrics don't auto scroll and full screen defaults to the queue

### ISSUE THREAD

**Issue by ThatOneGuy808** [ciderapp/Cider-2#365]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

September 15th, 2023 14:48 PST

### Operating System Version

Debian 12 Bookworm

### Describe the Bug

When on the lyrics screen in full screen, they no not seem to auto scroll unless you scroll a little bit first. Also, when going into full screen, it defaults to the queue. I personally would rather have the ability to have it default to the lyrics
![image](https://github.com/ciderapp/Cider-2/assets/50556872/8094336f-8b3e-4ef7-a5c8-d7dd6a22f3b1)

### Steps to Reproduce

1. Play any song with lyrics
2. Enter full screen
3. Click the lyrics tab
4. When lyrics begin in the song, they won't scroll when they get to the bottom
5. Scroll the lyrics down a bit, they should reset and begin scrolling on their own

### Build timestamp

1694815133837

**Comment by cryptofyre** [comment]
First, make sure your mouse is not hovered over the lyrics side otherwise it halts the auto-movement.

Second, you can already set this yourself in the `Advanced > Tweaks` menu.

![image](https://github.com/ciderapp/Cider-2/assets/33162551/03c50427-f559-4b38-8f9b-ea4ba35e94dc)

**Comment by ThatOneGuy808** [comment]
Sorry about the last response

The auto scroll thing still seems to be an issue

Also, I don't see the starting tab option in the tweaks menu. Maybe I don't have it for some reason

**Comment by ThatOneGuy808** [comment]
I think this has been fixed now so I'm gonna close this. Thanks for fixing it if you did
