### ISSUE TITLE
[Bug] [UI] When using Compact View, Next track button acts as Previous

### ISSUE THREAD

**Issue by CmdrFigrow** [ciderapp/Cider-2#367]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0 Sabiro - Installed 10:57 18/09/2023

### Operating System Version

Windows 11 21H2

### Describe the Bug

When using Compact view and clicking Next Track button, acts as Previous Track action (see repro video, doesn't happen when using regular view)
![image](https://github.com/ciderapp/Cider-2/assets/30815814/031d083e-ebce-4bce-8342-ff8ca90b1a73)

### Steps to Reproduce

1. Start playing from middle of Playlist or album
2. Shrink window width until Cider enters Compact View (indicated by current track details appearing at bottom of screen)
3. Click Next ⏭️ button in footer
**--- Expected Behaviour: ---**
4. Cider plays next track in playlist
**--- Actual Behaviour: ---**
4. Cider acts as if Previous Track button was pressed, either going back to the start of the current track or playing the previous track from the queue

### Anything else?

Repro Video:
https://github.com/ciderapp/Cider-2/assets/30815814/b40272ef-6d52-44fa-9bd7-0325ddbcc5fa

### Build timestamp

17/09/2023 21:16:34

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
