### ISSUE TITLE
[Bug]: Scroll position is not maintained on navigating back from album page

### ISSUE THREAD

**Issue by charlesharries** [ciderapp/Cider-2#368]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 17/09/2023, 15:46:14

### Operating System Version

macOS Ventura

### Describe the Bug

Scroll position is not maintained when navigating into an album and back out again.

Submitting the bug under macOS but is present on Linux .deb build as well.

### Steps to Reproduce

1. Click **Albums** in the sidebar
2. Scroll down, enough to load the next "page" of albums in the infinite scroll
3. Click into an album
4. Click the **Back** button
5. Page is back at the top of the list of albums, with no subsequent "pages" loaded

### Build timestamp

1695041390014

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
