### ISSUE TITLE
Can't share links of songs in library of playlists

### ISSUE THREAD

**Issue by jjeroennl** [ciderapp/Cider-2#370]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

9/16/2023 (df6bae...)

### Operating System Version

Fedora 38

### Describe the Bug

Cider doesn't seem to actually put the song URL in the clipboard when using the share functionality. Instead "undefined" gets pasted. It does seems to work under "Browse" but it doesn't work in playlists or Library. 

### Steps to Reproduce

1. Right click any song inside Library or Playlists.
2. Click Share
3. Click Apple Music or Copy with song.link
4. Paste

### Anything else?

I'm not sure if this has impact on the clipboard, but I'm using Wayland.

**Comment by coredev-uk** [comment]
Resolved in next release
