### ISSUE TITLE
[Bug]: Arabic on synced lyrics reads wrong

### ISSUE THREAD

**Issue by Sizzle-Z** [ciderapp/Cider-2#371]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

https://imgur.com/a/qXqEcl8

### Operating System Version

Windows 10 Pro 22H2

### Describe the Bug

All of the arabic lyrics that are synced up with the music are messed up. Arabic reads from right to left but the synced lyric viewer forces them to read from left to right (like english).

![image](https://github.com/ciderapp/Cider-2/assets/93177291/f3f5bd5b-ff60-40dc-bae2-30ed2f9278ab)
 

### Steps to Reproduce

1. Go to a song that has synced arabic lyrics (ex. [Keify Kida (ft. Disco Misr) by Wegz](https://music.apple.com/ca/song/1591280474)).
2. Play the song & open the lyric viewer

### Build timestamp

1695188611272

**Comment by xBiei** [comment]
This could be fixed by using a fallback font that support Arabic characters.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
