### ISSUE TITLE
Playlists not syncing

### ISSUE THREAD

**Issue by ben-utas** [ciderapp/Cider-2#372]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.1.0

### Operating System Version

Edition	Windows 11 Home Version	22H2 Installed on	‎30/‎09/‎2022 OS build	22621.2283 Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Describe the Bug

Playlists don't seem to be syncing with apple music. Any songs added or removed to my playlists on cider will not show on my Android Apple Music app. Only workaround I have at the moment is to modify playlists on my phone, which isn't great. I have had similar issues before with playlists with clientDB turned on, which I can see is now forced to be on.

### Steps to Reproduce

1. Add a song to a playlist.
2. Refresh apple music on a native client and check the playlist.

**Comment by coredev-uk** [comment]
Did you install the app from the Microsoft Store?

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
