### ISSUE TITLE
Lyrics ghosting/persistent when rapidly skipping tracks

### ISSUE THREAD

**Issue by Raspberrynani** [ciderapp/Cider-2#373]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 18/09/2023, 4:16:34am

### Operating System Version

Windows 11 Pro for Workstations, 22H2

### Describe the Bug

When rapidly skipping tracks, the lyrics from the previous track will persist on the lyrics pane/sidebar.

![image](https://github.com/ciderapp/Cider-2/assets/54159650/93c1b2ac-3a24-47e6-987e-cb011015ce88)

### Steps to Reproduce

1. Open any playlist or album (all the tracks in the playlist/album might need to have lyrics)
2. Play any tracks that have lyrics (and open lyrics pane/sidebar)
3. Rapidly skip the tracks

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
