### ISSUE TITLE
[Bug]: AMP  Lyrics now looks small

### ISSUE THREAD

**Issue by jmylo10** [ciderapp/Cider-2#374]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

20-9-2023 , 10.55:55 pm 1 Quiasar v2.12.6 | Sabiro

### Operating System Version

Windows 10 Pro 22H2 64bits Comp 19045.3448

### Describe the Bug

Now the AMP Lyrics in the Inmersive mode looks pretty small, around 300 px, before the v2.2 update, the lyrics were a bigger size. In the Visual configuration I try to set up the lyrics font size but it doesnt works.

### Steps to Reproduce

1- Play any song
2- Select Full Screen or Inmersive mode
3-Select Lirics view
![imagen_2023-09-21_212120344](https://github.com/ciderapp/Cider-2/assets/122817074/10db2004-8616-4bb2-a419-715b5faeea3b)
![imagen_2023-09-21_212148983](https://github.com/ciderapp/Cider-2/assets/122817074/41d27739-3374-4405-8d70-bd0908d02eba)

### Build timestamp

1695348802948

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
