### ISSUE TITLE
Have to sign in daily

### ISSUE THREAD

**Issue by ArcTheSpark2** [ciderapp/Cider-2#375]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Version 2.2.0 | built on 17/09/2023, 16:45:53 | Quasar v2.12.6

### Operating System Version

KDE Neon 5.27 (Debian)

### Describe the Bug

When I open the application every morning, I have to sign into my Apple Music account again.
It will always open in "Preview Mode". 

![Screenshot_20230922_065248](https://github.com/ciderapp/Cider-2/assets/118931687/8cd92d02-6dcf-465a-8dd1-1094e51de1b9)

### Steps to Reproduce

1. Open the application.
2. Open Cider-2 and sign into Apple Music
3. turn off my laptop
4. turn on my laptop
5. Open Cider, it will open in preview mode again

**Comment by cryptofyre** [comment]
Make sure to redownload the latest available build from Itch.io that corrects this, we've already patched this bug.

**Comment by ArcTheSpark2** [comment]
Wow, thank you, yes sorry I didn't see that there was a new version released 6 hours again. 
Thank you for the awesome software and for all your hard work on Cider.
