### ISSUE TITLE
Songs aren't in order of Recently Added

### ISSUE THREAD

**Issue by Kentakoong** [ciderapp/Cider-2#376]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

9/22/2023, 5:25:57 AM | Quasar v2.12.6 | Electron

### Operating System Version

macOS Ventura 13.5.2 (22G91)

### Describe the Bug

When in the Songs View when first loaded, the songs aren't in order

### NOT IN ORDER
<img width="1822" alt="Screenshot 2023-09-22 at 18 11 59" src="https://github.com/ciderapp/Cider-2/assets/35761701/46579fa2-f96c-4cd7-9037-e653e3ef5273">

### IN ORDER
<img width="1822" alt="Screenshot 2023-09-22 at 18 12 24" src="https://github.com/ciderapp/Cider-2/assets/35761701/314835b4-a0b0-4173-bdff-a551c0ec327f">

### Steps to Reproduce

1. Start Cider
2. Go to the Songs Tab
3. Hit Refresh
4. Now the songs are in order...

https://github.com/ciderapp/Cider-2/assets/35761701/8b958ad8-0346-45b4-b02d-7feb0d3d4b82

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
