### ISSUE TITLE
Extensive Delays When Casting

### ISSUE THREAD

**Issue by WormholeAlien** [ciderapp/Cider-2#377]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2023-09-20, 11:55:55 p.m.

### Operating System Version

Windows 11 Home Build 22621

### Describe the Bug

When using the Airplay feature to cast music, Cider will connect to the device quickly but the delay in getting music to play or change is 30-40 seconds. Not the 2-3 noted in the panel. 

This is a real bummer as I got the app for it's casting functionality as I like to make playlists while I work during the day. With this kind of buffer, I would just go back to using my phone.

Love what your team is working to accomplish with this app!

### Steps to Reproduce

1. Clicked on Airplay button
2. Selected Device
3. Pressed play on music/skip to next song
4. Wait 30+ seconds for sound to come from external device

**Comment by vapormusic** [comment]
What is your device spec (PC and Airplay device)? I have never heard of a 30s delay before.

**Comment by WormholeAlien** [comment]
I'm using a Surface Laptop 5 and a Google Chromecast Ultra.

My LG CX also technically has Airplay built-in but that didn't work at all
(pin can up and app connected but the music never loaded).

**Comment by vapormusic** [comment]
Oh yeah that's Chromecast then, i do notice that there is significant delay there. I'm more concerned that the LG TV cant stream the audio

**Comment by WormholeAlien** [comment]
Is 30 seconds normal with Cider and Chromecast?

**Comment by vapormusic** [comment]
No, but if you pause Chromecast via your TV remote, the Chromecast will keep the audio buffers for seamless resume, causing a delay

**Comment by WormholeAlien** [comment]
Yes, I noticed that. However,  that doesn't help with switching tracks or
playlists.

**Comment by vapormusic** [comment]
Hmm I will try to look for a way to mitigate that

**Comment by WormholeAlien** [comment]
Thank you!

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
