### ISSUE TITLE
Mixed lyrics

### ISSUE THREAD

**Issue by Haridula** [ciderapp/Cider-2#378]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 9/21/2023, 6:55:55 AM | Quasar v2.12.6 | Sabiiro c927TO0c66c6ca874T69c7564881050052e878lef

### Operating System Version

Windows 11 Home 22H2

### Describe the Bug

The lyrics of the previous song and the playing one just got mixed.

### Steps to Reproduce

1. Start Cider
2. Start playing music
3. Unfocus Cider
4. Open the lyrics of a current song
5. Wait for the next track
6. Done. Your lyrics of the previous and the playing track are mixed.

### Anything else?

Two examples of the bug
![Cider_x7WVlV552a](https://github.com/ciderapp/Cider-2/assets/144393063/9f1239d6-dcfb-4522-8ac2-ba0106e0e2ea)
![Cider_RvWiz3vX2K](https://github.com/ciderapp/Cider-2/assets/144393063/8a086693-f901-429a-aba8-0f329d2f7b66)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
