### ISSUE TITLE
New "Search by playlist" feature: also adds Apple Music playlists to the search list.

### ISSUE THREAD

**Issue by AndyMznc** [ciderapp/Cider-2#380]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 22/09/2023 00:27:57 | Quasar v2.12.6 | Electron ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

macOS Sonoma 14.0

### Describe the Bug

I've already reported this bug on Discord, but I've decided to create a bug report about it. Even though it must already have been found by the team.
A few weeks ago, you added a playlist search system to add new music (which was one of my requests, thanks!).
But when we do a search, we also get Apple Music playlists in the list, which is restrictive when we name our playlists the same way as Apple's, we don't know which one is ours.
What's more, the box appears at the very top of Cider by default (the possibility of navigating with the arrows would be great, by the way !)

### Steps to Reproduce

1. Right-click on the song
2. Add to playlist
3. Find the playlist to which you wish to add the song
4. Here: We can find the AM playlist in addition to my personal playlist + The search field is at the top of the Cider application (probably because I have a lot of playlists and they appear at the top).

### Anything else?

![screen_01](https://github.com/ciderapp/Cider-2/assets/115222358/fbe18f83-47a5-48b1-a2f8-b47d20526a80)
![screen_02](https://github.com/ciderapp/Cider-2/assets/115222358/a5ab4048-9dee-491c-8e0b-fb72ea3cea23)

**Comment by cryptofyre** [comment]
Noted! Thanks for the feedback, we'll fix this in 2.2.1.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
