### ISSUE TITLE
moving album cover's brightness seems too high 

### ISSUE THREAD

**Issue by teddy0115** [ciderapp/Cider-2#381]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

some days ago

### Operating System Version

Windows 11 Pro version 22H2

### Describe the Bug

moving album cover's brightness is too high 
![화면 캡처 2023-09-24 220250](https://github.com/ciderapp/Cider-2/assets/136608993/c2907fcb-2d38-4072-8476-550aa861f45d)

### Steps to Reproduce

i turned on the moving album cover option

**Comment by cryptofyre** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/33162551/62fc3c93-d7d4-458d-8c6d-08e6370bc1b1)

Try this option, it should resolve or fix your oversaturation issues.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
