### ISSUE TITLE
Cider 2.20 Does Not work with Mullvad VPN

### ISSUE THREAD

**Issue by arsonust** [ciderapp/Cider-2#382]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/17/2023

### Operating System Version

Windows 10 Home 10.0.19045 Build 19045

### Describe the Bug

When trying to Open Cider 2.20 with Mullvad on, The app will not load and will show a Grey Screen. When Mullvad is disabled it will load as normal.  Also when the App is open and Mullvad is turn on things like Home,Listen Now and Browse Will not work.

### Steps to Reproduce

Turn on Mullvad. 
Open Cider 

Open Cider
Turn on Mullvad
Go to Home or any other option.

**Comment by cryptofyre** [comment]
This is due to how Apple Music handles storefronts, unfortunately there isn't a whole lot we can do about this.
