### ISSUE TITLE
Lyrics with more than 2 vocalists display wrong

### ISSUE THREAD

**Issue by RobertRR11** [ciderapp/Cider-2#383]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.2.0 Built on 21.9.2023, 05:55:55

### Operating System Version

Windows 10 Home 22H2

### Describe the Bug

Songs that have multiple vocalists display wrong in lyrics.
From what I see with Apple Music on mobile, the lyrics change from left to right every time the vocalist changes, meaning a vocalist that displayed on the left before could be on the right after 2 other vocalists.
On Cider, it looks like only the last vocalist is displayed on the right, making everyone else display on the left even if there are more than 2 in a song.

### Steps to Reproduce

1. Play a song with more than 2 vocalists, example: "Standard (feat. Trettmann, Gringo, Ufo361 & Gzuz)"
2. Open lyrics or full screen view

### Anything else?

Lyrics in Cider: 
![image](https://github.com/ciderapp/Cider-2/assets/57044042/ab8253b8-8003-4281-b070-a0f8be9f66b2)

Lyrics in Apple Music:
![image](https://github.com/ciderapp/Cider-2/assets/57044042/5ea588c2-0f23-40ef-a1c0-f307f48663b4)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
