### ISSUE TITLE
Album artwork not correctly refreshing in immersive view

### ISSUE THREAD

**Issue by RisenID** [ciderapp/Cider-2#385]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

9/22/2023 (version 2.2.0 reupload of the fixed .rpm)

### Operating System Version

Linux fedora 6.6.0-0.rc2.20230922git27bbf45eae9c.23.fc40.x86_64

### Describe the Bug

Album artwork does not update in immersive view.

### Steps to Reproduce

Played an apple music playlist
Skipped a song halfway through (seems to not matter if its skipped or just moves to the next song)

### Anything else?

![Screenshot_20230926_032454](https://github.com/ciderapp/Cider-2/assets/94130108/9c7f172f-7ea6-49be-b9f9-24d48f5fa15d)
![Screenshot_20230926_032523](https://github.com/ciderapp/Cider-2/assets/94130108/0cb587dc-d27a-46e4-8ae1-064c1bcea168)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
