### ISSUE TITLE
Playlists get cut off at 800 songs

### ISSUE THREAD

**Issue by supremeblank** [ciderapp/Cider-2#387]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 11 22H2

### Describe the Bug

Each playlist doesn't show more than 800 songs, even though there clearly are more songs, since Apple Music on my phone shows more than 800 songs, and if I edit the playlist through Cider, I can see the songs that get cut off.

### Steps to Reproduce

1. Open any playlist with 800+ songs
2. Scroll down to the end of the playlist

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
