### ISSUE TITLE
Last.fm integration is buggy

### ISSUE THREAD

**Issue by n-1-c-k-y** [ciderapp/Cider-2#390]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Cider 2.2.0 Latest Pre-Release

### Operating System Version

Windows 11

### Describe the Bug

When the album is by 'Various Artists,' it scrobbles with the artist as 'Various Artists' instead of the primary artist of the song. Most of the time, it doesn't remove the featured artists correctly, and some songs doesn't even scrobble. It also removes the featured artists on the Discord RPC (It shouldn't).

![Cider_hUXM9JMoHF](https://github.com/ciderapp/Cider-2/assets/55335959/5b75607a-a612-4487-b5a3-ad7edbb40ac9)
![nicememe rufBpDdTOZ6L8kudMKR](https://github.com/ciderapp/Cider-2/assets/55335959/450d8bfe-1eeb-4472-9aab-157f6d880a9b)
![nicememe IhINm22erDvdGQIJXOo](https://github.com/ciderapp/Cider-2/assets/55335959/a7a83456-8e9a-4842-a243-ad9974b89166)
![firefox_GQGbIJcV1K](https://github.com/ciderapp/Cider-2/assets/55335959/130b7d98-0aa5-4dd1-8de7-2b29654659b3)

### Steps to Reproduce

1. Enable Remove Featured Artists with "Artist List"
2. Play one of these songs: https://music.apple.com/br/album/the-scotts/1509730426?i=1509730429, https://music.apple.com/br/song/1445949267, https://music.apple.com/br/album/better-days/1573415040?i=1573415045
3. Check Last.fm

**Comment by n-1-c-k-y** [comment]
It's been an issue since June.

**Comment by coredev-uk** [comment]
Its very hard to remove the correct artist as using LastFM's correction API doesn't help because other services have already scrobbled the wrong data, so lastfm just returns whatever we give them. The remove featured config option just removes feat. using regex from the song name, and for the artist name we just run an api call to Apple to get the artist list returning the first one it gives us, which in most cases is wrong. If you have any other suggest/implementation that gets it right please share.

**Comment by n-1-c-k-y** [comment]
> Its very hard to remove the correct artist as using LastFM's correction API doesn't help because other services have already scrobbled the wrong data, so lastfm just returns whatever we give them. The remove featured config option just removes feat. using regex from the song name, and for the artist name we just run an api call to Apple to get the artist list returning the first one it gives us, which in most cases is wrong. If you have any other suggest/implementation that gets it right please share.
can't you use the cider 1 method? it worked fine

**Comment by n-1-c-k-y** [comment]
You could try this, get the ID of the first artist with MusicKit.getInstance().nowPlayingItem.relationships.artists.data[0].id and make a request to the API to get the name of the artist (this is how it works in Cider 1, I think)

**Comment by n-1-c-k-y** [comment]
This fixes the issues I mentioned, apart from the issue with the Discord RPC
