### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by kanishka-sahoo** [ciderapp/Cider-2#391]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

I am using the AppImage 2.2.0 version

### Operating System Version

ArchLinux latest (at time of report)

### Describe the Bug

On clicking the `Disable This Section` button in the `Shazam Playlist was not found.` section, the prompt does not disappear. Also, the prompt talking about explicit material being opt-in appears every time even if opted o=in. 

### Steps to Reproduce

1. Open the Cider-2.2.0 AppImage
2. Scroll Down to the bottom
3. Click on the `Disable This Section` button

**Comment by cryptofyre** [comment]
Made the prompt show once, and the shazam removal should work again as of the latest pre-release. Thanks for the report!
