### ISSUE TITLE
[Bug]: The picture of the custom songs didn't show correctly in immersive mode

### ISSUE THREAD

**Issue by iamyx123** [ciderapp/Cider-2#392]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0 microsoft store

### Operating System Version

windows11 22H2

### Describe the Bug

![{C2B44588-829B-4e92-8119-7BC7CAA10FC8}](https://github.com/ciderapp/Cider-2/assets/88130457/8c5a0f3d-e382-452c-b80d-b719c8aa1842)

### Steps to Reproduce

1.upload a song from iTunes
2.play a song and open immersive mode

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
