### ISSUE TITLE
Last.fm scrobbling no longer works with local files uploaded to iCloud Music Library

### ISSUE THREAD

**Issue by stewartkyle** [ciderapp/Cider-2#393]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 11 22H2

### Describe the Bug

When playing songs that have been uploaded to a user's iCloud Music Library, the tracks will not be scrobbled to Last.fm. iCloud Music Library songs were successfully scrobbling on Cider (2.0.0), but have been broken since 2.1.0. Scrobbling still works with songs that are being streamed directly from Apple Music.

### Steps to Reproduce

1. Upload a local file to your iCloud Music Library.
2. Enable Last.fm connectivity in Cider.
3. Play a song from Apple Music and check your Last.fm profile to confirm that scrobbling is working.
4. Play a song from your iCloud Music Library and see that it has not been scrobbled.

**Comment by stewartkyle** [comment]
It looks like this bug is caused by enabling "Remove Featured Artists" under Settings -> Connectivity -> Track Adjustments. When this setting is set to "None" or "Track Name", scrobbling works for iCloud Music Library tracks. When it is set to "Artist List" or "Both", scrobbling iCloud Music Library tracks stops working.

**Comment by cryptofyre** [comment]
Should also be resolved in the latest pre-release. We changed the way artists are handled for Rich Presence / Last.FM

**Comment by bradr3d** [comment]
This is happening for me on the version I downloaded from Itch today (1/18/2024)
