### ISSUE TITLE
Artists are not sorted alphabetically in the Library

### ISSUE THREAD

**Issue by stewartkyle** [ciderapp/Cider-2#394]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 11 22H2

### Describe the Bug

When navigating to Library -> Artists, the artists are not sorted alphabetically as they were in the previous version of Cider (2.1.0). There is no obvious order to the current sorting and no way to change it back to alphabetical.

### Steps to Reproduce

1. Navigate to Library -> Artists.
2. See that the artists are not sorted alphabetically.

**Comment by cryptofyre** [comment]
Resolved in the latest pre-release, stay tuned.
