### ISSUE TITLE
[Bug]: Now Playing widget does not respect color setting

### ISSUE THREAD

**Issue by seyaidev** [ciderapp/Cider-2#396]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 11 22H2

### Describe the Bug

Creating a Connect widget for a device does not use the Color setting supplied.

### Steps to Reproduce

1. Go to Connect Dashboard
2. Create a new widget for a device without changing the color
3. Create a new widget for a device with a different color setting
4. Observe that they look exactly the same

### Anything else?

Inspecting the widget element shows only one place a color a is defined and it's a hard coded RGB.

![image](https://github.com/ciderapp/Cider-2/assets/10445573/e3bec81f-113e-4c82-a754-940699407bd9)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
