### ISSUE TITLE
[Bug]: Year isn't displayed on locally synced albums

### ISSUE THREAD

**Issue by seyaidev** [ciderapp/Cider-2#397]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 11 22H2

### Describe the Bug

The albums below have the years 2020 and 2023 respectively, but they don't show up. I added them to my iCloud Music Library via iTunes upload since they aren't available on streaming platforms.

### Steps to Reproduce

1. Upload song(s)/albums to iCloud Music Library via iTunes
2. Check that the year is displayed on iTunes
3. Check on Cider

### Anything else?
Screenshots are from Cider and iTunes (Windows), respectively

![image](https://github.com/ciderapp/Cider-2/assets/10445573/fc819548-4d07-4d6e-bed1-694ca4bc8fb1)
![image](https://github.com/ciderapp/Cider-2/assets/10445573/0aab3b5b-af25-4c25-bd99-ebeec4367ed1)

![image](https://github.com/ciderapp/Cider-2/assets/10445573/4243dc4c-45d6-4842-a507-82eb8841ab07)
![image](https://github.com/ciderapp/Cider-2/assets/10445573/9a1d8440-5f47-438f-a802-d18859280291)

### Build timestamp

1696360176325

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
