### ISSUE TITLE
[Bug] Messed up margins on immersive player (One)

### ISSUE THREAD

**Issue by xBiei** [ciderapp/Cider-2#399]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

c927f0c66c6ca874f69c7564881050052e8281ef

### Operating System Version

Windows 11 Pro 23H2

### Describe the Bug

The margins/paddings on immersive player (one) from window width 1046px ~ approx. 1300px as you can see in the images below. 

### Steps to Reproduce

1. Play a song.
2. Open immersive player (one)

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/65196493/97680683-c33c-43c4-996a-556c7716403f)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
