### ISSUE TITLE
Random pausing at start of next song

### ISSUE THREAD

**Issue by l-zen** [ciderapp/Cider-2#401]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

2.2.0

### Operating System Version

Pop!_OS 22.04 LTS

### Describe the Bug

Randomly the music will stop at the start of the next song in queue.

### Steps to Reproduce

It occurs while listening to a playlist on shuffle.

**Comment by Amaru8** [comment]
Hey! Did you enable the Flavor Hack setting under Advanced?

**Comment by l-zen** [comment]
No i dont have it enabled

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
