### ISSUE TITLE
[Bug]: Windows 11: Low resolution Icon in taskbar and start menu

### ISSUE THREAD

**Issue by SnartFridge** [ciderapp/Cider-2#403]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Last Updated 24/09/2023

### Operating System Version

Windows 11 22H2

### Describe the Bug

App icon on taskbar is rendered at a low resolution and in Windows start menu lacks antialiasing.
![image](https://github.com/ciderapp/Cider-2/assets/123705853/256b72c5-20f0-4d24-ba2c-44bef16490f7)

![image](https://github.com/ciderapp/Cider-2/assets/123705853/88c9d055-f12b-4722-a3f1-a182d4bd99df)

### Steps to Reproduce

1. Install Windows
2. Open Start Menu with 'super key' also known as Windows key
3. Open MS store
4. Download Cider 2
5. Wait for it to install
6. Look for Icons when installed

### Anything else?

I don't know if this is a limitation of the Microsoft store or not.
Also, I could not find the version of Cider I had, as it is not easily available to view on the MS store, sorry.

### Build timestamp

1696676053346

**Comment by Clyxos** [comment]
Same Problem here.

**Comment by ozumado** [comment]
Same here, its been like that for ages, its disappointing this problem isnt being addressed at all.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
