### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by govind-prog** [ciderapp/Cider-2#404]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

21/09/23

### Operating System Version

windows 10 home

### Describe the Bug

the airplay does not work

### Steps to Reproduce

just thought of using the airplay but after the few minutes my device is not displaying

### Connect Device ID

Quasar v2.12.6

### Build timestamp

1696682182197

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
