### ISSUE TITLE
[Bug]: Immersive Screen goes completely white so text can't be read

### ISSUE THREAD

**Issue by TWB0109** [ciderapp/Cider-2#405]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on  9/21/2023, 4:27:31 PM | Quasar v2.12.6 | Electron ceed39250d55f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

Linux lizard 6.5.4-1-default \#1 SMP PREEMPT_DYNAMIC Wed Sep 20 05:07:04 UTC 2023 (fdd7e9e) x86_64 x86_64 x86_64 OpenSUSE TW GNU/Linux

### Describe the Bug

When going into immersive mode, the background turns totally white and nothing is visible other than the album covers, this is, if the cover is not white itself.

### Steps to Reproduce

1. Play an album, playlist, song or station.
2. Three dots at the top left corner > Immersive || Album cover at the lower left corner > Immersive.

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/53587182/14827a85-a49c-467c-982c-55c293edd60d)

### Connect Device ID

v2.0.0 Linux 6.5.4-1-default

### Build timestamp

1696794348588

**Comment by TWB0109** [comment]
Any updates on this?

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
