### ISSUE TITLE
Can't add or fav the current song playling from a playlist

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#406]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

4.10.23 build

### Operating System Version

Windows 10

### Describe the Bug

I can't add the current playing song to my library or favourite it when the song is from a playlist.

The changes are also not getting applied
![image](https://github.com/ciderapp/Cider-2/assets/34512773/d965b9a9-9b1f-4adb-9953-739bd9cd093b)
also it does not show my current state if it is already in my library

![image](https://github.com/ciderapp/Cider-2/assets/34512773/2d29f279-0b43-472e-bfde-4b4344e471fe)

### Steps to Reproduce

1. open playlist
2. start song
3. right click on current player, add to lib/fav

**Comment by UnbreakCode** [comment]
I also can't open the album or artist 
![image](https://github.com/ciderapp/Cider-2/assets/34512773/4dddcaea-9295-4f7c-85f0-f86ac9cf42fe)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
