### ISSUE TITLE
Can't see properties from current playing song of my playlist

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#407]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

4.10.23 build

### Operating System Version

Windows 10

### Describe the Bug

Opening the propertiesof the currently played song does not work if the song is from a playlist.

![image](https://github.com/ciderapp/Cider-2/assets/34512773/1c719af3-c4da-49ab-91a0-cc9b8133c2f3)
![image](https://github.com/ciderapp/Cider-2/assets/34512773/f960af8d-0f4c-45f0-8242-47c221c693a7)

### Steps to Reproduce

1. open playlist
2. play a song
3. right click on player ->Properties

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
