### ISSUE TITLE
Can't play music from my 2019 Replay

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#408]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

4.10.23 build

### Operating System Version

Windows 10

### Describe the Bug

I can't play 80% of my songs from my replay 2019. The songs still exists in the AM catalog and I can listen to them if I search manually.

![image](https://github.com/ciderapp/Cider-2/assets/34512773/2a96222b-d3ec-46e3-8a4d-4c74fa710f94)

### Steps to Reproduce

1. open a 2019 replay
2. play some songs

**Comment by Amaru8** [comment]
Hey there! A fix has been pushed to the development codebase. 🚀
