### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Romerrooo** [ciderapp/Cider-2#412]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Today

### Operating System Version

Windows 10 pro

### Describe the Bug

Connection to apple music problem

### Steps to Reproduce

Every time i sign in

### Build timestamp

1697316443983

**Comment by Dymus** [comment]
I experience this issue on Ubuntu 20.04, I installed through .deb, the latest version of Cider, it is 2.2.0, built on 9/14/2023, and it's been there for more than a month, I am unable to use the app AT ALL.

The window to sign in with Apple credentials does not show at all.
![ezgif com-video-to-gif (5)](https://github.com/ciderapp/Cider-2/assets/16743179/56e613fa-28d0-4d58-a526-b585501bb9ef)

**Comment by endy128** [comment]
This is happening on Ubuntu 23.04 too.

**Comment by coredev-uk** [comment]
Restart the client, when you login and get the connection error just press ok, it’s a weird bug with apples auth, and with the way we do the auth window for electron platforms.
