### ISSUE TITLE
[Bug]: Storefront Country Region preventing from accessing certain songs and albums

### ISSUE THREAD

**Issue by Kowken** [ciderapp/Cider-2#413]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Cider 2.20 from itch.io (both Portable and installer have the same issue)

### Operating System Version

Windows 11 Professionnel Version	22H2 22621.2428 Windows Feature Experience Pack 1000.22674.1000.0

### Describe the Bug

When I log on to my French Apple Music Account, the WebViewer tells me that an error has occurred and some content become innaccessible afterwards (especially from the search bar).  I'm quite confident in my claims because I can choose and play any song just fine from preview mode (when I'm not connected to my account). 

### Steps to Reproduce

1. Log into Apple Music through Cider using a French (and possibly other foreign) account
2. Choose password identification
3. Enter password
4. The webviewer will display a message saying that an error occurred and the non-preview mode will load normally afterwards
5. However many songs and albums are not accessible through the search bar anymore.

### Anything else?

Here are a few console logs, the first one is when I want to play an "unavailable song":
https://cdn.discordapp.com/attachments/1163172188367626342/1163175174623989900/image.png?ex=653e9e4c&is=652c294c&hm=525c0cfe5ca655c6a72b3337a59988919e9edf81e41a194c3ed5b8a30670eb73&

The second one is when I want to display the "unavailable album":
https://cdn.discordapp.com/attachments/1163172188367626342/1163175462017703976/image.png?ex=653e9e90&is=652c2990&hm=3e6c245701d41bfe102ee2063fb42577af0a8d560c029666107452d59ed244a0&

The third and fourth ones are the root of my suspicion regarding storefront country region (that and the fact that everything works correctly in preview mode):
https://cdn.discordapp.com/attachments/1163172188367626342/1163175886959423498/image.png?ex=653e9ef6&is=652c29f6&hm=6707426880e4522f474783c35f30b6e1b39eb6a680de51bd30cc565cda0d728b&
https://cdn.discordapp.com/attachments/1163172188367626342/1163175887232045158/image.png?ex=653e9ef6&is=652c29f6&hm=ac6b1d7641fd7a3c6fa4c94432474e4448085e36ce4a51208a9299e747291a64&

I did test that I could play the song on iTunes and the french region of the beta apple music web player

This is quite similar to #279 as it has the same starting point but things may have not been fixed completely even with 2.2.0 release

**Comment by Kowken** [comment]
To back up my theory, I can go to an album by and only by typing its url fro; the french Apple Music browser.

For example, https://beta.music.apple.com/fr/album/cyberpunk-2077-radio-vol-2-original-soundtrack/1541001394 works but https://beta.music.apple.com/us/album/cyberpunk-2077-radio-vol-2-original-soundtrack/1540792622 does not

**Comment by coredev-uk** [comment]
Some storefronts do restrict playback, this is a limitation of how Apple's API works. Usually its down to country restrictions, but it can sometimes be down to how the artist has added the music. Storefront calls are set by us, so if you want to be able to access certain pages. If you are on the latest version, I suggest changing your language to one that matches a storefront that can access the page, if not then it will fallback to your MusicKit Storefront which would be assigned based on your Apple ID. Not much more can be done on this because of how Apple has set it up.

**Comment by Kowken** [comment]
> Some storefronts do restrict playback, this is a limitation of how Apple's API works. Usually its down to country restrictions, but it can sometimes be down to how the artist has added the music. Storefront calls are set by us, so if you want to be able to access certain pages. If you are on the latest version, I suggest changing your language to one that matches a storefront that can access the page, if not then it will fallback to your MusicKit Storefront which would be assigned based on your Apple ID. Not much more can be done on this because of how Apple has set it up.

Thank you for your answer. Do you mean by that that I have to set my language to French for instance if I want to access the French storefront ? Because I tried and it did not work at all.

**Comment by Kowken** [comment]
Also I can access some album cover I couldn't before thanks to the Canadian French layout but I still cannot access the songs.
