### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by notdominicc** [ciderapp/Cider-2#414]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2 windows store

### Operating System Version

windows 11

### Describe the Bug

x icon in playlist search bar doesn't clear text

### Steps to Reproduce

search text in a playlist search and click the x icon

### Build timestamp

1697622897323

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
