### ISSUE TITLE
[Bug]: cider audio laboratories stops working periodically. I have to restart the program to make it work again

### ISSUE THREAD

**Issue by tasita220** [ciderapp/Cider-2#415]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.2.0 - Sabiiro - 9/20/23

### Operating System Version

Windiws 11 22H2

### Describe the Bug

cider audio laboratories stops working periodically. I have to restart the program to make it work again

### Steps to Reproduce

IDK

### Build timestamp

1697644663177

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
