### ISSUE TITLE
[Bug]: Discord Rich Presence broken with latest Discord update

### ISSUE THREAD

**Issue by LasagnaFairy** [ciderapp/Cider-2#417]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 9/20/2023 9:55:55pm

### Operating System Version

Windows  11 Home

### Describe the Bug

Discord rich presence has stopped working. I have tried the troubleshooting FAQ advice, tried toggling things on and off, reinstalling, etc. but nothing has worked. I think this happened with the most recent Discord update.

### Steps to Reproduce

I updated to the most recent version of Discord. 

### Build timestamp

1698050196846

**Comment by Abg3hoben** [comment]
just got the same problem

**Comment by cryptofyre** [comment]
We cannot do much about this as we are using Discord's official methods of RPC that haven't changed for years, you will need to approach Discord for this issue unfortunately.
