### ISSUE TITLE
"Optimize for Steam Deck" features do not persist on relaunch

### ISSUE THREAD

**Issue by minecraftDigi101** [ciderapp/Cider-2#418]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

2.2.0 Appimage

### Operating System Version

SteamOS 3.4.11

### Describe the Bug

I've been having this recurring issue where the "Optimize for Steam Deckl" toggle in advanced only works until you relaunch Cider, and then you'd have to go back into settings and switch it off and back on again to re-enable it.

Going into more detail, turning on the Steam Deck Optimization toggle works as expected at first with its noticeably bigger GUI and fullscreen, but the next time I re-open it, the GUI is scaled back to default and the fullscreen no longer functions. If I wanted to temporarily fix this issue, I would have to go back into settings, go into the advanced tab, toggle off "Optimize for Steam Deck", and then toggle it back on each time I relaunch Cider.

### Steps to Reproduce

1. Toggle the "Optimized for Steam Deck" toggle on
2. Close and Re-open Cider
3. Check Cider>Settings>Advanced after relaunch and see if the "Optimized for Steam Deck" toggle is still on. If it is, yet the GUI is smaller than before the relaunch and Cider has the minimize, maximize, and close buttons still showing, than the bug has been recreated congrats! 

### Anything else?

This issue happens in both Gaming Mode and Desktop Mode, and I used the app image version of it to test the issue. I believe it also has this issue on the .rpm release as well

**Comment by coredev-uk** [comment]
When turning the option on there is no need to restart the app. Restarting the app before closing the settings modal in this case would not save the settings. Only when turning it off you would get a popup to reload the app, in this case the settings are saved before the reload.

**Comment by minecraftDigi101** [comment]
The issue that I had was where the toggle would be on, but the enlarged GUI would not persist when I reopened the app again, even though the toggle would still be on after the reboot, so I would have to toggle it off and back on again to reload it. Does this happen to others as well or just me?
