### ISSUE TITLE
Windows 11: audio output device resets sometimes

### ISSUE THREAD

**Issue by kovapatrik** [ciderapp/Cider-2#419]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

16/09/2023 - Sabiiro

### Operating System Version

Windows 11 Pro Version 22H2

### Describe the Bug

Sometimes (inconsistently, so not on every restart) the audio output of Cider resets. I manually sets it to a non-default output device, and it randomly resets to default.

### Steps to Reproduce

1. Change audio output device of Cider (on Windows: Right click on the Sound icon in the taskbar -> Volume mixer -> Change the output device of the app `Microsoft Edge WebView2`
2. ?? (wait some time)
3. The output device resets

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
