### ISSUE TITLE
[Bug]: ClientDB writing absurd amount of data to disk

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider-2#420]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

"2.2.0 Wrap Up Build", released 2023-10-18 00:34 GMT

### Operating System Version

Windows 10 22H2 (19045.3570)

### Describe the Bug

When Cider is launched, it writes a lot of data onto the disk, frequently writing over 500MB. (average value, best case is ~250MB, worse case is ~900MB)

### Steps to Reproduce

1. Launch [SysInternals Procexp](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) as administrator
2. Select "Disk Write Bytes" from View → Select Columns…
3. Sort the "Process" row alphabetically so processes are shown hierarchically
4. Launch Cider
5. See writes to disk from WV2

### Library Statistics
Tracks: 4794 (84 imported)
Albums: 547 (6 imported)
Artists: 274
Playlists: 38 AM playlists, 12 iTunes playlists

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/32032824/aae0515c-2f49-4c41-a849-858004895591)
*After 5mins of playing with ClientDB*

![image](https://github.com/ciderapp/Cider-2/assets/32032824/367e70bc-26c1-4ccd-a623-554abe240451)
*After 5mins of playing without ClientDB*

### Build timestamp

1698160642005

**Comment by SoNothingMC** [comment]
Note: This was originally made known to me by a user. However, their metrics shows full I/O out of the WV2 process, while mine only shows Disk R/W data. (what they're actually concerned about)

**Comment by coredev-uk** [comment]
Every song in your (inc. playlists) library would be written to the database on launch.

**Comment by coredev-uk** [comment]
ClientDB is being cycled out on favour of a new caching api.
