### ISSUE TITLE
Search Feature 

### ISSUE THREAD

**Issue by rocketman1776** [ciderapp/Cider-2#423]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/20/23

### Operating System Version

Windows 10 19045.3570

### Describe the Bug

The search feature only work for Apple Music, nothing happens when I try to search anything in my library.

### Steps to Reproduce

The search bar after you click the home tab.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
