### ISSUE TITLE
Clicking on Shuffle after clicking on ... next to a playlist on the Home page doesn't start playing the playlist

### ISSUE THREAD

**Issue by trparky** [ciderapp/Cider-2#424]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 10/25/2023, 12:39:02 AM | Quasar v2.12.6 | Sabiiro | 4dc91c50264af81afc2ce8a7c8a9af@662e6be72

### Operating System Version

Windows 11 22H2 22621.2428

### Describe the Bug

Clicking on the Shuffle option after clicking on the ... next to a playlist doesn't play the playlist.

### Steps to Reproduce

1. Go to the Home page.
2. Click on the ... next to a playlist.
3. Click on Shuffle.
4. Nothing happens.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
