### ISSUE TITLE
Missing songs in library.

### ISSUE THREAD

**Issue by Zentae** [ciderapp/Cider-2#425]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/21/2023

### Operating System Version

Windows 11 22H2

### Describe the Bug

At each launch of the cider application, when i go to Library > Songs, i always need to refresh the page via its dedicated button in order to retrieve missing songs. I feel like it's very annoying to refresh the song library every time i launch the app.

Page at launch: https://ibb.co/YWTLJHr
Page after refresh: https://ibb.co/qD6nSG1

### Steps to Reproduce

None

**Comment by Logboy2000** [comment]
I have a very similar issue. I even tried uninstalling to no avail. Both new songs and deleted songs will not update until refreshing.

**Comment by Logboy2000** [comment]
TEMPORARY FIX: 
DELETE EVERYTHING IN THIS FOLDER
%LocalAppData%\sh.cider.sabiiro\EBWebView\Default\IndexedDB
This took waaayyy too long to find.



Note to devs:
Please just remove library indexing you can only use this on Wi-Fi anyway

**Comment by cryptofyre** [comment]
We've removed library caching in 2.3.0, this should no longer be an issue.

**Comment by Logboy2000** [comment]
Thank you very much (:

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
