### ISSUE TITLE
Volume is to high, 33% should be 100%

### ISSUE THREAD

**Issue by d4g** [ciderapp/Cider-2#427]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.20

### Operating System Version

Windows 11 22H2 2506

### Describe the Bug

The output volume of cider is to high. Even at 50% volume set in cider, the volume is overblown. In the windows mixer, the volume br is maxed out all the time. I need to reduce the volume in cider to around 33% to get reasonable results.

### Steps to Reproduce

1. Start cider
2. Play a song
3. Set volume to 100%
4. Everything is blown out and crushed, windows shows a constant 100% volume in the sound settings, external DAC shows also 100% volume all the time

**Comment by coredev-uk** [comment]
With version 3.3 there is a setting (enabled by default) called Exponential Volume which rectifies this issue.

**Comment by d4g** [comment]
There is no version 3.3? Version 2.2 is the current release, at least in the windows store. Is version 2.3 up for a release? And are you referring to that version?

**Comment by coredev-uk** [comment]
Version 2.3.0 is the upcoming release. Expect it within the coming months.
