### ISSUE TITLE
Upcoming lyrics are from previous song

### ISSUE THREAD

**Issue by jxhug** [ciderapp/Cider-2#428]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 9/21/2023, 3:27:57 PM | Quasar v2.12.6 | Electron ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

macOS Sonoma 14.1

### Describe the Bug

When playing a song the upcoming lyrics are not from the current song, but instead the song that was previously played. When the lyric is playing or has been played, it displays the correct one.

### Steps to Reproduce

I played some Travis Scott songs and noticed this. Artist probably doesn't matter though :)

### Anything else?

Fixed by closing and reopening the lyrics tab.

**Comment by cortosi** [comment]
I confirm it, same bug here.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
