### ISSUE TITLE
Repeatedly clicking the previous track button freezes player

### ISSUE THREAD

**Issue by markanthmore** [ciderapp/Cider-2#429]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 9/21/2023, 3:27:57 PM | Quasar v2.12.6 | Electron ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

Ubuntu 22.04.2 LTS

### Describe the Bug

A few things happen when spamming the previous track button. Spamming it many time takes you to the first song as expected, then the play button visually switches to the pause button and back to play sporadically. Nothing plays for about 8 seconds at it remains frozen, and then it will play the first song of the album. If you spam it from a later position in the album and it stops mid album, the song will play as intended. But reaching the first track of an album seems like it continues to attempt a previous track selection, although no such track exists.

### Steps to Reproduce

Just spam clicking the previous song button.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
