### ISSUE TITLE
Resizing a window really small creates some UI issues

### ISSUE THREAD

**Issue by markanthmore** [ciderapp/Cider-2#430]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 9/21/2023, 3:27:57 PM | Quasar v2.12.6 | Electron ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

Ubuntu 22.04.2 LTS

### Describe the Bug

Some UI issues when attempting to resize the window very small. There doesn't seem to be a min size set so I can essentially shrink the window to nothing. 

### Steps to Reproduce

Resize the window beyond any practical size, and it will create issues

![Screenshot from 2023-11-02 23-17-49](https://github.com/ciderapp/Cider-2/assets/94228589/ce4a447f-fcda-414a-9232-cbfead5c469f)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
