### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Tommyfu0603** [ciderapp/Cider-2#433]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

21-9-2023

### Operating System Version

windows 11 22h2

### Describe the Bug

when i click the play song,it could not play 

### Steps to Reproduce

same as title

### Connect Device ID

c927f0c66c6ca874f69c7564881050052e8281ef

### Build timestamp

1699026208410

**Comment by d3rpp** [comment]
@Tommyfu0603 could you please open up a ticket on our discord server and send a screenshot of the Console when you try to play a song?

To get the console use `ctrl + shift + i` and click the "Console" tab at the top.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
