### ISSUE TITLE
Scroll Bar appeared and stuck on lyric sections

### ISSUE THREAD

**Issue by Faey000** [ciderapp/Cider-2#436]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2 days ago which is on 4 november 2023

### Operating System Version

windows 10 pro

### Describe the Bug

theres two scroll bars that appeared out of the blue on lyric sections snd it wont dissapeared

### Steps to Reproduce

1. i just open the lyric section on the player then the bug appears

**Comment by Kawasumii** [comment]
Same issue. Using Windows 11 Pro and Program from MS Store

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
