### ISSUE TITLE
Volume decreases on close

### ISSUE THREAD

**Issue by itsjst** [ciderapp/Cider-2#437]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 28. 10. 2023, 11:34:59 | Quasar v2.13.0 | Sabiiro fc841535754a54f65f30fe543el6af6abcldb4cd

### Operating System Version

Windows 10 22H2 with AtlasOS v0.3.0

### Describe the Bug

When I close Cider with volume on 50% and then open it back up the volume is now 32%. If I then close it and open it again the volume will stay at 32%. So the volume changes only on the first close. The amount by how much it reduces varies on the % (from 30% down to 14%, from 10% to 2%), but when its on 100% it stays the same (on 99% it goes down to 98%).
When I start up my computer and then open Cider the volume is always on 1%, no matter the % I left it on.

### Steps to Reproduce

Close Cider and then open it.

### Anything else?

This only happens when exponential volume is turned on.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
