### ISSUE TITLE
Cider unable to load multiple songs

### ISSUE THREAD

**Issue by addievo** [ciderapp/Cider-2#438]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

21/9/23::13:55:55

### Operating System Version

W11-22623.1020

### Describe the Bug

1. Cider is skipping numerous songs on multiple playlists and artist radios.
2. This behaviour seems to be entirely random and not based on explicit settings or such.
3. Apple music's region is currently set to India, however I using it from Australia (could be an influencing factor?) Probably not as I can use the native Apple Music app well enough.
4. I have tried reinstalling it thru Microsoft store to no avail.

### Steps to Reproduce

1. Use an account of Indian region (possibly?).
2. Try to play https://music.apple.com/in/playlist/1-mon-b%C3%A9b%C3%A9/pl.u-zPyLlJ5Fe6Y1dK4
3. Profit?
4.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
