### ISSUE TITLE
[Bug]: WebView using secondary GPU even when hardware acceleration is disabled

### ISSUE THREAD

**Issue by edge261** [ciderapp/Cider-2#44]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

I expect Cider to use the primary GPU since it's a laptop with 2 gpus. But even disabling hardware acceleration in the settings menu, it completely ignores that and renders in the secondary gpu, using way more battery and generating more heat.

### Steps to Reproduce

Open Cider, then check Task Manager.

**Comment by coredev-uk** [comment]
MusicKit can be a bit weird when it comes to content restrictions. Please go to https://tv.apple.com/settings and sign in to check your content restrictions. This may be different to ones on your phone and/or on other Apple platforms (don't ask its just Apple being themselves).

**Comment by edge261** [comment]
This bug still exists on the Sabiiro version.

**Comment by coredev-uk** [comment]
Closing this, it appears we cannot directly control which GPU the application uses with Tauri.
