### ISSUE TITLE
Unwanted scroll bars

### ISSUE THREAD

**Issue by minhdangphuoc** [ciderapp/Cider-2#443]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 9/17/2023, 11:16:34 PM

### Operating System Version

Window 11 Home 22H2

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/37279565/4c1ebf8b-8b76-409d-ab95-f8433dc69bef)
![image](https://github.com/ciderapp/Cider-2/assets/37279565/6462a1db-894e-45db-989f-afc19ca9687a)
As you can see, there are some "empty" scroll bars in my screenshots. They are so annoying. 

### Steps to Reproduce

First appearance 
1. Open application.
2. Click an album 
3. You can see it appears next to the animated artwork.

Second appearance 
1. Change to immersive View.
2. You will see it appears at the right side.

**Comment by tscharich** [comment]
I'm having the same issues. For me it's only an issue on Windows. I use Cider on Mac and Ubuntu also and have never experienced that issue.

![image](https://github.com/ciderapp/Cider-2/assets/13457461/0653e09f-1d4b-451e-b693-d6487532269a)
This is a photo is what happens to me on the lyrics page in immersive mode.

**Comment by coredev-uk** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/64542347/36f7567f-7b93-4c81-9bef-49276ae9863d)
