### ISSUE TITLE
[Bug]:播放列表问题

### ISSUE THREAD

**Issue by TonyKingWJX** [ciderapp/Cider-2#444]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

自己创建、最常用的播放列表中的音乐有许多重复的

### Operating System Version

win11 22H2

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/115714101/0efc272f-d857-444c-848a-626f42336098)
播放列表里的音乐是重复的，在applemusic上没有遇到

### Steps to Reproduce

我也不知道怎样做到的，反正播放列表就是这样

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/115714101/560b20e4-ac83-41be-9a50-1e29a3c1b16b)

### Build timestamp

1699843042468

**Comment by coredev-uk** [comment]
Please submit issues in English
