### ISSUE TITLE
[Bug]: UI sort order is incorrect

### ISSUE THREAD

**Issue by IsaacMarovitz** [ciderapp/Cider-2#446]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Version 2.2.0 (Built 21/09/2023)

### Operating System Version

macOS Sonoma 14.1

### Describe the Bug

Search results are drawn behind playback controls.

### Steps to Reproduce

1. Search for something with a window sufficiently small for the search results and playback bar to overlap
2. Sort order is incorrect

### Anything else?

<img width="518" alt="Screenshot 2023-11-13 at 19 35 03" src="https://github.com/ciderapp/Cider-2/assets/42140194/17d4973b-1602-4a2e-9ebd-528f1c0024f7">

**Comment by coredev-uk** [comment]
Edge case, the application was not made to be run in such a way.
