### ISSUE TITLE
Login not being saved. Login everytime after PC Reboots.

### ISSUE THREAD

**Issue by MaybeFX** [ciderapp/Cider-2#447]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 17.9.2023 

### Operating System Version

Windows 10 Pro

### Describe the Bug

The Login info to my Apple Music account dont get saved properly. Everytime I restart my computer I have to login to apple music again in order for cider to work.
It shows the Welcome Screen everytime.

### Steps to Reproduce

No Idea how to reproduce, applications starts and its just the welcome screen leaving me with no other option than to login again,

**Comment by coredev-uk** [comment]
Have you reinstalled?

**Comment by NighterStyle** [comment]
I am having the same issue,did you manage to fix it?

**Comment by coredev-uk** [comment]
Ensure you are on the latest version. Try deleting the application data folder found in `%localappdata%/sh.cider.sabiiro` and reinstalling. 

If your download is obtained from itch or the MS store you will need to wait for the 2.3.0 update in the coming days, this contains a patch for correct persistence.
