### ISSUE TITLE
Played tracks are not displayed in recently played on AM profile

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#448]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

10.11.2023 build

### Operating System Version

win10 22h2

### Describe the Bug

Played tracks/albums are not displayed in recently played on my AM profile

### Steps to Reproduce

1. play a song
2. check am preview/mobile

**Comment by coredev-uk** [comment]
iirc vapor had a work around for this

**Comment by UnbreakCode** [comment]
any updates on this? that's really annoying

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
