### ISSUE TITLE
Icons & Buttons Missing

### ISSUE THREAD

**Issue by BURRROW** [ciderapp/Cider-2#449]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Cant view due to bug.

### Operating System Version

Windows 10

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/151400106/10a650b3-62da-4641-b7ad-cda65fd89a85)

Many buttons or images appear and disappear for no apparent reason.

### Steps to Reproduce

1. Opened Cider

that's about it...

**Comment by coredev-uk** [comment]
Please update your application to the latest version and perform a clean installation (delete `%localappdata%/sh.cider.sabiiro` and reinstall).

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
