### ISSUE TITLE
Can't access certain albums via search

### ISSUE THREAD

**Issue by alanpmartin** [ciderapp/Cider-2#450]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

21/09/2023

### Operating System Version

Windows 11

### Describe the Bug

The search function finds albums, but often is left hanging when I click on them. If I go to the same album via my own library, it loads instantly. 

### Steps to Reproduce

Search for an album in the search bar at the top of the screen. Around half hang for me, I'd say.

https://github.com/ciderapp/Cider-2/assets/151430072/bafe5764-ed5c-4b4d-b4ce-8b7cb598c661

**Comment by coredev-uk** [comment]
Another weird bug. Could you open the devtools (Ctrl+Shift+I) and screenshot the console?

**Comment by alanpmartin** [comment]
@coredev-uk 

Sure! I'm not a developer, so it doesn't mean much to me, but I think this is the bit that appeared when I did clicked on an album via search...
![Screenshot 2023-12-12 013400](https://github.com/ciderapp/Cider-2/assets/151430072/0f8e3dfd-c02d-405c-b919-cb41b27331f5)

**Comment by AlexA1S** [comment]
I have the same issue too. This time with some of the Katy Perry songs.

The one im trying to play is "California Gurls", doesnt play. When I right click on the albumn to show it, it also doesnt load.

![Untitled](https://github.com/ciderapp/Cider-2/assets/68241926/b22347b8-16ba-40ee-89ce-9c6b925d7325)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
