### ISSUE TITLE
[Bug]: Closing the rewritten mini player quits the program rather than minimizing it to tray

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#456]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 11/29/23 at 6:23 PM (the most recent build posted in preleases as of creating this bug report)

### Operating System Version

Windows 11 22H2 22621.2715

### Describe the Bug

Even when the Minimize to Tray option is enabled in settings, clicking the X in the mini player closes out the program entirely rather than to the tray. 

### Steps to Reproduce

1. Enabled minimize to tray in the settings
2. Entered the mini player
3. Clicked on the X expecting it to minimize to the tray, but instead Cider closes fully

### Build timestamp

1701315384624

**Comment by booploops** [comment]
behavior was modified in later RC.  the close button now dismisses the mini player
