### ISSUE TITLE
[Bug]: Pinned Items can't be edited

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#458]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0-rc.1

### Operating System Version

Windows 11 22H2 22621.2715

### Describe the Bug

Items pinned to the home screen don't respect the editing pane when trying to move items around. The editing pane shows the items being moved around, but it's not reflected on the home page itself, and the editing pane reverts back to what's shown on the home screen upon restarting the app. 

### Steps to Reproduce

1. Pinned items to the home screen
2. Opened the editing pane to adjust the order
3. Dragged an item to a different spot
4. The moved item is reflected in the editing pane, but not on the home screen (even when changing pages to refresh the home screen)
5. Restart the app
6. Opened the app again
7. Reopened the editing pane to find that edits have been reverted

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/95056585/1580fceb-d0f1-4180-b6a8-5152b017023a)
An example of edits not being reflected

### Build timestamp

1701383092545

**Comment by mpar-22** [comment]
I am using connect yes, I was on the latest 2.3.0 build at the time though (the release candidate build), not 2.2.0.

**Comment by mpar-22** [comment]
I'm still having issues on the latest version of Cider (2.3.0-RC2). Is it patched in a newer build not accessible to testers yet?

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
