### ISSUE TITLE
[Bug]: Musixmatch Translation not working for some songs

### ISSUE THREAD

**Issue by chbmckie** [ciderapp/Cider-2#459]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

2.3.0 RC

### Operating System Version

MacOS Sonoma

### Describe the Bug

When playing the song De Chill (feat. David Otero) by Zzoilo, despite the song being available on musixmatch with translations, they don't show up even with the setting enabled.

### Steps to Reproduce

1. Enable lyric translations
2. Play the song De Chill (feat. David Otero) by Zzoilo
3. Notice the lack of translations

### Build timestamp

1701622232830

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
