### ISSUE TITLE
Live lyrics doesn't match with the music

### ISSUE THREAD

**Issue by Donovan3692** [ciderapp/Cider-2#462]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

09/12/2023

### Operating System Version

macOS Sonoma 14.2 RC

### Describe the Bug

When you listen a music, futures lyrics of the music don't match with the music, it keep the previous lyrics of the previous music

### Steps to Reproduce

Enable live lyrics and listen a music, you will the the futures lyrics don't match with the music but match with the previous music

### Anything else?

https://github.com/ciderapp/Cider-2/assets/85370266/84404c25-b5cc-45db-872a-08f012b022af

**Comment by fernandosang** [comment]
Same here on the Linux app.

**Comment by scottti312** [comment]
Same here on the Windows 11. Cider version 2.2.0.

**Comment by cryptofyre** [comment]
This should be fixed in Cider 2.3.0, do let us to know if it continues when 2.3.0 is released very soon. Closing this for now.
