### ISSUE TITLE
[Bug]: Immersive mode and lyrics

### ISSUE THREAD

**Issue by Brize-Glace** [ciderapp/Cider-2#463]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 17/09/2023

### Operating System Version

Windows 11 Pro 23H2

### Describe the Bug

BUG 1: When you enter immersive view and access the lyrics (after the beginning of a song), you need to scroll down at the correct line to see the lyrics, which then scroll automatically correctly. Or sometimes the lyrics are not showing.
BUG 2: If CIDER 2 is not your selected tab while in immersive view, you have to move the mouse over the CIDER 2 application to correctly display the cover, name, and artists of the new music. Even if it is your selected tab, you still need to move the mouse for the display to update accurately in immersive view.

### Steps to Reproduce

BUG 1:
1. Enter immersive view
2. go to the lyrics
3. see that if it's not the beginning of a song that the lyrics are not working and you need to scroll at the correct line to enjoy proprely the lyrics.

https://github.com/ciderapp/Cider-2/assets/78274209/67ec7cc1-ca35-4682-9244-955bb873ef75

"BUG 2:
1. Enter immersive view.
2. Deselect the Cider 2 tab as your selected tab (or keep it selected).
3. Wait until the end of a song.
4. Observe (and move the mouse over the app)."

https://github.com/ciderapp/Cider-2/assets/78274209/01bfdd5f-29be-4014-bf5f-ec6976580991

### Anything else?

Thanks. Love your app 

### Build timestamp

1702246640119

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
