### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Harold-Brooks** [ciderapp/Cider-2#466]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/20/2023

### Operating System Version

windows 11 pro version 23H2

### Describe the Bug

I start playing a song and look at the now-playing section of the action center. it shows the song. when the next song starts playing I recheck the action center and the previous song is shown.

I expect the current song to be displayed when I check the action center

### Steps to Reproduce

1. open cider
2. que more than one song
3. check the action center while the first song is playing, and you will see it displayed there along with some controls
4. close the action center
5. let the next song begin playing
6. open the action center again, and you will see the previous song displayed in the now-playing section, you will not be able to use the controls to pause or skip the song from the now-playing section either

### Build timestamp

1702485958723

**Comment by cryptofyre** [comment]
Windows bug, we can't really do much about this for now as it doesn't happen on the Insider testing channels nowadays.
