### ISSUE TITLE
"Various Artists" displayed as Lin-Manual Miranda

### ISSUE THREAD

**Issue by IsaacMarovitz** [ciderapp/Cider-2#467]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Version 2.2.0 (Built 21/09/2023)

### Operating System Version

macOS Sonoma 14.1

### Describe the Bug

Albums credited to `Various Artists` instead show as being by Lin-Manuel Miranda. This can be seen on the Scott Pilgrim Vs. The World Soundtrack.

There also seems to be a discrepancy in the release year, Cider shows the earliest date of any song in the album, whereas Apple Music shows the most recent date of any song in the album.

Cider:
<img width="923" alt="Screenshot 2023-12-13 at 20 57 16" src="https://github.com/ciderapp/Cider-2/assets/42140194/81d446ff-8cdd-459c-914f-d7a065a875b3">

Apple Music:
<img width="1166" alt="Screenshot 2023-12-13 at 20 57 37" src="https://github.com/ciderapp/Cider-2/assets/42140194/416be98c-0cd9-4c77-8a15-44e95994f5d4">

### Steps to Reproduce

View the Scott Pilgrim Vs. The World Soundtrack album in Cider, observe incorrect artist and release year.

**Comment by IsaacMarovitz** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/42140194/c6bf1478-b329-4f7d-81f5-42cf4f5c4ece)

Persists in 2.3.0 RC 4

**Comment by cryptofyre** [comment]
We really have not a clue why this happens to you, and you only. Only thing I can suggest is to remove all Cider's related supporting files.
