### ISSUE TITLE
Replay doesnt work

### ISSUE THREAD

**Issue by unjuanpablo** [ciderapp/Cider-2#468]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

I install Cider today

### Operating System Version

Windows 11

### Describe the Bug

When i click on the 3 dots and select Replay, doesnt work, its always loading
![Screenshot_2](https://github.com/ciderapp/Cider-2/assets/153863394/a82d4182-69b9-4394-ade6-e5c6a38da61b)

### Steps to Reproduce

Click on the 3 dots, the click Replay

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
