### ISSUE TITLE
Add to queue/play next doesn't work when playing from radio

### ISSUE THREAD

**Issue by willbarkoff** [ciderapp/Cider-2#470]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

9/21/2023

### Operating System Version

Ubuntu 22.04.3 LTS x86_64

### Describe the Bug

When playing a radio station, I want to be able to queue another song to play next (as I can on iOS). It doesn't work.

### Steps to Reproduce

1. Start a radio station
2. Pick another song
3. Right click
4. Click the "play next button"

### Build timestamp

1702611772288

**Comment by jamopopper** [comment]
It doesn't work on Windows either, and it's been like this for a long time. Cider 1 also wasn't able to do this

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
