### ISSUE TITLE
GUI garbled and unusable

### ISSUE THREAD

**Issue by snds** [ciderapp/Cider-2#472]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Can't get the details due to the UI (see screenshot)

### Operating System Version

Windows 11 23H2, currently updated

### Describe the Bug

When loading and using Cider, the interface bugs out and replicates every element and effect.
![Cider Screenshot 2023-12-19](https://github.com/ciderapp/Cider-2/assets/570874/72ff6ea3-e3b1-489a-895d-8f157a4db33f)

### Steps to Reproduce

No clue how to reproduce. It happens just after connecting to Apple to load my user profile.

### Anything else?

I have uninstalled, reinstalled, repaired, and reset Cider to no avail. I cannot log in or out of Apple meaningfully to test if that is causing this, as it happens just after loading my Apple account information; the initial screen before signing me in does not seem to have this GUI issue. I have updated Windows with all the latest patches and ensured my GPU drivers are updated. This does not happen in ANY application other than Cider. Reboots do not solve this issue either.

**Comment by cryptofyre** [comment]
This is caused by Windows having some pretty awful HDR support in their own WV2 framework. I'd advise disabling HDR for the time being until a solution is found within WV2 and Windows itself.

We can't really do anything about this on our end as it's very random and doesn't happen to everyone and has no correlation to any of our code specifically.

**Comment by snds** [comment]
> This is caused by Windows having some pretty awful HDR support in their own WV2 framework. I'd advise disabling HDR for the time being until a solution is found within WV2 and Windows itself.
> 
> We can't really do anything about this on our end as it's very random and doesn't happen to everyone and has no correlation to any of our code specifically.

Fair enough. I'll just wait on using Cider until Windows offers a fix. Thanks for the context.
