### ISSUE TITLE
[Bug]: one of my playlists is showing 600 songs  instead of the original amount of songs thats in the playlist (612)

### ISSUE THREAD

**Issue by T-BeatzYT** [ciderapp/Cider-2#473]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

A month ago

### Operating System Version

Windows 10

### Describe the Bug

one of my playlists is showing 600 songs  instead of the original amount of songs thats in the playlist (612)

### Steps to Reproduce

Idk how, I just went down to the playlist and it showed the wrong amount of songs

### Build timestamp

1703117340144

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
