### ISSUE TITLE
[Bug]: Artist's Top Songs playlist doesn't play songs beyond 100th

### ISSUE THREAD

**Issue by lpaulino07** [ciderapp/Cider-2#474]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

12/20/2023

### Operating System Version

Arch Linux 6.6.7-arch-1

### Describe the Bug

Trying to play a song beyond the 100th in an artist's "Top Songs" will not work.

### Steps to Reproduce

1. Go to any artist's "Top Songs".
2. Scroll down beyond the 100th song.
3. Try to play the song.
4. Song will not play, as well as any song after it.

### Build timestamp

1703213093966

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
