### ISSUE TITLE
[Bug]: So I have a very long playlist from Ariana Grande, everytime I open it, cider doesnt load it fully, i have to press the button of load much times so it loads... its annoying.

### ISSUE THREAD

**Issue by MuriloNovel** [ciderapp/Cider-2#475]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.12.6

### Operating System Version

WINDOWS 11

### Describe the Bug

So I have a very long playlist from Ariana Grande, everytime I open it, cider doesnt load it fully, i have to press the button of load much times so it loads... its annoying.

### Steps to Reproduce

Well, just open a very long playlist 

### Build timestamp

1703360726292

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
