### ISSUE TITLE
Some Songs dosen't want to play by the client.

### ISSUE THREAD

**Issue by ardent06** [ciderapp/Cider-2#476]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

7e009fdcf24668b1d4551e81119c3ac2458e5444

### Operating System Version

Windows 11 23H2

### Describe the Bug

Only some of  songs plays.

### Steps to Reproduce

Clicked on search bar
and searched for "moves like jagger"
click on it
song should play. 

### Anything else?

https://drive.google.com/file/d/1jJkC2hitud1gcOnjQN7KQuOF1o1ioHBm/view?usp=drive_link

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
