### ISSUE TITLE
some, not all, playlist folders empty

### ISSUE THREAD

**Issue by morpson** [ciderapp/Cider-2#477]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 9/21/2023, 5:24:12 PM | Quasar v2.12.6 | Electron ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

macOS Sonoma 14.2.1

### Describe the Bug

1 of 3 playlist folders are empty/missing all playlists. The other 2 folders are working correctly. The playlists included in the empty folder are also not existing in search, library, etc. I've tried re-indexing the database and even creating a new folder with a different name and moving the playlists into it - the new folder does appear in cider but, it's empty.
![tempImagegPKJvS](https://github.com/ciderapp/Cider-2/assets/78716446/5be81ec3-fc11-443f-a23e-b082c05c63ed)

### Steps to Reproduce

From the playlists category

### Connect Device ID

07ddbdd5-8c33-4a3-a32f-208236b43735

### Build timestamp

9/21/2023, 5:24:12 PM

**Comment by coredev-uk** [comment]
Smart playlists are not supported in Cider. This is a limitation on Apples part as smart playlists are fetched using a separate proprietary API.
