### ISSUE TITLE
My instance of Cider 2.2.0 (Windows Store) seems to have problems syncing back to Apple Music

### ISSUE THREAD

**Issue by darumakku** [ciderapp/Cider-2#478]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/20/23

### Operating System Version

Windows 11 Home version 22H2

### Describe the Bug

I have a group of issues that I suspect are related to some problem syncing with my Apple Music account.

Any time I open Cider, whether or not it has previously been opened in the same Windows session, the app is in a default state showing that I am not signed in. The central pane says "You are not signed in" and the prompt at the top left of the window says "Sign into Apple Music." If I leave it for a few moments, it signs itself in, but as mentioned, does not retain this state between app sessions.

If I sign out of my Apple Music account and then sign back in, I get the "problem connecting" window. Eventually (after a few seconds) the app reflects the signed-in status.
<img width="583" alt="Screenshot 2023-12-27 161833" src="https://github.com/ciderapp/Cider-2/assets/155021728/4707cc29-33cf-4d2c-9e51-09bc5f5dab38">

I am unable to add songs to my library within Cider 2 - clicking the plus button generates no response, and the song/album/etc. is not added to my library; I am likewise unable to remove things from my library - clicking the trashcan icon in the ... menu generates no response. See attached GIF for examples of the former:

![Cider 2 2 0 bug](https://github.com/ciderapp/Cider-2/assets/155021728/e5b6cda6-8821-44c5-be9d-460f9f889af7)

The "recently listened" and recent searches in Apple Music for iOS and MacOS do not reflect activity within Cider 2, e.g. if I listen to an album within Cider 2 and then check my Apple Music for iOS ten minutes later, it does not show my listening activity. If I search Apple Music for a specific artist within Cider 2, and then start another search within Apple Music, it does not display recent searches. What's weirder is that in the course of troubleshooting this, I signed out of Cider 2, and upon signing back in, Cider 2 did not reflect the "recently played" activity from the app prior to my signing out. I suspect that because Cider has not been syncing my activity back to my Apple Music account, the activity was not subsequently reflected back to Cider 2 after the sign-out/sign-in.

### Steps to Reproduce

I am not sure if this is possible to reproduce without being able to sign into my account. Please let me know if you have suggestions.

### Anything else?

As mentioned, in trying to remedy this problem, I have tried signing out and signing back in without success. On December 17th, I tried uninstalling the Windows Store app and installing Cider 2.3 from the itch.io page; all of these same issues persisted in 2.3. I subsequently reinstalled the Windows Store version and the problems continue. 

If there is a specific application data folder I should try deleting, please let me know. I have not tried the portable version of the app.

**Comment by seyaidev** [comment]
Looks like the same problem as #448

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
