### ISSUE TITLE
Playlists Still Stopping at 100

### ISSUE THREAD

**Issue by Ezyne23** [ciderapp/Cider-2#481]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.1.0 [2023/7/16 (Quasar v2.11.10)] to Version 2.2.0 [2023/9/20 (Quasar v2.12.6)]

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

Where my personal playlists should be over 100 Songs, in Cider 2 they will stop at 100 and I cannot access any songs past that point

The following screenshot is presenting the same playlist in Cider Classic (on the Right) and in Cider 2 (on the Left)
![image](https://github.com/ciderapp/Cider-2/assets/134811348/ee65260c-91bb-4bbb-a493-1500cdb0b7fe)

### Steps to Reproduce

Have a playlist with over 100 Songs

There are no known extra steps needed to reproduce

### Anything else?

I have issued about this bug in the past before sometime around August, and I have not seen it get fixed anytime between then and now

### Connect Device ID

Version 2.2.0

### Build timestamp

2023/9/20

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
