### ISSUE TITLE
Cannot add album to playlist

### ISSUE THREAD

**Issue by jamesdesilva14** [ciderapp/Cider-2#482]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

9/21/2023 5:27:31PM

### Operating System Version

pop os 22.04

### Describe the Bug

When I try to add an album to a playlist, the pending actions tab (spinning circle) shows "Adding to playlist", but never finishes.  Checking the playlist shows that the songs on the album have not been added.

### Steps to Reproduce

1. Go to any album.
2. Click the "..." for the album.
3. Select "add to playlist" and click a playlist.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
