### ISSUE TITLE
[Bug]:Add new theme menu overlay my lists in mini player, it is not possible to add new themes.

### ISSUE THREAD

**Issue by c0cran** [ciderapp/Cider-2#484]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.2.0

### Operating System Version

Windows 10 22H2

### Describe the Bug

Add new theme menu overlay my lists in mini player, it is not possible to add new themes.
![Cider BUG](https://github.com/ciderapp/Cider-2/assets/156514907/74bb487b-61a6-43c4-ac45-d2bc098441c2)

### Steps to Reproduce

1- Open Mini Player
2- Add new theme to playlist

### Build timestamp

1705144850411

**Comment by c0cran** [comment]
My desktop has 4k resolution (3840x2160)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
