### ISSUE TITLE
Musixmatch lyrics only load in full screen mode

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#486]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0 RC 12

### Operating System Version

Windows 11

### Describe the Bug

Currently, the Musixmatch lyrics are only available in full screen mode. But it would be good if they could be loaded as soon as AM can't provide lyrics.

### Steps to Reproduce

Play a song that has no lyrics on AM (Laserkraft 3D - Weightless)

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
