### ISSUE TITLE
[Bug]: Missing playlists

### ISSUE THREAD

**Issue by moiep** [ciderapp/Cider-2#488]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Attached at the bottom 

### Operating System Version

Windows 11 Pro

### Describe the Bug

When I click on 'All Playlists' in sidebar, main page loads up blank and top right hand corner says 0 playlists. The loading/refresh cog in the top right corner also stays stuck on rotation.
<img width="770" alt="image" src="https://github.com/ciderapp/Cider-2/assets/104405105/62475588-7f1d-4f8d-92ca-30497f5bae44">

Recently added is also empty:
<img width="775" alt="image" src="https://github.com/ciderapp/Cider-2/assets/104405105/85a7f3b4-88b8-47f3-b6c2-752bb44fcd52">

### Steps to Reproduce

When I click on 'All Playlists' in sidebar, main page loads up blank and top right hand corner says 0 playlists. 

### Anything else?

My Build information
<img width="265" alt="image" src="https://github.com/ciderapp/Cider-2/assets/104405105/af2b39a6-a539-4bef-8732-f42bdd423261">

### Build timestamp

1705369617957

**Comment by divrep222** [comment]
> We've deployed a fix in the version 2.3.0-hotfix1 branch, you can update to this version in the update manager. Please try and update to this and enable "Use Experimental Playlist Retrieval Method" in Settings > Experiments. Then refresh the playlists.

Fixed my playlist display, thanks!
