### ISSUE TITLE
Does not Resize

### ISSUE THREAD

**Issue by shadowdemons09** [ciderapp/Cider-2#491]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

09/17/2023

### Operating System Version

Windows 11 Pro 23H2

### Describe the Bug

After opening, resizing/shaping/positioning app, closing, and reopening, does not retain its size, position or shape.

### Steps to Reproduce

Open Cider, position, resize/shape to own liking, close app, reopen.

**Comment by ChaosP1ayer** [comment]
Found this this morning as i was searching for exact same thing yesterday.
This is a thing, please address.
Thank you.
.\\

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.

**Comment by shadowdemons09** [comment]
really unfortunate. However, i did see from another user's posted issue that you are working on a replacement app that may include this functionality? Code name Arsene?

**Comment by coredev-uk** [comment]
> really unfortunate. However, i did see from another user's posted issue that you are working on a replacement app that may include this functionality? Code name Arsene?

Yes, this is a planned feature for it. No other big features will be added to the current codebase, all main ones are being put towards this new codebase.
