### ISSUE TITLE
Current sentence in Lyrics loses focus too soon.

### ISSUE THREAD

**Issue by MxValkyrae** [ciderapp/Cider-2#492]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 21/09/2023, Quasar v2.12.6

### Operating System Version

Fedora Workstation 39 (also an issue on Windows)

### Describe the Bug

When using lyrics each sentence starts and ends quite abruptly. There's no padding to focus each sentence slightly before and after it's sung. So quite often the current sentence will lose focus even if the singer hasn't quite finished the last word and it's quite jarring.

### Steps to Reproduce

Play a song, watch the lyrics.

**Comment by MxValkyrae** [comment]
It should be noted this is an issue with "Sing" word-synced lyrics. I don't seem to have this issue with the usual sentence-synced lyrics.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
