### ISSUE TITLE
Scrolling leaves artifacts in the window

### ISSUE THREAD

**Issue by dotbeseck** [ciderapp/Cider-2#493]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Installed 1/22/2024 Build 9/20/2023

### Operating System Version

Windows 11 Build 22635

### Describe the Bug

Upon opening Cider and movement of the window or scrolling leaves artifacts throughout the app. Makes the text blurry. 

### Steps to Reproduce

1. Open App
2. Move or scroll app
3. See artifacts left where text used to be.

### Anything else?

Here's a gif of it happening, it oddly seems to only happen on the Home Page. On album and playlist pages, its fine.
![artifacting](https://github.com/ciderapp/Cider-2/assets/77022002/3aef630f-5850-4582-8695-b4dd58827fd0)

**Comment by cryptofyre** [comment]
This seems to correlate with Cider 2.2.0 and HDR for some reason. This should be fixed in 2.3.0 I believe, as I have not experienced it in my testing.
