### ISSUE TITLE
[Bug]: "notification.playlistRefreshNoPlaylist" issue

### ISSUE THREAD

**Issue by karo-boss** [ciderapp/Cider-2#494]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

9/21/2023, 6:55:55 AM | Quasar v2.12.6 | Sabiiro c927f0c66c6ca874f69c7564881050052e8281ef

### Operating System Version

Windows 10 Pro

### Describe the Bug

It is always like this. I can't see my playlists and app always try to refresh. But nothing changes. And it continues weeks.
![Capture](https://github.com/ciderapp/Cider-2/assets/157516460/090b08aa-f778-4bea-a27e-d25faa025593)
![Captuaare](https://github.com/ciderapp/Cider-2/assets/157516460/12399ba4-5592-45c8-bd35-861f256cd427)

### Steps to Reproduce

I just open the app. And then it starts to refresh like always do. But it is endless process. Never stops and nothing changes. I play a playlist on my phone so I can able to find it at recently played section in app. Playlist section always empty. I try to reset database, repair the app, reinstall, disconnect apple music and reconnect etc. I like the app and using it like 18 hours a day, also I paid when  first installation. But I'm just bored with this bug. So please fix it or help me to fix it if anything I can do as a user.

### Build timestamp

1706028979975

**Comment by coredev-uk** [comment]
old bug, wait for the next itch release
