### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by SkyKiller6363** [ciderapp/Cider-2#495]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Quasar v2.12.6

### Operating System Version

Windows 11 22H2

### Describe the Bug

Lyrics don't automatically scroll intermittently. 

### Steps to Reproduce

Open a playlist, hit play or shuffle, then bring up the Lyrics. You should notice the lyrics highlight appropriately, but it won't start scrolling until I manually scroll down to match. Then it'll start scrolling automatically, until the next song, or the song after that, or part way through the song. 

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/112779914/9a03396b-b9e4-4bc0-8bd7-b083706faa64) 

(This shows that the lyric is NOT in the middle of the page like it's supposed to, and not automatically scrolling. 

![image](https://github.com/ciderapp/Cider-2/assets/112779914/b87076cf-aaf1-45ce-a97a-a20b830d0a70)

Couldn't find a Connect Device ID??? Sorry

### Build timestamp

1706109399691

**Comment by enzo-js** [comment]
they dont give a fuck. garbage ass devs have all but abandoned this app.

**Comment by SkyKiller6363** [comment]
Thank you for your input 🙄

**Comment by cryptofyre** [comment]
> they dont give a fuck. garbage ass devs have all but abandoned this app.

Yes, we do and no we haven't.
![image](https://github.com/ciderapp/Cider-2/assets/33162551/024c5881-1c83-468e-beb7-0852a9f6a40a)

**Comment by cryptofyre** [comment]
Anyways, that user has been banned from communicating with the organization.

Your issue has since been fixed in 2.3.0, thanks for the bug report!

**Comment by SkyKiller6363** [comment]
Awesome, thank you so much!

**Comment by SkyKiller6363** [comment]
So... the latest version I can seem to find is the 2.12.6. In order to get anything more than that, do I have to get the nightly builds?

**Comment by cryptofyre** [comment]
We should have an update out just around the corner.
