### ISSUE TITLE
[Bug]:months and months and months of no changes. SORT MY ARTISTS CORRECTLY

### ISSUE THREAD

**Issue by enzo-js** [ciderapp/Cider-2#496]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

garbage

### Operating System Version

windows 11

### Describe the Bug

yall dgaf. sort my artists correctly

### Steps to Reproduce

OPEN THE APP

### Anything else?

fuck off. 
![Cider_2doFzo5eym](https://github.com/ciderapp/Cider-2/assets/46859140/0b7d7eb4-2150-4b42-aac8-2a786d83c2c9)

### Connect Device ID

stfu

### Build timestamp

1706142589153

**Comment by cryptofyre** [comment]
Been fixed in 2.3.0, for a while.
![image](https://github.com/ciderapp/Cider-2/assets/33162551/cd6c874b-4089-4d76-9dff-2e820f7f32b9)
