### ISSUE TITLE
Brillo en el mini reproductor

### ISSUE THREAD

**Issue by sickolechuga** [ciderapp/Cider-2#500]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

si

### Operating System Version

Windows 10 Pro Versión 22H2

### Describe the Bug

al momento de poner el mini reproductor me di cuenta que en ciertas canciones el brillo de la imagen de la canción es muy alto, en otros se ve bien o normal por así decirlo. No se si se pueda corregir mediante la configuración de la app pero por lo que estuve revisando no encontré algo para poder solucionarlo. saludos 
![ok](https://github.com/ciderapp/Cider-2/assets/157974370/2d3bf3e9-7347-43f2-9608-c3b268fba7d6)
![Brightness](https://github.com/ciderapp/Cider-2/assets/157974370/a84582fb-8236-4294-a966-f248eea59025)
![Brightness 02](https://github.com/ciderapp/Cider-2/assets/157974370/aa992449-8109-43a4-a440-989d75b48a41)

### Steps to Reproduce

solo poner el mini reproductor

### Anything else?

como info adicional, compre la app a través de la Microsoft Store.

**Comment by coredev-uk** [comment]
English only please.
