### ISSUE TITLE
[Bug]: MacOS notifications do not auto-dismiss

### ISSUE THREAD

**Issue by eslothower** [ciderapp/Cider-2#501]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

9/21/2023

### Operating System Version

MacOS 14.2.1

### Describe the Bug

When a new song starts, a MacOS notification displays in the top right corner of my display saying what the song is that is now being played. However, the notification does not auto-dismiss like any other notification does. I have to manually swipe it away or hit the X button on the notification to dismiss it.

### Steps to Reproduce

1. Shuffle a playlist
2. Let a new song auto-play
3. The notification should display. Don't manually dismiss it. You will see that it won't auto-dismiss

### Build timestamp

1706542992921

**Comment by UmmActuallyJP** [comment]
Have you checked to see if Cider is set as a "banner" or an "alert in system settings? Alerts don't go away on their own until you interact with them. Banners are what you'd know as a 'normal' notification that goes away after a bit

system settings > notifications > cider > banners
![System Settings Screenshot on 02-12-2024@2x](https://github.com/ciderapp/Cider-2/assets/65521418/9d07b3a2-5f0a-4f99-affb-17d677559e90)

**Comment by eslothower** [comment]
That was it! Sorry for the silly ticket.

**Comment by coredev-uk** [comment]
I have since made a change that will remove the notification after 5 seconds in any case.
