### ISSUE TITLE
Animated Album Art very bright when turned on

### ISSUE THREAD

**Issue by yhqe** [ciderapp/Cider-2#502]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

"Built on 9/20/2023, 10:55:55 PM" c927f0c66c6ca874f69c7564881050052e8281ef

### Operating System Version

Windows 10 22H2 (Build 19045.3803), also occuring on Windows 11 23H2

### Describe the Bug

Whenever animated album art is shown, once it starts playing, it suddenly goes very bright. Here's an example from Destroy Lonely's "If Looks Could Kill (Directors Cut)":

![Cider_VNtHpv9r4R](https://github.com/ciderapp/Cider-2/assets/139268606/70cf73c0-98a8-4b2a-80c0-34c689775bdd)
Also happens in the album page, not just immersive mode:

![Cider_jQYBOBEibE](https://github.com/ciderapp/Cider-2/assets/139268606/b67511b1-0b12-430e-9cb0-49f68e0234e1)

### Steps to Reproduce

View any animated art anywhere.

### Connect Device ID

395fd91d-c115-49e1-954a-a16d8bf9946b

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
