### ISSUE TITLE
Playlist Folder artwork not displaying

### ISSUE THREAD

**Issue by a-rock-lobster** [ciderapp/Cider-2#503]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Version 2.2.0

### Operating System Version

14.2.1

### Describe the Bug

Playlist artwork displays fine, but playlist _folder_ artwork saved in the regular apple music client doesn't show up in Cider. I use Marvis on my phone and folder art does show up there which is nice when using the grid views to browse playlists. Folder art used to display in the "All Playlist" section in the regular music app but for some reason [Apple removed it](https://discussions.apple.com/thread/254164127?sortBy=best) from that view, so I was hoping to see it in Cider. I think it would be a nice addition. 

### Steps to Reproduce

If you've got some folders, click on All Playlists in Cider and witness the collection of grey folder icons.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
