### ISSUE TITLE
[Bug]: Artworks are not displaying in general

### ISSUE THREAD

**Issue by 0PandaDEV** [ciderapp/Cider-2#504]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0

### Operating System Version

Windows 11

### Describe the Bug

I cannot see any Artworks no matter on which page I go.

### Steps to Reproduce

-

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/70103896/7238839b-c003-4521-b9e2-bbc6e501ad69)

### Build timestamp

1706875279653

**Comment by 0PandaDEV** [comment]
Update: It's only for songs from Apple Music itself all the songs I added my self are displayed correctly

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
