### ISSUE TITLE
[Bug]: Limited connection directly after installing

### ISSUE THREAD

**Issue by Tctutt** [ciderapp/Cider-2#505]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Installed Cider 2/2/24 Build Details: "Built on 9/21/2023, 3:27:31 PM"

### Operating System Version

Linux arch 6.7.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000 x86_64 GNU/Linux

### Describe the Bug

After downloading Cider, I signed in. Once Cider finished loading in, switching from one menu to another was a bit laggy. After about 10 seconds network manager showed limited connection, I could not load any webpages in my browser, even local servers. When I clicked the loading circle at the top I think it said "Building Playlist Cache... 0/0." This internet issue persisted until I closed cider.

### Steps to Reproduce

1. After downloading, open the AppImage
2. I had to install FUSE so > sudo pacman -S fuse2
3. Open the appimage again 
4. Sign in to apple
5. Try to play the last song listened to
6. This is where the issue occurred, Orange Triangle appeared over the wifi symbol(Using Plasma as my Desktop Enviornment).

### Anything else?

I troubleshooted the bug by relaunching Cider a few times(during this step I was having a few issues with the app just not loading, not sure if it is related), the issue still persisted, and I got fed up and installed Cider 1 using yay. After launching it and playing a few songs I closed it and went back to try Cider 2 and signed in again, it worked without this internet issue. I did make sure that my internet didn't just coincidentally go out during this process. If it helps reach out to me, and I can provide what was logged in my terminal during this up until and during this issue.

### Build timestamp

1706895227778

**Comment by coredev-uk** [comment]
a very weird bug, can't say that I've ever seen anything like this before. Haven't really got any idea why this would be happening.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
