### ISSUE TITLE
Unable to deactivate normalization with cider audio lab enabled

### ISSUE THREAD

**Issue by benniblot** [ciderapp/Cider-2#506]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 02/02/2024, 00:48:07 | Quasar v2.14.2 | Sabiiro

### Operating System Version

Windows 11 Pro Version	23H2 Installed on ‎04/‎01/‎2024 OS build	22631.3085 Experience Windows Feature Experience Pack 1000.22684.1000.0

### Describe the Bug

I tried turning off audio normalization but nothing happened

### Steps to Reproduce

1. Click 3 dot menu
2. Change to Audio tab
3. (Turn on Cider Audio Lab and restart if disabled)
4. Turn off Audio Normalization
5. Hear how nothing changes

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
