### ISSUE TITLE
[Bug]: songs that already exist in playlist are still added 

### ISSUE THREAD

**Issue by amkar1m** [ciderapp/Cider-2#508]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0 2/1/2024

### Operating System Version

Windows 11 22H2

### Describe the Bug

i have songs that exist on my playlist and when i add them again, there's no longer a warning message that displays saying there's already a song in the playlist. 

### Steps to Reproduce

1. right click add song to playlist 

### Build timestamp

1706926578683

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
