### ISSUE TITLE
[Bug]: Custom CSS not loading on launch

### ISSUE THREAD

**Issue by SpaghettiiQ** [ciderapp/Cider-2#509]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 2/2/2024, 12:54:50 AM | Quasar v2.14.3 | Electron 27b7dcfcdfacec375d19809ad269885c40b24fe0

### Operating System Version

macOS Sonoma 14.3 23D56 arm64

### Describe the Bug

When launching cider (as in after quitting it), custom CSS filled in Settings > Visual > Sweetener > Custom CSS does not apply automatically.

However, after performing a change and clicking out of the text field, it applies.
This did not happen on the same OS and machine with the previous itch.io release.

### Steps to Reproduce

1. Open Cider 2.3.0
2. Write custom CSS in Settings > Visual > Sweetener > Custom CSS
3. Save it, at this point it should apply
4. Now quit Cider (cmd + q)
5. The CSS isn't applied on launch

### Anything else?

This is possibly related to another bug where selected volume on the volume slider doesnt work for the playlist "Suggested Songs" previews until it's changed in the current "session" (after launching the app after quitting it)
I created an issue for it as well. #510 

### Build timestamp

1706931683012

**Comment by booploops** [comment]
Issue to be resolved in 2.3.1
