### ISSUE TITLE
[Bug]: Volume set doesn't persist across app launch for Suggested Songs previews

### ISSUE THREAD

**Issue by SpaghettiiQ** [ciderapp/Cider-2#510]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 2/2/2024, 12:54:50 AM | Quasar v2.14.3 | Electron 27b7dcfcdfacec375d19809ad269885c40b24fe0

### Operating System Version

macOS Sonoma 14.3 23D56 arm64

### Describe the Bug

When you set volume using the volume slider, and quit Cider, after launching it next time the volume (while showing the correct value and working for normal songs) does not apply to song previews in the "Suggested Songs" section in user made playlists

### Steps to Reproduce

1. Open Cider 2.3.0
2. Set volume using the volume slider, preferably to a low amount so it is a noticeable difference
3. Quit Cider (cmd + q)
4. Launch Cider and go to a user-made playlist
5. Play one of the song previews in the "Suggested Songs" section at the bottom

### Anything else?

This is possible related to another bug with loading previously saved properties on launch #509 

### Build timestamp

1706932449802

**Comment by Timoms** [comment]
Can confirm, same on windows. You don't even need to quit the app - just go to another page in the suggested songs div and it will reset the volume.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
