### ISSUE TITLE
[Bug]: Lyrics misplaced(translated a little) in immersive mode

### ISSUE THREAD

**Issue by Ciel-MC** [ciderapp/Cider-2#511]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Cider 2.3.0, 2/3/2024 (Detail attached)

### Operating System Version

ArchLinux

### Describe the Bug

When in immersive mode, lyrics are shifted to the left and down, clipping into the album art and progress bar

### Steps to Reproduce

1. Open immersive mode
2. Switch to Lyrics
*Does seem to work for everyone, but infinitely reproducible for me

### Anything else?

SS cropped a bit but the song name and author is also shifted left a little, right on the window edge
![image](https://github.com/ciderapp/Cider-2/assets/47144701/9c0e1d1d-7025-49a0-81ef-562491633772)
![image](https://github.com/ciderapp/Cider-2/assets/47144701/42b11597-6aa8-439a-b541-429189e2cd7d)

### Build timestamp

1706954316910

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
