### ISSUE TITLE
[Bug]:dark mode glitch after minimizing and refocusing

### ISSUE THREAD

**Issue by shanix12345** [ciderapp/Cider-2#513]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

yesterday

### Operating System Version

windows 11

### Describe the Bug

after re focusing cider after it has been minimized it switches to light mode and multiple buttons are white colored rendering them unusable.

### Steps to Reproduce

1. minimize cider
2. re focus

### Anything else?

![image_2024-02-04_181512759](https://github.com/ciderapp/Cider-2/assets/158861060/ae6c36ee-942c-41f4-9e73-cb08f2a1658f)

### Build timestamp

1707088106609

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
