### ISSUE TITLE
[Bug]: Bottom of home page blocks cut off

### ISSUE THREAD

**Issue by BlueberryHoosk** [ciderapp/Cider-2#514]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 9/20/2023, 10:55:55 pm

### Operating System Version

Windows 11 Home 22H2 OS build 22621.3007

### Describe the Bug

The pinned items/recently played and other items on home page are cut off on the bottom.
![image](https://github.com/ciderapp/Cider-2/assets/110638799/37ddb43e-59b1-4385-bfa0-2c2c8dc89d43)

### Steps to Reproduce

home (it's like this every time i'm on the home page. I have the microsoft store version of the app)

### Anything else?

IDK if this counts as a bug, but it would be great if the bottoms of each blocked out area on this page weren't cut off. It's visually quite annoying, but the experience is still great C:

### Build timestamp

1707142961593

**Comment by booploops** [comment]
Outdated client, was resolved in 2.3.0
