### ISSUE TITLE
Chromecast / Airplay Devices Not Scrollable

### ISSUE THREAD

**Issue by keithcroshaw** [ciderapp/Cider-2#516]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

2/1/2024 6:54:50 PM | Quasar v2.14.3 | Electron 27b7dcfcdfacec375d19809ad269885c40b24fe0

### Operating System Version

MacOS Sonoma 14.2.1

### Describe the Bug

When presented with available Airplay/Chromecast devices I am unable to scroll through the list as it goes beyond the screen height. I see no scroll bars, the mouse wheel does not allow scroll.

### Steps to Reproduce

Open Cider, Click Airplay button, see devices, unable to scroll down.

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
