### ISSUE TITLE
[Bug]: Custom Playlist Art not loading for Pinned Playlists

### ISSUE THREAD

**Issue by chbmckie** [ciderapp/Cider-2#517]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

2.3.0

### Operating System Version

MacOS Sonoma

### Describe the Bug

When opening the Cider Home screen, the playlists I have pinned never load their artwork. When clicking into the playlists the art takes a minute but still loads eventually, yet the home screen ones never load, leaving empty boxes on my home screen.
![SCR-20240205-qbsd](https://github.com/ciderapp/Cider-2/assets/132846485/36dbfc88-3191-44b9-8b9a-d0de4f598a4f)

### Steps to Reproduce

1. Pin a playlist with custom artwork set.
2. Reload cider
3. Notice the unloaded images

### Connect Device ID

9ae41afd-546a-498e-a279-c92a3a2fd364

### Build timestamp

1707157412408

**Comment by coredev-uk** [comment]
This issue has been closed to consolidate the issue tracker for Cider 2.3.1 and later issues. If you believe this issue is still relevant, please open a new issue.
