### ISSUE TITLE
Favoriting doesn't work: "There was a problem with the request"

### ISSUE THREAD

**Issue by TWB0109** [ciderapp/Cider-2#518]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 2/1/2024, 5:50:28 PM | Quasar v2.14.3 | Electron 27b7dcfcdfacec375d19809ad269885c40b24fe0

### Operating System Version

Linux nixos 6.1.75 \#1-NixOS SMP PREEMPT_DYNAMIC Thu Jan 25 23:27:52 UTC 2024 x86_64 GNU/Linux

### Describe the Bug

When Favoriting any song, the star appears next to cider audio laboratories but it doesn't really do anything, the song is not added to the library nor to the favorite songs playlist.

### Steps to Reproduce

1. Open any album, playlist or artist.
2. Favorite a song.
3. Go to Favorite Songs/library.

The song isn't there

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/53587182/f3f305a3-cc30-42ff-961d-1e162524493e)

Favourited, but not in the favorite songs playlist.

### Connect Device ID

ec6a7bad-0460-4eaf-a9a6-d76fad290d55

### Build timestamp

Thu Feb 01 2024

**Comment by coredev-uk** [comment]
There was probably an API error that occurred whilst you tried to favourite the song, could you please open the devtools console using Ctrl+Shift+I and select console and post any errors that occur when you try to favourite the song. The playlist itself we do not directly add stuff to, that is done on Apple's side.

**Comment by a-sahonchik** [comment]
Having similar problem with Cider 2.3 on Ubuntu 22.04

I'm able to add songs to favorites from Library Songs list, but unable to do it from playback bar.
This problem appeared after updating to 2.3. I always added songs to favorites like this way, and there were no problems before.

I take a screenshot of API response, maybe it will help.

![2024-02-06_20-56](https://github.com/ciderapp/Cider-2/assets/39532116/72164be1-285e-439f-9d09-f597deaf4d21)

**Comment by TWB0109** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/53587182/04c937ac-cb96-42ba-885b-80f39be8de2e)
![image](https://github.com/ciderapp/Cider-2/assets/53587182/16be65a4-ca56-475a-82ba-f6ca85d4a6e2)
[localhost-1707249831641.log](https://github.com/ciderapp/Cider-2/files/14185580/localhost-1707249831641.log)


Here are my logs if that helps

**Comment by TWB0109** [comment]
It looks like this has been resolved with 2.3.1.
Closing this issue.
