### ISSUE TITLE
[Bug]: Can’t turn off audio normalization

### ISSUE THREAD

**Issue by djolep111** [ciderapp/Cider-2#522]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.1 Microsoft Store Version

### Operating System Version

Windows 11 Pro 23H2

### Describe the Bug

I try to turn off audio normalization in settings and there isn’t any effect. It just turn itself on when i restart the app and i don’t hear any difference when i turn those settings on and off

### Steps to Reproduce

1. Turned off audio normalization in audio settings
2. Played song and restarted app
3. Checked audio settings to see if audio normalization is turned off and it appears that it’s turned off
4. Played song and checked audio settings again and it appears that audio normalization turned itself on

### Build timestamp

1707413094085

**Comment by coredev-uk** [comment]
Turn on audio lab, then uncheck audio normalisation then turn off audio lab, just a UI flow bug.
