### ISSUE TITLE
[Bug]: Missing favorite icon in ListItem

### ISSUE THREAD

**Issue by h0ckerman** [ciderapp/Cider-2#523]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 08.02.2024, 10:53:38 | Quasar v2.14.3 | Sabiiro

### Operating System Version

Windows 10 19045.3086 (22H2)

### Describe the Bug

**There are no Favorite icons near tracks from my library. Basically i want to see what tracks i favorited but the icon does not appear until i right-click on a song. I want to see those icons exactly from an album page, not from the Favorites page.**

https://github.com/ciderapp/Cider-2/assets/35598335/b5d4cfdc-2c33-4ee9-833d-b79e383d9f0d

**In addition, the buttons in the context menu are not relevant when opening the menu itself. They update after a couple of seconds (as seen in the video)**

### Steps to Reproduce

1. Go to _Recently Added tab_
2. Choose any release that you added to your library that has any favorited tracks.
3. See that there is no "Star" icon near tracks. 

**_To make the icon appear, right click on a song._**

### Anything else?

The request that is being sent to the apple (https://amp-api.music.apple.com/v1/me/library/albums/l.MTzmcA1/tracks?offset=0&l=en-GB&platform=web&limit=100&include=albums&extend=inFavorites) does seem to contain inFavorites key, that is, in this case, is true. But Cider does not want to render this correctly.

_Here is the part of the response that apple sents me:_

```json
{
    "id": "i.MoxK81VCvbdG0a4",
    "type": "library-songs",
    "href": "/v1/me/library/songs/i.MoxK81VCvbdG0a4?l=en-GB",
    "attributes": {
        "albumName": "FRIENDS-",
        "genreNames": [
            "Hip-Hop"
        ],
        "trackNumber": 10,
        "releaseDate": "2023-12-22",
        "durationInMillis": 105226,
        "artwork": {
            "width": 1200,
            "height": 1200,
            "url": "ARTWORK URL",
            "hasP3": false
        },
        "playParams": {
            "id": "i.MoxK81VCvbdG0a4",
            "kind": "song",
            "isLibrary": true,
            "reporting": true,
            "catalogId": "1721526073",
            "reportingId": "1721526073"
        },
        "discNumber": 1,
        "hasCredits": false,
        "hasLyrics": true,
        "inFavorites": true,
        "name": "ЯЗЫК ТЕЛА (Bonus Track)",
        "artistName": "4n Way"
    },
    "relationships": {
        "albums": {
            "href": "/v1/me/library/songs/i.MoxK81VCvbdG0a4/albums?l=en-GB",
            "data": [
                {
                    "id": "l.MTzmcA1",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/l.MTzmcA1?l=en-GB",
                    "attributes": {
                        "trackCount": 3,
                        "genreNames": [
                            "Hip-Hop"
                        ],
                        "releaseDate": "2023-12-22",
                        "inFavorites": false,
                        "name": "FRIENDS-",
                        "artistName": "4n Way",
                        "artwork": {
                            "width": 1200,
                            "height": 1200,
                            "url": "ARTWORK URL",
                            "hasP3": false
                        },
                        "dateAdded": "2023-12-26T17:11:30Z",
                        "playParams": {
                            "id": "l.MTzmcA1",
                            "kind": "album",
                            "isLibrary": true
                        }
                    }
                }
            ]
        }
    }
}
```

### Connect Device ID

1df2aed8-6ca4-48bb-9fe5-050f9659da65 (?)

**Comment by coredev-uk** [comment]
That's not how the application has been designed, we do not match iTunes or Apple Music web, we take our own approach. There is a star on the bar next to the time which states whether or not its favourited. You can favourite it whilst playing through the playback panel or through the context menu.
<img width="495" alt="image" src="https://github.com/ciderapp/Cider-2/assets/64542347/fddc7684-75fb-428e-9303-254670ce04b6">

**Comment by h0ckerman** [comment]
Well, _yes_, but

> There is a star on the bar next to the time which states whether or not its favourited.

I mean the problem is that the star is only shown after a right-click. But i _personally_ would like to see the star when i open an album or a single.

> That's not how the application has been designed

Do you mean that the star should appear _**only**_ after a right click?

**Comment by coredev-uk** [comment]
Didn’t realise that part, yeah it’s a bug

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/f1bc8ac28a6fad80a41c8434ab756be82320479c
