### ISSUE TITLE
Last.FM login doesn't work with RPC Server disabled

### ISSUE THREAD

**Issue by RuiNtD** [ciderapp/Cider-2#524]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

v2.3.1 built on 2/8/2024, 12:53:38 AM

### Operating System Version

Windows 11 23H2

### Describe the Bug

Trying to connect to Last.fm gives a "localhost refused to connect" error after clicking Allow Access if RPC Server is disabled

### Steps to Reproduce

1. Go to settings
2. Click the Connectivity tab
3. Ensure "RPC Server" is disabled and restart Cider if needed
4. Click "Sign into Last.FM"
5. Login to Last.FM and click Allow Access.

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/1149870/68694533-e07d-495b-a912-830f98facea4)

**Comment by RuiNtD** [comment]
Apparently this is caused by RPC server being disabled.

**Comment by coredev-uk** [comment]
We've deployed a fix for this that enables the RPC server for Last.FM auth.
