### ISSUE TITLE
[Bug]: NavBtn in my playlists

### ISSUE THREAD

**Issue by happizy** [ciderapp/Cider-2#525]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.1

### Operating System Version

Windows 10 21H2

### Describe the Bug

I tried to remove two playlists from my library but they stay as NavBtn elements. They are black placeholders and send back to the home page when trying to remove them.

![image](https://github.com/ciderapp/Cider-2/assets/61943115/4348842e-bf85-42b5-9e2f-940b443d6eb8)

### Steps to Reproduce

It happened on an older build (possibly classic cider) but it stayed here since... I guess you can reproduce it on earlier builds trying to remove playlists from your library with dubious internet connection.

### Anything else?

You're doing great work !!! I like the new update system 👍

### Build timestamp

1707473781819

**Comment by divrep222** [comment]
Can confirm, I'm seeing this behavior on previous builds, as well as on 2.3.1.  Windows 10.

**Comment by seany** [comment]
Still having this issue on v2.3.2_3, Windows 10. 
![Cider_mIHreOnifK](https://github.com/ciderapp/Cider-2/assets/33362877/a52e768f-2644-4d11-82b2-c5e9eb277d80)

**Comment by divrep222** [comment]
> Still having this issue on v2.3.2_3, Windows 10. Attempted to clear cache, revert to legacy playlists, and neither worked.
Same here.  Switching to legacy playlists no longer fixes this behavior for me.

**Comment by seany** [comment]
Still present in v2.4.0_1, Windows 10.

**Comment by seany** [comment]
bump

**Comment by nabn** [comment]
Seeing this on 2.4.1_0 (macos) too

**Comment by divrep222** [comment]
Are Cider playlists available anywhere locally in a human readable format, like JSON?  I briefly searched but didn't find anything.  These "NavBtn" playlists show up in multiple Cider instances on different machines, so there's likely something in there that Apple is storing but knows not to display within Apple Music.

**Comment by seany** [comment]
Playlists on Apple Music containing emojis cause it. Hopefully it can be fixed soon.

**Comment by divrep222** [comment]
> Playlists on Apple Music containing emojis cause it. Hopefully it can be fixed soon.

I don't think that's it for me.  I wouldn't have included emoji in my playlist names.  It started on an older version of Cider when I mistakenly created some blank playlists and then was unable to delete them.

**Comment by coredev-uk** [comment]
Resolved in next release.

**Comment by divrep222** [comment]
Still not resolved in 2.5.0_2, Windows 10.  These empty playlists are now displayed as "Untitled" instead of "NavBtn".  Still unable to remove them from library.  Attempting to do so shows a confirmation dialog, but clicking "OK" simply closes the dialog and the playlist remains.

**Comment by cryptofyre** [comment]
Remove these from your iOS/Android device as they are ghost playlists created by those apps that we can't exactly "touch" effectively through the public API.

**Comment by divrep222** [comment]
> Remove these from your iOS/Android device as they are ghost playlists created by those apps that we can't exactly "touch" effectively through the public API.

I figured it was something like that.  Thanks for taking a look.  Strangely, they don't show up in iOS; I have only ever seen them in Cider.

**Comment by seany** [comment]
> Still not resolved in 2.5.0_2, Windows 10.  These empty playlists are now displayed as "Untitled" instead of "NavBtn".  Still unable to remove them from library.  Attempting to do so shows a confirmation dialog, but clicking "OK" simply closes the dialog and the playlist remains.

Same issue applies to me. I was unable to find these ghost playlists on the Apple Music app, so I'm not exactly sure what I should be deleting.

**Comment by seany** [comment]
Bumping - I've deleted every playlist on Apple Music and they're still there @cryptofyre. Not sure what else I can do.

**Comment by seany** [comment]
Bumping again @cryptofyre
