### ISSUE TITLE
[Bug]: Launch window size

### ISSUE THREAD

**Issue by selly139** [ciderapp/Cider-2#526]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

within the year

### Operating System Version

Windows 10

### Describe the Bug

Every time I launch Cider it is a certain window size on a certain monitor. I would prefer if the window could just return to its previously left location or have the option to set one. I use two monitors and would like it to pop up on my secondary one more easily. 

### Steps to Reproduce

Each launch without fail

### Build timestamp

1707519412343

**Comment by coredev-uk** [comment]
We are not making any further changes to the current windows backend codebase, however this feature is on the roadmap for the rework. I'd like to ask that you'd wait for the updated codebase (code named Arsene) whenever that should come out. Sorry I cant do more.

**Comment by selly139** [comment]
No worries! I’ve just started minimizing to tray instead to preserve it for each boot. Thanks for all the work! Incredible softwareOn Feb 19, 2024, at 7:38 PM, Core ***@***.***> wrote:﻿
We are not making any further changes to the current windows backend codebase, however this feature is on the roadmap for the rework. I'd like to ask that you'd wait for the updated codebase (code named Arsene) whenever that should come out. Sorry I cant do more.
