### ISSUE TITLE
Playlists out of order

### ISSUE THREAD

**Issue by divrep222** [ciderapp/Cider-2#527]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.1

### Operating System Version

Windows 10 21H2

### Describe the Bug

In 2.3.1, the display order of playlists and playlist folders (both in the left nav & in the Playlists view) has become somewhat random.  Playlist folders are out of order, and underneath them the individual playlists are also out of order.  

Playlists were shown in alphabetical order in 2.3.0.  

### Steps to Reproduce

Load Cider --> view playlist order in left-hand nav section

### Anything else?

![Screenshot 2024-02-09 182924](https://github.com/ciderapp/Cider-2/assets/67206199/8f64aa72-88f0-48d0-a28f-c0f6ca8ad675)

**Comment by coredev-uk** [comment]
please screenshot the current order and whether or not you have legacy playlist mode enabled in experiments

**Comment by divrep222** [comment]
> please screenshot the current order and whether or not you have legacy playlist mode enabled in experiments

Enabling legacy playlist mode seems to have resolved the issue, thanks!
