### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by ArrivingHare** [ciderapp/Cider-2#528]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0

### Operating System Version

Windows 10

### Describe the Bug

In Discord it shows "playing cyder" not "listening to cyder" i think that would be better

### Steps to Reproduce

eneble discord rich presence

### Build timestamp

1707550683958

**Comment by coredev-uk** [comment]
We cannot set it to playing cider as it is a limitation of DiscordRPC. It can only be done with Vencord using [RicherCider](https://cider.sh/docs/richer-cider). Not much more can be done on this.
