### ISSUE TITLE
[Bug]: Discord RPC Doesn't Work Properly with Long Artist Names

### ISSUE THREAD

**Issue by vracton** [ciderapp/Cider-2#530]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.2-prerelease1

### Operating System Version

Windows 11 22H2

### Describe the Bug

Note: This may also be an issue with long song names, I couldn't find any songs to test though.

Whenever I have the `by {artist}` text in for the Discord RPC and play a song with a very long artist name, the RPC on discord only shows the paused state for the previous song (I have Clear Discord Rich Presence on Pause disabled).

### Steps to Reproduce

1. Make sure `by {artist}` is in State or Details in the RPC customizer.
2. Play a song with a long artist name. ex: https://music.apple.com/us/song/1537806863

### Build timestamp

1707621344262

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/0150aaf6b433863ecc3afcd6dffa5bbabfc0df91
