### ISSUE TITLE
[Bug]: Playlists aren't loading at all

### ISSUE THREAD

**Issue by 1kaiyounglee** [ciderapp/Cider-2#531]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

08/02/2024

### Operating System Version

Windows 10 Home Single Language version 22H2

### Describe the Bug

Playlists don't show up in the playlists section. Some can still be accessed from Home > Recently Played and work fine, but I have enough playlists where I can't access them all from there (images below for clarity)

![image_2024-02-11_174805897](https://github.com/ciderapp/Cider-2/assets/128564329/94da93af-d191-4dfc-b365-0395cfb60d6d)

![image_2024-02-11_174923927](https://github.com/ciderapp/Cider-2/assets/128564329/a9ed52cc-b34b-4932-9981-b73d2c0367e0)

### Steps to Reproduce

This has been an issue since I installed through the link I was sent after purchasing. Opened a ticket on discord to try trouble shooting (reinstalling, singing in/out, clearing cache etc) but it was eventually closed due to no issue being found,

### Build timestamp

1707633606236

**Comment by 1kaiyounglee** [comment]
Also in version 2.2.x (? not sure exact but from like a week ago), there was this issue (see below)
![image_2024-02-11_175332057](https://github.com/ciderapp/Cider-2/assets/128564329/0f65a086-2c1f-408f-8789-add5bfbd1986)


Also for reference the ticket I opened (now closed) in the discord was #1336

**Comment by coredev-uk** [comment]
This bug has been since fixed in 2.3.1, if you experience issues try enabling the legacy playlist method in settings > experiments

**Comment by 1kaiyounglee** [comment]
> This bug has been since fixed in 2.3.1, if you experience issues try enabling the legacy playlist method in settings > experiments

I am on 2.3.1 and they still dont show with/without legacy. Have tried reinstalling, logging in and out, clearing cache, and also tried the 2.3.2prerelease5 (from the update section of the app) and nothing seems to change. If it helps - I get the same issue on Apple Music Web.
