### ISSUE TITLE
Autoplay state not saving on exit

### ISSUE THREAD

**Issue by Kief5555** [ciderapp/Cider-2#532]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2/7/2024, 11:53:38 PM I Quasar v2.14.3 1 Sab-iiro eff68968956da5e787c2ce7a413382653c4eb58e

### Operating System Version

W11 Pro 23H2 Build 22631.3085

### Describe the Bug

When enabling autoplay (the infinity icon in the queue list), it doesn't save my changes. So everytime I kill the app (restart or taskkill or graceful exit), it disables it for the next time I launch. Really annoying because I have to re-toggle.

In the queue list icon, it says its enabled, but it's not actually (because no suggestions in the list)

### Steps to Reproduce

1. Press on the queue list 
![image](https://github.com/ciderapp/Cider-2/assets/67562560/7a89b44a-609a-4c60-9b47-bed59f89f4a1)
2. Press the infinity icon
![image](https://github.com/ciderapp/Cider-2/assets/67562560/8f1c2ee7-acb2-4f47-8439-e0df3626940e)
3. Terminate the app 
4. Relaunch
5. Play any single song
6. Try to skip 
7. Theres the bug, it just resets it to 00:00 instead of going to next.

**Comment by coredev-uk** [comment]
Due to the use of Apple's component here, the button is disabled before any items are queued, thus this is why the button is not lit up. This is the intended way, we might revisit the change later on. If you want to change your autoplay state I suggest queuing an item then changing it.

I have made a change on the frontend to disable the autoplay icon when a song is not queued. This should rectify the inconsistency.

**Comment by Kief5555** [comment]
> Due to the use of Apple's component here, the button is disabled before any items are queued, thus this is why the button is not lit up. This is the intended way, we might revisit the change later on. If you want to change your autoplay state I suggest queuing an item then changing it.
> 
> I have made a change on the frontend to disable the autoplay icon when a song is not queued. This should rectify the inconsistency.

The icon not showing is fine, but the problem is the user input isn't save. It's **very** annoying to having to re-toggle the item.

**Comment by coredev-uk** [comment]
Try updating to the latest prerelease, this is fixed
