### ISSUE TITLE
2.3.1 - Lost external (Spotify playlist) after relaunch

### ISSUE THREAD

**Issue by polaraditia** [ciderapp/Cider-2#533]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2/8/2024, 2:53:38 PM | Quasar v2.14.3 | Sabiiro | eff68968956da5e787c2ce7a413382653c4eb580

### Operating System Version

Windows 10 Home Single Language 22H2

### Describe the Bug

My previous successfully imported Spotify playlists lost after relaunch.
![image](https://github.com/ciderapp/Cider-2/assets/5745134/a0af82f1-ff27-4231-9c9e-d1685cfaf427)

### Steps to Reproduce

1. External Playlists > Import From > Spotify
2. Paste my playlist link, for example BuzzInMyHead: https://open.spotify.com/playlist/5ezTkrAd7bvibYMqLvQZvR 
3. Click OK
4. Playlist successfully imported (Playlist name, image, description, song list) 👍
![image](https://github.com/ciderapp/Cider-2/assets/5745134/be828eee-25b1-4a56-abd3-25aedd386ff1)

6. Exit Cider
7. Open Cider
8. My spotify playlist lost :(
![image](https://github.com/ciderapp/Cider-2/assets/5745134/af13a700-9907-4e94-8bce-fe78737d0746)

### Anything else?

I don't know if this feature just for import playlist temporarily from Spotify before copied/added to native Apple playlist or meant to stay/persist between launch in Cider

### Build timestamp

Built on 2/8/2024, 2:53:38 PM | Quasar v2.14.3 | Sabiiro | eff68968956da5e787c2ce7a413382653c4eb580

**Comment by cryptofyre** [comment]
This is intended behavior, please add it to your Apple Music library if you'd like it to persist.
