### ISSUE TITLE
[Bug]: Smart Playlists within Nested Folders Not Displaying

### ISSUE THREAD

**Issue by DiscordianEris** [ciderapp/Cider-2#535]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2/8/2024, 12:53:38 AM | Quasar v2.14.3 eff68968956da5e787c2ce7a413382653c4eb580  Sabiiro eff68968956da5e787c2ce7a413382653c4eb580

### Operating System Version

Windows 11 22H2

### Describe the Bug

There are a number of smart playlists I nest within a chain of folders and they do not show up in the last folder in the chain. As an example, I have smart playlists that place all the tracks I add in  a calender year. Each of these individual smart playlists exists within their own folder for similar playlists, (i.e year added or decade of when the song came out) which exists within another folder. When navigating to the folder where the smart playlists exist none are displayed.  

![image](https://github.com/ciderapp/Cider-2/assets/159965405/cd0d8570-816c-463c-be7f-7f445a68d54c)

![image](https://github.com/ciderapp/Cider-2/assets/159965405/f041a769-9434-4e63-b5f5-75c6205ea3b0)

![image](https://github.com/ciderapp/Cider-2/assets/159965405/6e8eaea9-2b5b-4624-88bf-e340e82b8375)

 

### Steps to Reproduce

1) Create a playlist folder

2) Create a second playlist folder and place within the first playlist folder.

3) Add smart playlists to the second folder

### Anything else?

The playlists appear on iTunes, the stock Apple Music app on iOS, and Marvis Pro.  

### Build timestamp

1707872732077

**Comment by coredev-uk** [comment]
Smart playlists are not supported in Cider, we cannot access the relevant data for smart playlists as it is not available in MusicKit. If you'd like this to be implemented, ask Apple to add it to MusicKit.
