### ISSUE TITLE
Favorite / Remove Favorite and Remove from Library doesn't work on some screens

### ISSUE THREAD

**Issue by RuiNtD** [ciderapp/Cider-2#536]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

v2.3.2-prerelease2

### Operating System Version

Windows 11 23H2

### Describe the Bug

You can't add or remove songs from favorites from the library or from the Now Playing panel; and you can't remove from library in the Now Playing panel.

### Steps to Reproduce

1. Go to Recently Added under Library and click on any album.
2. Right click any song and click Favorite / Remove Favorite.
3. Play any song.
4. Click the song's album art from the Now Playing panel.
5. Try both the Favorite / Remove Favorite and Remove from Library buttons.

### Anything else?

Favorite / Remove Favorite works correctly from search and from playlists. 

### Build timestamp

2/13/2024, 6:05:39 AM

**Comment by coredev-uk** [comment]
Some changes have been made recently to fix this. Please update to the next prerelease as soon as its out.
