### ISSUE TITLE
Random pauses and stops of the Music

### ISSUE THREAD

**Issue by 0PandaDEV** [ciderapp/Cider-2#537]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.2-prerelease3

### Operating System Version

Windows 11

### Describe the Bug

It's completely random, but very often the Music just stops playing, and I have to click play again in the GUI or skip to the next song

### Steps to Reproduce

1. Install the newest pre-release
2. Play some music
3. Wait for the bug to occur

**Comment by coredev-uk** [comment]
This is an unfortunate caveat with MusicKit that we cannot fix ourselves. We are working on a remake of MusicKit in our own solution which should fix this issue, however until then I don't have anything I can suggest outside of just ensure you are not playing music on another device.
