### ISSUE TITLE
Last Played Song

### ISSUE THREAD

**Issue by AsqhalPayvey** [ciderapp/Cider-2#538]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.1

### Operating System Version

Windows 10 22H2

### Describe the Bug

Actually this is not a bug but a feature that has not been added, so the last song I played will disappear/reset after closing and reopening the application. I want the creator of this application to immediately add this feature because it is really needed.

### Steps to Reproduce

1. Play any song
2. Close the app
3. Open the app
4. The previous song will be lost

### Anything else?

I apologize for this because this is not a bug but a feature that has not been implemented, I hope the developer can provide this feature in future updates.

**Comment by coredev-uk** [comment]
We dont do feature requests through github, if you'd like to request it pass it through our Discord feature-request channel(s)
