### ISSUE TITLE
Scobbles on Last FM

### ISSUE THREAD

**Issue by mpratsaki** [ciderapp/Cider-2#540]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

a5979cd027ece2917017534ac47dfccc5bfc60e3

### Operating System Version

Windows 11 Home 23H2

### Describe the Bug

When a song is scrobbled on Last.FM it doesn't appear the feature artists, and that has as a result to scobble a different track. When I scrobble from both my phones (Android and iPhone) the featured artists are scrobbling correclty but on Cider it scrobble a different track
 

### Steps to Reproduce

When I just hover the mouse above the play-pause when on Immersive mode, the featured artists are just disappearing

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/110930793/585b161c-f1e1-4aa7-aac5-72b423bec945)
The first song is a track scrobbled on Cider and the second is the same scrobbled through the phone

In the second and third photo is what happening
![image](https://github.com/ciderapp/Cider-2/assets/110930793/1ed541f9-8eaf-4e1a-a8cf-1e6bdcd6bc72)
![image](https://github.com/ciderapp/Cider-2/assets/110930793/3bba7a4d-16f5-4183-8f71-4c4e4ade2a5c)
This happens when I hover the mouse

**Comment by coredev-uk** [comment]
I suggest changing remove featured artists in settings > connectivity > lastfm track adjustments to artist list over both/track name. This is clear in the settings what this does, I recommend reading them in future.
