### ISSUE TITLE
[Bug]: Party song not sync with my friend

### ISSUE THREAD

**Issue by TAKZOBYE** [ciderapp/Cider-2#541]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2/17/2024, 6:07:42 AM I Quasar v2.14.3 I Sabiiro a5979cd027ece2917017534ac47dfccc5bfc60e3

### Operating System Version

Edition	Windows 11 Home Version	23H2 Installed on	‎5/‎8/‎2023 OS build	22631.3155 Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Describe the Bug

My friend is head of party when my friend play song, in my application not sync with my friend

### Steps to Reproduce

1. I join the party
2. My friend play some song
3. My song in my application not sync

### Build timestamp

1708269521544

**Comment by coredev-uk** [comment]
The current version of Cider Connect has been discontinued and a new alternative is being worked on.
