### ISSUE TITLE
[Bug]: Playlists  STILL aren't loading

### ISSUE THREAD

**Issue by 1kaiyounglee** [ciderapp/Cider-2#542]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

08/02/2024

### Operating System Version

Windows 10 Home Single Language version 22H2

### Describe the Bug

Same issue that I had before that was closed despite not being resolved - playlists just won't display in the sidebar/when I click the button.

![image](https://github.com/ciderapp/Cider-2/assets/128564329/245c58e3-d6e7-49d9-89ba-d06d90505945)

I've tried Legacy Playlist Retrieval in Experiments, on version 2.3.1 and on 2.3.2 pre5.
I've signed in and out on both versions and tried with/without legacy etc.
I've reinstalled multiple times to no avail.

I have had this issue since like early January when I first purchased cider through itchio

### Steps to Reproduce

Open the app and look for playlists

### Build timestamp

1708342903485

**Comment by coredev-uk** [comment]
Please check if your playlists appear on https://music.apple.com

**Comment by 1kaiyounglee** [comment]
> Please check if your playlists appear on https://music.apple.com

![image](https://github.com/ciderapp/Cider-2/assets/128564329/6c255f69-ae85-431d-93d9-6abd2f7e6ebc)
no it doesn't show up here either - is there something wrong w/ my applu music acc?

**Comment by coredev-uk** [comment]
This would be an issue with your account yes. Please forward this issue onto them, through contacting their support.
