### ISSUE TITLE
Played tracks are not displayed in recently played on AM profile

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#543]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.1

### Operating System Version

Windows 11

### Describe the Bug

Played tracks/albums are not displayed in recently played on my AM social profile
see: https://github.com/ciderapp/Cider-2/issues/448

note: AM Web does show it on your social profile so Cider is missing some requests maybe

### Steps to Reproduce

play an album/song

**Comment by coredev-uk** [comment]
@vapormusic are you working on this? I thought I remembered seeing you working on a thing similar to this a while back. I might be wrong, just lmk if you are.

**Comment by Amaru8** [comment]
Hey! I tried gathering some intel about this a few months ago, and the Flavor Hack feature seemed to be what broke it for songs played on the Recently Added page. What page did you use to play the song?

**Comment by vapormusic** [comment]
> @vapormusic are you working on this? I thought I remembered seeing you working on a thing similar to this a while back. I might be wrong, just lmk if you are.

I have never attempted to fix this actually. However, the Listening To tab in my profile is working correctly.

**Comment by coredev-uk** [comment]
> > @vapormusic are you working on this? I thought I remembered seeing you working on a thing similar to this a while back. I might be wrong, just lmk if you are.
> 
> I have never attempted to fix this actually. However, the Listening To tab in my profile is working correctly.

mb

**Comment by UnbreakCode** [comment]
> However, the Listening To tab in my profile is working correctly.

Yes, the "Recently played" section on my "Listen now" page will also be updated. But not directly on my social profile(iOS,macOS).
Other people were also able to recreate the behavior in the Discord

**Comment by nolageek** [comment]
Any progress on this? I'm also seeing this behavior. "Recently Play" doesn't get updated no matter if I play songs from "songs", "albums", or Playlists.

**Comment by cryptofyre** [comment]
I've done my best to address this issue in more areas, Apple's very particular about how they collect this data and it's not documented very well.
