### ISSUE TITLE
[feature request] Create playlist and add songs to it in right click. 

### ISSUE THREAD

**Issue by YjzJim** [ciderapp/Cider-2#544]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

arch package

### Operating System Version

arch

### Describe the Bug

The feature request page doesn't work anymore, so i can only report it here, sorry.

I can use right click to add songs to a playlist, but i can not create a playlist and add them to it at the same time. It will be particularly useful when putting different artists' works in different folders. and use different playlist to store albums. In this case, i have to go to that folder, create a playlist, manually name them and go back to add the songs, kind of a fuss. The macos version of apple music "official" client has this function.

### Steps to Reproduce

.

**Comment by coredev-uk** [comment]
It states clearly on the issue template that feature requests will be closed and that all requests should be directed towards Discord, thus I'll be closing it. Please do not do this again.
