### ISSUE TITLE
Last FM intergration not working

### ISSUE THREAD

**Issue by Depraved7409** [ciderapp/Cider-2#545]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

I installed Cider from Itch.io

### Operating System Version

Windows 11 Pro 23H2

### Describe the Bug

When I went to go connect my Last FM account to Cider it errors out and freezes for a moment before giving my the error, "localhost refused to connect." This has only occured on Windows and this didn't happen on Linux.

### Steps to Reproduce

Click "Sign into Last.FM" under the Connectivity tab in settings and attempt to sigh in on Windows.

https://github.com/ciderapp/Cider-2/assets/105536632/d8220c3e-75e7-4ffc-ba96-d12204399c77

### Anything else?

It appears to be a issue with Edge Webview2 not being able to connect to Cider properly but I am not a programmer so I don't really know if this is accurate. 

### Build timestamp

Cider 2.3.1 and Windows 11 Pro 23H2.

**Comment by coredev-uk** [comment]
Hello, this bug was previously identified and is fixed in the latest release. Please check that you are on the latest version.

**Comment by Depraved7409** [comment]
@coredev-uk I am currently running the latest stable version of Cider.
![Screenshot 2024-02-21 134522](https://github.com/ciderapp/Cider-2/assets/105536632/5a7461e9-c68f-4706-b214-b2c860d68408)

**Comment by coredev-uk** [comment]
I suggest going to updates and selecting the prerelease

**Comment by Depraved7409** [comment]
Thank you! That fixed the problem. @coredev-uk
