### ISSUE TITLE
[Bug] Error playing from Library/Playlists

### ISSUE THREAD

**Issue by soyoonbae** [ciderapp/Cider-2#546]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Linux

### Build Details

2/8/2024, Quasar v2.14.3 Electron

### Operating System Version

Ubuntu 20.04

### Describe the Bug

I can play songs from home/search. But the songs from my playlists/library are not playable. When I click "Play" button, selected songs in my library/playlist are added to queue, but it does not play. This freezing does not affect using the app itself, and the freezing does not prevent me from playing any song from home/search.

### Steps to Reproduce

Play songs from library/playlist(add to queue).

**Comment by coredev-uk** [comment]
Could you please state what the outcome was on Apple Music web?

**Comment by soyoonbae** [comment]
Hello, thank you for your response.

I've found out that on the Apple Music web the same problem happens.
Error message says "You cannot listen to this music on Apple Music web. Use
the app instead".
I am Korean and using the Korean Apple Music website, so the message may be
different in English.

I will wait for your reply. Thank you.


2024년 2월 21일 (수) 오후 6:34, Core ***@***.***>님이 작성:

**Comment by coredev-uk** [comment]
I've never seen this behaviour before. Cider and Apple Music web use MusicKit to control playback and queuing, so I imagine this is a fault/limitation with MusicKit. I suggest maybe checking out [this](https://support.apple.com/ko-kr/109341) guide by Apple and checking that the 'Apps with Access' section within the Apple Music app has 'Apple Music and TV Commerce' enabled. Then Apple Music web again.

If that does not fix your issue then you will need to contact Apple support, as we cannot help you further. Good luck.
