### ISSUE TITLE
[Bug]: Broken Montara Layout

### ISSUE THREAD

**Issue by trevorraney** [ciderapp/Cider-2#548]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2-prerelease7 | Built on 2/22/2024, 10:57:20 PM | Sabiiro | 7a3dfcff3cb2f1a5b39a892fcbe28cbc3d8e170c

### Operating System Version

Windows 11 Pro, 23H2

### Describe the Bug

After updating to prerelease version 2.3.2-7, the Montara layout style doesn't display the track element. See images for comparison between 2.3.1 stable and 2.3.2-7. Also doesn't appear in Mavericks view. Mojave and Calico are fine though

Montara 2.3.2-7
![image](https://github.com/ciderapp/Cider-2/assets/64988493/fc73be30-a818-4e24-9486-0e3b87387c0e)

Montara 2.3.1
![image](https://github.com/ciderapp/Cider-2/assets/64988493/13b1b1f4-bf4d-4f14-8cbc-393595eac861)

Mavericks 2.3.2-7
![image](https://github.com/ciderapp/Cider-2/assets/64988493/0c8fdb9a-18c5-41ab-8c77-b6cd1ac0f8c6)

Calico 2.3.2-7
![image](https://github.com/ciderapp/Cider-2/assets/64988493/1d98837f-6895-460f-8545-19b8881eb8dd)

Mojave 2.3.2-7
![image](https://github.com/ciderapp/Cider-2/assets/64988493/b94cf8ed-d1ce-4ea4-9988-7bdb33d34391)

### Steps to Reproduce

1. Updated to 2.3.2-7

### Connect Device ID

cCag1Sh5EUwDw5rrPDWa

### Build timestamp

1708667216415

**Comment by coredev-uk** [comment]
I am unable to recreate this in the latest version. The missing aspects look like Apple Music components, so check to make sure the Apple Music website is not being blocked by your network.
