### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by RobLW** [ciderapp/Cider-2#551]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Linux

### Build Details

Yesterday

### Operating System Version

RPM install on Fedora Linux 6.7.5-200 with Gnome 39 desktop

### Describe the Bug

1) Please consider updating the tray icon to match the launch icon, or possibly provide users the ability to select from a choice of tray icons.
The icon for launching (red) the app is different to the icon found in the tray (purple). I appreciate you might consider this "nitpicking" but its actually extremely impactful getting frustrated during a working day trying to decipher the correct tray icon to control my music when I have multiple icons with similar colour/designs.

2) Even though I've already minimised the window to my tray, when I click on the tray icon the option says "hide" I then click this to change it to "show" then doing it all again to bring the window up.

In Gnome I have extensions : 
* Window List - provides a "task bar" of open windows 
* AppIndicator and KStatusNotification Status (the tray icons)

Both of these extensions ship with Gnome and are not installed from 3rd party.

Many thanks for Cider, It truly fills in a gap that Apple neglect for iphone users who prefer to use Linux on their computers.

### Steps to Reproduce

Covered this in the bug description.

**Comment by coredev-uk** [comment]
This has been fixed, and the fix will be available as of the next backend Electron release.
