### ISSUE TITLE
[Bug]: Last.FM Integration Broken on macOS

### ISSUE THREAD

**Issue by EmptyVisual** [ciderapp/Cider-2#553]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

macOS

### Build Details

2.3.2-prerelease14 | Built on 27/02/2024, 20:31:41 | Electron | 04ba35833c2247fd5f7061cd2adb93dc67af9764

### Operating System Version

macOS Sonoma 14.3.1

### Describe the Bug

When attempting to sign into Last.FM and authorize the app connection within the popup window in Cider 2.0 on macOS, I encounter an internal server error message.

### Steps to Reproduce

1. Open Cider.
2. Navigate to Settings.
3. Proceed to Connectivity.
4. Select "Sign in to Last.FM."
5. In the popup window, attempt to log in.
6. Authorize/Allow app connection.
7. Observe the Internal Server Error screen.

### Anything else?

<img width="912" alt="image" src="https://github.com/ciderapp/Cider-2/assets/4710051/15681237-1dcc-404b-8b45-bdb56f6be237">

### Build timestamp

1709050558446

**Comment by coredev-uk** [comment]
This has been fixed and will be available in the next backend Electron release.
