### ISSUE TITLE
[Bug]:Playlists aren't syncing 

### ISSUE THREAD

**Issue by BigIntestine** [ciderapp/Cider-2#554]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2-prerelease14 | Built on 2/27/2024, 4:31:41 AM | Sabiiro | 04ba35833c2247fd5f7061cd2adb93dc67af9764

### Operating System Version

Windows 11

### Describe the Bug

fully signed into my apple music account and my playlists just randomly disappeared and I don't know where it went. I haven't figured out why and I couldn't get it back. 

### Steps to Reproduce

happened randomly 

### Build timestamp

1709077704616

**Comment by Azkaellion** [comment]
I'm having the same issue as of today, Cider was working fine last night.

**Comment by cryptofyre** [comment]
This is due to an Apple Music outage. Nothing we can do for now.

![image](https://github.com/ciderapp/Cider-2/assets/33162551/bbd0b8f7-d14d-4f19-942f-5fae4b641313)
