### ISSUE TITLE
[Bug]: Broken Devanagari Script in Sing when pulling lyrics from MXM

### ISSUE THREAD

**Issue by Otus9051** [ciderapp/Cider-2#555]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Linux

### Build Details

08/02/24 Build

### Operating System Version

Debian 12

### Describe the Bug

If Hindi lyrics are pulled from Musicmatch and put onto Sing Lyrics this happens:
![image](https://github.com/ciderapp/Cider-2/assets/58171861/48db6fdf-d14b-4e5d-96d9-02ff70e2990a)

But the lyrics are fine when Sing is disabled:
![image](https://github.com/ciderapp/Cider-2/assets/58171861/e5715bce-9ad2-474a-96f6-8d884561057b)

As far as I am concerned, Apple Music itself uses Romanized Lyrics instead of the Devanagari script.

### Steps to Reproduce

1. Play any Hindi music
2. Turn on Sing lyrics/immersive mode
3. Profit!

### Build timestamp

1709117755645

**Comment by coredev-uk** [comment]
Testing this out on mxm now, its using the Romanized lyrics, so ima close this
