### ISSUE TITLE
trying to reopen Cider

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [ciderapp/Cider-2#556]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.1

### Operating System Version

Windows 10 Home 19045.4046

### Describe the Bug

For some reason when I try reopening Cider after I closed it (to play in the background), it doesn't open but if I click it again it does open.

https://github.com/ciderapp/Cider-2/assets/93408587/f4dd92d7-be7f-4a8e-ac1b-65229a97b2cb

### Steps to Reproduce

I couldn't figure out what triggers this bug but here's this
1. Try to open Cider
2. Try to open Cider again

### Anything else?

Just discovered this only happens once during the active session. Also it won't happen through the tray icon.

**Comment by coredev-uk** [comment]
Our current Windows backend is being depreciated in favor of a newer improved codebase. I'll forward this issue onto that repo to prevent issues like this from happening. I cannot provide updates on this, you will just need to wait for the update.
