### ISSUE TITLE
[Bug]: Quit option does not work when minimize to tray is enabled

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#558]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2.0-RC1 | Built on 3/1/2024, 6:00:40 PM | Sabiiro | 18cc5a2d67829e4d5e5bd3b479aa22d68e5a68bb

### Operating System Version

Windows 11 22H2 22621.3155

### Describe the Bug

Whenever minimize to tray is enabled, the quit button in the three dot menu doesn't do anything. It does work when minimize to tray is disabled, however.

### Steps to Reproduce

1. Enable minimize to tray if not already enabled
2. open the menu with the three dots
3. press quit
4. nothing :3

### Build timestamp

1709420644404

**Comment by coredev-uk** [comment]
Backend changes to Windows will be passed along to our new backend (named Arsene), chances are these bugs are probably already fixed, but in the likelihood it hasn't been fixed they will be made aware. This will be closed and updates will not be provided.
