### ISSUE TITLE
[Bug]: Pause Animated Artwork When out of Focus doesn't work

### ISSUE THREAD

**Issue by keis4ri** [ciderapp/Cider-2#559]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2.0-RC1 | Built on 3/1/2024, 7:00:40 PM | Sabiiro | 18cc5a2d67829e4d5e5bd3b479aa22d68e5a68bb

### Operating System Version

Windows 11, although it happens on Linux as well

### Describe the Bug

Intended Behaviour is for Animated Artwork to continue playing despite being out of focus, such as when Cider is on a secondary monitor. However, Cider ignores this option completely and pauses animated artwork when out of focus anyways.

### Steps to Reproduce

1. Disable this option.
2. Animated artwork _should_ continue playing after focusing another window, but doesn't.

### Build timestamp

1709495546312

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/c0bd2388e643fb387b8422f9a903301bb601d156
