### ISSUE TITLE
[Bug]: Can't bring taskbar up when taskbar is set to automatically hide

### ISSUE THREAD

**Issue by natee99** [ciderapp/Cider-2#561]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

08/02/2024, 07:53:38

### Operating System Version

Windows 11 Home Version 22H2

### Describe the Bug

Unable to bring up the taskbar with the mouse when on Cider, I have to press the windows key or alt tab to get out/

### Steps to Reproduce

Have taskbar set to automatically hide in windows settings, happens anywhere in Cider

### Anything else?

-

### Build timestamp

1709564832676

**Comment by coredev-uk** [comment]
Backend changes to Windows will be passed along to our new backend (named Arsene), chances are these bugs are probably already fixed, but in the likelihood it hasn't been fixed they will be made aware. This will be closed and updates will not be provided.
