### ISSUE TITLE
[Bug] If port 9500 is in use app cannot be used

### ISSUE THREAD

**Issue by gaboprieto** [ciderapp/Cider-2#562]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [x] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

MacOS

### Build Details

2.3.1

### Operating System Version

Mac 14.1.2 (23B92)

### Describe the Bug

If port 9500 is in use the app does not run
<img width="501" alt="Screenshot 2024-03-05 at 4 10 45 PM" src="https://github.com/ciderapp/Cider-2/assets/22604600/42b45ae9-fabf-41da-9157-0388c1f51018">

### Steps to Reproduce

1. Run any http server on 9500 before starting cider.
2. Try launching cider.

**Comment by coredev-uk** [comment]
We intend to put a port option in for the rewrite of the electron backend, however, currently, there is no way to get around this. If you have an application running on port 9500 please close it. 

If you are not aware of any application running on this port, then you probably already have the application open in the background, in that case just go into Activity Monitor and look for Cider. Outside this, I cannot help much more.
