### ISSUE TITLE
Suggested songs play at max volume 

### ISSUE THREAD

**Issue by Grass69z** [ciderapp/Cider-2#564]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

microsft store version most recent as of 3-6-23

### Operating System Version

Windows 11

### Describe the Bug

If you have a set volume, when you play a suggested song, it turns it up to maximum volume.

### Steps to Reproduce

Scroll to the bottom of a playlist and play a suggested song while you have your song volume set to 0.

**Comment by cryptofyre** [comment]
Bug is now fixed in 2.3.0
