### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by CanadiaDry** [ciderapp/Cider-2#566]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2.0-RC2 | Built on Invalid Date | Sabiiro | 03b352d618c2c296a1306cccb8d71a79cbfc277a

### Operating System Version

Windows 11, multiple versions tried

### Describe the Bug

![cider bug](https://github.com/ciderapp/Cider-2/assets/135390405/b627bcd2-dff9-444a-a3d7-b8ca38906a57)
When in dark mode, the app slowly gets really buggy and all motion sticks in place and duplicates itself. See image above.

### Steps to Reproduce

It happens every time I'm in dark mode, but sometimes I can make it stop by switching to light mode, exiting out of settings, and then going back into settings and setting it to dark mode again. 

### Anything else?

I've tried going to 2.3.2.0 RC2 and it still had the same issue. Downgraded back to 2.3.1 and the issue prevails. Reinstalling the program doesn't work either.

### Build timestamp

1709859290593

**Comment by coredev-uk** [comment]
Turn off HDR

**Comment by CanadiaDry** [comment]
THANK YOU! It was turned on for my other monitor so I didn't notice.
