### ISSUE TITLE
[Bug]: auto/infinite play queue visual bug

### ISSUE THREAD

**Issue by selly139** [ciderapp/Cider-2#568]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.8.24

### Operating System Version

Windows 10

### Describe the Bug

The queue for auto-play shows the current album i was playing instead of the upcoming tracks. However, there are some tracks listed after. Upon removing the top song (first of seeming repeat of album) the following tracks began to disappear. So, i think there is a glitch with the album overlaying the queue. 

### Steps to Reproduce

just happens with albums alone i think, sometimes the queue is not visually occurring at all though (blank menu upon opening)

### Build timestamp

1710027489463

**Comment by cryptofyre** [comment]
Can you see if this issue is still relevant on the new 2.3.2 which has an updated Queue system?
