### ISSUE TITLE
[Bug]: cider APP BETA does not connect to desktop queue as remote

### ISSUE THREAD

**Issue by selly139** [ciderapp/Cider-2#569]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.8.24

### Operating System Version

Windows 10

### Describe the Bug

The app is just blank and shows nothing playing, not sure if i set something up incorrectly or if it wasnt adapted for c2

### Steps to Reproduce

everytime. 

### Build timestamp

1710027778365

**Comment by coredev-uk** [comment]
Please expand on your issue and what version of the app you are using

**Comment by selly139** [comment]
I do not see how I'm supposed to expand on a blank screen, the app essentially does not function in any way besides logging in to Apple Music. 

app version: testflight cider remote 2.1 (8) 
iOS version: 17.3.1  (iPhone 12 Pro)

**Comment by coredev-uk** [comment]
So are you on about the iOS remote app?

**Comment by selly139** [comment]
I’m pretty sure that’s abundantly clear by now.On Mar 13, 2024, at 2:16 PM, Core ***@***.***> wrote:﻿
So are you on about the iOS remote app?

**Comment by coredev-uk** [comment]
That still doesnt make it clear, you literally just replied a email footer. If you prefer I can not help you. You have just complained about the app beta being blank and not connecting to desktop queue, whatever that means. If this issue is related to the iOS app as you havent made clear at all. You havent said if this is an issue with the Remote app on iOS or the desktop app.

From everything you've said, I'm just gonna go off you this being an issue with the iOS app, in which case, this app is not currently being supported, the main developer assigned to this has been focused on other areas. As only one developer has made and developed this, this is out of my control. If you really want this app to be working I suggest reaching out to Swiftzerr (the app dev).

I cannot take this any further here. If I got it wrong and you're on about the desktop app, reply and I'll reopen the ticket.

The next time you open a ticket, please follow the template carefully and actually state the steps to recreate, dont just skip through because you want to complain.

**Comment by selly139** [comment]
This is just paragraphs of slop, what work do you think you’re accomplishing with this? Ask a pointed question off-bat instead of telling me it’s incomplete. I provided an obvious app version alongside iOS version which should have made it perfectly clear what I’m discussing. THE REMOTE APP IS BLANK: there is literally nothing else for me to provide. Up front, if you understood the product system it seems you would have quickly noted that this is no longer a function. Absurdly Idiotic really that I could sign up for a beta that is no longer functioning. Y’all gotta shut that down and pass on the memo so we don’t get our hopes up. I really expected more professionality here. This was childish to read and respond to. On Mar 14, 2024, at 1:46 PM, Core ***@***.***> wrote:﻿
That still doesnt make it clear, you literally just replied a email footer. If you prefer I can not help you. You have just complained about the app beta being blank and not connecting to desktop queue, whatever that means. If this issue is related to the iOS app as you havent made clear at all. You havent said if this is an issue with the Remote app on iOS or the desktop app.
From everything you've said, I'm just gonna go off you this being an issue with the iOS app, in which case, this app is not currently being supported, the main developer assigned to this has been focused on other areas. As only one developer has made and developed this, this is out of my control. If you really want this app to be working I suggest reaching out to Swiftzerr (the app dev).
I cannot take this any further here. If I got it wrong and you're on about the desktop app, reply and I'll reopen the ticket.
The next time you open a ticket, please follow the template carefully and actually state the steps to recreate, dont just skip through because you want to complain.

**Comment by coredev-uk** [comment]
We are not paid for this, nor are any of the other devs handling issues, so take my response as only what you're getting. If something is not working in the main app, then I might be able to do something, outside this I cannot do anything. Swift is well aware of the state of the app. I am not responding any more to you if you are just going to complain. 

And at no point during the issue did you say 'The remote app is blank'. We get a lot of issues, varying in degree and area of our project, so you saying 'app is blank' can imply both desktop or mobile app. 

All the best.

**Comment by selly139** [comment]
I wouldn’t pay anyone for your thinking either lmao this coulda been so simple On Mar 14, 2024, at 6:18 PM, Core ***@***.***> wrote:﻿
We are not paid for this, nor are any of the other devs handling issues, so take my response as only what you're getting. If something is not working in the main app, then I might be able to do something, outside this I cannot do anything. Swift is well aware of the state of the app. I am not responding any more to you if you are just going to complain.
And at no point during the issue did you say 'The remote app is blank'. We get a lot of issues, varying in degree and area of our project, so you saying 'app is blank' can imply both desktop or mobile app.
All the best.
