### ISSUE TITLE
When opening app i cant play music

### ISSUE THREAD

**Issue by GeicoUnderwater** [ciderapp/Cider-2#571]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2/8/2024 

### Operating System Version

windows 11

### Describe the Bug

everytime i start my pc amd try to use cider it wont let me play music, i have to enter task manager, end the process and then re open the app to be able to play music

### Steps to Reproduce

Shut down my pc, start it open cider and the try to listen to something, enter task manager end the process and re open the app to be able to listen 

### Connect Device ID

latest

**Comment by cryptofyre** [comment]
Cannot reproduce, in both typical environments and low memory environments. Check your network connection settings and or your GPU drivers perhaps?
