### ISSUE TITLE
Volume is not saved when exiting the program

### ISSUE THREAD

**Issue by theironraiden** [ciderapp/Cider-2#572]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

Version 2.3.1 08/02/2024 08:53:38 Quasar 2.14.3 Sabiiro

### Operating System Version

Windows 11 22631.3235

### Describe the Bug

Volume setting works ok during normal use. However, volume is not saved after closing and reopening the program. It's stuck at the first value I entered when I installed the program and closed (22%).

### Steps to Reproduce

Open the program, volume is the same value as previous session (22%). Change volume, (40% for example) close, open again, volume is again 22%.

**Comment by coredev-uk** [comment]
Could be an issue with config persistence. Please go to `%appdata%/sh.cider.sabiiro` and delete the `spa-config.json` file then fully close the app and reopen.

**Comment by theironraiden** [comment]
Hi,

I could not find the file on the stated route, but found it on AppData\Local\Packages\27554FireDevElijahKlauman.CiderEA_270bejk4xgzqp\LocalCache\Roaming\sh.cider.sabiiro

Removing the file and restarting did not fix the issue, it just removed all customizations and settings.

Updating to 2.3.2.1 did not help either.

**Comment by coredev-uk** [comment]
Are you using Cider Connect Settings Sync?

**Comment by theironraiden** [comment]
Hi,

I tried with both settings sync on and off and had the same result (I tried this before even opening the ticket, actually). Also tried it with Connect core on and off, same result, volume goes to 22% after every app restart.

**Comment by coredev-uk** [comment]
Closing this in favour of https://github.com/ciderapp/Cider-2/issues/657
