### ISSUE TITLE
Not All Playlists are Showing

### ISSUE THREAD

**Issue by jesserosenbaum** [ciderapp/Cider-2#573]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Linux

### Build Details

2/7/2024

### Operating System Version

Ubuntu 23.10 - 6.5.0-25-generic

### Describe the Bug

When browsing the my Playlists, not Apple Music Playlists, I can only get as far as the letter S for my playlists.  Anything after that is not shown.  I was specifically looking for one I made called **Spring 2024**, but I cannot see it in Cider 2.3.1.  I can see it on music.apple.com as shown below.  I have over 80 playlists, but can only see ~75.

Cider 2.3.1 View:
![Cider 2 3 1 Playlist View 20240312](https://github.com/ciderapp/Cider-2/assets/163149495/c0f53cfe-3eb4-492c-bef0-63d16fc87b8b)

Apple Music Website View:
![Apple Music Playlist View 20240312](https://github.com/ciderapp/Cider-2/assets/163149495/63894651-d2b9-43db-9220-837f9e617576)

### Steps to Reproduce

1. Open Cider Music App
2. Using the Navigation menu on the left, scroll to the Playlists section, not Apple Music Playlists, and keep scrolling until you reach the end.
3. Observe that if there are unable to see all playlists; I can only see ~75 of my playlists

### Connect Device ID

Cider 3.2.1

**Comment by coredev-uk** [comment]
This might be an issue with caching, please right click on the playlist header in the sidebar and click refresh. If it still does not appear, is this playlist unique in any way? Like is it a smart playlist or comprised of iTunes uploaded songs etc.

**Comment by jesserosenbaum** [comment]
Hello.  I just tried to refresh the playlists and it did not work, sorry to say.  Below (attached) is a screen recording of me trying a few times.  This is not a smart playlist nor Apple Music Playlist.  It's just one I made on my own.

[Cider Playlist Refresh Test.webm](https://github.com/ciderapp/Cider-2/assets/163149495/25a16d8a-55d3-45c4-a7d5-77a3149ab7ec)

**Comment by chispito** [comment]
Same issue here, refresh does not fix this... it's not the first time this happens to me, in some other version of the app, I remember having this same issue, and it was fixed with an update, from what I remember...

**Comment by jesserosenbaum** [comment]
I did just update to 2.3.2 and the issue persists.

**Comment by chispito** [comment]
Still the same with version 2.3.2.1... 😑

**Comment by jesserosenbaum** [comment]
> Still the same with version 2.3.2.1... 😑

Same here.

**Comment by coredev-uk** [comment]
To all of you, does all the playlists appear when you select the All Playlists option?

**Comment by chispito** [comment]
New version, same problem...😔

**Comment by chispito** [comment]
I downloaded the latest version but it did not work...BUT! Turning on the legacy retrieval method did the trick, please don't change this!! Many thanks for all your help!

**Comment by jesserosenbaum** [comment]
I can confirm that turning on Legacy Retrieval Method resulted in all Playlist downloading / showing.

**Comment by yokelpole** [comment]
Chiming in as well to say that I was having the same issue but legacy playlists fixed it for me as well - FWIW the non-legacy way of fetching appeared to only fetch 100 of my playlists while legacy pulls in all 208.
