### ISSUE TITLE
[Bug]: Playlist folders don't include apple music playlists

### ISSUE THREAD

**Issue by Noctember** [ciderapp/Cider-2#575]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### What operating system are you using?

Windows

### Build Details

2.3.2.0 | Built on Invalid Date | Sabiiro | b68c3db21100bd6ed7e84420c10426717b568d72

### Operating System Version

n/a

### Describe the Bug

The folders should either show up under apple music playlists, or include those playlists and be removed from the apple music playlists sections of the sidebar

### Steps to Reproduce

1. Create a playlist folder and add an apple music playlist to it
2. Open cider

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/20407566/94ba8591-8ccb-4576-8d38-004122387e57)
![image](https://github.com/ciderapp/Cider-2/assets/20407566/93e76917-9f4d-4fd4-9aff-a3ca070081c3)

### Build timestamp

1710462229342

**Comment by coredev-uk** [comment]
You have the Apple Music section collapsed, which is where your playlists are. Even if you store it in a folder, we put them in their own section. Please make sure you check the interface before making issues in the future

**Comment by Noctember** [comment]
> You have the Apple Music section collapsed, which is where your playlists are. Even if you store it in a folder, we put them in their own section. Please make sure you check the interface before making issues in the future
I'm aware... There are no folders under `Apple Music Playlists`, which I've mentioned above. Please read carefully before responding.

![image](https://github.com/ciderapp/Cider-2/assets/20407566/36386c8f-190e-4eb6-bf48-50d4fce6707a)

**Comment by au5ton** [comment]
Why not preserve the folders how we made them, instead of putting them in their own section without any hierarchy? I don't really get this design choice. @coredev-uk

**Comment by coredev-uk** [comment]
This was a decision made a long time ago, without my involvement, so I'm not sure why. I'll run it by the rest of the team to get their thoughts.

**Comment by au5ton** [comment]
Thank you
