### ISSUE TITLE
Animated Artwork is way too bright

### ISSUE THREAD

**Issue by CoconutBin** [ciderapp/Cider-2#576]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### What operating system are you using?

Windows

### Build Details

v2.3.2.0

### Operating System Version

Windows 10 Pro version 22H2

### Describe the Bug

All the Animated Artwork on Albums is way too bright.

### Steps to Reproduce

1. Turn on Animated Artwork
2. Open Immersive Mode / Go to Album with Animated Artwork

### Anything else?

This is what it looks like with Animated Artwork turned on
![image](https://github.com/ciderapp/Cider-2/assets/75740238/ef660f1b-4c64-4afb-b1a8-1d51674ce849)
![image](https://github.com/ciderapp/Cider-2/assets/75740238/aa03545b-8953-478f-aa6f-54e23458fd1b)

This is what it looks like with Animated Artwork turned off
![image](https://github.com/ciderapp/Cider-2/assets/75740238/8084781c-bcc0-46d0-9234-317de170b857)
![image](https://github.com/ciderapp/Cider-2/assets/75740238/170e3ad0-525b-41cd-bc6c-c7fabfaeb477)

**Comment by cryptofyre** [comment]
Please ensure your GPU drivers are up to date, older NVIDIA/AMD drivers have a saturation issue.
