### ISSUE TITLE
[Request]: Need to add artwork changing feature

### ISSUE THREAD

**Issue by ripapi** [ciderapp/Cider-2#577]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### What operating system are you using?

Windows

### Build Details

2.3.2.0 | Built on Invalid Date | Sabiiro | b68c3db21100bd6ed7e84420c10426717b568d72

### Operating System Version

Windows 11

### Describe the Bug

I think it would be much more interesting to have the ability to replace or add artwork in the property panel.

### Steps to Reproduce

It should work in the same way as iTunes: 
Remplacing: select the image and replace it by pasting an other with ctrl V or drag and drop an image, then select the one you want to delete.
Adding: use drag and drop with an image or simply past it with ctrl V

### Build timestamp

1710586109194

**Comment by cryptofyre** [comment]
This is not **currently** possible within Apple's API limitations but we will always keep an eye out on when this can be done without breaking or manipulating things we shouldn't.
