### ISSUE TITLE
[Bug]:Discord RPC don't stop when music paused

### ISSUE THREAD

**Issue by Brize-Glace** [ciderapp/Cider-2#579]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### What operating system are you using?

Windows

### Build Details

2.3.2.0 | Built on March 15th, 2024 | Sabiiro | b68c3db21100bd6ed7e84420c10426717b568d72

### Operating System Version

Windows 11 Pro 23H2 | Build 22631.3296

### Describe the Bug

The Discord RPC stays on when my music is paused even though the option to turn off the Discord RPC when the music is paused is enabled.

### Steps to Reproduce

1. Turn on Discord RPC and turn on "Disable Discord Rich Presence when music is paused"
2. Play a music and make sure that you see you RPC on discord
3. Pause the music

### Build timestamp

1710635714142

**Comment by coredev-uk** [comment]
Old bug afaik. Sometimes Discord does take a minute to clear the status
