### ISSUE TITLE
[Bug]: When clicking on a song the music won't play

### ISSUE THREAD

**Issue by CodingMakoto** [ciderapp/Cider-2#581]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 14.4

### Commit Hash

6d28d866c04a05d34605ec0afe0ad387d608b01d

### Connect Instance ID

57c3ca0b-5e92-41af-adcc-712399ee6492

### Build Timestamp

19/03/2024 07:31:20

### Describe the Bug

When i open Cider and click on any song the song isn't playing but the button is doing the play animation and turn back not playing. I've checked and i'm signed in successfully with Apple Music.

The button stay like the picture:

<img width="1007" alt="Capture d’écran 2024-03-19 à 10 10 40" src="https://github.com/ciderapp/Cider-2/assets/89703992/39c7b469-ebac-4f7a-879b-ed7a7d74770e">

### Steps to Reproduce

- Open Cider App
- Click on any song or playlist

### Anything else?

I'm using Cider App 2.3.2.1

**Comment by J-Stuff** [comment]
For anyone experiencing this issue. Ensure your Apple Content Restrictions are disabled for Explicit music.

You can turn them off on your iPhone by going to:
`Settings > Screen Time > Content & Privacy Restrictions > Disable` or
`Settings > Screen Time > Content & Privacy Restrictions > Content > Music, Podcasts, News, Fitness > Explicit`

**Comment by coredev-uk** [comment]
When you initially signed in there would've been a notification warning you of this ^. Most of the time it is either the explicit check or the DRM failed, in which case just restart the app. That's all I can do to help.
