### ISSUE TITLE
hovering over a ui element highlights it

### ISSUE THREAD

**Issue by Harold-Brooks** [ciderapp/Cider-2#585]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11 Pro 23H3

### Commit Hash

6d28d866c04a05d34605ec0afe0ad387d608b01d

### Connect Instance ID

e9332b22-bef7-4fd9-9e0c-7cf158bea0f2

### Build Timestamp

3/19/2024, 1:31:20 AM

### Describe the Bug

sometimes when i hover over certain UI elements they turn a highlighted color of gray. this is a different thing than what usually happens with highlighting the song you hover over. its very distracting

### Steps to Reproduce

1. open cider
2. move your mouse around the UI
3. you will see strange things being highlighted

https://github.com/ciderapp/Cider-2/assets/87270162/b604b5ab-4118-4138-b6f8-9c37c0a453d5

**Comment by aabbey33** [comment]
I've had this issue as well, though its now advanced to doubling up or re-highlighting of entries to a new constant state

<img width="679" alt="image" src="https://github.com/ciderapp/Cider-2/assets/7175893/f025eedf-de47-4800-9f2b-a7e225fe3010">

same behavior to trigger the issue. 

Windows Store
e2c4453f1234558822d2ea7b764dc0d43a05813c
build time: 3/22/2024, 4:23:49 PM

**Comment by coredev-uk** [comment]
Turn off HDR
