### ISSUE TITLE
Audio Output Device not Saving

### ISSUE THREAD

**Issue by PiersonSilver** [ciderapp/Cider-2#586]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

6d28d866c04a05d34605ec0afe0ad387d608b01d

### Connect Instance ID

not-logged-in

### Build Timestamp

3/19/2024, 2:31:20 AM

### Describe the Bug

Whenever I open the app, the Output device I selected in the windows advanced sound settings don't save, resorting back to what my master output device is. I imagine this has something to do with having a GoXLR and the multiple output options/drivers. 

(Ex. if I set the output for cider/webview2 to 'music', but my main output is 'sample', the windows settings will still show 'music' as the selected output, but it will play the sound through 'sample').

### Steps to Reproduce

Any time the app is opened, this reset happens. As mentioned above, I think this has to do with the multiple outputs of the GoXLR.

### Anything else?

This is an issue that I had with the apple music app (it was significantly worse on there since it would switch between outputs each song, for cider, I just have to switch off and switch back on to the output I want anytime I open the app and it saves for the duration of the usage). 
The iTunes app used to have an option within their settings to chose an output device within the app itself and I never had an issue with it, idk if that's something.

**Comment by coredev-uk** [comment]
@booploops gonna assign this one to you as maybe a feature request for dotnet. Not too sure if dotnet does allow for more freedom with audio device, or if this issue is just a windows mistake.
