### ISSUE TITLE
Clicking Quit with Close to Tray enabled doesn't fully close app

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#587]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 11 22H2 (22621.3296)

### Commit Hash

f31459e4f8f18c59b6084e28689d281057212b9b

### Connect Instance ID

fc135b00-d54b-4a1b-8bc0-c9a310c4ce96

### Build Timestamp

3/21/2024, 9:17:32 AM

### Describe the Bug

When Close to Tray is enabled, clicking quit in the main menu doesn't close the app fully, but closes it to the tray like the X button. The only way to fully close the window is with alt + f4 or right-clicking the icon in the taskbar and clicking close window.

### Steps to Reproduce

1. Enable Close to Tray
2. Click on the 3 dots to open the menu
3. Click quit

**Comment by coredev-uk** [comment]
Fixed with https://github.com/ciderapp/Izanagi/commit/e2c4453f1234558822d2ea7b764dc0d43a05813c
Please wait for the next spa release.
