### ISSUE TITLE
I cannot use Airplay on linux (deb / appimage)

### ISSUE THREAD

**Issue by JesseRiemens** [ciderapp/Cider-2#588]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.5.0-25-generic

### Commit Hash

6d28d866c04a05d34605ec0afe0ad387d608b01d

### Connect Instance ID

not-logged-in

### Build Timestamp

3/19/2024, 7:31:20 AM

### Describe the Bug

I want to use Airplay like I could with cider classic, but I can't. I see no airplay button anywhere in the interface. 
![image](https://github.com/ciderapp/Cider-2/assets/33691143/e0d2696b-ff59-4e96-aaa7-b34780e7c409)

### Steps to Reproduce

1. Tried to find airplay

**Comment by JesseRiemens** [comment]
😶

**Comment by JesseRiemens** [comment]
🙃

**Comment by coredev-uk** [comment]
We are in the process of depreciating the current implementation of AirPlay. We discourage the use of it until it is either rewritten by ourselves or a community plugin is made. No more work will be done on the current implementation, so I shall be closing your issue.
