### ISSUE TITLE
Bug Report: Cannot make Bug Report

### ISSUE THREAD

**Issue by thiccaxe** [ciderapp/Cider-2#589]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Fedora 39

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Describe the Bug

bug report - cannot make bug reports.
```js
    ER(`https://github.com/ciderapp/Sabiiro-BugTracker/issues/new?assignees=&labels=%F0%9F%95%93+Pending%2C%F0%9F%90%9B+Bug&template=bug_report.yaml&title=[Bug]%3A&uid=${je("connect.uuid") || ""}&ver=${new Date(process?.env?.FRONTEND_BUILT ? "1710459986056" : new Date().getTime()).getTime()}&build_details=${encodeURIComponent(r)}`)
```

### Steps to Reproduce

Click report bug button.

### Anything else?

process is undefined. This should be replaced with the front-end alternative  `window.__BUILDINFO__.FRONTEND_BUILT`

**Comment by coredev-uk** [comment]
Is fixed in latest prereleases, please wait for the next itch release.
