### ISSUE TITLE
Close to Tray not working with Native Title Bar

### ISSUE THREAD

**Issue by Chrispycode** [ciderapp/Cider-2#590]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.7.7-1-MANJARO

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

not-logged-in

### Build Timestamp

23/03/2024, 00:23:49

### Describe the Bug

When closing the window with the native title bar and close to tray enabled, the app is not minimized but closed.
[Screencast from 2024-03-23 23-05-43.webm](https://github.com/ciderapp/Cider-2/assets/22537998/37279028-c922-4d5f-8960-ed31bf0c275e)

### Steps to Reproduce

1. Enable close to tray
2. Enable native title bar 
3. close the window with the close button

### Anything else?

I use Gnome Wayland

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/8f0b45f2d1a99b7d0aeec3bd7abaa9cd51ddcc8c
