### ISSUE TITLE
Itunes Library not working properly

### ISSUE THREAD

**Issue by JeffFun33** [ciderapp/Cider-2#591]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsft Store

### Operating System

Windows 11

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

ababd267-74c7-435d-bb44-ced056535de3

### Build Timestamp

3/22/2024, 7:23:49 PM

### Describe the Bug

Itunes library is very incomplete. What is showing up is a very small fraction of my laibrary and most of the tracks that are showing up are greyed out with this message: "PlayParams are missing. This song has likely been removed from Apple Music". 
However all songs are available and working in iTunes. 

### Steps to Reproduce

I click on songs in "Library" and then hover over the song title.

**Comment by coredev-uk** [comment]
iTunes fetches music differently with its own proprietary API. What was the outcome when you tested with AM web?
