### ISSUE TITLE
Cannot add songs to my playlist

### ISSUE THREAD

**Issue by Alvi136** [ciderapp/Cider-2#594]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [ ] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

not-logged-in

### Build Timestamp

3/23/2024, 1:23:49 AM

### Describe the Bug

I cannot add songs to my playlist.

### Steps to Reproduce

1. went to an album (tried with a few ones). 
2.right clicked on it
3.and then i left clicked on my playlist
4. isnt there :(

**Comment by cryptofyre** [comment]
Try in 2.4.0, otherwise I cannot reproduce this.
