### ISSUE TITLE
RPC Server not working for Discord on Fedora

### ISSUE THREAD

**Issue by CapJackSparrow98** [ciderapp/Cider-2#596]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.7.10-200.fc39.x86_64

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

not-logged-in

### Build Timestamp

23/3/2024, 00:23:49

### Describe the Bug

In Cider 2 the RPC Server isn't working. In my profile card the music i'm playing is not showed.

Instead in Cider 1.6.2 the RPC server is working properly.

### Steps to Reproduce

1. Open Cider 2
2. Activate RPC Server
3. Open Discord
4. Start music on Cider 2
5. The music infos aren't showed in the profile card of Discord.

### Anything else?

Cider 2 settings.
![image](https://github.com/ciderapp/Cider-2/assets/31597742/b4ed6232-c7a7-4c29-9db7-a2a573819f9a)

System infos

![image](https://github.com/ciderapp/Cider-2/assets/31597742/b9dac378-a01e-4961-8ca7-9e7e30b45eb0)

**Comment by cryptofyre** [comment]
This is due to Discord likely running in a Flatpak environment vs. Cider running as a standardized system package. Install Discord as a regular system application and this behavior should rectify itself.
