### ISSUE TITLE
Multiple discord RPC instances running at the same time

### ISSUE THREAD

**Issue by blackxfiied** [ciderapp/Cider-2#598]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 23.3.0 ?? macOS 14.3.1

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

b49fa3bd-c0fd-44fd-a5ad-4972f5efecc5

### Build Timestamp

3/23/2024, 7:23:49 AM

### Describe the Bug

When using Cider, multiple instances of the DiscordRPC are created, and 4 out of 5 of the listed statuses in that image are of the same thing.

<img width="328" alt="image" src="https://github.com/ciderapp/Cider-2/assets/41133734/fe405fa3-b52d-429d-b53e-569317aeb77c">

### Steps to Reproduce

Normal usage of Cider

**Comment by cryptofyre** [comment]
Discord clientside bug, additional RPC instances are **not** shown for other users.
