### ISSUE TITLE
shuffle makes it crash

### ISSUE THREAD

**Issue by sunmorai** [ciderapp/Cider-2#601]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft store

### Operating System

Windows 11

### Describe the Bug

every time i click shuffle in /library/songs, the app freezes and I have to task manager out. 

### Steps to Reproduce

click shuffle in /library/songs

**Comment by cryptofyre** [comment]
Invalid issue, could not reproduce.
