### ISSUE TITLE
[macOS] [feature request] Title bar menu options

### ISSUE THREAD

**Issue by blackxfiied** [ciderapp/Cider-2#603]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 14.3.1 || Cider 2.3.2.2

### Describe the Bug

Cider 1 has title bar options for playback, preferences, etc.. which is not currently implemented in Cider 2.

### Steps to Reproduce

n/a

**Comment by coredev-uk** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/64542347/3f58a00c-638a-4039-8c09-1ea5fcbcbdf2)
It makes it clear at the top of the issue report. This is for bugs.

**Comment by blackxfiied** [comment]
yeah, apologies
i realised that so i made a discord feature request and linked it to this github page
please go there if possible 😀
