### ISSUE TITLE
JS error when trying to open Cider while it's minimized to tray

### ISSUE THREAD

**Issue by rob-lachapelle** [ciderapp/Cider-2#604]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.6.22-281.current

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

20d4c8e8-225d-4950-974b-87ca2504de7c

### Build Timestamp

03/04/2024, 22:01:00

### Describe the Bug

While Cider is currently running and playing music but minimized to the tray, I get 2 JS errors when trying to open it from taskbar shortcut.  If I right click the tray icon then select show, I don't get the errors. This is using the AppImage.

### Steps to Reproduce

1. Open cider play some music then close the main window so that is minimizes to the tray.
2. Try to open Cider using a taskbar shortcut.
3. The first error appears then when I click ok the second appears.

### Anything else?

![error1](https://github.com/ciderapp/Cider-2/assets/18560087/f24b15c8-95cb-4018-8e81-23562a34122c)
![error2](https://github.com/ciderapp/Cider-2/assets/18560087/36915b49-a06b-427a-b9b9-d1065a0fe24f)

**Comment by coredev-uk** [comment]
Will be fixed in 2.5.0
