### ISSUE TITLE
I can't move my songs on playlists, it just loads infinitly when i click to save

### ISSUE THREAD

**Issue by MuriloNovel** [ciderapp/Cider-2#605]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.io

### Operating System

Windows 11

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

03/04/2024, 23:01:00

### Describe the Bug

I could, and out of the blue it stopped working (maybe cus i tried on a very long playlist? idk) (but it was working just fine)

### Steps to Reproduce

Tried to move songs on my playlist

**Comment by kirundist** [comment]
I have this issue too, unable to edit long playlists at all (add song, remove song, re-arrange tracks, etc.), however playlists less than 100 tracks seem to work fine.  Windows 11, Cider version 2.3.2.3.  Downgrading to 2.3.2.2 hasn't fixed the issue.
