### ISSUE TITLE
Explicit Content

### ISSUE THREAD

**Issue by Javivujij** [ciderapp/Cider-2#606]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

macOS 23.4.0

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

6b768af0-046b-4426-b331-eba4d6269e92

### Build Timestamp

3/4/2024, 20:01:00

### Describe the Bug

no puedo reproducir canciones que tienen contenido explicito, ya he buscado en las configuraciones y no encontré nada para habilitarlos 

### Steps to Reproduce

1 abrir cider
2 ir a alguna canción con contenido explicito
3 reproducirla
4 ERROR no reproduce

**Comment by cryptofyre** [comment]
Esta es una configuración que deberá configurar en Apple Music en la Web. Cider no le permite cambiar el comportamiento de qué contenido explícito puede reproducirse. Esto está controlado por Apple.
