### ISSUE TITLE
UI Doesn't Refresh When HDR is Enabled

### ISSUE THREAD

**Issue by nickolaos** [ciderapp/Cider-2#607]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Describe the Bug

When Windows 11 HDR is enabled, the UI seems to fail to refresh its state whenever any interaction occurs, including hover interactions. See attached image for what ends up happening.

### Steps to Reproduce

1. Open app to Home screen with HDR enabled on Windows 11
2. Move Cider window, hover or click on any UI objects, or otherwise interact with the window

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/18318058/f38a1259-b7a6-4296-97cf-b08d20811083)

**Comment by cryptofyre** [comment]
Cannot get this to happen on my end, potentially graphics driver related?
