### ISSUE TITLE
Can't queue anything if listening to a song based radio station

### ISSUE THREAD

**Issue by xPaiiN** [ciderapp/Cider-2#608]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

e9022733-50ad-4895-915d-315ce3c0cf0c

### Build Timestamp

4.4.2024, 04:01:00

### Describe the Bug

Hey, I've realized that I cannot queue ANY song, if I'm in a single song radio station.

So I right click on a song and select "Start Radio" and then want to e.g. queue a song from another playlist, then it is not playing the song as the next song and not showing it in the queue.
If I press "Play Next" or "Play Last" and skip the song, it just plays the next song of the radio but not my queue.

I tried it multiple times to see if it was just some bug or coincidence, but it didn't go away and the issue didn't resolve on it's own

### Steps to Reproduce

1. Start radio station on a song
2. Queue any other song as "Next"
3. But it won't work

### Anything else?

I tried waiting to see if further down in the queue the issue won't be present anymore, but the order doesn't matter. It even can be the 2nd song of the radio and it won't queue

**Comment by coredev-uk** [comment]
See https://github.com/ciderapp/Cider-2/issues/663
