### ISSUE TITLE
Search not working for library

### ISSUE THREAD

**Issue by xPaiiN** [ciderapp/Cider-2#611]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

e9022733-50ad-4895-915d-315ce3c0cf0c

### Build Timestamp

4.4.2024, 04:01:00

### Describe the Bug

Hey, it seems when searching for a song, and selecting Library, it is not working at all. Either there are no search results at all, or when Library is selected, it's still searching in Apple Music.

### Steps to Reproduce

1. Search for a song
2. Select Library
3. Either nothing is loading or it is showing results from Apple Music.

If you type the song name first, and then press Library, it searches Apple Music, but first selecting Library and then typing the song,  it's not even searching for anything. I think the search is then broken and you need to type multiple letters again and press Enter multiple times to make the search work again...

**Comment by Hezkore** [comment]
I can confirm that this is still an issue in Cider 2.4 _(Itch.io)_.

**Comment by booploops** [comment]
Related to internal project issue: (AMSearch) Library Search Rework
[#392](https://github.com/ciderapp/Izanagi/issues/392)

In 2.4.1 the non functional tab for Library is going to be temporarily removed until a suitable replacement is ready in either 2.4.2 or 2.4.3
