### ISSUE TITLE
Repeat status not saved when exit the app

### ISSUE THREAD

**Issue by fancccyyy** [ciderapp/Cider-2#613]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

 Microsoft Store

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

2024/4/4 10:01:00

### Describe the Bug

My repeat status is not saved when I leave the app, so I have to click on the repeat button each time I launch cider. quite annoying

### Steps to Reproduce

1. Open the app
2. click on the REPEAT button
3. close the app
4. you'll see the REPEAT feature isn't activated

**Comment by cryptofyre** [comment]
Client persistence is not yet available and is expected later in the timeline for this fiscal year.
