### ISSUE TITLE
i can't play a song

### ISSUE THREAD

**Issue by JunKerophile** [ciderapp/Cider-2#615]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

04/04/2024 04:01:00

### Describe the Bug

The songs won't play, even after restarting the app, cleaning the cache, restarting the PC, shuting down the app, it just doesn't wants to play a song

https://github.com/ciderapp/Cider-2/assets/63109127/009db460-f94e-4acb-92fd-f400f9637157

### Steps to Reproduce

started the app and wanted to play a song

### Anything else?

sometimes, the app just display a gray screen, and nothing else. Restarting the app and sometimes even the PC doesn't solve the problem

**Comment by JunKerophile** [comment]
Even after uninstalling and reinstalling the app, delete all the file with Revo Uninstaller, rebooting the PC, the issue still here
I bought Cider like, 3 days ago, worked sooo well, and suddenly, it stopped working

**Comment by cryptofyre** [comment]
Could you provide logs when you attempt playback in a video example? CTRL + SHIFT + I should open the DevTools menu.

**Comment by JunKerophile** [comment]
> Could you provide logs when you attempt playback in a video example? CTRL + SHIFT + I should open the DevTools menu.

Thanks for your reply ! Here what i got when i press ctrl + shift + I :
![image](https://github.com/ciderapp/Cider-2/assets/63109127/c63d8724-5970-4ca5-be16-19d184f5d781)

**Comment by cryptofyre** [comment]
Could you try running the following command in the console?

```
MusicKit.getInstance().volume = 1
```

See if that resolves the issue, if not try disabling all Cider Audio Lab settings.

**Comment by JunKerophile** [comment]
Okay, it seems to work with that. Thanks a lot ! 🙏

**Comment by cryptofyre** [comment]
Happy to help, closing this issue and we'll have a more permanent fix for this in an upcoming patch update.

**Comment by maikirakiwi** [comment]
Adding to the convo before crypto forgets what I said in general:
-> audio lab got init too fast, faster than the audiocontext that was supposed to be created.
