### ISSUE TITLE
lyrics window - no bounds on scroll 

### ISSUE THREAD

**Issue by thiccaxe** [ciderapp/Cider-2#616]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Fedora wayland

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Describe the Bug

Lyrics window:
- Scroll using mousewheel is slow(er than the rest of the application)
- No bounds on scrolling.

### Steps to Reproduce

Use a scrolling action on the lyrics window. Touchpad and mouse seem to work. Mojave layout if relevant.

**Comment by RestartB** [comment]
Just managed to recreate the slow scrolling bug and the lack of bounds bug. Happens on the sidebar and in immersive mode for me. I'm on Windows v2.3.2_3 through the MS Store

https://github.com/ciderapp/Cider-2/assets/79792966/d019ea7c-4854-48a1-946f-449b20587bd7

**Comment by RestartB** [comment]
Can confirm that the bugs are still present on both `2.4.0_1` and `2.4.1_0-prerelease1`.
