### ISSUE TITLE
Windows aarch64/arm64 request

### ISSUE THREAD

**Issue by PaintNinja** [ciderapp/Cider-2#617]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Describe the Bug

Hello, been enjoying this app on my Surface Pro X and think it's a decent step up over the official one, however, I noticed it's running in emulated mode as it doesn't have a native ARM binary for Windows yet.

If you could add a native build for Windows on ARM that would be greatly appreciated - should offer improved performance and battery life as a result.

### Steps to Reproduce

1. Download Cider (Preview) from the Microsoft Store
2. View the system requirements on the store listing and observe that there's only an x64 architecture, no ARM
3. Run the application and check the process details in task manager. Observe that it shows as x64 architecture instead of Arm64
![image](https://github.com/ciderapp/Cider-2/assets/3158390/95e37a41-bfdc-456c-b39f-8c839b910022)

**Comment by cryptofyre** [comment]
On the timeline for events, requires some minor changes to ring-rs to compile successfully. I have investigated this on my own volition and it does require an arm64 Windows environment to accomplish.
