### ISSUE TITLE
Language settings not used for Apple Music content

### ISSUE THREAD

**Issue by astatide** [ciderapp/Cider-2#618]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.8.5-301.fc40.x86_64

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

4/4/2024, 4:01:00 AM

### Describe the Bug

My region for my Apple Store is set to Spain; however, I primarily speak English and the Cider language is set to "American English".  All the Cider UI text is indeed in English; however, much of the text coming from Apple music is in Spanish (playlist names, artist biographies, search results).   I'm on version 2.3.2_3
![image](https://github.com/ciderapp/Cider-2/assets/9011779/0adb5d5a-3dd1-4e4d-8a20-482f05ed111e)

### Steps to Reproduce

If you're not already in a non-US region, you'd have to change your region at the App Store which requires _unsubscribing_ from everything, waiting for the remaining subscription to expire, then changing regions.  I can't recommend that, but it's possible that simply changing the Cider language doesn't impact the backend (perhaps try changing it to Spanish and seeing if what comes in from Apple's backend is in Spanish or not?)

### Anything else?

I'm happy to test any potential fixes.  Also, the issue is _not_ present on Apple Music on iOS; all the results there are returned to me in English, as my phone is set to that.

**Comment by coredev-uk** [comment]
The language which API calls will return in is based your current storefront. So for the Spanish storefront the supported languages are `'es-ES', 'en-GB', 'ca'`. The language setting in the Cider settings will try to apply the language you selected to the API calls given that the language is supported under the storefront.

The storefront is hard-set thought your apple Id currently. Changing this to a user-set preference may cause issues thus why it is not given. 

There is logs in console when a language is applied correctly, but no notification is shown which will probably change in the future but outside that not more will be done.

And just for additional context a storefront is where media is fetched from (E.g. Browse page results, Search results etc.), these will all be adjusted to that specific country. Each storefront supports a certain list of languages.

**Comment by coredev-uk** [comment]
If you are interested in finding out which storefront supports which language you can find out by running this API call in console which will return an object with language codes and the supportedLanguageTags array in attributes.

`(await MusicKit.getInstance().api.v3.music('v1/storefronts')).data.data`

**Comment by astatide** [comment]
Ah, my phone is set to British English, which is probably why I don’t notice this behavior there.  I’ll try and change Cider to British English and see if it works.  Thanks.

**Comment by astatide** [comment]
Actually, I’ve set it to British English, which is supported by the store front, but it still seems to be returning results in Spanish.

**Comment by astatide** [comment]
Sorry, I think I’m just confused about what is “not planned” in this case, as based on what you told me it should probably likely work so long as I’ve selected a supported language, which I have done.  So it doesn’t sound like an apple backend issue but instead something on the Cider end, unless Apple’s API ignores the requested language in the payload.  I’m not requesting any language override or any feature like that.
