### ISSUE TITLE
Song.Link Share Option Missing From Player

### ISSUE THREAD

**Issue by jlee0111** [ciderapp/Cider-2#619]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

When sharing a currently playing track by right clicking the album art/ song title in the player, only Apple Music shows up as a share option. If right clicking the same track in another place, like in it's album for example, the song.link option then shows up. It forces the user to have to go to the album that a track belongs to in order to share it with the song.link option.

### Steps to Reproduce

1. Pick and play a song
2. See share options from player
3. See share options from other elements

### Anything else?

![Screenshot 2024-04-24 194401](https://github.com/ciderapp/Cider-2/assets/115668613/76eda676-508d-474e-8116-dba923900a1c)
![Screenshot 2024-04-24 194422](https://github.com/ciderapp/Cider-2/assets/115668613/e2ecb1d4-4481-44ac-a293-e953efa48b51)

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/66da01fa8cc2141acf1c5bddceafd91792c67355
