### ISSUE TITLE
Search Bar Doesn't Show Library Items

### ISSUE THREAD

**Issue by BushMasterJM** [ciderapp/Cider-2#620]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

4/3/2024, 7:01:00 PM

### Describe the Bug

When searching in the top search bar while having library selected, the drop down still shows items in Apple Music and not my library. I'm pretty sure this is a big but I could be wrong and its not yet supposed to function that way.

### Steps to Reproduce

Have the Library button selected while music is playing and search in the search bar.

**Comment by Hezkore** [comment]
I can confirm that this is still an issue in Cider 2.4 _(Itch.io)_.
