### ISSUE TITLE
Cider periodically stops playing after certain tracks at an interval of about 5-15 min This observed on now two occasions, when playing the discovery station. 

### ISSUE THREAD

**Issue by MickeyOern** [ciderapp/Cider-2#621]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

4/4/2024, 4:01:00 AM

### Describe the Bug

Cider periodically stops playing after certain tracks at an interval of about 5-15 min This observed on now two occasions, when playing the discovery station. 

### Steps to Reproduce

Play the station.

**Comment by cryptofyre** [comment]
Cannot reproduce, try fixing your network conditions or disabling any overclocks/undervolts you may have, as they affect DRM.
