### ISSUE TITLE
The app doesn't play any songs

### ISSUE THREAD

**Issue by zachardavid** [ciderapp/Cider-2#624]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

Whenever I try to play a song that is not locally imported to my library through iTunes, nothing happens. The issue might be on my end but I'm really not sure, so I thought by posting here I could get some kind of explanation on what the problem could be.

Here's a picture of what the console outputs whenever I press play on a track/album
![Untitled](https://github.com/ciderapp/Cider-2/assets/151763600/65de37d0-06a1-4179-a240-ee276141ae24)

### Steps to Reproduce

I don't know the reason for it, probably a connection issue of some sort

### Anything else?

This happens randomly; sometimes the app lets me play songs for weeks, but other times it just doesn't function properly.

**Comment by ParkytGaming** [comment]
I am having the same issue as well.

**Comment by cryptofyre** [comment]
Looks like you have content restrictions on your account prohibiting you from playing types of music, this is not an issue with Cider but **MusicKit** as an entirety. Take a look at your account's content restrictions and your countries restrictions as Apple works alongside governmental policies.

**Comment by zachardavid** [comment]
The problem has been resolved, thank you.

Dávid Zachár
