### ISSUE TITLE
Sidebar Lyrics are getting 

### ISSUE THREAD

**Issue by d3rpp** [ciderapp/Cider-2#628]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Fedora Linux

### Commit Hash

6ed35872732cb631b33ed92f44ccd79d39072f77

### Build Timestamp

18/04/2024, 13:20:37

### Describe the Bug

When lyrics are in the sidebar, they get so close to the top of the window that the drop shadow at the top start going on top of active lines.

![image](https://github.com/ciderapp/Cider-2/assets/45675641/1a5958f1-3e2e-442b-9993-e43005c6f8be)

This makes the sidebar lyrics very difficult to use.

Only really causes issue if the following Tweaks are activated:

![image](https://github.com/ciderapp/Cider-2/assets/45675641/39b588f7-e4fa-486b-8ab8-a6474aac6bf5)

### Steps to Reproduce

Activate the Tweaks as shown above, play a song with lyrics, open the sidebar lyrics

**Comment by d3rpp** [comment]
God this feels so ironic that I'm using this things, now I get to experience the quality of Cider Support that I used to provide lmao (albeit I was not good at it).

**Comment by cryptofyre** [comment]
wouldn't run single lyrics everywhere, lyrics compositor for that is kinda weird on a size that small

**Comment by d3rpp** [comment]
![aaaaauuuughhh](https://cdn.d3rpp.dev/aaauuuuggghhh.gif)

**Comment by booploops** [comment]
Fixed in Cider 2.4.1 Beta 4
