### ISSUE TITLE
previous/play/next and minimise/restore/close buttons are white squares

### ISSUE THREAD

**Issue by omegadevice** [ciderapp/Cider-2#630]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Micerosoft Store

### Operating System

Windows 

### Commit Hash

7d5564d9a035b91d9a09a1eab3f19477f3ffe18e

### Connect Instance ID

not-logged-in

### Build Timestamp

03/05/2024, 19:35:13

### Describe the Bug

Some UI elements are missing / display as white boxes. They function as normal but do not draw.
The overall UI does not appear unless I refresh/f5 on startup, which may be related.

### Steps to Reproduce

1.Start the app as normal
2. (refresh the UI)
3. that's it!

### Anything else?

![Cider_piPbHKbcCj](https://github.com/ciderapp/Cider-2/assets/78792798/88cc11f5-42d4-483d-a3eb-75afbfc7df0f)

**Comment by coredev-uk** [comment]
Please run a [clean install](https://cider.sh/docs/legacy-docs/support/troubleshooting#_1-clean-installation). If icons are failing to load, your install is broken.
