### ISSUE TITLE
"Not Signed In" Infinite Loading

### ISSUE THREAD

**Issue by amandafaery** [ciderapp/Cider-2#633]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

7d5564d9a035b91d9a09a1eab3f19477f3ffe18e

### Connect Instance ID

not-logged-in

### Build Timestamp

5/3/2024, 2:35:13 PM

### Describe the Bug

When I open the app it says "You are not signed in" and is stuck loading. I am unable to click on anything or do anything besides exit the app.
![Screenshot (140)](https://github.com/ciderapp/Cider-2/assets/125159746/b56fa05f-916a-4d78-a7ac-51021222c8dc)

### Steps to Reproduce

I opened the app.

**Comment by baconapplications** [comment]
I am having the same issue.

**Comment by FoxTale-Labs** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/72300200/f0b25de7-3460-47ee-b3d6-16380d7649ef)
Same issue

**Comment by FoxTale-Labs** [comment]
Also, sign in withuser token doesn't work either.

**Comment by cryptofyre** [comment]
Please update to the latest hotfix version in the app using the update button in the quick menu.

2.4.0_1

**Comment by baconapplications** [comment]
> Please update to the latest hotfix version in the app using the update button in the quick menu.
> 
> 2.4.0_1

Fix worked.  Thank you!
