### ISSUE TITLE
When streaming radios (Radio 1, etc), only the miniplayer can recognise metadata (song title and artist name, etc), also animated lyrics dont work streaming radios either

### ISSUE THREAD

**Issue by kaer1a** [ciderapp/Cider-2#636]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch.io

### Operating System

Windows 

### Commit Hash

dfd13d600f9ccd89b5c0d1ceab593f90200b6bba

### Connect Instance ID

45398964-e423-4cc7-aa84-62bc7f69f36e

### Build Timestamp

09/05/2024, 02:04:55

### Describe the Bug

When I'm streaming radios on Cider 2. The only metadata that shows up on the now playing feed is the cover art; everything else is just "-". Even in immersive mode, there's still no song title/song artist (only cover art).
But, if I'm in the miniplayer, I'm able to see lyrics, a song title and the artist name.

Also, the lyrics don't do anything on the radio, theyre just there and don't animate or anything (when testing on miniplayer)

### Steps to Reproduce

stream a radio (like apple music radio 1 for example), and see if it youre able to get a song title and artist name, if not...
go on the miniplayer and it should be there

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/144589136/abb7aecc-c8af-448a-8098-c7d298553aea)
![image](https://github.com/ciderapp/Cider-2/assets/144589136/091734f6-ef35-4584-bcde-ff72984a4974)

(i dont like taylor swift) - i was just trying to listen to the radio and then i discovered this lmao

**Comment by Amaru8** [comment]
Works fine for me on the latest build. Can you verify whether this is still an issue?

**Comment by Amaru8** [comment]
Discussed on Discord with @kaer1a , the issue is not present in the latest version.
https://discord.com/channels/843954443845238864/1254248941780729898/1289992089068769381
