### ISSUE TITLE
MacOS not prioritizing cider with music controls when other content is playing in a different app

### ISSUE THREAD

**Issue by Kief5555** [ciderapp/Cider-2#640]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

macOS 23.5.0 (this was generated, I'm on 14.5)

### Commit Hash

247e299e8c3cfc440d9012dd50949e2679864dcb

### Connect Instance ID

not-logged-in

### Build Timestamp

5/8/2024, 5:57:55 PM

### Describe the Bug

MacOS not prioritizing cider with music controls via keyboard or OS.
This means, if I have another application running and playing content (eg Youtube on safari), all music controls will be focused on safari and not cider.

Eg skip button, pause button.

### Steps to Reproduce

1. Play music on cider
2. Play something on YouTube on safari
3. spam the skip key on your keyboard until your fingers can't no more

**Comment by coredev-uk** [comment]
This is not really how it works. We cannot prioritise Cider over other applications, this would be down to how Apple has set up its media interface.
