### ISSUE TITLE
"In nan day" bug

### ISSUE THREAD

**Issue by ramenzackreall** [ciderapp/Cider-2#641]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

macOS 13.6.7

### Commit Hash

0519461f4b33ce8c97d448734255a67c97109c28

### Connect Instance ID

logged-in

### Build Timestamp

5/15/2024, 3:41:27 PM

### Describe the Bug

I see a album with the date being "in nan day"
![Screenshot 2024-05-17 at 2 12 42 PM](https://github.com/ciderapp/Cider-2/assets/97124407/f1238688-b6f6-4fb4-9af6-86c6f90cf029)

### Steps to Reproduce

Just look

### Anything else?

naw

**Comment by coredev-uk** [comment]
What album is this?
