### ISSUE TITLE
Airplay Casting error.

### ISSUE THREAD

**Issue by AW1534** [ciderapp/Cider-2#642]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.1.0-21-amd64

### Commit Hash

247e299e8c3cfc440d9012dd50949e2679864dcb

### Connect Instance ID

not-logged-in

### Build Timestamp

09/05/2024, 01:57:55

### Describe the Bug

When i enable Airplay, Disable it and then enable it again i get the following error.

![image](https://github.com/ciderapp/Cider-2/assets/62200778/b1d5e15e-fc5e-46ae-9fc0-60b77f8a4df9)

This repeats for each time i dsable and reenable it from here.

### Steps to Reproduce

Settings > Audio 

AirPlay Casting: on
AirPlay Casting: off
AirPlay Casting: on

**Comment by AW1534** [comment]
@coredev-uk sorry for the mention but i think i was too late to bump this, but it is definitely still an issue. 

Would you please remove the stale tag

**Comment by coredev-uk** [comment]
We are in the process of depreciating the current implementation of AirPlay. We discourage the use of it until it is either rewritten by ourselves or a community plugin is made. No more work will be done on the current implementation, so I shall be closing your issue.
