### ISSUE TITLE
first time login error

### ISSUE THREAD

**Issue by brightpavilions** [ciderapp/Cider-2#643]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 23.5.0

### Commit Hash

247e299e8c3cfc440d9012dd50949e2679864dcb

### Connect Instance ID

not-logged-in

### Build Timestamp

5/8/2024, 5:57:55 PM

### Describe the Bug

Hello. I just downloaded Cider for my M3 Mac, and am unable to login to Apple Music. I receive a couple of errors. See attached. I'm using 2.4.0_1

### Steps to Reproduce

Simply trying to sign in to Apple Music. 
<img width="261" alt="SCR-20240517-mrju" src="https://github.com/ciderapp/Cider-2/assets/24417126/a66f0334-5cdc-4cfb-83aa-078cd8b506c3">
<img width="501" alt="SCR-20240517-mobt" src="https://github.com/ciderapp/Cider-2/assets/24417126/0a56df91-a90b-40e6-bee8-99c31b8d1c95">

### Anything else?

My AppleID is working properly. This is only happening with Cider.

**Comment by coredev-uk** [comment]
You're account being locked is not a Cider issue. The first error is a result of the authentication process going wrong. Please try logging into Apple music web, if that does not work you will need to contact Apple support.
