### ISSUE TITLE
Allowed to add Songs to collaborative Playlists but song isn't added

### ISSUE THREAD

**Issue by DwieDave** [ciderapp/Cider-2#645]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 23.4.0

### Commit Hash

247e299e8c3cfc440d9012dd50949e2679864dcb

### Connect Instance ID

not-logged-in

### Build Timestamp

9.5.2024, 02:57:55

### Describe the Bug

I can't add songs to collaborative Playlists.
The functionality however seems to be non-existant with the Web Version of AM as well. 
But on AM Web there is no option to add the song to those playlists because they are not listed in the context-menu there.

In Cider the option exists and gives positive Feedback (Song has been added) 
But the song isn't added.

### Steps to Reproduce

- Create a Collaborative Playlist on Account A
- Share Playlist (with edit privilege) to Account B
- Login to Cider with Account B 
- Try to add a song to the shared playlist.

**Comment by coredev-uk** [comment]
Currently, Collaborative Playlists are not supported by the Apple Music API, when this feature comes available we'll be happy to implement it.

**Comment by DwieDave** [comment]
I would propose removing the functionality for collaborative playlists as long ita not supported because it is really confusing getting a positive feedback and no actual result.
