### ISSUE TITLE
Apple account Login Problem

### ISSUE THREAD

**Issue by Pranab0p** [ciderapp/Cider-2#648]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft app store

### Operating System

Windows 

### Commit Hash

7ed90bcc0fddc8dbaeaaaca200a30b277e2f4152

### Connect Instance ID

not-logged-in

### Build Timestamp

23/5/2024, 8:03:49 am

### Describe the Bug

apple account login failed

### Steps to Reproduce

apple account login failed
![Screenshot 2024-05-28 110302](https://github.com/ciderapp/Cider-2/assets/133628091/1bbc5604-1896-4ed6-b354-30db8f9ce672)

**Comment by coredev-uk** [comment]
Just sign into Apple Music again... This looks similar to an old issue, so please reopen the issue if its still continuing.
