### ISSUE TITLE
Mini & compact player have redundant titlebar controls when using native titlebars on Linux

### ISSUE THREAD

**Issue by rgbmew** [ciderapp/Cider-2#649]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.8.10-300.fc40.x86_64

### Commit Hash

7ed90bcc0fddc8dbaeaaaca200a30b277e2f4152

### Build Timestamp

5/22/2024, 10:33:49 PM

### Describe the Bug

When enabling native titlebars on Linux, and switching to the mini or compact player mode, it continues rendering the native titlebar, and built-in titlebar; wasting space, covering up track information, and making redundant window controls.

Images captured on KDE Plasma 6.0.5, using Wayland, on appimage 2.4.1_0-prerelease2

![Screenshot_20240529_004740](https://github.com/ciderapp/Cider-2/assets/42557645/3421ddac-0df1-44ff-84c2-23f149e6df39)
![Screenshot_20240529_005405](https://github.com/ciderapp/Cider-2/assets/42557645/41377ed9-482f-4ab6-8a70-70100948eb7e)

### Steps to Reproduce

Open Settings>Visual>Title Bar Style, select "Native," then enable mini/compact player.

### Anything else?

I've only tested this on Plasma 6.0.5 Wayland. It may be different on GNOME, wlroots, and xorg desktops, due to how KDE Plasma implements server side decoration on Wayland.

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/cb247437d2844261d0fe19cfe20be3f694ab6b37
