### ISSUE TITLE
/currentPlayingSong not working.

### ISSUE THREAD

**Issue by nrthbound** [ciderapp/Cider-2#650]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Mac OS Sonoma

### Describe the Bug

After enabling RPC in the Cider settings, I was able to use Hoppscotch to test most of the endpoints with expected results, however; `/currentPlayingSong` doesn't work. It doesn't return anything as the endpoint cannot be reached.

### Steps to Reproduce

Load up any API tool (Hoppscotch, Postman, Insomnia, etc), and try to make a `GET` request to `http://localhost:10769/currentPlayingSong`.

### Anything else?

Awesome app otherwise, and while I don't *need* RCP support, it'd make add "Currently Listening To" labels in OBS way easier.

**Comment by coredev-uk** [comment]
What version is this occurring on

**Comment by nrthbound** [comment]
2.4.0_1 - that's what it was 22 days ago anyway.

**Comment by nrthbound** [comment]
Just getting a 500 status now. Again, all of the other endpoints work except `/currentPlayingSong`

**Comment by nrthbound** [comment]
I got it working. I had to remove Cider completely as something didn't jive with the update, and that one endpoint just didn't want to update properly with everything else. All good now.
