### ISSUE TITLE
Add WebSocket for Linux

### ISSUE THREAD

**Issue by xXPerditorXx** [ciderapp/Cider-2#651]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.9.2-arch1-1

### Commit Hash

7ed90bcc0fddc8dbaeaaaca200a30b277e2f4152

### Connect Instance ID

not-logged-in

### Build Timestamp

5/23/2024, 4:33:49 AM

### Describe the Bug

On Windows, I was able to enable WebSocket and RPC under Connectivity Settings, but on linux (arch), there is only the option for RPC Server.

### Steps to Reproduce

Open settings, scroll to the bottom at connectivity tab.

**Comment by coredev-uk** [comment]
This is in the pipeline for 2.5.0. Please keep feature requests to Discord though ty.
