### ISSUE TITLE
Cider 2.4.1 UI controls aren't working on Linux

### ISSUE THREAD

**Issue by B00giee** [ciderapp/Cider-2#652]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.io

### Operating System

Linux 6.8.0-76060800daily20240311-generic

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 2:59:57 PM

### Describe the Bug

Pause, Next, and Previous do not work on UI tool bar. 

### Steps to Reproduce

Click on small icon on tool bar while song is playing attempt to pause, skip, or go back. You will get an error.

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/157347616/ab5b1574-257d-4761-8c79-ee04ac28029e)
![image](https://github.com/ciderapp/Cider-2/assets/157347616/a1636400-2f31-4468-a8b5-d6245410545b)

**Comment by B00giee** [comment]
FYI- Already purged all files, config folders, and fresh install. Still the same.

**Comment by B00giee** [comment]
![image](https://github.com/ciderapp/Cider-2/assets/157347616/e71a1fec-64da-493f-94fa-73996bb2f46e)
![image](https://github.com/ciderapp/Cider-2/assets/157347616/b77589f4-6a57-4852-a7a0-8cbfa64a2f3b)

**Comment by coredev-uk** [comment]
Is this interacting with the app through MPRIS?

**Comment by coredev-uk** [comment]
I cannot replicate this, I have tried for both our MPRIS integration and Menubar which is suspect is your issue, but bother seem to work as intended. What build are you using (AppImage, deb, rpm, tar.gz etc.)?
