### ISSUE TITLE
Window Persistence doesn't work on secondary monitor

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Cider-2#654]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 

### Commit Hash

752bd04a1b3177ba0f1b4c954364fb0234c93467

### Connect Instance ID

not-logged-in

### Build Timestamp

5/31/2024, 9:49:53 PM

### Describe the Bug

When closing and re-opening Cider, windows persistence doesn't work if I have moved the window to my secondary monitor; it instead opens towards the bottom of my screen (pictured below). 

![image](https://github.com/ciderapp/Cider-2/assets/95056585/6b80653e-8f66-4344-9642-42c7a3d4f9a4)

### Steps to Reproduce

1. Open Cider
2. Move window to secondary monitor
3. Close Cider
4. Re-open Cider

### Anything else?

Like I mentioned in my previous bug report (concerning the MiniPlayer, issue #653), my main monitor is running at 125% scale @ 1440p, while my secondary monitor is running at 100% scale at 1080p.

**Comment by cryptofyre** [comment]
Should be fixed in an upcoming release (2.5.0)

**Comment by mpar-22** [comment]
I should clarify, this is on the latest alpha version of 2.5.0 (not sure if the report already specifies)

**Comment by kristianpennacchia** [comment]
I'm encountering a possibly related issue on Windows with two monitors.

If I have Cider open on my 2nd monitor and switch to the mini-player, then click the close button (X), Cider will instead open on my 1st (primary) monitor and the window size will also change instead of going back to the size I set on my 2nd monitor.

**Comment by mpar-22** [comment]
Yeah, I'm also having that issue on the latest patch
