### ISSUE TITLE
The download link to the Cider Remote V2 apk isn't working

### ISSUE THREAD

**Issue by Supernoww** [ciderapp/Cider-2#655]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 10

### Describe the Bug

The download link to the apk is broken and it says brings up an error saying this bucket cannot be viewed.

### Steps to Reproduce

1. Went to the Cider Remote website
2. Clicked on "Download APK"
3. Got error 403 "This bucket cannot be viewed"

### Anything else?

<img width="1100" alt="Screenshot 2024-06-02 121008" src="https://github.com/ciderapp/Cider-2/assets/91606457/001de8f4-2eb7-4322-9cbb-1310f8432db1">
<img width="1115" alt="Screenshot 2024-06-02 121055" src="https://github.com/ciderapp/Cider-2/assets/91606457/b65ca7dd-bb84-4f45-b40d-52504df9d7d4">

**Comment by coredev-uk** [comment]
This issue board is for the main client, please forward mobile app related issues to Discord.
