### ISSUE TITLE
UI Flickering in the entire App

### ISSUE THREAD

**Issue by ericwaetke** [ciderapp/Cider-2#656]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.1.91

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 8:59:57 PM

### Describe the Bug

When interacting with the UI, certain elements flicker, making interacting with them almost not possible
[Screencast from 2024-06-02 14-05-04.webm](https://github.com/ciderapp/Cider-2/assets/8260492/21724f98-dbda-4809-b54e-d5d148b26c9e)

### Steps to Reproduce

Just open the app and hover over stuff I guess.

I've just recently switched from windows to NixOS, so i guess that would make it reproducable?

I'm on NixOS 23.11 with Gnome
![image](https://github.com/ciderapp/Cider-2/assets/8260492/89aca12e-ef94-4373-a0f7-ac32a5ff37c9)

This is my Nix File I used to install Cider. (got this from @sapphic.moe on Discord)

```nix
{ 
  appimageTools,
  lib,
  ...
}:

appimageTools.wrapType2 rec {
  pname = "cider";
  version = "2.4.1";
  name = "${pname}-${version}";

  src = /home/eric/Music/Cider/Cider-linux-appimage-x64.AppImage;

  extraInstallCommands = let
    contents = appimageTools.extract { inherit name src; };
  in ''
    mv $out/bin/${name} $out/bin/${pname}

    install -m 444 -D ${contents}/${pname}.desktop -t $out/share/applications
    substituteInPlace $out/share/applications/${pname}.desktop \
      --replace 'Exec=AppRun' 'Exec=${pname}'
    cp -r ${contents}/usr/share/icons $out/share
  '';

  meta = with lib; {
    description = "A new look into listening and enjoying Apple Music in style and performance.";
    homepage = "https://github.com/ciderapp/Cider";
    license = licenses.agpl3;
    platforms = [ "x86_64-linux" /* ... */ ];
  };
}
```

**Comment by coredev-uk** [comment]
As Cider is not officially supported on NixOS, we cannot help. I suggest looking into flickering with electron apps on Nix. If you are using wayland, this can be problematic as electron apps can be a bit funny in those circumstances. I cannot help you any further than this, sorry.
