### ISSUE TITLE
Show complete album

### ISSUE THREAD

**Issue by Ariana-temp** [ciderapp/Cider-2#658]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

2024-05-30, 3:04:36 a.m.

### Describe the Bug

Every album shows the "show complete album" button regardless if the full album is already added to library and visible or not. When clicking the show complete album button, any animated album art then becomes active. Before clicking this button, animated album covers do not play.

### Steps to Reproduce

Select an album in your recently added that you can confirm has an animated cover, insure the full album has been added to library, check for "show complete album" button. Click this button and check if animated cover is now playing or remains static

**Comment by coredev-uk** [comment]
The album view in Recently Added is a library view which does not have animated artwork due to the way Apple have it set up. When clicking show complete album it will take you to the 'catalog' version of the album which contains all the data for animated artwork. This is just the way that recently added works.
