### ISSUE TITLE
"Last Playlist" upon Right-Click of song Appearing as "undefined"

### ISSUE THREAD

**Issue by sudo-thoth** [ciderapp/Cider-2#659]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 23.5.0

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 3:00:03 PM

### Describe the Bug

"Last Playlist" upon Right-Click of song and within the "add to last playlist, <song name>" the song name appears as "undefined". So It appears as "Add to Last Playlist, undefined". Only occurs after repeating "add to last playlist" a few times in repetition on multiple unique songs. 
![image](https://github.com/ciderapp/Cider-2/assets/109883548/d05ff8df-8528-4266-ac30-8434d5bb1efb)

### Steps to Reproduce

How to invoke runtime error. Add a song to a new playlist via the right click->search for non-existent playlist-> click create playlist. Song A added to New playlist named "Playlist 1". Upon right click on a new song->add to last playlist appears as "Add to Last Playlist, Playlist 1". now Song B added. Now upon right clicking on a new song-> add to last playlist appears as "Add to Last Playlist, undefined" but the click action event still responds as expected adding the song to the correct "last playlist".

Hopefully this is well explained. 

### Anything else?

Also waiting on the Airplay Feature to be improved but thanks for everything else.

**Comment by coredev-uk** [comment]
Very strange issue, I cannot replicate this. I will add an additional check to not display the recent playlists if there is no name for the playlist found. Other than this, as I cannot replicate it I cannot do much more.

As for Airplay, this is a very under worked feature that has essentially been abandoned since the main developer who worked on it has left and the rest of the team are focused on other areas of the app. Hopefully we can revisit it soon and one of us can get a grasp and understand it.

**Comment by sudo-thoth** [comment]
Here is a video showing me refreshing the playlists in cider. Then showing all my playlists in Apple Music vs Cider records of them. It stopped at the Playlist “recorded”, perhaps it reached a limit or max amount of playlists displayed in the sidebar. Please update this to be unlimited so I can easily access all my playlists.

https://github.com/user-attachments/assets/bc41db60-f7cf-4d9b-ad65-3242051aa2cb
