### ISSUE TITLE
[Feature] Keep cider screen position on restart.

### ISSUE THREAD

**Issue by HyPeRXKo** [ciderapp/Cider-2#662]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

W11

### Describe the Bug

Everytime i open cider, i need to move and resize it to my third screen, it's a bit annoying.

### Steps to Reproduce

Change position and size of cider, quit and restart it.

### Anything else?

Thanks for the app! it's a godsend when trying to move from spotify :)

**Comment by coredev-uk** [comment]
Feature requests are handled purely in discord. It is stated clearly on the issue template.
