### ISSUE TITLE
Can't add song/album to "Play Next" when listening to "My Station" (Or any station in general)

### ISSUE THREAD

**Issue by NeymarGamerYT** [ciderapp/Cider-2#663]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 3:04:36 AM

### Describe the Bug

On the iOS (or normal Apple Music Client) when you're listening to any Station, you can add songs or albums to the queue via the "Play Next" or "Play Later" buttons, but in Cider it doesn't seem to work.
When i add any song to "Play Next", it doesn't shows on the queue and in fact, it doesn't plays afterwards. It just plays the next song on the station.

The issue has prevailed since i've tried Cider for the first time in v2.3.1.

### Steps to Reproduce

1. Pick a Music Station (i.e "My Station" or "Discovery Station")
2. Add any song or album to queue via the "Play Next" or "Play Later" button

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/41163060/cf36e5ed-8f2b-461f-83a3-ff50c99e8056)
![image](https://github.com/ciderapp/Cider-2/assets/41163060/b2464118-f884-4ec0-98e8-b53afcd22a8a)
![image](https://github.com/ciderapp/Cider-2/assets/41163060/947ef18c-9615-41ec-93f0-75a7cc166ace)
![image](https://github.com/ciderapp/Cider-2/assets/41163060/a3e31424-89b6-4e85-8827-278055f34ac4)

**Comment by coredev-uk** [comment]
Since a station is considered a different kind media that does not have a queue like standard albums/playlists, this cannot be done as its a limitation with MusicKit. The only way in which this could be done is re-queueing the current song outside of a playlist and adding the chosen song to the queue, which would be janky and would not be seamless. Following in AM web, I will grey the option out when a station is playing.
