### ISSUE TITLE
Can't add songs to shared playlists

### ISSUE THREAD

**Issue by speedy1804** [ciderapp/Cider-2#664]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30.5.2024, 09:04:36

### Describe the Bug

I have the problem that I cannot add songs to shared playlists, although the message appears that the song has been successfully added.

### Steps to Reproduce

Take a song, try adding it to a shared playlist.

**Comment by coredev-uk** [comment]
Shared playlists are not currently supported by the MusicKit API, thus we cannot support it.
