### ISSUE TITLE
Cider does not download Apple Music Smart Playlists

### ISSUE THREAD

**Issue by RobinBlackguard** [ciderapp/Cider-2#665]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.8.0-35-generic

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 2:59:57 PM

### Describe the Bug

The current version of Cider for Apple Music does not download any of my smart playlists.

### Steps to Reproduce

I open the app after having signed into my Apple Music account.  I check the playlists on the left hand side and see that only normal playlists are present, not the smart playlists.

**Comment by coredev-uk** [comment]
It is clearly documented in our feature list that smart playlist are not available due to api limitations. Apple doesn’t provide us with a way to fetch smart playlists thus they are not in the app.
