### ISSUE TITLE
Silent Crash on SteamDeck in GameMode

### ISSUE THREAD

**Issue by ArnePret** [ciderapp/Cider-2#666]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

SteamOS 3.5.19

### Describe the Bug

When Cider is launched from Desktop mode everything works just fine.
When Cider is launched from Game mode a black screen appears and after half a minute the program is closed automatically.

### Steps to Reproduce

Download .tar.gz from itch. (Version 2.4.0)

Extract and add /opt/Cider/cider to steam.

Run /opt/Cider/cider in desktop mode, log in with apple.
Everything should work here.
(Updating to 2.4.1_0 doesn’t change the behavior)

Go to game mode and run cider from there. Just the Steam Logo with a blue circle around it appears.

**Comment by ArnePret** [comment]
Settings: Advanced -> Optimize for Steam Deck
And
Settings: Experiments -> Enable Game Mode
Don’t change the behavior.

**Comment by cryptofyre** [comment]
Add "--no-sandbox" in the launch arguments in SteamOS.
