### ISSUE TITLE
Low Quality Animated Artwork

### ISSUE THREAD

**Issue by lexog17** [ciderapp/Cider-2#668]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows  11

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/5/2024, 9:04:36

### Describe the Bug

When starting the immersive view, I select the Sonoma layout of the Artwork, thus occupying the entire screen (a super interesting and cool option, thanks for that). But the problem comes with the playback of the animated artwork. Let's say the Artwork is a GIF. The moment it starts playing, it looks super blurry (which is understandable since it’s the first time it loads). After 2 or 3 seconds, the GIF loads at the desired maximum resolution (which can be changed in settings, I have it set to 8). But here comes the problem; when the GIF ends and starts to play again, it returns to its minimum resolution (blurry), which makes the immersive view (with animated artwork) a bit uncomfortable. I understand that this is normal due to the resolution loading process, but I don’t know if there’s any way to solve this. Anyway, thank you very much, I love this app!

### Steps to Reproduce

1-  Click on Inmersive View on Any album ( important: any album that has animated artwork )

2- Click on settings > Set Style > Sonoma 

3- Return to settings and click on Animated  Artwork ( to Activate it )

4- See the blurry artwork 

After 2 or 3 seconds, the GIF loads at the desired maximum resolution (which can be changed in settings, I have it set to 8). But here comes the problem; when the GIF ends and starts to play again, it returns to its minimum resolution (blurry

**Comment by coredev-uk** [comment]
See https://github.com/ciderapp/Cider-2/issues/627
