### ISSUE TITLE
Display driver stops functioning when playing music (only sometimes)

### ISSUE THREAD

**Issue by Thundernerd** [ciderapp/Cider-2#671]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 9:04:36 AM

### Describe the Bug

Sometimes when I start to play music my display driver breaks. This does not happen consistently but it only happens when playing music with Cider.

### Steps to Reproduce

1. Open Cider
2. Play music
3. Notice display driver stops working

### Anything else?

The only way I can seem to resolve this is by unplugging my screen and plugging it back in. Afterwards it functions like normal again and I can play music as normal.

I've tried the ctrl+win+shift+b to reset my video driver but that unfortunately doesn't seem to make a difference.

**Comment by Thundernerd** [comment]
Is there any way for me to provide a log file? I just had it happen again and would love to provide more info if possible.

**Comment by coredev-uk** [comment]
Run nvcleanstall (assuming you have an nvidia graphics card) / or remove your graphics drivers and perform a clean install. Issues like this tend to be a broken driver.

**Comment by Thundernerd** [comment]
I did a clean install through nvcleanstall and the issue still happens. Is there any way for me to provide a log file of sorts? Also note that this is the only software where this issue happens. I haven't had any graphical issues whatsoever aside from this (that I'm aware of)

**Comment by coredev-uk** [comment]
There is not a huge amount I can do, I do not experience this nor do I use windows. To my knowledge, there is not any display logs we can retrieve on Windows, the application log may be beneficial but getting that would involve you launching the application from the command line.

We are working on a new backend for Cider on Windows, so all I can recommend is sit tight until it's ready, or I can ask another member of the team to help you out further.

**Comment by Thundernerd** [comment]
Thanks for the reply. I'll wait for the new backend to arrive! (I'll still keep using it though).

Should I close this issue?

**Comment by coredev-uk** [comment]
Leave it open, close it if the issue clears up with the new backend.

**Comment by Thundernerd** [comment]
Is Cider 2.5.0 considered to have the new backend? I'm on commit 3baa7bbffd664e9dfcd1847204c49a8b2eee5962.
Unfortunately it still seems to happen :(

**Comment by coredev-uk** [comment]
It is. I'm sorry to hear it's still happening. At this stage the only other alternative is either contact Microsoft support or a full reinstall. Considering you seem to be the only person experiencing this, we cannot much more.

**Comment by Thundernerd** [comment]
Thankfully it doesn't happen every time I use Cider, so I'm not going to reinstall Windows!
I'll close this issue, thanks for the assistance!
