### ISSUE TITLE
Some lyrics miss the blanking between words

### ISSUE THREAD

**Issue by freeqimmy** [ciderapp/Cider-2#672]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

2024/5/30 15:04:36

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/20817726/c6e5e51b-9ece-49a7-bb80-bff5eb59ade1)
The lyrics shown in official Apple Music app and properties is all good.
[UPDATE] After I turned off the Sing lyrics, it appears well.

### Steps to Reproduce

By now this is the only song I've found which can produce this bug.

**Comment by freeqimmy** [comment]
keep this alive

**Comment by freeqimmy** [comment]
First of all, thank you for your response in time.
However, it seems this issue hasn't been solved. In Cider 2.5.0 Beta 4, the latest version available, the lyrics shown in immersive mode when Sing lyrics option is active still looks like this:
![image](https://github.com/user-attachments/assets/6e0e3e0e-3a81-4682-9937-9be0c641138b)
In another song in this EP, similar issue happens:
![image](https://github.com/user-attachments/assets/fdccd9e3-da5c-4014-a003-3c38d355899a)
By now I think there might be some problem with the original lyric source, or it could be the strategy in Cider's frontend design, I cannot be sure but would like to help. If it's convenient, could you give me some clues where I can collect the log files? @coredev-uk 
I love Cider as always, again, thanks so much for creating this marvelous client of Apple Music.
 #683 I see this issue is fixed

**Comment by coredev-uk** [comment]
I did test this myself and did not get the behaviour you are experiencing. What source are the lyrics coming from and do you have any unique settings/themes?
