### ISSUE TITLE
Discord RPC doesn't work if discord is installed through flatpak

### ISSUE THREAD

**Issue by joeyjooste** [ciderapp/Cider-2#674]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

flatpak

### Operating System

Void Linux

### Describe the Bug

Rich Presence doesn't connect when both apps are installed through flatpak (I suspect it's because discord is).

Here is a link to a simple fix for it: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

### Steps to Reproduce

Install both apps from flatpak.
Test if rich presence is detected in discord.

**Comment by coredev-uk** [comment]
Cider 2 is not officially supported in flatpak, and the nature of flatpak is to sandbox apps, which prevents the applications from communicating with each other over rpc. The only version of cider on flathub is cider 1 which has been archived and is no longer supported.
