### ISSUE TITLE
Songs playing with double audio

### ISSUE THREAD

**Issue by GhostyOrc9** [ciderapp/Cider-2#675]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Windows Store

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/05/2024, 08:04:36

### Describe the Bug

When I play a song it doubles the audio with a very slight delay, so I'm hearing the song twice.

### Steps to Reproduce

It happens when I play any song.  I just downloaded Cider from the windows store, then I logged in and selected the 3rd option down when choosing the layout.  I opened my playlist and changed the sort order a couple of times and now everything plays in double.

### Anything else?

https://github.com/ciderapp/Cider-2/assets/113845839/49609538-6d7e-46e9-8193-ec98c1e9401d

**Comment by Xepois** [comment]
seems to be an issue with cider's audio lab, turning off adrenaline processor fixes it.

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/Izanagi/commit/6efdf97e2b6b53bb393c85260fc563b2073de207

Will be available in 2.4.2.
