### ISSUE TITLE
No Audio Playback from Cider (not even shown in Volume Mixer on any output-device)

### ISSUE THREAD

**Issue by thedogmaniac** [ciderapp/Cider-2#677]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/05/2024, 09:04:36

### Describe the Bug

Sometimes when I open Cider, there is absolutely no sound output on any audio device I have connected.
When I go to the Windows Volume Mixer, it doesn't even show up in there. I looked through every output-device I have, and it doesn't show up. This seems to happen randomly, I can't reproduce it on command. Only a computer restart fixes it. Only restarting Cider does not.
But this only happens with Cider. Every other Program, Game, Music-Player works fine. 

### Steps to Reproduce

1. Start Computer (Windows 11)
2. Check Audio Device for Sound-Output
3. Test Audio Output with Windows Volume Mixer.
4. Open Cider (no sound output)
5. Check Windows Volume Mixer to check if Cider is playing on another audio device
6. Cider is nowhere to be found in the volume mixer, checked every single audio device
7. Restart PC
8. Cider plays back sound again and shows up in volume mixer.

**Comment by thedogmaniac** [comment]
Update, it now suddenly works again without restarting my PC. Didn't know what exactly caused it, but it happened after I randomly clicked on the progress bar during a song. 
The missing sound still happens on my PC, but I guess after a few restarts it randomly does work. 
Was about the 4th restart of Cider and then clicking in the progress bar.
If I can narrow down the behaviour, I'll write here.

**Comment by coredev-uk** [comment]
Probably down to a webview2 inconsistency, just clean install the application if it happens again.
