### ISSUE TITLE
Alt-Menu bar is always visible in white

### ISSUE THREAD

**Issue by Chrispycode** [ciderapp/Cider-2#679]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Manjaro Gnome Wayland

### Describe the Bug

When enabling native window controls on gnome the Alt-Menu bar is always present and won't go away.
Only workaround I found was turning immersive mode on and off, then the  bar disappears.

### Steps to Reproduce

1. Go to settings and enable native window controls 
2. restart cider 
3. White bar appears
![image](https://github.com/ciderapp/Cider-2/assets/22537998/101dc20e-8f78-441d-9853-5dce1ba36fc7)

**Comment by Chrispycode** [comment]
The issue disappeared with the latest update's

**Comment by coredev-uk** [comment]
@Chrispycode was this fixed using the experimental builds, or was an update done through the in-app updater?
If the update was done through in-app this would most likely be an external factor.

**Comment by Chrispycode** [comment]
It was fixed using the in-app updater
