### ISSUE TITLE
Volume slider shows "-Infinity" (when the slider is set to 0) when dB SPL display is enabled.

### ISSUE THREAD

**Issue by ZEUSGMJ** [ciderapp/Cider-2#680]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/05/2024, 09:04:36

### Describe the Bug

Probably not really a high prio bug, but something that can be looked into(?)
A small UI issue, which I found when playing around the app. I had the dB SPL display enabled, as shown below:
![image](https://github.com/ciderapp/Cider-2/assets/42777277/01ef2940-06eb-4273-8395-e99bf43dcc35)

And noticed that when the volume slider is set to 0, it would show as "-Infinity".
![image](https://github.com/ciderapp/Cider-2/assets/42777277/47662662-a9c8-47a9-bc37-3d4f0d9dbfcd)

Hope this helps!

### Steps to Reproduce

1. Go to settings.
2. Click on "Visual" tab.
3. Scroll down and click on "Advanced".
4. Scroll down, while "Advance" section is expanded, and enable `dB SPL Display`.
5. Close settings, and play any music.
6. Set the slider to 0, and you'll see instead of saying 0 dB SPL, it'll be `-Infinity`.

**Comment by coredev-uk** [comment]
Fixed in 2.4.2
