### ISSUE TITLE
Maximizing window causes segfault

### ISSUE THREAD

**Issue by ghost** [ciderapp/Cider-2#681]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.5.0-41-generic

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/31/2024, 1:59:57 AM

### Describe the Bug

When I maximize the Cider window, segmentation fault error happens. It does not happen in full screen immersive.

### Steps to Reproduce

Maximize the window and the app crashes immediately

**Comment by coredev-uk** [comment]
What desktop environment and distro are you using?

**Comment by nluziaf** [comment]
I'm using ZorinOS with Gnome DE

**Comment by coredev-uk** [comment]
Surprising to see this on gnome, have you got any unique setting on in regards to the window (E.g. native window frame, close button minimize etc.)

**Comment by nluziaf** [comment]
Apparently it happens in X11. In Wayland, I can't fullscreen Cider (except in Immersive Mode) because I don't have window controls in it.

**Comment by coredev-uk** [comment]
Deleted user...
