### ISSUE TITLE
Sing lyrics words are sometimes incorrectly broken up

### ISSUE THREAD

**Issue by Erinaaaaaaa** [ciderapp/Cider-2#683]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/05/2024, 09:04:36

### Describe the Bug

Sometimes, the words are split in half across two lines on Sing lyrics, when that should not be the case
![image](https://github.com/ciderapp/Cider-2/assets/20820425/50a8ffb2-848c-4d80-ad35-ba0fa7cd2e31)

### Steps to Reproduce

Anywhere Sing lyrics are visible - in my case, in Immersive mode

- Be in Immersive Mode
- Play a song with Sing lyrics - for example, Dua Lipa's _Illusion_

### Anything else?

Could be related to #672, but I'm not sure hence the separate issue.

**Comment by coredev-uk** [comment]
Unfortunately this word is split, meaning the timings for the word are split across several individual components, making this a lot more annoying, this may take a bit longer to do.
