### ISSUE TITLE
cider is shown as chromium in volume mixers

### ISSUE THREAD

**Issue by Chrispycode** [ciderapp/Cider-2#684]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Manjaro Gnome Wayland

### Describe the Bug

Playback is identified as Chromium in volume mixers like pavucontrol on linux. This can be really confusing if using another electron app.

### Steps to Reproduce

1. Start Music
2. go to volume mixer application like pavucontrol
3. Cider is show as Chromium

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/22537998/e6bb9c80-7490-4f3b-9be0-b5d4c1cbd1dd)

**Comment by AW1534** [comment]
This happens to me on debian gnome x11

**Comment by coredev-uk** [comment]
Cider runs on Electron which is chromium. This is unfortunately how Electron functions with the media interface, there is not much we can do.

**Comment by Chrispycode** [comment]
ok thank you, I also found a issue on the electron github for this
https://github.com/electron/electron/issues/27581
