### ISSUE TITLE
Arm version cannot download

### ISSUE THREAD

**Issue by junebkk73** [ciderapp/Cider-2#687]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

 Microsoft Store

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

2024. 5. 30. 오후 4:04:36

### Describe the Bug

I heard there have arm version of cider preview, but through microsoft store, download only x64 version, 
How can I download arm version of cider?

### Steps to Reproduce

1. from galaxybook 4 edge which is arm version of windows.
2. download from microsoft store.
3. and it shows in task manager as x64

**Comment by cryptofyre** [comment]
Waiting for dotnet to hit stable, doing it on tauri is a pain in the ass in a msixbundle.

**Comment by cryptofyre** [comment]
Included in the latest 2.5.x Microsoft Store releases.
