### ISSUE TITLE
Songs arent available 

### ISSUE THREAD

**Issue by kubszot** [ciderapp/Cider-2#697]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30.05.2024, 09:04:36

### Describe the Bug

I have a songs added to my playlist and i just figured out that they are available to listen. First i thougth that they have been deleted (ye shit) but i checked on my phone and in native apple music app and nothing seemed to be wrong. I readded song to the playlist using cider (when i open album i can listen them all) few of them were still unavailable to play.
![image](https://github.com/user-attachments/assets/f9102ddf-c3b1-40df-854f-ced050f6474d) <- before readding
![image](https://github.com/user-attachments/assets/51f9f1e0-19bf-4348-a2d9-ef828d6aff70) <- after, current status

### Steps to Reproduce

Described in bug :)

**Comment by kubszot** [comment]
UPDATE: I don't know what happend but it seems the music is now available. I was 3 days away from PC and when i logged it and checked the cider to see is that issue still happening. To my surprise everything is back to normal. I did nothing to cider i just added a song to playlist a few days ago but i am not sure did it changed anything then. 
![image](https://github.com/user-attachments/assets/9ce8d0e2-b6ba-48b9-a1a5-b3bc1287ceda)

**Comment by cryptofyre** [comment]
Apple may have done some backend fixes to this, we don't really know why or what causes this and there isn't very much we can do about it as obviously we are not Apple in this situation.

Next time it does happen I highly recommend using the Feedback Hub app on your phone, or directly reporting it via this URL. https://www.apple.com/feedback/apple-music.html

Glad everything is working out for you now though!
