### ISSUE TITLE
App freezes when song changes in background (arch linux)

### ISSUE THREAD

**Issue by marcusleonas** [ciderapp/Cider-2#698]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [x] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Arch

### Describe the Bug

The app constantly freezes and becomes unresponsive when running in the background, then processes my request after a few mins. After a bit of playing around, i found the bug occures when the song changes in the background.

### Steps to Reproduce

1. Shuffle a playlist
2. let the song end in the background

**Comment by coredev-uk** [comment]
Hello!

Apologies for the delayed response. What playlist were you queuing and what desktop environment are you running?
