### ISSUE TITLE
Pressing CTRL+P sometimes triggers a print and locks the app

### ISSUE THREAD

**Issue by jae1911** [ciderapp/Cider-2#699]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

30/05/2024, 10.04.36

### Describe the Bug

Sometimes, when pressing CTRL+P to trigger the immersive mode, the Windows Print popup will appear instead. Upon closing that window, sometimes, nothing on the app can be clicked anymore.

### Steps to Reproduce

1. Click to modify volume
1. Press CTRL+P (sometimes, CTRL+SHIFT+P will be needed)
2. The Print window opens, close it
3. Notice how nothing can be clicked in the app

**Comment by coredev-uk** [comment]
The default ctrl+p binding has been removed in favor of ctrl+o for immersive.
