### ISSUE TITLE
沉浸模式下快捷设置字体超出

### ISSUE THREAD

**Issue by TonyKingWJX** [ciderapp/Cider-2#700]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 

### Commit Hash

e102963f817ab90300178d54e93257f811871113

### Connect Instance ID

not-logged-in

### Build Timestamp

2024/7/10 20:37:52

### Describe the Bug

最新2.5.0.0沉浸模式下设置字体超出，如图
![image](https://github.com/user-attachments/assets/5cffa30d-8f71-4e39-8b0c-af9596285f45)

### Steps to Reproduce

在应用窗口未全屏情况下打开沉浸模式，再点击最左上角的图标，background type字体超出
![Uploading image.png…]()

**Comment by coredev-uk** [comment]
Support is only given in English.
