### ISSUE TITLE
Broken onboarding 

### ISSUE THREAD

**Issue by ldstevens** [ciderapp/Cider-2#701]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 23.5.0

### Commit Hash

d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7

### Connect Instance ID

not-logged-in

### Build Timestamp

5/31/2024, 4:03:23 AM

### Describe the Bug

Trying Cider for the first time, but lots of bugs on first run:
— Sign In with Apple doesn't appear to work at first (returns to log in screen).
— Layout & light/dark preference not respected.
— Switching from dark to light mode is broken (works for the preferences panel, but not the player, where text turns black but background in sidebar stays black).

Will continue testing ✌🏻

### Steps to Reproduce

First run of app.

**Comment by cryptofyre** [comment]
@booploops ^ I myself have noticed this, been having to click bypass after signing in for a while now, could be revisited before 2.5's launch.
