### ISSUE TITLE
FM radio station playback fails silently

### ISSUE THREAD

**Issue by nicholasdehnen** [ciderapp/Cider-2#706]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 10

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

2024-05-30, 3:04:36 a.m.

### Describe the Bug

Trying to play any "real" radio stations fails silently.
- Clicking on the play icon does nothing
- Double-clicking changes the currently playing song to the station, but immediately stops playback.

Likely related to #262, which was closed due to issue tracker consolidation.

Apple Music Web shows a dialog box with message: `Not Available on the Web - You can listen to this in the Apple Music app.`
Cider should show a similar message and list this as a limitation if there is no way to make this work.

### Steps to Reproduce

1. Search for "NPR Illinois"
2. Try to play first result under "Stations"

**Comment by coredev-uk** [comment]
Radio's are not supported through MusicKit, I'm not sure why they are served in the stations results, but this is a limitation from Apple, with playback only support through their proprietary applications.

**Comment by nicholasdehnen** [comment]
I am totally fine with this not being implemented - but maybe Cider can show a message (like it apparently used to!), that radio stations can't be played? The current situation where there is no feedback at all is somewhat confusing.

The [website](http://archive.today/2024.08.20-163231/https://cider.sh/learn-more) also lists not limitations to Cider - I only found this out after purchasing the app. I would appreciate more transparency regarding this, the feature comparison table on the website could be easily extended to indicate that there is no radio support on both Cider, and AM Web.

**Comment by coredev-uk** [comment]
I'll have a look into maybe hiding it or enabling the popup, not sure how it worked previously with the dialog popup. If the item does not have any unique attributes it may not be possible to disable/hide the item.
