### ISSUE TITLE
Wrong animated album artwork

### ISSUE THREAD

**Issue by actual-boring** [ciderapp/Cider-2#708]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

5/30/2024, 9:04:36 AM

### Describe the Bug

The animated album artwork for the album "This is how tomorrow moves" by Beabadoobee is wrong.

### Steps to Reproduce

1. Open the personalized home page or the artist page.
2. Click on the album called "This is how tomorrow moves".
3. Observed the wrong animated artwork.

![image](https://github.com/user-attachments/assets/d09ebf6c-6bb4-45b7-8905-7c2751b30f43)
![image](https://github.com/user-attachments/assets/ac0ae00c-cbdc-4a47-8d4d-b417b52bc9b5)

### Anything else?

When opening up the properties for the album that wrong artwork is absent.

**Comment by coredev-uk** [comment]
This is the data that Apple returns. I have just checked this myself. Either the artist set the animated artwork that way or Apple screwed up. If you really want it disabled, you can disable the extended editorial layout in Settings > Visual > Content Preferences. Feel free to report it to Apple on their [feedback](https://www.apple.com/feedback/apple-music.html) page.
