### ISSUE TITLE
Player defaults to first song when trying to play a video from album

### ISSUE THREAD

**Issue by ironman9356** [ciderapp/Cider-2#709]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows11

### Commit Hash

098a60e1301a58f734d21064b2a2bcfc9b4b1520

### Connect Instance ID

not-logged-in

### Build Timestamp

1717052676223

### Describe the Bug

When you try to play a music video in an album (usually in the lower end of the album) it defaults to the first song in the album
I was told it is not possible yet to watch music videos via the album page, but when you click on a music video in an album instead just playing the audio like it does/is supposed to.

### Steps to Reproduce

1. Open an album with music videos in it (preferably at the end) for example: thank u, next (Bonus Videos) by Ariana Grande
2. Scroll down to the end of the album
3. Click on one of the music videos

Expected result:
Video plays. If video is not available the audio is played

Actual result:
Album starts from the first song

**Comment by unquenchedservant** [comment]
Should note this appears to be moreso than just related to videos. 

Trying to play a specific song in an album, video or audio, results in the first song being played if queued instead of play + clear

**Comment by ironman9356** [comment]
Bump. I still have this issue on version 2.5.1_1 (latest stable)

**Comment by ironman9356** [comment]
Bump
Current version 2.5.2_5 
Bug still exists

**Comment by ironman9356** [comment]
Bump
V2.5.3_3 issue still persists

**Comment by Ayush-Afre** [comment]
Bump 
In v2.5.4_0 , albums with videos in them dont play at all

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/citadel/commit/d9ad574cb123ed1804396b97033c130dce5ceb1e
Should be available in the next experimental builds and in stable later this month.
