### ISSUE TITLE
Pressing ctrl + p does not open the immersive mode.

### ISSUE THREAD

**Issue by ismaelosuna7824** [ciderapp/Cider-2#715]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

windows 11

### Describe the Bug

Pressing ctrl + p does not open the immersive mode.

### Steps to Reproduce

Pressing ctrl + p

**Comment by svalencia014** [comment]
Same here

**Comment by booploops** [comment]
Default binding in an update will change to `CTRL+O`. For technical reasons we can no longer use CTRL + P.

You can change this keybinding ahead of time in the current version in General / Keybindings
![image](https://github.com/user-attachments/assets/0058c0fa-2ace-4d28-8d1d-cc6aa9be8aad)
