### ISSUE TITLE
songwriters appear in the lyrics

### ISSUE THREAD

**Issue by metinthumbsup** [ciderapp/Cider-2#717]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

mc

### Operating System

windows 10

### Describe the Bug

In immersive mode, the song's writers appear at the end of the lyrics as if they were lyrics
![p2](https://github.com/user-attachments/assets/8a4d9263-06f4-4802-bacd-a3d01a3d3f0f)
![p1](https://github.com/user-attachments/assets/f157fe96-24a4-4f6c-80ba-d3f877846207)

### Steps to Reproduce

1. i switched to immersive mode
2. opened the lyrics

**Comment by coredev-uk** [comment]
Fixed in next release.
