### ISSUE TITLE
Song in library don't load

### ISSUE THREAD

**Issue by w00dy1981** [ciderapp/Cider-2#718]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

17/08/2024, 7:00:06 am

### Describe the Bug

when in library mode song view doesn't load any songs however Artist and album work

![image](https://github.com/user-attachments/assets/45ab645a-ab82-4bb7-b9b6-97dbc99a3d9e)
![image](https://github.com/user-attachments/assets/53339c56-d4c9-414b-8056-239304608dfe)

![image](https://github.com/user-attachments/assets/3edc1539-fa08-40fd-b831-36ee98c63b2a)

### Steps to Reproduce

1. clicked on songs, blank screen
2. clicked on Artist tab, click an artist then an album. Songs showed.
3. clicked albums view, clicked an album. songs on that album showed.
4. went back to songs view, still no songs loading. the app has been open for hours.
5. have clicked refresh multiple times.

### Anything else?

No that's all. Thank you for your great app!

**Comment by cryptofyre** [comment]
Update to the latest hotfix in the "..." menu and under "Updates"

And install the AirPlay dependency in Settings > Experiments if that doesn't fix it otherwise.

**Comment by w00dy1981** [comment]
> Update to the latest hotfix in the "..." menu and under "Updates"
> 
> And install the AirPlay dependency in Settings > Experiments if that doesn't fix it otherwise.

![image](https://github.com/user-attachments/assets/fd43c047-c6d8-448c-9b0f-5102b1ae2115)
![image](https://github.com/user-attachments/assets/7563140e-aaf0-42fc-b24c-395e52734cd7)
![image](https://github.com/user-attachments/assets/f1518828-a06c-40ca-974d-699cda8bf7fa)
Hey there, I just checked and have both the latest patch and airplay turned on. Library songs still don't show up

**Comment by w00dy1981** [comment]
An update this. I've just installed on my work pc which is on Windows 10 using the airplay setting turned on.

I turned off the setting and my library songs disappeared. I enabled airplay again my songs won't show up again.

**Comment by coredev-uk** [comment]
What behavior did you experience with Apple Music web?

**Comment by w00dy1981** [comment]
Songs loaded as normal. 

Since the last update songs seem to be loading consistently across devices and platforms.
