### ISSUE TITLE
animated artwork

### ISSUE THREAD

**Issue by Nfans-collab** [ciderapp/Cider-2#719]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft store

### Operating System

Windows 

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

8/17/2024, 5:00:06 AM

### Describe the Bug

i can see the animated artwork on my pc discord and my phone's discord but my friends can't see the artwork at all

### Steps to Reproduce

play a song that has animated artwork
go on discord and check your activity to see if the artwork are being animated
check your friend's phone's discord and go to your discord profile > activity to see if the artwork are being animated

### Anything else?

that's it

**Comment by cryptofyre** [comment]
This isn't a problem with Cider itself, you'd need to report this to Discord.
