### ISSUE TITLE
I hope to complete the function string so that our users can help with translation.

### ISSUE THREAD

**Issue by jay900604** [ciderapp/Cider-2#722]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord 

### Operating System

Windows 11

### Describe the Bug

We hope to complete most of the functional strings currently appearing in Cider 2.5.0 so that our users can help with translation and localization.

Many features are still only available in English, making them unfriendly to users of other languages.

### Steps to Reproduce

Many features are still only available in English, making them unfriendly to users of other languages.

**Comment by coredev-uk** [comment]
https://translate.cider.sh

**Comment by jay900604** [comment]
The translation platform is 100% ready, but there are still many functions in Cider that cannot be translated. The URL you gave me still does not solve my problem.

**Comment by coredev-uk** [comment]
We are working on adding translations to all new features, but this will take time. The platform I linked to is where you can translate stuff when it is available. Experimental features will not be translated. 

Please bear in mind that we are a small team and we cannot always provide translations as quick as possible for everything. We are still working off a in areas pre-beta codebase with translation going back to Cider v1.

**Comment by jay900604** [comment]
I hope you can spend more time on translation, because the window is too long, and you can indeed use advanced and experimental functions for now, but please make up for other aspects. After all, your Cider is already a paid software.

**Comment by coredev-uk** [comment]
The developers are not paid. We are not Apple, and do not have any experience developing ‘perfect’ software. We are comprised of volunteers putting their own time into it. So please do not expect everything to be perfect

**Comment by jay900604** [comment]
I am not blaming, I just hope that by adding relevant strings, this community can operate more perfectly. After all, Cider is a software that is paid for, and I have always provided translation help for Cider's Chinese language.
