### ISSUE TITLE
Pressing shuffle on my playlist just plays it

### ISSUE THREAD

**Issue by Vlackmaybe** [ciderapp/Cider-2#723]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

Windows 

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

8/16/2024, 4:00:06 PM

### Describe the Bug

When i press the shuffle button on my playlist, it just starts playing the songs from the first track to the last.

### Steps to Reproduce

Click on the shuffle button and it should play it from track one to the last one instead of shuffling

### Anything else?

here's the video of whats happening
https://github.com/user-attachments/assets/5469fb5c-f941-4889-becf-955ff57a835d

**Comment by coredev-uk** [comment]
It will still shuffle it unless you go our of your way to disable shuffle. How it currently works is that it will queue the first song then enable shuffle. This is how Apple made MusicKit queuing.
