### ISSUE TITLE
[2.5.0_2] Light theme borked, playslists missing from sidebar

### ISSUE THREAD

**Issue by M3n747** [ciderapp/Cider-2#724]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.io

### Operating System

Windows 10

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

16.08.2024, 23:00:06

### Describe the Bug

After installing version 2.5.0_2, despite being set to light theme, the main window is grey and the sidebar is completely black:
https://i.imgur.com/cvP4ZP5.png

For comparison, 2.4.0.1 looked like this:
https://i.imgur.com/WprwmM1.png

Also please note that playlists are missing from the sidebar.

### Steps to Reproduce

1. Make sure light theme is selected
2. Install 2.5.0_2
3. Run Cider

**Comment by coredev-uk** [comment]
I suggest resetting your config and doing a clean install. I cannot replicate this on my system.

**Comment by M3n747** [comment]
I launched it just now, it updated to 2.5.1_1 and it looks fine now.
