### ISSUE TITLE
Sing lyrics with double vocals are semi-broken

### ISSUE THREAD

**Issue by DuumXH** [ciderapp/Cider-2#726]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

MacOS Sonoma 14.6.1

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

1723842006643

### Describe the Bug

Songs that have Sing lyrics with double vocals are displayed incorrectly after playing them out.

### Steps to Reproduce

1. Open any song with sing lyrics and double vocals
2. Wait for the lyrics with double vocals to finish
3. Scroll back and see the doubled and broken lyrics.

### Anything else?

Song's writers are also being doubled:

<img width="1512" alt="Screenshot 2024-08-19 at 02 00 07" src="https://github.com/user-attachments/assets/ffd2f251-d531-4064-8004-b9b4e8be8039">

Reference for broken lyrics:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1584672d-1af3-45fd-b2b1-695449b5313a">

**Comment by coredev-uk** [comment]
Fixed in next release
