### ISSUE TITLE
Song in Library but not in apple music - plays but does not scrobble?

### ISSUE THREAD

**Issue by sininspira2** [ciderapp/Cider-2#727]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Describe the Bug

Cider doesn't seem to be scrobbling purchased songs in my library that aren't actually in Apple Music. I've attached a log of playing one of the impacted songs.

### Steps to Reproduce

Played the song from my library, checked Lastfm. Played another song from apple music and lastfm scrobbles correctly.

### Anything else?

[localhost-1724024918617.log](https://github.com/user-attachments/files/16653260/localhost-1724024918617.log)

**Comment by coredev-uk** [comment]
Thanks for providing the log, however it does not appear to contain much useful information. Would confirm that this song is *not* an iTunes uploaded song and post the item attributes.

You can get these from going to settings > advanced enable developer inspect for media items then right clicking on the song that does not scrobble and clicking inspect, then copy all the text you see and post it here.

**Comment by smasimar** [comment]
Sounds like this might be related to the issue I am having with manually added songs:
https://github.com/ciderapp/Cider-2/issues/638

**Comment by coredev-uk** [comment]
Duplicate of #638
