### ISSUE TITLE
White lines on the cider app on windows

### ISSUE THREAD

**Issue by Etx4n** [ciderapp/Cider-2#728]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

Windows 

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

16/8/2024, 15:00:06

### Describe the Bug

There are white lines on the cider app on windows 
![image](https://github.com/user-attachments/assets/be7ffd2d-b6d8-4d5d-a0b9-365f8eb2d8f6)

### Steps to Reproduce

By opening the app

**Comment by coredev-uk** [comment]
Fixed in next release.
