### ISSUE TITLE
Some Songs doesnt play

### ISSUE THREAD

**Issue by teslajammer** [ciderapp/Cider-2#733]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

not-logged-in

### Build Timestamp

20.8.2024, 03:26:53

### Describe the Bug

Some songs arent playing when i klick on them and when i put them in my list they wont play

### Steps to Reproduce

Idk

**Comment by coredev-uk** [comment]
'Steps to Reproduce' I.e. state what songs you cannot play. Simple stating the issue is not that helpful.

**Comment by teslajammer** [comment]
Midnightcity m83 and summertime sadness are the songs that doesnt play so far i dont know ho to reproduce after the latest update from the microsoft store this problem startet

**Comment by coredev-uk** [comment]
Are you playing either of these through your library (I.e playlist / anything under the library section on the side)?

**Comment by teslajammer** [comment]
I just searched them and then if i klick on them to start the song thats playing stops but nothing hapens and if i try to start them over my libary the doenst start aswell

**Comment by coredev-uk** [comment]
Could you do ctrl+shift+I and send a screenshot of what appears in the console when you try to play it

**Comment by teslajammer** [comment]
![Screenshot 2024-08-22 014544](https://github.com/user-attachments/assets/39f24601-eeb2-4272-8a9b-a7d6d0240807)

**Comment by coredev-uk** [comment]
The CONTENT_UNAVAILABLE message usually means either the media you are trying to play is either
1. restricted from your AppleID account's region or
2. your account is setup for restricted playback where explicit music is unable to play. 
Going based off the fact its midnight city you are trying to play (which is not explicit) it will be down to your accounts region.

Have you adjusted any of the Apple Music settings in the General > Apple Music section? If so which ones and please check your account [here](https://appleid.apple.com/account/manage/section/information) to see what region it is set to.

**Comment by coredev-uk** [comment]
If you are using a trial version of Apple Music, this will also cause this behavior.

**Comment by teslajammer** [comment]
its set to germany and on the phone version of apple music it works fine on my iphone i use the pay version of apple music

**Comment by coredev-uk** [comment]
What happened when you tried to play it on the Apple Music website?

**Comment by teslajammer** [comment]
it plays fine

**Comment by lnbxyz** [comment]
Also happening to me, I'm in Brazil and I can't play some albums such as Visions by Grimes or the Severance Season 1 Soundtrack. Both work just fine on my phone or on the official AM Windows app.

**Comment by lnbxyz** [comment]
Changing the region in settings seems to fix it, but it's weird that it's not set to the correct region by default. The setting also has some text saying you probably shouldn't change it, that discourages users from touching it... maybe some UX improvements could be made here.

**Comment by teslajammer** [comment]
![image](https://github.com/user-attachments/assets/776483c4-56a4-4609-8da5-7e30e2971a09)
just switchet from germany to us and back t o germay now it works just fine

**Comment by coredev-uk** [comment]
> Changing the region in settings seems to fix it, but it's weird that it's not set to the correct region by default. The setting also has some text saying you probably shouldn't change it, this discourages users from touching it... maybe some UX improvements could be made here.

Usually not changing it is best. The default value is the one assigned by MusicKit, so its surprising that changing it fixes your issues. I'm thinking it might be a more dynamic value, so I might change the default option to be auto / musickit assigned.
