### ISSUE TITLE
Taskbar media controls look transparent compared to default media controls 

### ISSUE THREAD

**Issue by edge261** [ciderapp/Cider-2#735]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store / Discord

### Operating System

Windows 11

### Describe the Bug

As the title says, the media controls in the taskbar looks transparent... specially if compared to the default media controls...

They look as if those buttons are disabled / nothing is being played. They work, though.

Cider:
![image](https://github.com/user-attachments/assets/c473fa4b-9c94-4618-9d08-8b90ab37491e)

Spotify:
![image](https://github.com/user-attachments/assets/e87948dc-0a81-4df8-8c1e-964e61c5ec02)

Media Player:
![image](https://github.com/user-attachments/assets/2cacb45a-fe20-472a-ab94-2142aeae70d2)

### Steps to Reproduce

Just open the app.

**Comment by edge261** [comment]
bump

**Comment by edge261** [comment]
ping

**Comment by cryptofyre** [comment]
Fixed.

![g8GS8LcjQf](https://github.com/user-attachments/assets/c9adae67-5da3-4d8a-8c93-4a4a0e6aaf3e)

**Comment by cryptofyre** [comment]
Not yet, will come in a different update.
