### ISSUE TITLE
Favoriting/Star a Song in the playback bar still doesn't add song to library

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#736]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 11

### Commit Hash

334672e26adb38a1ad983abcefecf488020909c6

### Build Timestamp

22.8.24

### Describe the Bug

If I'm starring/favoriting OR add(+) a song in the playback bar the current song is not getting added to the library
![image](https://github.com/user-attachments/assets/1674a50a-54fd-4fb4-bb95-f635eb269c26)

### Steps to Reproduce

1. play a song
2. right click on playback bar and press + or star icon

**Comment by UnbreakCode** [comment]
cider locally shows that the track has a star, but it hasn't in AM Web

**Comment by PierreSchwang** [comment]
Can confirm, same issue for me sadly. Not visible in Cider nor native Apple Music apps. Even adding it to a playlist via the playback bar does not seem to work - but it is marked as a favorite.

**Comment by AutumnRivers** [comment]
Same issue here. Cider also won't let you remove it from the local library, despite showing the trash can icon. Doesn't show in library on Cider after refreshing library, and doesn't appear in Apple Music Android app.

**Comment by cryptofyre** [comment]
Fixed in PTB build 10.
