### ISSUE TITLE
cider don't want to read a specific music

### ISSUE THREAD

**Issue by ZachZok** [ciderapp/Cider-2#739]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

Windows 

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

logged in

### Build Timestamp

20/08/2024, 3:26:53 am

### Describe the Bug

For some reason since the cider 2.5 update I can't listen to the song G.O.A.T. by polyphia, I just updated my client and it doesnt want to listen to this song, It juste swap with another one

### Steps to Reproduce

I just go to the polyphia page and click on the song and it just pick a random song

**Comment by ZachZok** [comment]
bump

**Comment by ZachZok** [comment]
bump

**Comment by coredev-uk** [comment]
What behavior occurs on Apple Music web?

**Comment by ZachZok** [comment]
It works everywhere else litteraly, the album is still out on the apple music web, I can listen to it on the mobile app, but still on cider since the first stable version of cider 2.5 I can't listen to the album, for some obscure reason

**Comment by coredev-uk** [comment]
Please check that your storefront setting is set to your current account region. (settings > general > Apple Music)

**Comment by ZachZok** [comment]
It was that, thx
