### ISSUE TITLE
Plugin info does not load at all

### ISSUE THREAD

**Issue by TheFirstComix** [ciderapp/Cider-2#743]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

not-logged-in

### Build Timestamp

2024-08-19, 6:26:53 p.m.

### Describe the Bug

When I click on a plugin to download it, it gets stuck loading and I can't download it.

https://github.com/user-attachments/assets/29d2f40c-41b6-43c4-af6c-a575250c9cf3

### Steps to Reproduce

Go to the marketplace and click on any plugin or theme.

### Anything else?

I have tried restarting my app and I have confirmed my internet is working properly. I am also on the latest version of Cider

**Comment by keis4ri** [comment]
Bumping, [this thread](https://discord.com/channels/843954443845238864/1276790680462819378/1277101843427753985) has encountered the same issue. Initially, Cloudflare DNS was to blame, but was confirmed to not be the issue. Looking at Network tab shows that loading the marketplace takes anywhere from 5-8 seconds to load, and loading individual projects does not load at all, at least on Cider. 
![image](https://github.com/user-attachments/assets/2313fbb8-65b8-4c63-81df-8d8c8cbfc9e1)
This however, does load.
![image](https://github.com/user-attachments/assets/738f159b-03a4-4553-aef9-1abf0d18aea6)
Not sure what's causing this.

**Comment by Jakubk15** [comment]
Bumping, I'm experiencing same issue on Windows 11, Microsoft Store version

**Comment by SocietasEvanescentes** [comment]
Just came here to report the same thing; I can't install Dislike Skipper Plugin or catppuccin mocha theme.

**Comment by elliotjarnit** [comment]
Issue was with an endpoint change. It's fixed now.

**Comment by SocietasEvanescentes** [comment]
Thanks for the swift response and fix 🙂

Hope you have a great rest of your day!
