### ISSUE TITLE
Slow performance on Windows 11 / Not saving some preferences

### ISSUE THREAD

**Issue by Carolis** [ciderapp/Cider-2#744]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11 

### Commit Hash

70fad40dcd8e1b6d6cc0e8979fdf5f52626f5f37

### Connect Instance ID

not-logged-in

### Build Timestamp

8/24/2024, 2:41:40 PM

### Describe the Bug

It's lagging a lot and gets stuck whenever I try to play any music. The music starts way too late

Also, it's not saving the state when I choose to not show the modal showed in the video

I already tried cleaning the app data (shift+clicking the icon) and reinstalling

### Steps to Reproduce

I recorded a short video on YouTube to show what's happening
[https://www.youtube.com/watch?v=lCuz0pHASd4](https://www.youtube.com/watch?v=lCuz0pHASd4)

### Anything else?

System specs
![image](https://github.com/user-attachments/assets/a4930b6d-396e-420c-9b5c-1b8344a73d91)

I also [mentioned ](https://itch.io/t/4049639/cider-is-too-slow-on-windows-11) this issue on itch

**Comment by cryptofyre** [comment]
This seems related to your playlist size, MusicKit can't handle super long playlists like that very effectively.
