### ISSUE TITLE
[2.5.1] Failed to authorize with apple msuic

### ISSUE THREAD

**Issue by KaniuBillows** [ciderapp/Cider-2#745]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Describe the Bug

When I try to sign in with apple music, I got this:
![image](https://github.com/user-attachments/assets/74c7f59f-46e0-4d43-970b-aa6b9825b91d)

and I try to open the web-view console, I  got this:

![image](https://github.com/user-attachments/assets/ccc638c8-e008-457d-b608-7c0d19be95ac)

### Steps to Reproduce

I just open cider, and try to singed in. I got this.

### Anything else?

the version info: 
![image](https://github.com/user-attachments/assets/ff943a40-35c9-42a5-ad84-3cf8caf72bd1)

**Comment by coredev-uk** [comment]
What occurs when you try signing into Apple Music web?

**Comment by KaniuBillows** [comment]
> What occurs when you try signing into Apple Music web?

I can sign into Apple Music web successfully in the small window that pops up. I checked the box to remember the device, not sure if that has an effect or not.

**Comment by KaniuBillows** [comment]
Just now, I retried singing in, this time choosing to sign in via e-mail, and it actually worked, it's confusing but good that it works, I'll close this issue for now
