### ISSUE TITLE
Cannot press `esc` to cancel "Enter Apple Music URL" Dialog

### ISSUE THREAD

**Issue by Gallium314** [ciderapp/Cider-2#747]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

70fad40dcd8e1b6d6cc0e8979fdf5f52626f5f37

### Connect Instance ID

not-logged-in

### Build Timestamp

2024-08-24, 1:41:40 p.m.

### Describe the Bug

Pressed the escape key when the "Enter Apple Music URL" dialog was open, and the window simply pulsed instead of closing. 

### Steps to Reproduce

1. clicked on "..."
2. clicked on "Apple Music"
3. clicked on "Open URL"
4. pressed the `esc` key

**Comment by booploops** [comment]
Resolved in 2.5.2
