### ISSUE TITLE
Cider doesn't play songs.

### ISSUE THREAD

**Issue by jqvvn** [ciderapp/Cider-2#751]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

87a066f6a3fc6333788ee2d66670ffe1b037d04f

### Build Timestamp

8/29/2024, 7:09:39 AM

### Describe the Bug

I opened Cider, i pressed on (name)'s station, and first time it has happened it showed a name of the song and it didn't start playing. Then I restarted Cider and still again no playback. I updated it (it was 2.5.0) and still the same error occurs. I've tried portable app and it worked for few songs and it happened again. Neither Music videos work. Apple Music Web works so I don't get why it happens. I have tried different settings for playback, network related stuff and still nothing.

### Steps to Reproduce

I opened Cider, hit play and nothing.

**Comment by jqvvn** [comment]
It's a shame that it doesn't work but it's still not finished so I can't talk much about it

**Comment by madebydre** [comment]
Same issue...For months now.

**Comment by jqvvn** [comment]
I just realised, Apple Music 1 radio works.. but nothing else is.

**Comment by jqvvn** [comment]
**Update:**
Found out explicit music doesn't work. The other non-explicit songs does.
Is there any way to get around that?

**Comment by riverfog7** [comment]
its the same for me. I cannot play songs on my own playlist but i can play songs when i go into artists / albums / etc

**Comment by jqvvn** [comment]
> its the same for me. I cannot play songs on my own playlist but i can play songs when i go into artists / albums / etc

Only thing we can do is wait. But guessing from a tag "stale/wont fix" we have 5% luck

**Comment by coredev-uk** [comment]
What song were you playing to cause this error?

**Comment by oldfieldtc** [comment]
Might be related, but I was having issues with some albums playing and others not - in the dev tools, I was getting 'content not available' errors. What I did to fix it was change my storefront in Settings > General > Apple Music (was set as US when should've been UK) and then sign out and back in to Apple Music. I'm no longer getting any 'content not available' errors and all albums are loading and playing with no issue.

**Comment by coredev-uk** [comment]
Yeah this was an issue with the release, since then we have made an auto option and made that default. We have also hidden the option away in advanced settings, due to the issues stemming from this.

**Comment by alanpmartin** [comment]
> Might be related, but I was having issues with some albums playing and others not - in the dev tools, I was getting 'content not available' errors. What I did to fix it was change my storefront in Settings > General > Apple Music (was set as US when should've been UK) and then sign out and back in to Apple Music. I'm no longer getting any 'content not available' errors and all albums are loading and playing with no issue.

I just logged in to report a similar issue of some albums playing and others not - this seems to have fixed it! Thanks so much - it was driving me mad.

**Comment by S-zombie** [comment]
Same issue here. Happened today. No music plays at all, no artists, no albums, no radios. I can explore the app, go into albums, artists, etc., I tried everywhere, but hitting play doesn't do anything, adding to queue doesn't populate it, music videos don't start. Apple Music site and app on my phone both work. I'm on version 2.5.3 patch 3, stable, was working yesterday.

**Comment by cryptofyre** [comment]
Please make sure you are not using the "Dislike Skipper" plugin, this plugin is known to cause issues with playback.

**Comment by S-zombie** [comment]
That was the culprit indeed! Thanks!

**Comment by jqvvn** [comment]
Thank you guys so much for the fixes. I have my Cider working just fine. I am sorry for being inactive I really just gave up but I noticed a lot of mails in my inbox and checked it. Again thank you for making this fix possible. Much love from Serbia!

**Comment by dominicmaguire** [comment]
> Might be related, but I was having issues with some albums playing and others not - in the dev tools, I was getting 'content not available' errors. What I did to fix it was change my storefront in Settings > General > Apple Music (was set as US when should've been UK) and then sign out and back in to Apple Music. I'm no longer getting any 'content not available' errors and all albums are loading and playing with no issue.

New Music Mix wasn't playing at all. This worked for me. Thank you.

**Comment by coredev-uk** [comment]
For future reference, use the experimental builds to fix this issue. This will come to stable soon.

**Comment by coredev-uk** [comment]
2.6.0 is now available which contains the storefront fixes. Microsoft store will be coming soon.
