### ISSUE TITLE
Attempting to 'Play Next' a track while listening to a station does not work

### ISSUE THREAD

**Issue by NoraVR** [ciderapp/Cider-2#752]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11 Enterprise 21H2

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Describe the Bug

Exactly as it says in the title. 
Expected behaviour is having it play the requested track next.

### Steps to Reproduce

1. Right click any song and click 'Start Radio'
2. Right click another song and click 'Play Next'
3. Skip the current song and observe it pick a random track instead of what was requested to be played next.

### Anything else?

![Example](https://github.com/user-attachments/assets/0c9ff675-0fc9-4270-9b84-6ec51e9572d0)

**Comment by coredev-uk** [comment]
Please see my response on #663
