### ISSUE TITLE
Flagged as PUA:Win32/Puamson by Windows Defender

### ISSUE THREAD

**Issue by Thundernerd** [ciderapp/Cider-2#754]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

Recently the downloaded installer has been flagged as PUA:Win32/Puamson by Windows Defender as shown in the image below.

![image](https://github.com/user-attachments/assets/cd2a3168-c9ba-4dbe-90ae-53dd56927f1c)

The file was already there and didn't cause this before, so I suspect something has been updated on the Windows Defender definitions side of things, but figured I'd report it here anyway.

### Steps to Reproduce

I'm not quite sure as this file only recently started being flagged and it on my drive before already.

**Comment by cryptofyre** [comment]
They keep doing this, I have no clue as to why. Virustotal shows zero false positives.

I'll try and contact Microsoft directly to get this resolved because this seems very odd to me.
