### ISSUE TITLE
Message displays in Chinese when NetEase can't find Lyrics

### ISSUE THREAD

**Issue by StevenTedYT** [ciderapp/Cider-2#755]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

not-logged-in

### Build Timestamp

20/08/2024, 03:26:53

### Describe the Bug

When NetEase cannot find the lyrics for a song, it displays a message in Chinese instead of English, even though the language settings are configured to English. This issue occurs specifically when playing instrumental music tracks, as shown in the attached screenshot.

### Steps to Reproduce

- Select an instrumental music track.
- Use the immersive mode.
- Notice the message displayed when no lyrics are found.

### Anything else?

![image](https://github.com/user-attachments/assets/cc092bb9-a8c1-4ca1-8303-7297db87bb41)

**Comment by StevenTedYT** [comment]
bump

**Comment by coredev-uk** [comment]
Can you copy that error message and send it here, I dont personally use netease, it was only for the duration in development and I never came across this.

**Comment by StevenTedYT** [comment]
纯音乐，请欣赏

**Comment by coredev-uk** [comment]
Thank you

**Comment by coredev-uk** [comment]
Added a check in https://github.com/ciderapp/citadel/commit/23ec4ced61174aae233791e34fed7ad4ce95887d
This should fix it, however I cannot be sure. I new build will be added to Taproom shortly with this, let me know how it goes for you.

**Comment by coredev-uk** [comment]
Due to the lack of response I'm gonna assume the fix worked.
