### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Kardel123** [ciderapp/Cider-2#759]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

MStore

### Operating System

Windows 

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

not-logged-in

### Build Timestamp

8/20/2024, 9:26:53 AM

### Describe the Bug

Remaining time/Elapsed time is not working on Discord.

### Steps to Reproduce

It is not reflecting in the discord activity overlay

### Anything else?

N/A

**Comment by coredev-uk** [comment]
This is a discord feature, not a cider feature. As far as I know, its enabled in current Canary builds, but they change it from time to time. Please don't open non-cider issues.
