### ISSUE TITLE
Scanning forwards/backwards on a song doesn't always work.

### ISSUE THREAD

**Issue by crockk** [ciderapp/Cider-2#760]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 10

### Describe the Bug

Intermittently, when trying to go to a different point in the song, it doesn't always register the input and continues playing from the current point. Not sure if this is a problem with my internet or an app problem. Doesn't seem to happen on the Apple Music Web player after some brief testing (I don't use the Apple Music Web player enough to be sure, to be fair. I hopped on and tried to recreate the bug but could not)

Example:

![ciderbug_clip_1_1](https://github.com/user-attachments/assets/48f224f2-789d-48b1-ae48-6c46532cb859)

### Steps to Reproduce

1. Play a song.
2. Try to scan forwards or backwards on the timeline, sometimes you have to do it a bunch before it happens, sometimes it happens right away.

**Comment by cryptofyre** [comment]
Seems like an internet issue due to the spinner in the top right, it seems to be struggling to even try and fetch its own resources for your library.

**Comment by crockk** [comment]
I see that, didn't notice that. Looks like it's downloading playlists. I have a lot of playlists so might just be catching up.
![image](https://github.com/user-attachments/assets/6a1f6e3f-35c3-4396-a864-5a3c720a494f)
