### ISSUE TITLE
liked songs not showing up in albums and playlists

### ISSUE THREAD

**Issue by Etx4n** [ciderapp/Cider-2#765]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

macOS 23.6.0

### Commit Hash

64aca31bef29dea4509168b34947593e30f3d75b

### Build Timestamp

6/9/2024, 19:44:27

### Describe the Bug

liked song doesn't show up on playlists or on albums 

### Steps to Reproduce

by clicking on any playlist or album with liked songs

**Comment by Etx4n** [comment]
bump

**Comment by coredev-uk** [comment]
Would you mind expanding on what you're on about? Are you saying that liked songs are not appearing or that they are in the playlist but did now show the liked state?

**Comment by Etx4n** [comment]
Just can't see "favourite track" icon like it shows on oficial apple music app
<img width="1298" alt="Captura de pantalla 2024-10-10 a la(s) 8 53 52 a m" src="https://github.com/user-attachments/assets/bdb82b77-cd10-401c-ad88-042d9fbffd33">
<img width="957" alt="Captura de pantalla 2024-10-10 a la(s) 8 54 11 a m" src="https://github.com/user-attachments/assets/951fc209-6d0f-4131-adb8-f423d6795cfc">

**Comment by coredev-uk** [comment]
This form of rating is only available through the iTunes API afaik. This API is proprietary and is not available to us. We can only access favourite songs and songs added to the library in this sense. Feel free to make a report to Apple requesting it in their MusicKit API.
