### ISSUE TITLE
App with every start reset position and size

### ISSUE THREAD

**Issue by MrCrowCZ** [ciderapp/Cider-2#766]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Describe the Bug

If not a bug, then it's suggestion to change that.

Everytime when I open the cider app it always open at the same place on the same screen. Since I have (and probably more people) more than 1 screen would be great if the app remember last position and size. 

Even the fancyzones from powertoys cannot "override" the position

### Steps to Reproduce

Open the app. Move it to different screen. Close the app. Open the app again. Voila.

**Comment by TheFirstComix** [comment]
this is true facts it always happens to me too
