### ISSUE TITLE
White borders around the app when fullscreen

### ISSUE THREAD

**Issue by amidstacy** [ciderapp/Cider-2#768]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

bf90c56292e9d8ff4066dddeb3b277a233f9ab19

### Connect Instance ID

not-logged-in

### Build Timestamp

9/13/2024, 5:16:17 PM

### Describe the Bug

White borders around the app, could this be a Cider problem or a scaling problem on my side? (please be the former) It only happens on Cider + the white borders disappear when it's minimized. I reported this last month and said it was gonna be fixed. 

Link to report: [](url)https://github.com/ciderapp/Cider-2/issues/720 

### Steps to Reproduce

Don't know

### Anything else?

![image](https://github.com/user-attachments/assets/4bd3ed31-27de-4449-aabb-8ca9966fcfd0)

**Comment by cryptofyre** [comment]
Make sure to fetch the latest version available on Itch, it should have a backend supp. patch to resolve this.

**Comment by BENZORICH** [comment]
Hi! I have the same problem and I am on this version:

![image](https://github.com/user-attachments/assets/7fe3188e-81ab-4bcc-a9ad-4f20a862ec02)

**Comment by cryptofyre** [comment]
Please reinstall from Itch or the Microsoft Store.

Updating in app will not update your backend client version, which needs done in this case.

**Comment by BENZORICH** [comment]
> Please reinstall from Itch or the Microsoft Store.
> 
> Updating in app will not update your backend client version, which needs done in this case.

Thanks that helped :D
