### ISSUE TITLE
UI menu droplist delay

### ISSUE THREAD

**Issue by FuzzyDark** [ciderapp/Cider-2#769]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

bf90c56292e9d8ff4066dddeb3b277a233f9ab19

### Build Timestamp

9/13/2024, 11:16:17 AM

### Describe the Bug

UI menus overlaying

### Steps to Reproduce

Opened top left corner "three dot" button.
Hovered mouse over drop list options fast enough to see the issue shown in the image. Can't say how fast, just fast enough, and it's not a really "picky" issue, it's slow enough to be a problem for regular users.

### Anything else?

![image](https://github.com/user-attachments/assets/b2240c8e-44e6-4ee1-97fa-e44273a2648f)

**Comment by FuzzyDark** [comment]
Bump

**Comment by coredev-uk** [comment]
This is more of a nitpicky thing with UI, our development time would be better spent focusing on bigger issues.
