### ISSUE TITLE
(bug w/ Close to Tray): Taskbar requesting new instance

### ISSUE THREAD

**Issue by jofrado2** [ciderapp/Cider-2#770]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

bf90c56292e9d8ff4066dddeb3b277a233f9ab19

### Build Timestamp

9/13/2024, 4:16:17 AM

### Describe the Bug

When I put cider in the background and try to open it from the taskbar (i configured the app so it goes to the toolbar instead of closing), the app tells me to close the other instance but i just want to open the app, now to open the app i need to click the toolbar arrow, search for the icon in the toolbar and click it, is a little annoying (I'm sorry if it's not clear, English is not my main language)

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/32437eb9-df95-49b9-a5a0-318479b7064f)

https://github.com/user-attachments/assets/05751435-7b23-40d7-9d66-0d0ad59856fb

### Anything else?

is stated to happen 3 updates ago

**Comment by mpar-22** [comment]
Also experiencing this issue, hoping it gets resolved soon

**Comment by cryptofyre** [comment]
Implemented in the next release.

https://github.com/user-attachments/assets/1a68c6b7-6867-42c2-9334-30065bdfd34d
