### ISSUE TITLE
Plugin was not installed due to incorrect format

### ISSUE THREAD

**Issue by SocietasEvanescentes** [ciderapp/Cider-2#771]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.io

### Operating System

Windows 11/macOS

### Describe the Bug

When trying to update or install plugins, the following error message appears:

![Screenshot 2024-09-13 210549](https://github.com/user-attachments/assets/2da92b79-24ed-431d-a48e-2a2946ce62ce)

### Steps to Reproduce

Try to update an already installed plugin.

### Anything else?

This has happened for the last two or three builds for me; I'm not sure what is causing it.

**Comment by booploops** [comment]
Not a bug, an update to that plugin submitted was in the wrong format.
