### ISSUE TITLE
GitHub button in About menu still links to Cider One's Repo

### ISSUE THREAD

**Issue by SocietasEvanescentes** [ciderapp/Cider-2#772]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.io

### Operating System

macOS/Windows

### Describe the Bug

Clicking the GitHub button in the about menu leads to the repo for the initial version of Cider, and not Cider 2. 

### Steps to Reproduce

1. Open Cider
2. Open About Menu
3. Click GitHub Option
4. You'll be redirected to Cider One's repo which is archived.

### Anything else?

Not really a bug, but a small overlook while releasing Cider 2. I didn't see any options for UX improvement/errors/etc. in the github issue reporter.

**Comment by coredev-uk** [comment]
Thanks for letting us know, this has been fixed.
