### ISSUE TITLE
Lyrics autoscrolling drops frames every few seconds

### ISSUE THREAD

**Issue by jacquesvfd** [ciderapp/Cider-2#774]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 24.1.0

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Connect Instance ID

not-logged-in

### Build Timestamp

8/19/2024, 9:26:53 PM

### Describe the Bug

When lyrics are autoscrolling in Immersive mode, the scrolling animation will drop multiple frames every couple scrolls, resulting in choppy-looking autoscrolling rather than smooth 60fps scrolling. It seems to be random: about half of the autoscrolls are choppy, the other half are smooth.

### Steps to Reproduce

1. Play a song with lyrics
2. Open Immersive mode
3. Wait for a few seconds. As lyrics scroll by, you'll notice that sometimes, it looks perfectly smooth, and other times, it looks like it's running at 30 or so FPS.

### Anything else?

https://github.com/user-attachments/assets/00577d91-a944-41b2-b361-c1ff00b28973

In this screen recording, you can see that the first couple lines animate at a choppy framerate, but the line "She turn to Spider-Woman if I bite her" animates at a buttery-smooth 60fps.

**Comment by jacquesvfd** [comment]
Bump!

**Comment by cryptofyre** [comment]
Not sure we can do much about this, this entirely comes down to how macOS chooses to render GPU processes in priority.

It may improve on the upcoming mac/linux backend update.
