### ISSUE TITLE
Can't see "favourite track" icon

### ISSUE THREAD

**Issue by mpratsaki** [ciderapp/Cider-2#776]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 11

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

14/09/2024, 5:43:51 am

### Describe the Bug

Even though I have favourited some tracks or some albums I can't see the favourite star icon in the songs
![image_2024-09-16_192102277](https://github.com/user-attachments/assets/066c3859-8af5-4831-8ce2-98cc72794858)

### Steps to Reproduce

Nothing, I just launced cider

**Comment by coredev-uk** [comment]
Duplicate of #765
