### ISSUE TITLE
RPC not working at all, regardless of settings.

### ISSUE THREAD

**Issue by nrthbound** [ciderapp/Cider-2#777]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Mac OS Sonoma 14.2.1

### Describe the Bug

I'm on Cider 2.5.2_5, I have enabled the RPC Server, and using Hoppscotch and Insomnia, it would seem that there is no server running. I've tried it with and without the requirement of an API token to make the request. This worked fine on a previous version (2.4). 

### Steps to Reproduce

- Ensure you're on Cider 2.5.2_5
- Go to Settings -> Connectivity -> Enable "RPC Server"
- Below that, click "Manage" for Manage External Application Access to Cider
- Disable "Require API Tokens"
- Using any API Endpoint Testing provider, try any of the provided endpoints in the Cider RPC Documentation (https://cider.sh/docs/client/rpc)
-

### Anything else?

Just to confirm, I'm not getting a permissions error, or any error related a problem with the endpoint. The server simply isn't running.

**Comment by cryptofyre** [comment]
Hey there, @nrthbound!

We've recently updated the API to utilize a new system so there are new docs that must be used!

These can be found here:

https://github.com/ciderapp/Cider-2/blob/main/docs/Cider%202.5.0%20Preview%20API.md

We plan on getting these rolled out to the main site fairly soon.
