### ISSUE TITLE
Cider skips multiple songs before finding one that's playable, and that one is only part of the song

### ISSUE THREAD

**Issue by CADawg** [ciderapp/Cider-2#778]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

14/09/2024 03:43:51

### Describe the Bug

When trying to play the song "Who's that chick" by David Guetta and Rihanna, it:
1) Doesn't play if I click the suggested result
2) Skips two songs down (failing to play the first two) and then plays a song which is not the full length but is cut strangely in the middle, which is not the case on the apple music web client (1:30 in cider vs 2:41 in Apple Music Web)

### Steps to Reproduce

1. Searched for "Who's that chick" on Cider with a UK Apple Music Subscription
2. Clicked play in the top recommendations row (nothing happens)
3. Clicked play on the first songs in the songs section (it jumps to song 3 which is a 1:30 length song cut from the middle of the full song rather than the entire song which is 2:41 on apple music web)

**Comment by CADawg** [comment]
Bump - checked and it still occurs

**Comment by coredev-uk** [comment]
Please check your storefront settings in General > Apple Music. Ensure that they are set to the 'Auto' option or to your account's storefront. If so, please also check if the song is playable on Apple Music web, if it is explicit then your account may be restricted.

**Comment by CADawg** [comment]
That's fixed it - didn't find auto in the options but United Kingdom works and fixes this issue - thanks!
