### ISSUE TITLE
Airplay: Clicking "Connect" loads for half a second and nothing happens

### ISSUE THREAD

**Issue by JustSxm** [ciderapp/Cider-2#779]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

2024-09-13, 10:43:51 p.m.

### Describe the Bug

When clicking "Connect" on my Sonos Speakers nothing happens. I only see a loading for half a second.

Heres a video in action:
https://streamable.com/5e79mb

### Steps to Reproduce

1. Clicked on Airplay
2. Clicked on Connect
3. Nothing happens.

**Comment by coredev-uk** [comment]
We are in the process of depreciating the current implementation of AirPlay. We discourage the use of it until it is either rewritten by ourselves or a community plugin is made.
