### ISSUE TITLE
Severe graphics bug with MFAA enabled

### ISSUE THREAD

**Issue by CamikazeLDN** [ciderapp/Cider-2#781]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

14/09/2024, 03:43:51

### Describe the Bug

When Multi-Framed Sampled AA (MFAA) is enabled in nVidia control panel cider suffers from severe graphics/UI issues. Moving the cursor to the sidebar and then around leaves a thick pixel trail and various elements flash. Text also blurs in places, particularly in the sidebar

### Steps to Reproduce

Open nVidia control panel and enable MFAA
Open Cider and navigate to the sidebar
Move cursor around the page and interact with UI and observe

**Comment by cryptofyre** [comment]
Don’t enable MFAA globally.
