### ISSUE TITLE
Endless "Downloading Playlist"

### ISSUE THREAD

**Issue by linkedilion** [ciderapp/Cider-2#782]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch.IO

### Operating System

Linux 6.10.10-200.fc40.x86_64

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

9/14/2024, 4:43:51 AM

### Describe the Bug

When listening to music, cider starts to randomly download playlist (don't know which, there is just "Downloading playlist"). It starts from ~4-5 instances of "Downloading Playlist" and with time, there will be tens of this. Because of it, i can't like any song, can't add something to my playlist and so on. The fix to it, is just restart the app, but then the problem will show itself with time. 

### Steps to Reproduce

I was just listening to some playlists. They were completely different.
![Screenshot from 2024-09-21 10-53-51](https://github.com/user-attachments/assets/1e31d623-493a-4011-bdd2-45534d13c53e)

**Comment by XCroatoanX** [comment]
+1, had the same issue lots of times, good taste of music btw :D

**Comment by coredev-uk** [comment]
Resolved in next release.
