### ISSUE TITLE
Volume bar not working properly with fractional scaling

### ISSUE THREAD

**Issue by XCroatoanX** [ciderapp/Cider-2#785]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Arch Linux

### Build Timestamp

9/14/2024, 4:43:51 AM

### Describe the Bug

While using the volume slider, the volume starts decreasing with an offset to the left of the cursor. I use fractional scaling at 125% on KDE 6.1.5. I have this issue already for multiple versions, and in the PTB, it's still present.

https://github.com/user-attachments/assets/81177e79-31f4-4106-9372-207a2e79cf9b

### Steps to Reproduce

1. Click on the volume bar
2. Drag it to lower the sound
3. At 0%, the cursor will be around the left quarter of your sound bar

**Comment by coredev-uk** [comment]
Disable the iOS style volume slider in Settings > Advanced > Tweaks.
