### ISSUE TITLE
Using Mini-player & re-opening Cider issue.

### ISSUE THREAD

**Issue by kaer1a** [ciderapp/Cider-2#788]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 24.1.0 & Windows 11

### Commit Hash

5d01e286a186b02b0c155fe941f6985ed2705edb

### Build Timestamp

9/28/2024, 12:21:39 AM

### Describe the Bug

When streaming a song and heading into mini-player, and then closing Cider (whilst in mini-player mode) and re-opening Cider causes The window to be sized in the way the mini-player was and re-sizing the "Home, Listen Now, New, Radio" tabs if you have them as tabs. If they're on the sidebar, they still appear.

### Steps to Reproduce

1. Set "Top Toolbar Widget" to be tabs. 
2. Stream any song
3. Go into the MiniPlayer (whilst streaming the song)
4. Close Cider (WHILST IN MINIPLAYER)
5. Re-open it.

You should see what I described prior.

### Anything else?

nop

**Comment by coredev-uk** [comment]
Resolved in next release.
