### ISSUE TITLE
No login popup window on click Sign in with Apple

### ISSUE THREAD

**Issue by cytsai1008** [ciderapp/Cider-2#789]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

After update to `2.5.3 Patch 1`, I got logout and cannot login back (the button not working)

### Steps to Reproduce

start Cider
click Sign into Apple Music
click Sign in with Apple

Nothing happened

### Anything else?

![image](https://github.com/user-attachments/assets/5c2f8d25-45e8-499a-8a5f-da58210c1f6e)
![image](https://github.com/user-attachments/assets/68d7c598-1f8a-47a4-83cb-5e31df9025fd)

**Comment by cryptofyre** [comment]
This is a rolling issue with Apple's API, you should expect this working again not too long from now.

I experienced it briefly in afternoon of the day and it cleared up 30-40 minutes after.

**Comment by lnbxyz** [comment]
> This is a rolling issue with Apple's API, you should expect this working again not too long from now.
> 
> I experienced it briefly in afternoon of the day and it cleared up 30-40 minutes after.

So this is an issue on Apple's side, not Cider? 
I'm experiencing the same thing. is there an ETA for a fix? It's been hours.
