### ISSUE TITLE
Cider can no longer load in Windows 11 24H2

### ISSUE THREAD

**Issue by nawka12** [ciderapp/Cider-2#790]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11 24H2

### Describe the Bug

![image](https://github.com/user-attachments/assets/6a30749f-9c68-491b-871b-c26cbd9ab312)

I just updated my Windows 11 from 23H2 to 24H2, the app was working fine on 23H2, but the app can no longer can be accessed with Windows 11 24H2.

### Steps to Reproduce

1. Update to Windows 11 24H2
2. Open the app

### Anything else?

I already tried uninstalling and installing it, but still not working.

**Comment by PGSCOM** [comment]
Try to remove C:\Users\(User)\AppData\Roaming\C2Windows

**Comment by nawka12** [comment]
https://github.com/user-attachments/assets/d9b15c5f-80ab-4e30-bbc4-6f42d333003e

I think the app is trying to download something on the background, but it's very slow. I have a 100Mbps connection so this is absurd.

Comparing the folder size to the one installed with my work PC:
Work PC (Win 11 23H2)
![image](https://github.com/user-attachments/assets/e781e011-7e33-46e6-9b01-9e1a365e2090)


My laptop (Win 11 24H2)
![image](https://github.com/user-attachments/assets/ae8a8570-69b3-4d12-8b6d-dbc49b5b5fb5)

**Comment by coredev-uk** [comment]
Please check that the Cider API is not being blocked. There was an outage with Apple Music previously, however this should not be causing this.

**Comment by nawka12** [comment]
> Please check that the Cider API is not being blocked. There was an outage with Apple Music previously, however this should not be causing this.

Not sure but the API is not blocked by firewall. But if you mean something else, lmk.
![image](https://github.com/user-attachments/assets/68b51d86-6f40-496c-8df8-cad6047caac6)

**Comment by nawka12** [comment]
Solved. The issue occurred because I was using BBR2 Congestion. Switching back to CUBIC solved the issue. This is not happening with 23H2 since I've used BBR2 for a while now. Probably a 24H2-only bug.

Sorry for the inconvenience I might caused. 

https://github.com/user-attachments/assets/1f40b073-77e8-4993-9404-a558effdfd9a
