### ISSUE TITLE
won't register hitting "play" i've tried every variation and apple music app is fine sooooooo?

### ISSUE THREAD

**Issue by fucchurryupmf** [ciderapp/Cider-2#791]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

681cc01a39ff5d4919330470f16dc35daebe0e66

### Build Timestamp

10/3/2024, 12:43:10 AM

### Describe the Bug

pressing play in every way possible doesn't work

### Steps to Reproduce

no idea not my job

### Anything else?

just realized you guys don't have lossless audio so i will probablly go elsewhere

**Comment by coredev-uk** [comment]
If you are interested in fixing the issue, please don't just open an issue and say ur going elsewhere. It is clearly stated that we don't support lossless.

As for your issue, we will need more information surrounding what you were trying to play, your subscription status, the behaviour on Apple Music web and whether it was an explicit song or not.

**Comment by cryptofyre** [comment]
It's a throw away GitHub account so, they probably wont provide any insight on this.
