### ISSUE TITLE
Theme installation for Cider 2.5.3.3 on Linux does not apply

### ISSUE THREAD

**Issue by flexiondotorg** [ciderapp/Cider-2#793]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

LInux (NixOS)

### Commit Hash

cc3527fd2e5beaae3189e383f177ee085c66fcef

### Build Timestamp

1727928590770

### Describe the Bug

I am running the AppImage of Cider 2.5.3.3 - Electron on Linux (NixOS). Installing a theme from the Marketplace has no effect. None of the themes apply.

I restarted Cider, but no theme change was applied. Cider recognizes that the Cappuccino Mocha theme has been installed.

### Steps to Reproduce

Steps to reproduce:

- Open Cider
- Menu → Marketplace → Themes
- Find "Catppuccin - Mocha" 
- Click Install

No theme change is made.

### Anything else?

While the Catpuccin theme is installed, the following is written to stdout:

```
(node:1318092) [node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
extracting to /home/martin/.config/sh.cider.electron/themes/12
```

**Comment by djwinston** [comment]
I can't apply any themes from marketplace too. After install themes I did not find any new theme options in the settings, except for the standard ones
#### Download Source: 
Microsoft store
#### Operating System
Windows 11 23H2
#### Build
2.5.3_3 - .NET

**Comment by djwinston** [comment]
> I can't apply any themes from marketplace too. After install themes I did not find any new theme options in the settings, except for the standard ones
> 
> #### Download Source:
> Microsoft store
> 
> #### Operating System
> Windows 11 23H2
> 
> #### Build/hash
> 2.5.3_3 - .NET / cc3527fd2e5beaae3189e383f177ee085c66fcef

Sorry my mistake. Lots of settings. It was not clear enough how to activate the installed theme. I was looking at the visual section. Author one of the custom themes helped to figure it out. Settings -> extensions -> themes -> open collapse menu of theme and apply style.

**Comment by coredev-uk** [comment]
Yeah the theme would not apply as soon as you install the plugin. You do need to apply it in settings.
