### ISSUE TITLE
Butterchurn Visualizer not opening with new updates

### ISSUE THREAD

**Issue by xScoot** [ciderapp/Cider-2#794]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows

### Commit Hash

cc3527fd2e5beaae3189e383f177ee085c66fcef

### Connect Instance ID

2

### Build Timestamp

10/3/2024, 12:09:50 AM

### Describe the Bug

everytime i try to open the visualizer from butterchurn on the plugin list it gives the error "localhost: 10767 says Audio Context not ready yet" it only started happening after the last couple of updates and its been re occuring every time i try to use the visualizer 
![Screenshot_2](https://github.com/user-attachments/assets/8bc9a5aa-b4f5-48ec-a8ae-fd79b8c97d1b)

### Steps to Reproduce

just trying to open the visualizer at all on my PC doesn't work,  ive tried to fix it but nothing works so far

### Anything else?

![Screenshot_2](https://github.com/user-attachments/assets/a89857bd-2cb5-40a0-8890-5ccc5215411a)

**Comment by cryptofyre** [comment]
Enable CiderAudio as specified in the plugins description, as these are not “official” Cider features do not use this bug tracker for this purpose.
