### ISSUE TITLE
Downlaod local files 

### ISSUE THREAD

**Issue by Donorris1** [ciderapp/Cider-2#795]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Mircosdt stroe 

### Operating System

Windows 

### Commit Hash

cc3527fd2e5beaae3189e383f177ee085c66fcef

### Build Timestamp

10/3/2024, 12:09:50 AM

### Describe the Bug

I was able to down load 3 local files but after I would drag the file into the app and it would one another window plating the song not in cider 

### Steps to Reproduce

I dont know 

### Anything else?

no

**Comment by cryptofyre** [comment]
Cider does not support local files at this time.
