### ISSUE TITLE
Collaboration Playlist Update Issue

### ISSUE THREAD

**Issue by BoochySans** [ciderapp/Cider-2#798]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

Opening a Collaboration playlist labels the Playlist as last updated in January 1 1970

### Steps to Reproduce

Any collaborative playlists
![image](https://github.com/user-attachments/assets/2327c90e-53c4-409b-876d-01b3a2d115b9)
![image](https://github.com/user-attachments/assets/e4c5c9c0-274d-4e6e-a7ce-8efc111716e2)

**Comment by cryptofyre** [comment]
api cant do anything here
