### ISSUE TITLE
Random Pausing Bug

### ISSUE THREAD

**Issue by DarthObi** [ciderapp/Cider-2#801]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

3dcac5e742425fe560417100df7acbc1da4e3342

### Build Timestamp

10/3/2024, 1:53:40 AM

### Describe the Bug

The music would pause by itself and then resume sometime a few seconds or more. I tried uninstalling and reinstalling but the same issue happened.

### Steps to Reproduce

This happens at random

**Comment by cryptofyre** [comment]
This usually indicates something is wrong with your hardware settings, ex. an overclock, undervolt or an out of date bios can even cause this.

I’d highly recommend checking these things and reporting back, Apple’s DRM is very particular about these things.

**Comment by DarthObi** [comment]
I use a very high spec PC and have never overclocked anything. I made sure
that my AMD CPU, Graphics Card, Motherboard, BIOS are all up to date.
However, I noticed that when I play a game and listen is the only time the
pausing happens. Side note: I have an overlay for instant replay on just to
clip anything I wish. If this is an issue let me know! I
haven't experienced any of this in the past but I am now that I upgraded a
few hardware parts for my PC.

Thank You!

**Comment by diffty** [comment]
Hey! I have the same issue since a few days.

Songs randomly pauses then resume themselved after from a fraction of second to a few seconds.

I noticed that there's something printed in my console, each time it is happening (at least I believe) : `index.html#/am/listen-now:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

Anyway, thank you for your work on Cider, I love it <3

Version: 2.5.4_3
OS: ArchLinux
