### ISSUE TITLE
Random UI freeze on linux

### ISSUE THREAD

**Issue by Aurnytoraink** [ciderapp/Cider-2#802]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Fedora 40

### Commit Hash

d8f7fc7d2ef773260fb2cf8aef1bbcd5c87a3381

### Describe the Bug

Sometimes the UI freeze, but the music is still playing.

Technical characteristics:
- OS: Fedora 40
- Desktop manager: Gnome 46
- Window manager: Wayland
- Cider version: 2.5.0

### Steps to Reproduce

I don't know how to reproduce the bug for now. It seems to be random

### Anything else?

https://github.com/user-attachments/assets/11676aef-1ca1-4356-9b3c-c5e3ca3b89c4

**Comment by coredev-uk** [comment]
This could potentially be related to Wayland usage in Electron. We do have a rewrite that is close to release for the Linux/macOS builds, this could potentially fix your problem. I'll let you know when its available to see if this issue occurs on those builds.
