### ISSUE TITLE
Unreasonable CPU usage

### ISSUE THREAD

**Issue by ondono** [ciderapp/Cider-2#804]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux (6.11.1)

### Commit Hash

cc3527fd2e5beaae3189e383f177ee085c66fcef

### Build Timestamp

10/3/2024, 6:09:50 AM

### Describe the Bug

Cider seems to be taking an unreasonable amount of CPU time, even when not doing anything. This is extreme to the point that I can tell if Cider is open just by hearing my fans.

Cider is consistently at the top of my CPU usage list, even surpassing VMware (Windows VM machine with CAD software running on it). While I've heard that electron apps are resource hogs, this looks way too extreme.

### Steps to Reproduce

1. Open Cider
2. Open any monitoring app like htop

**Comment by cryptofyre** [comment]
This could be due to GPU acceleration not working as it should, we're testing something over on our beta backend site if you'd like to check it out its available at https://taproom.cider.sh

Download the experimental backend from there and see if your conditions improve (expect lots of unfinished implementations!)

**Comment by manymanecki** [comment]
Unless some option has to be turned on in the options, I notice no noticeable improvement over the stable version - GPU fans spike randomly during audio playback. Let me know if I can assist somehow, I'll be glad to help. Some information from my side:

**Download Source**
Linux 6.11.5-arch1-1
Itch / Taproom (no difference)

**Operating System**
EndeavourOS / Hyprland (I remember the bug on KDE too)

**Commit hash**
e524a50fafc0ec0b3033c0d3f99371131a710cba

Build Timestamp
8/16/2024, 7:12:04 PM (this one is weird given a fresh install from the taproom, old version(?))

**Comment by EmptyVisual** [comment]
I suspect this is hardware accel related. Testing both genten and genten2 from the taproom builds, I can observe almost an 80-90% CPU spike on both builds.

I've been able to reproduce this by simply scrolling through my 'Songs' Library that contains approximately 747 songs.

Environmentally speaking, all tests were performed on a fresh install of

**Comment by EmptyVisual** [comment]
I suspect this is related to hardware acceleration. Testing both Genten and Genten2 from the taproom builds, I notice a significant CPU spike of around 80-90% on both builds. 

Reproducing this issue by scrolling through my 'Songs' library of approximately 747 songs confirms the problem. 

I conducted tests on a fresh Arch installation with both stable and development Mesa drivers to rule out any graphical driver issues.


AMD Radeon 6900 XT
mesa 24.3.0_devel.197256.07ca1bbb056
Wayland (application runs in xwayland anyway)
Linux 6.11.6

**Comment by coredev-uk** [comment]
For the Genten-2 builds, I suggest messing around with the hardware acceleration settings and ensure you are on the latest version. Earlier version of the genten-2 experimental builds did have an incomplete implementation of hardware acceleration. Outside of this, it is just electron and an app that performs a lot of visual changes. I suggest turning down all the settings (+ turning on gamemode) if you really are after a more performant experience.
