### ISSUE TITLE
Title bar options on Fedora 40 KDE Plasma 6.2.1

### ISSUE THREAD

**Issue by bargais** [ciderapp/Cider-2#806]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

Linux 6.10.12-200.fc40.x86_64

### Commit Hash

d8f7fc7d2ef773260fb2cf8aef1bbcd5c87a3381

### Connect Instance ID

not-logged-in

### Build Timestamp

16/08/2024, 16:21:49

### Describe the Bug

After setting Title bar Style to native Cider no longer opens.

### Steps to Reproduce

Settings --> Visual --> General --> Title Bar Style change to Native

### Anything else?
Cider version - 2.5.3_3
To open Cider again I had to delete Cider, delete ~/.config/sh.cider.electron folder and install again from scratch or change /.config/sh.cider.electron/spa-config.yml file parameter titleBarStyle value back to "default" .

**Comment by coredev-uk** [comment]
If you are running wayland, I believe this can cause crashes with native frame and transparency.

**Comment by bargais** [comment]
Yes, running wayland

**Comment by coredev-uk** [comment]
I suggest wiping your config in .config/sh.cider.electron and keeping native frame disabled. Afaik this is a bug with electron on wayland, ill look into it further later on.
