### ISSUE TITLE
Impossible to delete playlist "named untitled"

### ISSUE THREAD

**Issue by Shoku666** [ciderapp/Cider-2#808]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 6.11.3-arch1-1/Windows 10

### Commit Hash

d8f7fc7d2ef773260fb2cf8aef1bbcd5c87a3381

### Connect Instance ID

not-logged-in

### Build Timestamp

8/16/2024, 3:21:49 PM

### Describe the Bug

![2024-10-22_21-45](https://github.com/user-attachments/assets/607c0d43-734b-43b2-ac56-466a85c877ea)
Hello,
I'm unable to delete playlists and when trying to do so the playlists actually multiply and it's very annoying because now i have at least 10 untitled playlist which i cannot delete and interact with (not present in apple music app on iphone)

### Steps to Reproduce

1. Delete playlist from library 
2. "Untitled" playlist appears

**Comment by nateranda** [comment]
This is happening to me too on MacOS ARM version 2.5.4. The official Apple clients don't show the untitled playlists, and signing in again or reinstalling Cider doesn't fix the issue.
