### ISSUE TITLE
What's the point of downloading music if offline app doesn't work

### ISSUE THREAD

**Issue by FuzzyDark** [ciderapp/Cider-2#809]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [x] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11

### Describe the Bug

Disconnected from the internet, tried opening the app, it needs to log in, no shot at trying to play anything because there's nothing to reproduce in the library...

### Steps to Reproduce

Disconnect Wifi
Open App
![image](https://github.com/user-attachments/assets/0941e33d-74fb-4a42-8e1a-633ff9e271a1)

**Comment by cryptofyre** [comment]
Cider does not advertise itself as being capable of offline playback.
