### ISSUE TITLE
Add album to Library "Are you sure you want to remove?" dialogue

### ISSUE THREAD

**Issue by artunbekannter** [ciderapp/Cider-2#810]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 11 24H2 26100.2152

### Commit Hash

4548c6b8fb6c499cf3ecd91c1fab4efe4e976717

### Build Timestamp

22/10/2024, 02:52:50

### Describe the Bug

When adding Albums or Apple Music playlists to the library using the "add" button (whether the item is already added to the library or has not been added) it prompts a "Are you sure you want to remove 'album name' from your library?" dialogue box.

See capture below for this.

![addbug](https://github.com/user-attachments/assets/04ba8077-dda9-489e-b586-344a037e69d4)

### Steps to Reproduce

Opening an album from the "Home" page, clicking into an album and pressing add (it will change from "add" to the tick as expected but prompt the dialogue box, the album is still added to library in Apple Music (and removed on subsequent press and confirmation).

Does not occur on adding single songs, nor playing titles.

### Anything else?

Clearing the cache and reinstalling has not resolved.
Storefront is set to United Kingdom, as is Apple Music language.

**Comment by coredev-uk** [comment]
This is a feature request, not a bug. Please direct feature requests to our discord server. It is stated when creating an issue that you should take this route.

**Comment by cryptofyre** [comment]
I directed them here, its a bug with the button status. It'll randomly change to added and prompt that which is not the correct functionality of this button.
