### ISSUE TITLE
Shuffle feature working incorrectly 

### ISSUE THREAD

**Issue by Ehthnn** [ciderapp/Cider-2#811]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

4548c6b8fb6c499cf3ecd91c1fab4efe4e976717

### Build Timestamp

10/21/2024, 8:52:50 PM

### Describe the Bug

Usually when shuffling on apple music, a random list of songs from the shuffled playlist are added to the queue. On the most recent version of cider, when I use the shuffle feature, a random song is chosen from the playlist and the rest of the songs in queue are added in chronological order. In other words a song is picked and the rest of the songs after it in the playlist are queued and the queue ends once you reach the end of the playlist. If youre lucky enough the shuffle feature will pick the last song in the playlist and only play that one song. 

### Steps to Reproduce

The shuffle button while in a playlist.

**Comment by cryptofyre** [comment]
Please report this feedback to Apple.

They handle everything to do with Shuffle, Autoplay, and various other playback features for the time being.

https://www.apple.com/feedback/apple-music.html
