### ISSUE TITLE
Many mistakes

### ISSUE THREAD

**Issue by Waxoooo** [ciderapp/Cider-2#812]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

4548c6b8fb6c499cf3ecd91c1fab4efe4e976717

### Connect Instance ID

Esteban Gazca

### Build Timestamp

21/10/2024, 6:52:50 p.m.

### Describe the Bug

The first mistake is that the infinite mode does not work correctly, sometimes it works and sometimes it doesn't, but 90% of the time it does NOT work, it simply does not put anything in the queue even though it is on.

The second one is that when you navigate between different parts of the application (Albums, songs, Home, etc) the application keeps loading and becomes unusable until you restart it (it also happens when you try to put the infinite mode).

The third one is that when you put the immersive mode on the main screen (when you have more than 1 monitor) the taskbar at the bottom of Windows disappears when you try to search in it (it's simply not there).

Apart from that, the app often gets slow, when it wasn't before.

And also now with whatever the app is freezing or loading without letting you do anything, it's also a bit annoying that when you restart the app you have to activate the infinite mode again.

My computer has a Ryzen 5 5600x and 16Gb of ram at 3200Mhz so I don't think that's the problem

### Steps to Reproduce

For the first error, just search for a SINGLE song, without an album, just the song and put it in infinite mode and it won't add any to the queue

The second is less common but it usually happens and it's that when you search for a plugin or theme quickly, you search between albums, songs, put it in infinite mode, the application keeps loading

And the third is just having more than 1 monitor and in the one you have selected as the main one in Windows, put cider and you give it immersive mode, after the Windows button or Ctrl + Esc and the whole taskbar won't appear

And the last one is something that I noticed since these versions appeared, before the application was very comfortable to use, without errors or with minimal errors, that's why I bought it because Apple Music was horrible, but recently I no longer see that big difference that there was before between Cider and Apple Music for Windows

### Anything else?

I tried to make it seem like a nice way to say the errors that the application has, I never wanted to be or seem rude or try to insult the work that they do since I know it is difficult.
They are just errors that have been there for a while, so I thought it would be better to send them all together

Cider is one of the best purchases I have ever made without a doubt.

**Comment by cryptofyre** [comment]
A lot of these seem like Apple's API being problematic, I'd recommend reporting some of the playback related issues to Apple themselves as there is nothing we can do from our end.

Second and third issue are fixed in a soon to be released update, as for your last one we haven't changed very much to cause that much of an issue, it sounds like just overall bad API responses from Apple.
