### ISSUE TITLE
Low resolution images on Home page

### ISSUE THREAD

**Issue by wunder-one** [ciderapp/Cider-2#818]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

4548c6b8fb6c499cf3ecd91c1fab4efe4e976717

### Build Timestamp

10/21/2024, 6:52:50 PM

### Describe the Bug

Low resolution images for "Made for you" playlists on Cider Home page. Other area of the app she the same albums at the correct resolution. For example the Apple Music Home page shows full resolution. This row of playlists on this specific page seems to be the only place I see this issue. 

I have been unable to get these images to refresh or update to the high res versions. I have tried

- Removing the row from my home page and then adding it back again.
- Signing out of Apple Music and back in.
- Uninstalling and reinstalling Cider (from the microsoft store)

I am wondering if this is a cached image that needs to be replaced. However, I don't know how to clear the cache for Cider.

### Cider Homepage with low res images
![Screenshot 2024-10-27 090115](https://github.com/user-attachments/assets/ccc8b96f-a078-4ae5-b363-b4b69947a3cc)

### Apple Music Homepage with normal res images
![Screenshot 2024-10-27 085906](https://github.com/user-attachments/assets/af1080d8-1007-4fca-b63b-dcc8353bd5fe)

### Steps to Reproduce

It seems like this was caused by slow internet.

1. I had cider running along with a few other apps
2. I changed some settings on my network, which caused my computer to have no internet for a few minutes.
3. I noticed the resolution had changed

I can't be sure this is the cause. I have not been able to get the images back to full resolution, so I have not been able to try recreating the issues.

### Anything else?

This is a purely cosmetic issue. Please feel free to mark as low priority. No impact on functionality.

**Comment by cryptofyre** [comment]
Fixed in an upcoming update.
