### ISSUE TITLE
socket api not working

### ISSUE THREAD

**Issue by ThatGravyBoat** [ciderapp/Cider-2#828]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

EndervoursOS

### Commit Hash

d8f7fc7d2ef773260fb2cf8aef1bbcd5c87a3381

### Build Timestamp

1723814509407

### Describe the Bug

I am trying to update my usage of the APIs to the latest socket API but I can not get any responses from Cider socket.io at all, it connects and that is it, no events afterwards. The normal rest API still works fine though.

### Steps to Reproduce

You can use this simple html I made that I have been using to test and nothing happens, the code is parts taken from the CiderDeck plugin.

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
<script src="https://cdn.socket.io/4.7.5/socket.io.min.js" integrity="sha384-2huaZvOR9iDzHqslqwpR87isEmrfxqyWOF7hr7BY6KG0+hVKLoEXMPUJw3ynWuhO" crossorigin="anonymous"></script>
<script>
    const CiderApp = io('http://[::1]:10767', {
        reconnectionAttempts: Infinity,
        reconnectionDelay: 1000,
        timeout: 10000 // 10 seconds timeout
    });

    CiderApp.on('connect', () => {
        console.log("connecting!")
        CiderApp.on("API:Playback", info => {
            console.log(info);
        });
    });
</script>
</body>
</html>
```

**Comment by cryptofyre** [comment]
IPV6 doesn't work correctly I believe, not sure why.

Doing localhost or 127.0.0.1 should though.

**Comment by ThatGravyBoat** [comment]
> IPV6 doesn't work correctly I believe, not sure why.
> 
> Doing 127.0.0.1 should though.

with `127.0.0.1` & `localhost` im getting a 404s with the response:
```json
{"message":"Route GET:/socket.io/?EIO=4&transport=polling&t=PCUbSTQ not found","error":"Not Found","statusCode":404}
```
```json
{"message":"Route GET:/socket.io/?EIO=4&transport=polling&t=PCUbysh not found","error":"Not Found","statusCode":404}
```

**Comment by cryptofyre** [comment]
Did you enable WebSockets in the Connectivity tab and if so what version & OS are you running.

**Comment by ThatGravyBoat** [comment]
stale bot on github issues, thats a new one...

this is still an issue

**Comment by cryptofyre** [comment]
We move at a rather alarming pace, so we primarily have one because we often lack the time to regularly update issues. Consequently, many problems are resolved through overtime.

Such as this issue, which you should now be able to solve by downloading the latest build on https://taproom.cider.sh

**Comment by ThatGravyBoat** [comment]
checked out the experimental builds on taproom did fix it, can work on a new Craftify update, thanks for getting it fixed

**Comment by cryptofyre** [comment]
Glad to hear it, looking forward to the new Craftify update!
