### ISSUE TITLE
raw values in [song properties → audio analysis]

### ISSUE THREAD

**Issue by vapidinfinity** [ciderapp/Cider-2#833]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 15.1 (24B83)

### Commit Hash

Izanagi/92ad8bb117781fdb0dd4fb9fd69f2489c3b95ad9

### Describe the Bug

Unsure if this is intended functionality, but in the properties tab, there're just raw values, with no handling whatsoever.
if it is intended functionalty, in production software, it's sorta unprofessional to ship a frontend that doesn't handle the processed values from the backend correctly
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/3f72fce5-c0d1-4115-b826-a0b758390819">

Danceability and Energy seem to be percentage values, while Key seems to be a JSON response of some sort of third-party library
<sub>but you already knew that</sub>

### Steps to Reproduce

<img width="96" alt="image" src="https://github.com/user-attachments/assets/4738b388-e60c-4840-9bea-4976ff6b6e19">

⬇️

<img width="427" alt="image" src="https://github.com/user-attachments/assets/c01deeab-8de0-4a1c-9c25-4badff8f88ab">

⬇️

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/20a22cee-0a8e-4431-b68d-7466b574cd56">

**Comment by coredev-uk** [comment]
Properties is intended to be this way, its just to give the users an insight into the attributes of the song, its more for power users over just general looking. It may be adapted for better usage in the future, but for now this is not changing.
