### ISSUE TITLE
nonfunctional cider raycast plugin

### ISSUE THREAD

**Issue by blackxfiied** [ciderapp/Cider-2#834]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 15.1 (24B83)

### Commit Hash

Izanagi/92ad8bb117781fdb0dd4fb9fd69f2489c3b95ad9

### Describe the Bug

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/517107aa-44f3-43bf-a725-093c8275faa6">

### Steps to Reproduce

install extension
use extesnin
extension no work!

**Comment by cryptofyre** [comment]
This is not an official plugin nor implementation, contact the plugin publisher.
