### ISSUE TITLE
Messed up titles

### ISSUE THREAD

**Issue by RobotChicken37** [ciderapp/Cider-2#838]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

windows 11

### Describe the Bug

Many of the titles and words have either "term" or "action" before them. Ex: "Term.library" "Term.AppleMusic" "action.Createnew" "Term.search" etc.

### Steps to Reproduce

1. Started my cider one day
2. It brokie
3. Sad

### Anything else?

![image_2024-11-19_174922074](https://github.com/user-attachments/assets/0655cc67-5f3e-4f73-afa4-0ef8b7748874)

**Comment by cryptofyre** [comment]
Check your internet connection if its blocking Crowdin services.
