### ISSUE TITLE
Maximizing Window with Native Window Bar Crashes Cider

### ISSUE THREAD

**Issue by sixteen4** [ciderapp/Cider-2#839]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch (pacman package)

### Operating System

Linux 6.11.9-zen1-1-zen

### Commit Hash

7b04e2c902aa2dab4065c276beb3302b22385240

### Build Timestamp

10/28/2024, 8:16:42 PM

### Describe the Bug

Normally, maximizing Cider with its default custom window bar works fine. However, if the Native window bar option is toggled, maximizing immediately crashes Cider.

Probably related to #681 , but specifically only when Native window bar is enabled.

### Steps to Reproduce

1. Settings > Visual > General > Title Bar Style -> Native
2. Restart Cider
3. Maximize Cider

### Anything else?

This is happening on Linux with KDE Plasma 6.2.3 (Wayland). Have not tried other desktop environments.

**Comment by coredev-uk** [comment]
I believe this is a bug with Electron, but cannot confirm. If you have the combination of transparency + native window frame it causes this on wayland. I do not know exactly, but it is out of our purview

**Comment by yerbestpal** [comment]
> I believe this is a bug with Electron, but cannot confirm. If you have the combination of transparency + native window frame it causes this on wayland. I do not know exactly, but it is out of our purview

I can confirm that switching to the default window frame is a temporary solution on Fedora KDE Plasma.

**Comment by coredev-uk** [comment]
Since the bug from Electron appears to be resolved on their end. Please could you confirm that this bug is occurring on the latest build from Taproom.

**Comment by sixteen4** [comment]
How can I test the latest build?

**Comment by coredev-uk** [comment]
As I said previously, on [Taproom](https://taproom.cider.sh/)

**Comment by sixteen4** [comment]
I tested the latest experimental AppImage from Taproom and the issue seems to be fixed.
