### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Wyral** [ciderapp/Cider-2#840]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch 

### Operating System

macOS 15.1 (24B83)

### Describe the Bug

Every time, I close my Mac, I get, depending on the time span, that it was closed, multiple Java Script errors.
<img width="372" alt="SCR-20241120-ketz" src="https://github.com/user-attachments/assets/15358b41-6b1b-4c90-a138-ae9a8072265b">

> A JavaScript error occurred in
the main process
Uncaught Exception:
Error: connection refused:
localtunnel.me:36797 (check your
firewall settings)
at Socket.<anonymous>
(<anonymous>:559:23327)
at Socket.emit (node:events:518:28)
at emitErrorNT (node:internal/streams/
destroy:169:8)
at emitErrorCloseNT (node:internal/
streams/destroy:128:3)
at process.processTicksAndRejections
(node:internal/process/
task_queues: 82:21)

### Steps to Reproduce

Open Cider. Stop Playback. Close the lid of the MacBook. Wait a bit. Open the Macbook and Cider should open this error message.

### Anything else?

It does not crash Cider. If you spam click "enter", to remove all errors, Cider works as usually.

**Comment by coredev-uk** [comment]
Please disable and antivirus or firewall you have installed. If this is a managed machine then this may also be playing a factor.

**Comment by Wyral** [comment]
okay, thanks for your reply.
just as a heads up, I have neither of them. My firewall is turned off and I don't have any antivirus installed. Just plain macOS.

I will try to reinstall the app, maybe this will fix it.
thx

**Comment by Wyral** [comment]
oh, okay I understand. Thanks for the more in-depth explanation.
no worries, I can still use cider, just need to spam enter every now and then.
