### ISSUE TITLE
Discord Integration doesn't work when client name is set to "AppleMusic"

### ISSUE THREAD

**Issue by kamez104** [ciderapp/Cider-2#841]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 11

### Describe the Bug

Discord Integration doesn't work when client name is set to "AppleMusic". It only works when client name is set to Cider.

### Steps to Reproduce

1. Open settings
2. Connectivity
3. Set client name to "AppleMusic" in the Discord Integration setting

**Comment by coredev-uk** [comment]
I cannot replicate this, please ensure you do not have any unique settings and/or third-party plugins enabled in Discord.
