### ISSUE TITLE
Add to library does not toggle correctly

### ISSUE THREAD

**Issue by Wyral** [ciderapp/Cider-2#845]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 15.1.1 (24B91)

### Describe the Bug

At some point, the add to library is just shown as already added for every song. 

<img width="741" alt="SCR-20241125-uagd" src="https://github.com/user-attachments/assets/9af68ecd-a521-4291-9a46-d6a0c77ebd7a">
Cider shows it as already added.
<img width="669" alt="SCR-20241125-uaov" src="https://github.com/user-attachments/assets/57d0d4e5-10c8-482e-9544-fca19f37f23b">
Apple Music shows the correct state as "add to library"

### Steps to Reproduce

Wasn't able to spot a specific pattern. After the playback of certain playlists (stations) it just occurs. And I only notice it every time, I hear a new song, and want to add it to my library.

**Comment by coredev-uk** [comment]
Please switch to the experimental builds found on [Taproom](https://taproom.cider.sh), this bug is fixed there.
