### ISSUE TITLE
Gapless playback doesn't work

### ISSUE THREAD

**Issue by peddy22** [ciderapp/Cider-2#847]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

itch.io

### Operating System

Windows 11

### Commit Hash

7b04e2c902aa2dab4065c276beb3302b22385240

### Build Timestamp

1730171802575

### Describe the Bug

Gapless playback doesn't work. Try playing "A State of Trance 2023 Yearmix (mixed)" for example. 

### Steps to Reproduce

1. Play continuous mix album
2. A small gap will  be present in between songs

**Comment by coredev-uk** [comment]
its apples feature, not ours, we just have a toggle to toggle it in musickit

**Comment by peddy22** [comment]
that is a shame. I remember it used to be a big deal on the iPod touch 2, where it worked. I swear it doesn't even work on my iPhone anymore.

**Comment by coredev-uk** [comment]
We tend to get very mixed usage with it, it only came to MusicKit.js around a couple of years back, it was one of the later features but we did have some users struggling with it, that's why we did add the toggle. Unfortunately it's just how apple does it, similar to other areas like shuffle and queue functionality, just messy
