### ISSUE TITLE
apple music cant login（apple music无法登录）

### ISSUE THREAD

**Issue by WilsonLi678** [ciderapp/Cider-2#864]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

Discord (Supporter Releases)

### Operating System

Windows 

### Commit Hash

ac990fab4b301012e3de4136c849024480d56d9b

### Build Timestamp

2024/12/8 06:57:41

### Describe the Bug

![屏幕截图 2024-12-09 212136](https://github.com/user-attachments/assets/d7ee35ff-739f-4565-a67c-505745196518)

### Steps to Reproduce

在支持者版本中apple music无法登录

**Comment by coredev-uk** [comment]
Support is only given in English, I can only help you so far.

I suggest trying to login through the [Apple Music website](https://beta.music.apple.com). I suspect it may be an issue with Apple auth with your storefront, or that you do not have a full Apple Music subscription. Outside this, if you cannot provide steps to reproduce in English I cannot help.
