### ISSUE TITLE
(Translation) German Grammar

### ISSUE THREAD

**Issue by 6i9i** [ciderapp/Cider-2#873]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

itch.io

### Operating System

Nobara Linux 40 (KDE Plasma) x86_64 (based on fedora)

### Build Timestamp

{"buildInfo":{"version":"2.6.0.2","commit":"75f5a54d6018d10c963cd5d8c7aad2afd529fc73","buildDate":"1734728910680","changelogUrl":"2.6.0-release"},"clientInfo":{"client":"genten","env":"production","arch":"x64","platform":"linux","platformFriendly":"Linux","build":"desktop","clientVersion":"2.6.0","capi":"v7rg9omctjn53fhtcde5c8uc"}}

### Describe the Bug

Hi there, I found a grammar mistake in the German translation.
![Cider_Grammatikfehler](https://github.com/user-attachments/assets/d9fd9a70-ddbb-4832-ab3d-d2044e7fa371)

The description's very first word currently reads "Geb" whereas "Gib" would be correct.
Imperativ, 2. Person Singular [du]: gib!
[Link to the German dictionary, the "Duden".](https://www.duden.de/konjugation/geben)

### Steps to Reproduce

In Settings -> Visual -> advanced -> 0 dBFS Calibration (2nd to last entry)

**Comment by coredev-uk** [comment]
Translations are crowd sourced from Crowdin. Feel free to suggest the change there. https://translate.cider.sh
