### ISSUE TITLE
Untitled Playlist

### ISSUE THREAD

**Issue by telmophane** [ciderapp/Cider-2#879]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

Microsoft Store

### Operating System

Windows undefined

### Commit Hash

506797671a45f90ff1ddccee5946e6d180438ef6

### Build Timestamp

23/12/2024, 23:39:32

### Describe the Bug

Bunch of deleted playlists appearing as Untitled

### Steps to Reproduce

Deleted a playlist on phone and somehow it appears Untitled on Cider
![Captura de ecrã 2024-12-24 114827](https://github.com/user-attachments/assets/acb32687-72c2-4edf-9253-197d2ae53e54)

**Comment by coredev-uk** [comment]
Do you have legacy playlist fetching enabled in settings?

**Comment by telmophane** [comment]
> Do you have legacy playlist fetching enabled in settings?

yes i do

**Comment by telmophane** [comment]
> Do you have legacy playlist fetching enabled in settings?

i just turned it off and it got resolved thankss
