### ISSUE TITLE
"App cannot be run outside of container environment" 

### ISSUE THREAD

**Issue by NotDeath27** [ciderapp/Cider-2#881]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

Microsoft Store

### Operating System

Windows 11

### Commit Hash

801d39c73eba16cc1780b72d12ba3bcb9be7184f

### Build Timestamp

2024-12-24, 3:36:39 p.m.

### Describe the Bug

You can't open Cider directly from the .exe file after the newest update on the Microsoft store. I had a desktop shortcut for Cider, but it no longer works. 

This is the window that pops up.
![image](https://github.com/user-attachments/assets/e7bd5096-c0cf-45d4-8e71-4f25f4bb83ff)

I'm assuming this is a bug because I could do it on previous versions

### Steps to Reproduce

Open the Cider.exe file from its folder in File Explorer instead of through Microsoft Store or the Search Bar
![image](https://github.com/user-attachments/assets/5d5fbe84-9b5a-448a-9e5d-9660b013342c)
(Which this just opens the window shown above)

**Comment by cryptofyre** [comment]
Cider will not open unless opened via the store ID context, this is intentional behavior and an anti-piracy mechanism. 

Open the start menu and create a shortcut using the start menu item for Cider instead.
