### ISSUE TITLE
[Bug]: App Not Loading

### ISSUE THREAD

**Issue by Ravioliii** [ciderapp/Cider-2#89]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

March 8th 2023 build

### Operating System Version

Windows 22H2

### Describe the Bug

After installing the latest ClientDB build, something has broken and made it only open a grey screen with no controls. I have tried deleting appdata, uninstall/reinstalling, restarting, and opening from the source file but the only way its fixed is by opening with Administrator. I can only trace it to the new build since I had the older March 8th build open and playing before attempting to use the new ClientDB. 

### Steps to Reproduce

1. Downloaded new build 
2. Got a grey screen
3. Went back to old
4. Still a grey screen

### Anything else?

[fujisan.log](https://github.com/ciderapp/Fujisan-BugTracker/files/10964732/fujisan.log)

**Comment by coredev-uk** [comment]
Reinstall the application and please try to give issues a title when you create them.

**Comment by cryptofyre** [comment]
No longer relevant.
